// src/react/pages/database/DatabaseTree.tsx
import { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'
import { Box, Tooltip, useTheme } from '@mui/material'
import { Schedule, Delete, Add } from '@mui/icons-material'
import { useI18nStore } from '../../stores/i18n.store'
import { useRedisStateStore, getPaginatedKeys } from '../../stores/redis-state.store'
import { useSettingsStore } from '../../stores/settings.store'
import { useCommonStore, onTreeEvent, emitTreeEvent } from '../../stores/common.store'
import { useMainCommandStore, onCommandEvent } from '../../stores/main-command.store'
import { request } from '../../stores/socket.service'
import { navigateTo } from '../../stores/navigation.store'
import { keysToTreeControl } from '../../stores/tree-builder'
import KeyNewOrSetDialog from '../../dialogs/KeyNewOrSetDialog'

import humanizeDuration from 'humanize-duration'

const ROW_HEIGHT = 28
const INDENT_PX = 20

export interface FlatTreeNode {
    label: string
    key: string
    level: number
    expandable: boolean
    type: 'folder' | 'element'
    childCount: number
    keysInfo?: { type: string; length: number; ttl?: number }
    _sourceNode?: any
}

// Type icon map
const typeIcons: Record<string, string> = {
    hash: 'fas fa-hashtag',
    list: 'fas fa-list-ol',
    set: 'fas fa-list',
    string: 'fas fa-ellipsis-h',
    zset: 'fas fa-chart-line',
    stream: 'fas fa-stream',
    json: 'fas fa-code',
    timeseries: 'fas fa-chart-area',
    bloom: 'fas fa-filter',
    cuckoo: 'fas fa-filter',
    topk: 'fas fa-trophy',
    cms: 'fas fa-chart-simple',
    tdigest: 'fas fa-chart-bar',
    vectorset: 'fas fa-brain',
}

export default function DatabaseTree({ resizeSignal }: { resizeSignal?: any }) {
    const strings = useI18nStore(s => s.strings)
    const keysRaw = useRedisStateStore(s => s.keysRaw)
    const keysInfo = useRedisStateStore(s => s.keysInfo)
    const page = useRedisStateStore(s => s.page)
    const search = useRedisStateStore(s => s.search)
    const connection = useRedisStateStore(s => s.connection)
    const redisTreeDivider = useSettingsStore(s => s.redisTreeDivider)
    const muiTheme = useTheme()
    const { confirm, toast, generalHandleError } = useCommonStore()
    const { refresh } = useMainCommandStore()

    const isReadonly = connection?.readonly === true
    const divider = redisTreeDivider || ':'

    const getExpansionKey = () => `p3xr-tree-expanded-${connection?.id || 'none'}-${useRedisStateStore.getState().currentDatabase ?? 0}`

    const [expandedKeys, setExpandedKeys] = useState<Set<string>>(() => {
        try {
            const raw = sessionStorage.getItem(getExpansionKey())
            return raw ? new Set(JSON.parse(raw)) : new Set()
        } catch { return new Set() }
    })
    const [keyNewDialogOpen, setKeyNewDialogOpen] = useState(false)
    const [keyNewDialogData, setKeyNewDialogData] = useState<any>(null)
    const [hierarchicalNodes, setHierarchicalNodes] = useState<any[]>([])
    const [, setTick] = useState(0) // for TTL repaints
    const parentRef = useRef<HTMLDivElement>(null)

    // Persist expansion state to sessionStorage
    useEffect(() => {
        try { sessionStorage.setItem(getExpansionKey(), JSON.stringify([...expandedKeys])) } catch {}
    }, [expandedKeys]) // eslint-disable-line react-hooks/exhaustive-deps

    // Restore expansion state on connection/db change
    const currentDb = useRedisStateStore(s => s.currentDatabase)
    useEffect(() => {
        try {
            const raw = sessionStorage.getItem(getExpansionKey())
            setExpandedKeys(raw ? new Set(JSON.parse(raw)) : new Set())
        } catch { setExpandedKeys(new Set()) }
    }, [connection?.id, currentDb]) // eslint-disable-line react-hooks/exhaustive-deps

    // Build tree when keys, divider, or page change
    useEffect(() => {
        const paginatedKeys = getPaginatedKeys()
        keysToTreeControl({
            keys: paginatedKeys,
            divider,
            keysInfo: keysInfo ?? {},
        }).then(({ nodes }) => {
            setHierarchicalNodes(nodes)
        })
    }, [keysRaw, keysInfo, divider, page, search])

    // Flatten visible nodes
    const dataSource = useMemo(() => {
        const result: FlatTreeNode[] = []
        const flatten = (nodes: any[], level: number) => {
            for (const node of nodes) {
                result.push({
                    label: node.label,
                    key: node.key,
                    level,
                    expandable: node.type === 'folder',
                    type: node.type,
                    childCount: node.childCount ?? 0,
                    keysInfo: node.keysInfo,
                    _sourceNode: node,
                })
                if (node.type === 'folder' && expandedKeys.has(node.key) && node.children?.length > 0) {
                    flatten(node.children, level + 1)
                }
            }
        }
        flatten(hierarchicalNodes, 0)
        return result
    }, [hierarchicalNodes, expandedKeys])

    // Virtual scrolling
    const virtualizer = useVirtualizer({
        count: dataSource.length,
        getScrollElement: () => parentRef.current,
        estimateSize: () => ROW_HEIGHT,
        overscan: 10,
    })

    // Re-measure when container resizes (console expand/collapse)
    useEffect(() => {
        virtualizer.measure()
    }, [resizeSignal])

    // Toggle expand/collapse
    const toggleExpand = useCallback((key: string) => {
        setExpandedKeys(prev => {
            const next = new Set(prev)
            if (next.has(key)) next.delete(key)
            else next.add(key)
            return next
        })
    }, [])

    // Select a key node
    const selectNode = useCallback((node: FlatTreeNode) => {
        navigateTo('database.key', { key: node.key })
    }, [])

    // Listen for key-new events from add buttons
    useEffect(() => {
        return onCommandEvent('key-new', (data: any) => {
            setKeyNewDialogData({ type: 'add', node: data?.node })
            setKeyNewDialogOpen(true)
        })
    }, [])

    const handleKeyNewClose = useCallback(async (result?: any) => {
        setKeyNewDialogOpen(false)
        setKeyNewDialogData(null)
        if (result?.key) {
            await useMainCommandStore.getState().refresh({ withoutParent: false, force: true })
            navigateTo('database.key', { key: result.key })
        }
    }, [])

    // Tree command event subscriptions
    useEffect(() => {
        const unsubs = [
            onTreeEvent('expand-all', () => {
                const allKeys = new Set<string>()
                const collect = (nodes: any[]) => {
                    for (const node of nodes) {
                        if (node.type === 'folder') {
                            allKeys.add(node.key)
                            collect(node.children ?? [])
                        }
                    }
                }
                collect(hierarchicalNodes)
                setExpandedKeys(allKeys)
            }),
            onTreeEvent('collapse-all', () => {
                setExpandedKeys(new Set())
            }),
            ...[1, 2, 3, 4, 5].map(level =>
                onTreeEvent(`expand-level-${level}`, () => {
                    const keys = new Set<string>()
                    const collect = (nodes: any[], depth: number) => {
                        for (const node of nodes) {
                            if (node.type === 'folder') {
                                if (depth < level) keys.add(node.key)
                                collect(node.children ?? [], depth + 1)
                            }
                        }
                    }
                    collect(hierarchicalNodes, 0)
                    setExpandedKeys(keys)
                })
            ),
        ]
        return () => unsubs.forEach(fn => fn())
    }, [hierarchicalNodes])

    // TTL adaptive repaint
    useEffect(() => {
        let timer: any
        const tick = () => {
            let minTtl = Infinity
            let hasExpired = false
            const fetchedAt = useRedisStateStore.getState().keysInfoFetchedAt ?? Date.now()
            const now = Date.now()

            for (const node of dataSource) {
                if (node.type === 'folder') continue
                const serverTtl = node.keysInfo?.ttl
                if (!serverTtl || serverTtl <= 0) continue
                const elapsed = Math.floor((now - fetchedAt) / 1000)
                const remaining = serverTtl - elapsed
                if (remaining <= 0) hasExpired = true
                else if (remaining < minTtl) minTtl = remaining
            }

            if (hasExpired) {
                refresh()
                timer = setTimeout(tick, 3000)
                return
            }

            setTick(t => t + 1)

            let interval: number
            if (minTtl <= 30) interval = 1000
            else if (minTtl <= 300) interval = 5000
            else interval = 30000

            timer = setTimeout(tick, interval)
        }
        timer = setTimeout(tick, 1000)
        return () => clearTimeout(timer)
    }, [dataSource])

    // --- TTL helpers ---
    const getRemainingTtl = useCallback((node: FlatTreeNode): number => {
        const ttl = node.keysInfo?.ttl
        if (!ttl || ttl <= 0) return -1
        const fetchedAt = useRedisStateStore.getState().keysInfoFetchedAt ?? Date.now()
        const elapsed = Math.floor((Date.now() - fetchedAt) / 1000)
        const remaining = ttl - elapsed
        return remaining > 0 ? remaining : -1
    }, [])

    const formatTtl = useCallback((node: FlatTreeNode): string => {
        const remaining = getRemainingTtl(node)
        if (remaining <= 0) return ''
        const hdOpts = useSettingsStore.getState().getHumanizeDurationOptions()
        return humanizeDuration(remaining * 1000, {
            ...hdOpts,
            largest: 2,
            round: true,
            delimiter: ' ',
        })
    }, [getRemainingTtl])

    const getTtlColor = useCallback((node: FlatTreeNode): string => {
        const remaining = getRemainingTtl(node)
        if (remaining <= 0) return ''
        if (remaining < 300) return '#f44336' // red
        if (remaining < 3600) return '#ff9800' // yellow/orange
        return '#4caf50' // green
    }, [getRemainingTtl])

    const isTtlPulsing = useCallback((node: FlatTreeNode): boolean => {
        return getRemainingTtl(node) > 0 && getRemainingTtl(node) < 30
    }, [getRemainingTtl])

    // --- Node actions ---
    const deleteKey = useCallback(async (e: React.MouseEvent, key: string) => {
        e.preventDefault()
        e.stopPropagation()
        try {
            await confirm({ message: strings?.confirm?.deleteKey })
            await request({ action: 'delete', payload: { key } })
            navigateTo('database.statistics')
            toast(typeof strings?.status?.deletedKey === 'function' ? strings.status.deletedKey({ key }) : '')
            await refresh()
        } catch (err) {
            generalHandleError(err)
        }
    }, [strings, confirm, toast, refresh, generalHandleError])

    const deleteTree = useCallback(async (e: React.MouseEvent, node: FlatTreeNode) => {
        e.stopPropagation()
        try {
            const msg = typeof strings?.confirm?.deleteAllKeys === 'function'
                ? strings.confirm.deleteAllKeys({ key: node.key }) : ''
            await confirm({ message: msg })
            await request({
                action: 'key-del-tree',
                payload: { key: node.key, redisTreeDivider: divider },
            })
            const toastMsg = typeof strings?.status?.treeDeleted === 'function'
                ? strings.status.treeDeleted({ key: node.key }) : ''
            toast(toastMsg)
            await refresh()
        } catch (err) {
            generalHandleError(err)
        }
    }, [strings, divider, confirm, toast, refresh, generalHandleError])

    const addKey = useCallback((e: React.MouseEvent, node: FlatTreeNode) => {
        e.stopPropagation()
        useMainCommandStore.getState().addKey({ event: e.nativeEvent, node: node._sourceNode ?? { key: node.key } })
    }, [])

    // --- Tooltip helpers ---
    const nodeTooltip = useCallback((node: FlatTreeNode): string => {
        if (node.type !== 'folder' && node.keysInfo) {
            const typeName = strings?.redisTypes?.[node.keysInfo.type] ?? node.keysInfo.type
            return typeName + ' - ' + node.key
        }
        return node.key
    }, [strings])

    const dialogEl = <KeyNewOrSetDialog open={keyNewDialogOpen} data={keyNewDialogData} onClose={handleKeyNewClose} />

    if (dataSource.length === 0) {
        return (
            <Box sx={{ p: 1, opacity: 0.5, fontSize: 13 }}>
                {strings?.label?.noKeys}
                {dialogEl}
            </Box>
        )
    }

    return (
        <Box ref={parentRef} sx={{ height: '100%', width: '100%', overflow: 'auto' }}>
            <Box sx={{ height: virtualizer.getTotalSize(), width: '100%', position: 'relative' }}>
                {virtualizer.getVirtualItems().map(virtualRow => {
                    const node = dataSource[virtualRow.index]
                    const remaining = getRemainingTtl(node)
                    const ttlColor = getTtlColor(node)
                    const pulsing = isTtlPulsing(node)

                    return (
                        <Box
                            key={`${node.type}-${node.key}`}
                            data-p3xr-tree-key={node.type === 'folder' ? '' : node.key}
                            sx={{
                                position: 'absolute',
                                top: 0,
                                left: 0,
                                width: '100%',
                                height: ROW_HEIGHT,
                                transform: `translateY(${virtualRow.start}px)`,
                                display: 'flex',
                                alignItems: 'center',
                                whiteSpace: 'nowrap',
                                cursor: 'default',
                                pl: `${node.level * INDENT_PX + 4}px`,
                                '&:hover .tree-actions': { visibility: 'visible' },
                            }}
                        >
                            {/* Folder icon (no spacer for elements — matches Angular) */}
                            {node.expandable && (
                                <Box
                                    component="span"
                                    onClick={(e: React.MouseEvent) => { e.stopPropagation(); toggleExpand(node.key) }}
                                    sx={{
                                        display: 'inline-block',
                                        fontFamily: "'Font Awesome 5 Free'",
                                        fontWeight: 900,
                                        fontSize: 24,
                                        lineHeight: '28px',
                                        width: 28,
                                        textAlign: 'center',
                                        mr: '4px',
                                        cursor: 'pointer',
                                        color: muiTheme.p3xr.treeBranchColor,
                                        '&::before': {
                                            content: expandedKeys.has(node.key) ? '"\\f07c"' : '"\\f07b"',
                                        },
                                    }}
                                />
                            )}

                            {/* Node label area */}
                            <Tooltip title={nodeTooltip(node)} placement="right" enterDelay={500}
                                slotProps={{ popper: { sx: { ml: '36px !important' } } }}>
                                <Box
                                    component="label"
                                    className="p3xr-database-tree-node"
                                    onClick={() => node.expandable ? toggleExpand(node.key) : selectNode(node)}
                                    sx={{
                                        cursor: 'pointer',
                                        display: 'inline-flex',
                                        alignItems: 'center',
                                        height: ROW_HEIGHT,
                                        whiteSpace: 'nowrap',
                                    }}
                                >
                                    {/* Type icon — same box size as folder icon for alignment */}
                                    {node.type !== 'folder' && node.keysInfo && typeIcons[node.keysInfo.type] && (
                                        <i
                                            className={typeIcons[node.keysInfo.type]}
                                            aria-hidden="true"
                                            style={{ display: 'inline-block', width: 28, textAlign: 'center', marginRight: 4, fontSize: 14 }}
                                        />
                                    )}

                                    <span className="p3xr-database-tree-node-label">{node.label}</span>

                                    {/* Folder child count */}
                                    {node.type === 'folder' && (
                                        <span style={{ opacity: 0.5, marginLeft: 4 }}>
                                            {divider}* <span>({node.childCount})</span>
                                        </span>
                                    )}

                                    {/* Element length (non-string/json) */}
                                    {node.type !== 'folder' && node.keysInfo?.type !== 'string' && node.keysInfo?.type !== 'json' && node.keysInfo && (
                                        <span style={{ opacity: 0.5, marginLeft: 4 }}>({node.keysInfo.length})</span>
                                    )}
                                </Box>
                            </Tooltip>

                            {/* TTL badge */}
                            {node.type !== 'folder' && remaining > 0 && (
                                <Tooltip title={`TTL: ${formatTtl(node)}`} placement="right" enterDelay={300}
                                    slotProps={{ popper: { sx: { ml: '36px !important' } } }}>
                                    <Box component="span" sx={{
                                        display: 'inline-flex',
                                        alignItems: 'center',
                                        ml: '4px',
                                        animation: pulsing ? 'p3xr-ttl-pulse 1s infinite' : 'none',
                                        '@keyframes p3xr-ttl-pulse': {
                                            '0%, 100%': { opacity: 0.7 },
                                            '50%': { opacity: 1 },
                                        },
                                    }}>
                                        <Schedule sx={{ fontSize: 16, color: ttlColor }} />
                                    </Box>
                                </Tooltip>
                            )}

                            {/* Action buttons (hover) — height matches row for continuous hover */}
                            {!isReadonly && (
                                <Box component="span" className="tree-actions" sx={{
                                    display: 'inline-flex',
                                    alignItems: 'center',
                                    visibility: 'hidden',
                                    height: ROW_HEIGHT,
                                    position: 'relative',
                                    top: -1,
                                }}>
                                    {node.type === 'folder' ? (
                                        <Tooltip title={typeof strings?.confirm?.deleteAllKeys === 'function' ? strings.confirm.deleteAllKeys({ key: node.key }) : ''} placement="right" enterDelay={300}
                                            slotProps={{ popper: { sx: { ml: '36px !important' } } }}>
                                            <Delete
                                                onClick={(e) => deleteTree(e, node)}
                                                sx={{ fontSize: '18px !important', width: 18, height: 18, cursor: 'pointer', color: 'error.main' }}
                                            />
                                        </Tooltip>
                                    ) : (
                                        <Tooltip title={strings?.intention?.delete} placement="right" enterDelay={300}
                                            slotProps={{ popper: { sx: { ml: '36px !important' } } }}>
                                            <Delete
                                                onClick={(e) => deleteKey(e, node.key)}
                                                sx={{ fontSize: '18px !important', width: 18, height: 18, cursor: 'pointer', color: 'error.main' }}
                                            />
                                        </Tooltip>
                                    )}
                                    <Tooltip title={strings?.intention?.addKey} placement="right" enterDelay={300}
                                        slotProps={{ popper: { sx: { ml: '36px !important' } } }}>
                                        <Add
                                            onClick={(e) => addKey(e, node)}
                                            sx={{ fontSize: '18px !important', width: 18, height: 18, cursor: 'pointer', color: muiTheme.p3xr.commonWarnColor }}
                                        />
                                    </Tooltip>
                                </Box>
                            )}
                        </Box>
                    )
                })}
            </Box>
            {dialogEl}
        </Box>
    )
}

// src/ng/pages/database/database-tree.component.ts
import { Component, Input, Inject, OnInit, OnDestroy, NgZone, ElementRef, ViewChild, ChangeDetectorRef, ChangeDetectionStrategy, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CdkVirtualScrollViewport, ScrollingModule } from '@angular/cdk/scrolling';
import { MatTooltipModule } from '@angular/material/tooltip';

import { I18nService } from '../../services/i18n.service';
import { CommonService } from '../../services/common.service';
import { ThemeService } from '../../services/theme.service';
import { SocketService } from '../../services/socket.service';
import { KeyNewOrSetDialogService } from '../../dialogs/key-new-or-set-dialog.service';
import { NavigationService } from '../../services/navigation.service';
import { MainCommandService } from '../../services/main-command.service';
import { TreeBuilderService } from '../../services/tree-builder.service';
import { RedisStateService } from '../../services/redis-state.service';
import { SettingsService } from '../../services/settings.service';

import { htmlEncode } from 'js-htmlencode';
import humanizeDuration from 'humanize-duration';

export interface FlatTreeNode {
    label: string;
    key: string;
    level: number;
    expandable: boolean;
    type: 'folder' | 'element';
    childCount: number;
    keysInfo?: { type: string; length: number; ttl?: number };
    // Reference to the original hierarchical node (for expandedNodes sync)
    _sourceNode?: any;
}

@Component({
    selector: 'p3xr-database-tree',
    standalone: true,
    imports: [
        CommonModule,
        ScrollingModule,
        MatTooltipModule,
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './database-tree.component.html',
    styleUrls: ['./database-tree.component.scss'],
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DatabaseTreeComponent implements OnInit, OnDestroy {
    @Input() p3xrResize: any;
    @Input() p3xrMainRef: any;
    @ViewChild(CdkVirtualScrollViewport) private viewport?: CdkVirtualScrollViewport;

    dataSource: FlatTreeNode[] = [];
    isEnabled = false;
    isReadonly = false;
    divider = ':';
    readonly strings;
    private expandedKeys = new Set<string>();
    private expandedNodeObjects: any[] = [];
    private hierarchicalNodes: any[] = [];

    private get expansionStorageKey(): string {
        const connId = this.state.connection()?.id || 'none';
        const db = this.state.currentDatabase() ?? 0;
        return `p3xr-tree-expanded-${connId}-${db}`;
    }

    private saveExpansion(): void {
        try { sessionStorage.setItem(this.expansionStorageKey, JSON.stringify([...this.expandedKeys])); } catch {}
    }

    private restoreExpansion(): void {
        try {
            const raw = sessionStorage.getItem(this.expansionStorageKey);
            if (raw) this.expandedKeys = new Set(JSON.parse(raw));
        } catch {}
    }
    private readonly unsubs: Array<() => void> = [];

    constructor(
        @Inject(NgZone) private readonly ngZone: NgZone,
        @Inject(ElementRef) private readonly elementRef: ElementRef,
        @Inject(I18nService) private readonly i18n: I18nService,
        @Inject(CommonService) private readonly common: CommonService,
        @Inject(ThemeService) private readonly theme: ThemeService,
        @Inject(SocketService) private readonly socket: SocketService,
        @Inject(KeyNewOrSetDialogService) private readonly keyNewOrSetDialog: KeyNewOrSetDialogService,
        @Inject(NavigationService) private readonly nav: NavigationService,
        @Inject(MainCommandService) private readonly cmd: MainCommandService,
        @Inject(ChangeDetectorRef) private readonly cdr: ChangeDetectorRef,
        @Inject(TreeBuilderService) private readonly treeBuilder: TreeBuilderService,
        @Inject(RedisStateService) private readonly state: RedisStateService,
        @Inject(SettingsService) private readonly settingsService: SettingsService,
    ) {
        this.strings = this.i18n.strings;
        effect(() => {
            this.i18n.currentLang();
            this.cdr.markForCheck();
        });
    }

    ngOnInit(): void {
        this.syncGlobalState();
        this.attachWindowFocusListener();
        this.startPolling();
        this.startTtlRepaint();

        // Subscribe to MainCommandService events
        const subDelete = this.cmd.keyDelete$.subscribe((arg) => {
            this.ngZone.run(() => this.deleteKey(arg.event, arg.key));
        });
        this.unsubs.push(() => subDelete.unsubscribe());

        const subRename = this.cmd.keyRename$.subscribe((arg) => {
            this.ngZone.run(() => this.renameKey(arg.event, arg.key));
        });
        this.unsubs.push(() => subRename.unsubscribe());

        const subKeyNew = this.cmd.keyNew$.subscribe((arg) => {
            this.ngZone.run(() => this.addKey(arg.event, arg.node ? { ...arg, _sourceNode: arg.node } as any : arg as any));
        });
        this.unsubs.push(() => subKeyNew.unsubscribe());

        const subTreeEnabled = this.cmd.treeControlEnabled$.subscribe((enabled) => {
            this.ngZone.run(() => { this.isEnabled = enabled; });
        });
        this.unsubs.push(() => subTreeEnabled.unsubscribe());

        const subTreeRefresh = this.cmd.treeRefresh$.subscribe(() => {
            this.ngZone.run(() => {
                this.syncGlobalState();
                this.rebuildTree();
            });
        });
        this.unsubs.push(() => subTreeRefresh.unsubscribe());

        const subExpand = this.common.treeExpandAll$.subscribe(() => this.ngZone.run(() => {
            const allFolderKeys = new Set<string>();
            const collect = (nodes: any[]) => {
                for (const node of nodes) {
                    if (node.type === 'folder') {
                        allFolderKeys.add(node.key);
                        collect(node.children ?? []);
                    }
                }
            };
            collect(this.hierarchicalNodes);
            this.expandedKeys = allFolderKeys;
            this.flattenVisibleNodes();
            this.syncExpandedNodesToGlobal();
            this.saveExpansion();
            this.cdr.markForCheck();
        }));
        this.unsubs.push(() => subExpand.unsubscribe());

        const subCollapse = this.common.treeCollapseAll$.subscribe(() => this.ngZone.run(() => {
            this.expandedKeys = new Set();
            this.flattenVisibleNodes();
            this.syncExpandedNodesToGlobal();
            this.saveExpansion();
            this.cdr.markForCheck();
        }));
        this.unsubs.push(() => subCollapse.unsubscribe());

        const subExpandLevel = this.common.treeExpandToLevel$.subscribe((level: number) => this.ngZone.run(() => {
            const keys = new Set<string>();
            const collect = (nodes: any[], depth: number) => {
                for (const node of nodes) {
                    if (node.type === 'folder') {
                        if (depth < level) {
                            keys.add(node.key);
                        }
                        collect(node.children ?? [], depth + 1);
                    }
                }
            };
            collect(this.hierarchicalNodes, 0);
            this.expandedKeys = keys;
            this.flattenVisibleNodes();
            this.syncExpandedNodesToGlobal();
            this.saveExpansion();
            this.cdr.markForCheck();
        }));
        this.unsubs.push(() => subExpandLevel.unsubscribe());

        setTimeout(() => {
            this.isEnabled = true;
            this.cdr.markForCheck();
        }, 50);
    }

    ngOnDestroy(): void {
        this.unsubs.forEach(fn => fn());
    }

    // --- TTL (computed on-the-fly from fetchedAt, single 30s repaint) ---

    private ttlRepaintTimer: any;

    private startTtlRepaint(): void {
        const tick = () => {
            this.cdr.markForCheck();
            let minTtl = Infinity;
            let hasExpired = false;
            for (const node of this.dataSource) {
                if (node.type === 'folder') continue;
                const serverTtl = node.keysInfo?.ttl;
                if (!serverTtl || serverTtl <= 0) continue;
                const remaining = this.getRemainingTtl(node);
                if (remaining <= 0) {
                    hasExpired = true;
                } else if (remaining < minTtl) {
                    minTtl = remaining;
                }
            }
            if (hasExpired) {
                this.cmd.refresh();
                // Retry soon in case refresh was throttled
                this.ttlRepaintTimer = setTimeout(tick, 3000);
                return;
            }
            let interval: number;
            if (minTtl <= 30) {
                interval = 1000;
            } else if (minTtl <= 300) {
                interval = 5000;
            } else {
                interval = 30000;
            }
            this.ttlRepaintTimer = setTimeout(tick, interval);
        };
        this.ttlRepaintTimer = setTimeout(tick, 30000);
        this.unsubs.push(() => clearTimeout(this.ttlRepaintTimer));
    }

    getRemainingTtl(node: FlatTreeNode): number {
        const ttl = node.keysInfo?.ttl;
        if (!ttl || ttl <= 0) return -1;
        const fetchedAt = this.state.keysInfoFetchedAt() ?? Date.now();
        const elapsed = Math.floor((Date.now() - fetchedAt) / 1000);
        const remaining = ttl - elapsed;
        return remaining > 0 ? remaining : -1;
    }

    formatTtl(node: FlatTreeNode): string {
        const remaining = this.getRemainingTtl(node);
        if (remaining <= 0) return '';
        const hdOpts = this.settingsService.getHumanizeDurationOptions();
        return humanizeDuration(remaining * 1000, {
            ...hdOpts,
            largest: 2,
            round: true,
            delimiter: ' ',
        });
    }

    getTtlClass(node: FlatTreeNode): string {
        const remaining = this.getRemainingTtl(node);
        if (remaining <= 0) return '';
        if (remaining < 30) return 'p3xr-tree-ttl-red p3xr-tree-ttl-pulse';
        if (remaining < 300) return 'p3xr-tree-ttl-red';
        if (remaining < 3600) return 'p3xr-tree-ttl-yellow';
        return 'p3xr-tree-ttl-green';
    }

    // --- Tree data ---

    trackByKey(_index: number, node: FlatTreeNode): string {
        return node.key;
    }

    isExpanded(node: FlatTreeNode): boolean {
        return this.expandedKeys.has(node.key);
    }

    toggleExpand(node: FlatTreeNode): void {
        if (this.expandedKeys.has(node.key)) {
            this.expandedKeys.delete(node.key);
        } else {
            this.expandedKeys.add(node.key);
        }
        this.flattenVisibleNodes();
        this.syncExpandedNodesToGlobal();
        this.saveExpansion();
    }

    // --- Node actions ---

    selectNode(node: FlatTreeNode): void {
        this.navigateTo('database.key', {
            key: node.key,
        });
    }

    async deleteKey(event: Event, key: string): Promise<void> {
        try {
            event.preventDefault();
            event.stopPropagation();

            await this.common.confirm({
                message: this.i18n.strings().confirm.deleteKey,
            });

            await this.socket.request({
                action: 'key/delete',
                payload: { key },
            });

            if (typeof window['gtag'] === 'function') {
                window['gtag']('config', this.settingsService.googleAnalytics, { page_path: '/delete' });
            }

            this.navigateTo('database.statistics');
            this.common.toast(this.i18n.strings().status.deletedKey({ key }));

            await this.cmd.refresh();
            this.rebuildTree();
        } catch (e) {
            this.common.generalHandleError(e);
        }
    }

    async renameKey(event: Event, key: string): Promise<void> {
        try {
            event?.stopPropagation?.();

            const newKey = await this.common.prompt({
                title: this.i18n.strings().confirm.rename.title,
                placeholder: this.i18n.strings().confirm.rename.placeholder,
                initialValue: key,
                ok: this.i18n.strings().intention.rename,
                cancel: this.i18n.strings().intention.cancel,
            });

            await this.socket.request({
                action: 'key/rename',
                payload: { key, keyNew: newKey },
            });

            if (typeof window['gtag'] === 'function') {
                window['gtag']('config', this.settingsService.googleAnalytics, { page_path: '/rename' });
            }

            this.navigateTo('database.key', {
                key: newKey,
            });
            this.common.toast(this.i18n.strings().status.renamedKey);

            await this.cmd.refresh();
            this.rebuildTree();
        } catch (e) {
            this.common.generalHandleError(e);
        }
    }

    async deleteTree(event: Event, node: FlatTreeNode): Promise<void> {
        try {
            event.stopPropagation();

            await this.common.confirm({
                message: this.i18n.strings().confirm.deleteAllKeys({ key: node.key }),
            });

            const divider = this.settingsService.redisTreeDivider();
            await this.socket.request({
                action: 'key/del-tree',
                payload: {
                    key: node.key,
                    redisTreeDivider: divider,
                },
            });

            this.common.toast(this.i18n.strings().status.treeDeleted({ key: node.key }));

            // If currently viewing a key under the deleted tree, go to statistics
            const currentPath = location.pathname;
            if (currentPath.startsWith('/database/key/')) {
                const currentKey = decodeURIComponent(currentPath.slice('/database/key/'.length).replace(/~/g, '%'));
                if (currentKey.startsWith(node.key + divider)) {
                    this.navigateTo('database.statistics');
                }
            }

            await this.cmd.refresh();
            this.rebuildTree();
        } catch (e) {
            this.common.generalHandleError(e);
        }
    }

    async addKey(event: Event, node: FlatTreeNode): Promise<void> {
        try {
            event.stopPropagation();

            const response = await this.keyNewOrSetDialog.show({
                type: 'add',
                $event: event,
                node: node._sourceNode ?? { key: node.key },
            });

            await this.cmd.refresh();
            this.rebuildTree();

            this.navigateTo('database.key', {
                key: response.key,
            });
        } catch (e) {
            this.common.generalHandleError(e);
        }
    }

    // --- Tooltips ---

    extractNodeTooltip(node: FlatTreeNode): string {
        if (node.type !== 'folder' && node.keysInfo) {
            const strings = this.i18n.strings();
            return htmlEncode((strings.redisTypes?.[node.keysInfo.type] ?? node.keysInfo.type) + ' - ' + node.key);
        }
        return htmlEncode(node.key);
    }

    deleteTreeTooltip(node: FlatTreeNode): string {
        return this.i18n.strings().confirm?.deleteAllKeys?.({ key: node.key }) ?? '';
    }

    // --- Tree rebuild ---

    private rebuildTree(): void {
        this.divider = this.settingsService.redisTreeDivider() ?? ':';
        this.isReadonly = this.state.connection()?.readonly === true;

        const keys: string[] = this.state.paginatedKeys() ?? [];
        const keysInfo: any = this.state.keysInfo() ?? {};

        // Restore saved expansion state if current set is empty (fresh mount or connection/db switch)
        if (this.expandedKeys.size === 0) {
            this.restoreExpansion();
        }

        this.treeBuilder.keysToTreeControl({
            keys,
            divider: this.divider,
            keysInfo,
        }).then(({ nodes }) => {
            this.hierarchicalNodes = nodes;
            this.flattenVisibleNodes();
            this.requestViewRefresh();
        });
    }

    private flattenVisibleNodes(): void {
        const result: FlatTreeNode[] = [];

        const flatten = (nodes: any[], level: number) => {
            for (const node of nodes) {
                result.push({
                    label: node.label,
                    key: node.key,
                    level,
                    expandable: node.type === 'folder',
                    type: node.type,
                    childCount: node.childCount ?? 0,
                    keysInfo: node.keysInfo,
                    _sourceNode: node,
                });

                if (node.type === 'folder' && this.expandedKeys.has(node.key) && node.children?.length > 0) {
                    flatten(node.children, level + 1);
                }
            }
        };

        flatten(this.hierarchicalNodes, 0);
        this.dataSource = result;
    }

    private syncExpandedNodesToGlobal(): void {
        // Build array of node objects matching the expanded keys
        const expandedNodeObjects: any[] = [];
        const collectExpanded = (nodes: any[]) => {
            for (const node of nodes) {
                if (node.type === 'folder' && this.expandedKeys.has(node.key)) {
                    expandedNodeObjects.push(node);
                }
                if (node.children?.length > 0) {
                    collectExpanded(node.children);
                }
            }
        };
        collectExpanded(this.hierarchicalNodes);

        // Keep expanded nodes locally
        this.expandedNodeObjects = expandedNodeObjects;
    }

    private syncGlobalState(): void {
        this.divider = this.settingsService.redisTreeDivider() ?? ':';
        this.isReadonly = this.state.connection()?.readonly === true;
    }

    // --- Polling for change detection ---

    private startPolling(): void {
        let lastSnapshot = '';
        const id = setInterval(() => {
            const snapshot = JSON.stringify({
                keysLength: this.state.paginatedKeys()?.length,
                page: this.state.page(),
                divider: this.settingsService.redisTreeDivider(),
                readonly: this.state.connection()?.readonly,
            });
            if (snapshot !== lastSnapshot) {
                lastSnapshot = snapshot;
                this.ngZone.run(() => {
                    this.syncGlobalState();
                    this.rebuildTree();
                });
            }
        }, 300);
        this.unsubs.push(() => clearInterval(id));
        // Initial build
        this.ngZone.run(() => this.rebuildTree());
    }

    private attachWindowFocusListener(): void {
        const focusListener = () => {
            if (this.isEnabled) {
                this.ngZone.run(() => {
                    this.isEnabled = false;
                    setTimeout(() => {
                        this.isEnabled = true;
                        this.rebuildTree();
                    });
                });
            }
        };
        window.addEventListener('focus', focusListener);
        this.unsubs.push(() => window.removeEventListener('focus', focusListener));
    }

    // --- Navigation ---

    private navigateTo(state: string, params?: any): void {
        this.nav.navigateTo(state, params);
    }

    private requestViewRefresh(): void {
        setTimeout(() => {
            try {
                this.cdr.detectChanges();
                this.viewport?.checkViewportSize();
            } catch {
                // Ignore late refreshes during teardown.
            }
        });
    }
}

<cdk-virtual-scroll-viewport
    *ngIf="dataSource.length > 0 && isEnabled"
    [itemSize]="28"
    class="p3xr-database-tree-viewport">

    <div *cdkVirtualFor="let node of dataSource; trackBy: trackByKey"
         class="p3xr-database-tree-row"
         [style.padding-left.px]="node.level * 20 + 4">

        <!-- Folder expand/collapse icon / leaf spacer for sibling alignment -->
        @if (node.expandable) {
            <span class="p3xr-tree-branch-head"
                  [class.tree-expanded]="isExpanded(node)"
                  [class.tree-collapsed]="!isExpanded(node)"
                  (click)="toggleExpand(node); $event.stopPropagation()">
            </span>
        } 

        <!-- Node content -->
        <span [attr.data-p3xr-tree-key]="node.type === 'folder' ? '' : node.key">
            <label class="p3xr-database-tree-node"
                   (click)="node.expandable ? toggleExpand(node) : selectNode(node)"
                   [matTooltip]="extractNodeTooltip(node)"
                   matTooltipPosition="right"
                   matTooltipClass="p3xr-tree-node-tooltip">

                <!-- Type icon for elements -->
                @if (node.type !== 'folder' && node.keysInfo) {
                    @switch (node.keysInfo.type) {
                        @case ('hash') { <i class="p3xr-database-treecontrol-node-icon fas fa-hashtag" aria-hidden="true"></i> }
                        @case ('list') { <i class="p3xr-database-treecontrol-node-icon fas fa-list-ol" aria-hidden="true"></i> }
                        @case ('set') { <i class="p3xr-database-treecontrol-node-icon fas fa-list" aria-hidden="true"></i> }
                        @case ('string') { <i class="p3xr-database-treecontrol-node-icon fas fa-ellipsis-h" aria-hidden="true"></i> }
                        @case ('zset') { <i class="p3xr-database-treecontrol-node-icon fas fa-chart-line" aria-hidden="true"></i> }
                        @case ('stream') { <i class="p3xr-database-treecontrol-node-icon fas fa-stream" aria-hidden="true"></i> }
                        @case ('json') { <i class="p3xr-database-treecontrol-node-icon fas fa-code" aria-hidden="true"></i> }
                        @case ('timeseries') { <i class="p3xr-database-treecontrol-node-icon fas fa-chart-area" aria-hidden="true"></i> }
                        @case ('bloom') { <i class="p3xr-database-treecontrol-node-icon fas fa-filter" aria-hidden="true"></i> }
                        @case ('cuckoo') { <i class="p3xr-database-treecontrol-node-icon fas fa-filter" aria-hidden="true"></i> }
                        @case ('topk') { <i class="p3xr-database-treecontrol-node-icon fas fa-trophy" aria-hidden="true"></i> }
                        @case ('cms') { <i class="p3xr-database-treecontrol-node-icon fas fa-chart-simple" aria-hidden="true"></i> }
                        @case ('tdigest') { <i class="p3xr-database-treecontrol-node-icon fas fa-chart-bar" aria-hidden="true"></i> }
                        @case ('vectorset') { <i class="p3xr-database-treecontrol-node-icon fas fa-brain" aria-hidden="true"></i> }
                    }
                }

                <span class="p3xr-database-tree-node-label">{{ node.label }}</span>

                <!-- Folder child count -->
                @if (node.type === 'folder') {
                    <span class="p3xr-database-tree-node-count">{{ divider }}* <span style="opacity: 0.5;">({{ node.childCount }})</span></span>
                }

                <!-- Element length (non-string) -->
                @if (node.type !== 'folder' && node.keysInfo?.type !== 'string' && node.keysInfo?.type !== 'json' && node.keysInfo) {
                    <span class="p3xr-database-tree-node-count">({{ node.keysInfo.length }})</span>
                }


            </label>

            <!-- TTL indicator (outside label to avoid tooltip conflict) -->
            @if (node.type !== 'folder' && getRemainingTtl(node) > 0) {
                <span class="p3xr-tree-ttl-badge" [class]="getTtlClass(node)"
                      [matTooltip]="'TTL: ' + formatTtl(node)" matTooltipPosition="right"
                      matTooltipClass="p3xr-tree-node-tooltip">
                    <span class="material-icons p3xr-tree-ttl-icon">schedule</span>
                </span>
            }
        </span>

        <!-- Action buttons (shown on row hover via CSS, hidden in readonly) -->
        @if (!isReadonly) {
            <span class="p3xr-database-tree-actions">
                <!-- Delete tree (folder) / Delete key (element) -->
                @if (node.type === 'folder') {
                    <span [matTooltip]="deleteTreeTooltip(node)" matTooltipPosition="after" matTooltipClass="p3xr-tree-node-tooltip">
                        <span class="material-icons p3xr-database-treecontrol-delete-icon"
                              (click)="deleteTree($event, node)">delete</span>
                    </span>
                } @else {
                    <span [matTooltip]="strings()?.intention?.delete" matTooltipPosition="after" matTooltipClass="p3xr-tree-node-tooltip">
                        <span class="material-icons p3xr-database-treecontrol-delete-icon"
                              (click)="deleteKey($event, node.key)">delete</span>
                    </span>
                }

                <!-- Add key -->
                <span [matTooltip]="strings()?.intention?.addKey" matTooltipPosition="after" matTooltipClass="p3xr-tree-node-tooltip">
                    <span class="material-icons p3xr-database-treecontrol-folder-icon"
                          (click)="addKey($event, node)">add</span>
                </span>
            </span>
        }
    </div>
</cdk-virtual-scroll-viewport>
