// src/ng/pages/database/key/key-set.component.ts
import { Component, Inject, OnInit, OnChanges, SimpleChanges, ChangeDetectorRef, CUSTOM_ELEMENTS_SCHEMA, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { BreakpointObserver } from '@angular/cdk/layout';
import { I18nService } from '../../../services/i18n.service';
import { SocketService } from '../../../services/socket.service';
import { CommonService } from '../../../services/common.service';
import { JsonViewDialogService } from '../../../dialogs/json-view-dialog.service';
import { KeyNewOrSetDialogService } from '../../../dialogs/key-new-or-set-dialog.service';
import { MainCommandService } from '../../../services/main-command.service';
import { RedisStateService } from '../../../services/redis-state.service';
import { SettingsService } from '../../../services/settings.service';
import { KeyTypeBase } from './key-type-base';
import { HexMonitorComponent } from './hex-monitor.component';
import { KeyPaging } from './key-paging';
import { KeyPagerInlineComponent } from './key-pager-inline.component';

@Component({
    selector: 'p3xr-key-set',
    standalone: true,
    imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatTooltipModule, KeyPagerInlineComponent, HexMonitorComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './key-set.component.html',
    encapsulation: ViewEncapsulation.None,
})
export class KeySetComponent extends KeyTypeBase implements OnInit, OnChanges {
    paging: KeyPaging;
    pagedItems: Array<{ index: number; value: any }> = [];

    constructor(
        @Inject(I18nService) i18n: I18nService, @Inject(SocketService) socket: SocketService,
        @Inject(CommonService) common: CommonService, @Inject(JsonViewDialogService) jsonViewDialog: JsonViewDialogService,
        @Inject(KeyNewOrSetDialogService) keyNewOrSetDialog: KeyNewOrSetDialogService,
        @Inject(BreakpointObserver) breakpointObserver: BreakpointObserver,
        @Inject(MainCommandService) cmd: MainCommandService,
        @Inject(ChangeDetectorRef) cdr: ChangeDetectorRef,
        @Inject(RedisStateService) redisState: RedisStateService,
        @Inject(SettingsService) settingsService: SettingsService,
    ) {
        super(i18n, socket, common, jsonViewDialog, keyNewOrSetDialog, breakpointObserver, cmd, cdr, redisState, settingsService);
        this.paging = new KeyPaging({ settingsService });
    }

    ngOnInit(): void { this.updatePaging(); }
    ngOnChanges(c: SimpleChanges): void { if (c['p3xrValue']) this.updatePaging(); }

    updatePaging(): void {
        if (!this.p3xrValue) return;
        this.paging.figurePaging(this.p3xrValue.length);
        this.updatePagedItems();
    }

    updatePagedItems(): void {
        if (!this.p3xrValue) { this.pagedItems = []; return; }
        this.pagedItems = this.p3xrValue.slice(this.paging.startIndex, this.paging.endIndex)
            .map((v: any, i: number) => ({ index: this.paging.startIndex + i, value: v }));
    }

    async addSet(event: Event): Promise<void> {
        try {
            await this.keyNewOrSetDialog.show({ $event: event, type: 'append', model: { type: 'set', key: this.p3xrKey } });
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    async deleteSetMember(index: number, event: Event): Promise<void> {
        try {
            await this.common.confirm({ message: this.i18n.strings().confirm?.deleteSetMember });
            await this.socket.request({ action: 'key-set-delete-member', payload: { key: this.p3xrKey, value: this.p3xrValueBuffer[index] } });
            this.common.toast(this.i18n.strings().status?.deletedSetMember);
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    async editValue(index: number, value: any, event: Event): Promise<void> {
        try {
            const editValue = typeof value === 'string' && value.length >= this.maxValueAsBuffer
                ? this.p3xrValueBuffer[index] : value;
            await this.keyNewOrSetDialog.show({
                $event: event, type: 'edit',
                model: { type: 'set', key: this.p3xrKey, value: editValue },
            });
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    copyItem(value: any): void { this.copy(value); }
    showJsonItem(value: any, event: Event): void { this.showJson(value, event); }
    downloadItem(index: number): void { this.downloadBuffer(this.p3xrValueBuffer[index]); }
}

<p3xr-key-pager-inline [paging]="paging" (pageChanged)="updatePagedItems()"></p3xr-key-pager-inline>
<div class="p3xr-key-type-table">
    <div class="p3xr-key-type-header">
        <span style="flex: 95%">{{ strings?.page?.key?.set?.table?.value || 'Member' }}</span>
        <span style="flex: 5%; text-align: right">
            @if (!isReadonly) {
                <button mat-icon-button (click)="addSet($event)" matTooltip="Add">
                    <mat-icon>add</mat-icon>
                </button>
            }
        </span>
    </div>
    @for (item of pagedItems; track item.index) {
        <div class="p3xr-key-type-row">
            <span class="p3xr-value-col" [class.p3xr-pre]="valueFormat !== 'hex'" style="flex: 95%; cursor: pointer" (click)="editValue(item.index, item.value, $event)">@if (valueFormat === 'hex') {<p3xr-hex-monitor [value]="truncateDisplay(item.value)" [truncated]="isTruncated(item.value)"></p3xr-hex-monitor>} @else {{{ formatValue(truncateDisplay(item.value)) }}@if (isTruncated(item.value)) {<span style="opacity: 0.5;">...</span>}}</span>
            <span style="flex: 5%; text-align: right" class="p3xr-key-type-row-actions">
                @if (!isReadonly) { <mat-icon class="icon-warn" (click)="deleteSetMember(item.index, $event)" matTooltip="Delete">delete</mat-icon> }
                <mat-icon class="icon-accent" (click)="showJsonItem(item.value, $event)" matTooltip="JSON">table_chart</mat-icon>
                <mat-icon class="icon-accent" (click)="copyItem(item.value)" matTooltip="Copy">content_copy</mat-icon>
                <mat-icon class="icon-accent" (click)="downloadItem(item.index)" matTooltip="Download">download</mat-icon>
                @if (!isReadonly) { <mat-icon class="icon-primary" (click)="editValue(item.index, item.value, $event)" matTooltip="Edit">edit</mat-icon> }
            </span>
        </div>
    }
</div>

// src/vue/pages/database/key/KeySet.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import HexMonitor from './HexMonitor.vue'
import KeyPagerInline from './KeyPagerInline.vue'
import KeyNewOrSetDialog from '../../../dialogs/KeyNewOrSetDialog.vue'
import JsonViewDialog from '../../../dialogs/JsonViewDialog.vue'
import { useI18nStore } from '../../../stores/i18n'
import { useRedisStateStore } from '../../../stores/redis-state'
import { useCommonStore } from '../../../stores/common'
import { request } from '../../../stores/socket.service'
import { type Paging, createPaging, rePaging, formatValue, truncateDisplay, isTruncated, copyToClipboard, downloadBuffer, str } from './key-type-base'

const props = defineProps<{ response: any; value: any; valueBuffer: any; keyName: string; valueFormat: string }>()
const emit = defineEmits<{ refresh: [] }>()
const strings = computed(() => useI18nStore().strings)
const isReadonly = computed(() => useRedisStateStore().connection?.readonly === true)
const common = useCommonStore()

const paging = ref<Paging>(createPaging(0))
const pagedItems = ref<Array<{ index: number; value: any }>>([])
const editDialogOpen = ref(false)
const editDialogData = ref<any>(null)
const jsonViewOpen = ref(false)
const jsonViewValue = ref('')

function updatePaged(p: Paging) {
    paging.value = p
    if (!props.value) { pagedItems.value = []; return }
    pagedItems.value = props.value.slice(p.startIndex, p.endIndex).map((v: any, i: number) => ({ index: p.startIndex + i, value: v }))
}
watch(() => props.value, () => { if (props.value) updatePaged(rePaging(paging.value, props.value.length)) }, { immediate: true })

function addItem() { editDialogData.value = { type: 'append', model: { type: 'set', key: props.keyName } }; editDialogOpen.value = true }
function editItem(index: number, val: any) { editDialogData.value = { type: 'edit', model: { type: 'set', key: props.keyName, value: val } }; editDialogOpen.value = true }
function handleEditClose(r?: any) { editDialogOpen.value = false; editDialogData.value = null; if (r) emit('refresh') }
async function deleteItem(index: number) {
    try { await common.confirm({ message: str(strings.value?.confirm?.deleteSetMember) }); await request({ action: 'key/set-delete-member', payload: { key: props.keyName, value: props.valueBuffer?.[index] } }); common.toast(str(strings.value?.status?.deletedSetMember)); emit('refresh') }
    catch (e) { if (e !== undefined) common.generalHandleError(e) }
}
</script>

<template>
    <div>
        <KeyPagerInline :paging="paging" @page-changed="updatePaged" />
        <div class="p3xr-key-table-header">
            <span style="flex:95%;">{{ str(strings?.page?.key?.set?.table?.value) }}</span>
            <span style="flex:5%;text-align:right;display:flex;justify-content:flex-end;align-items:center;"><v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.add)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" style="cursor:pointer;color:inherit;" @click="addItem">mdi-plus</v-icon></template></v-tooltip></span>
        </div>
        <div v-for="(item, i) in pagedItems" :key="item.index" class="p3xr-key-table-row" :class="{ 'p3xr-key-table-odd': i % 2 === 0 }">
            <span class="p3xr-key-table-value" style="flex:95%;" @click="!isReadonly && editItem(item.index, item.value)">
                <HexMonitor v-if="valueFormat === 'hex'" :value="truncateDisplay(item.value)" />
                <template v-else>{{ truncateDisplay(formatValue(item.value, valueFormat)) }}<span v-if="isTruncated(item.value)" style="opacity:0.5;">...</span></template>
            </span>
            <span style="flex:5%;" class="p3xr-key-table-actions">
                <v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.delete)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-error));" @click="deleteItem(item.index)">mdi-delete</v-icon></template></v-tooltip>
                <v-tooltip :text="str(strings?.intention?.jsonViewShow)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="jsonViewValue = String(item.value ?? ''); jsonViewOpen = true">mdi-file-tree</v-icon></template></v-tooltip>
                <v-tooltip :text="str(strings?.intention?.copy)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="copyToClipboard(String(item.value ?? ''))">mdi-content-copy</v-icon></template></v-tooltip>
                <v-tooltip :text="str(strings?.intention?.downloadBuffer)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="downloadBuffer(valueBuffer?.[item.index], keyName)">mdi-download</v-icon></template></v-tooltip>
                <v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.edit)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-primary));" @click="editItem(item.index, item.value)">mdi-pencil</v-icon></template></v-tooltip>
            </span>
        </div>
        <KeyNewOrSetDialog :open="editDialogOpen" :data="editDialogData" @close="handleEditClose" />
        <JsonViewDialog :open="jsonViewOpen" :value="jsonViewValue" @close="jsonViewOpen = false" />
    </div>
</template>
<style src="./key-table.css"></style>
