// src/ng/dialogs/ai-settings-dialog.component.ts
import { Component, Inject, ViewEncapsulation, ChangeDetectorRef, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatToolbarModule } from '@angular/material/toolbar';
import { DialogCancelButtonComponent } from '../components/dialog-cancel-button.component';
import { I18nService } from '../services/i18n.service';
import { SocketService } from '../services/socket.service';
import { CommonService } from '../services/common.service';
import { RedisStateService } from '../services/redis-state.service';

@Component({
    selector: 'p3xr-ai-settings-dialog',
    standalone: true,
    imports: [
        CommonModule, FormsModule,
        MatDialogModule, MatFormFieldModule, MatInputModule,
        MatButtonModule, MatIconModule, MatToolbarModule,
        DialogCancelButtonComponent,
    ],
    template: `
        <form (ngSubmit)="save()" novalidate>
            <mat-toolbar class="p3xr-dialog-toolbar p3xr-mat-layout-strong">
                <span mat-dialog-title class="p3xr-dialog-title">
                    {{ strings().label?.aiSettings || 'AI Settings' }}
                </span>
                <button mat-icon-button type="button" (click)="cancel()">
                    <mat-icon>close</mat-icon>
                </button>
            </mat-toolbar>

            <mat-dialog-content class="p3xr-dialog-content">
                <div class="p3xr-padding">
                    <div style="margin-bottom: 16px; opacity: 0.8; font-size: 13px;">
                        {{ strings().label?.aiGroqApiKeyInfo || 'Optional. Your own Groq API key for better performance. Get a free key from' }}
                        <a href="https://console.groq.com" target="_blank" style="color: inherit; text-decoration: underline;">console.groq.com</a>
                    </div>

                    <mat-form-field style="width: 100%;" subscriptSizing="dynamic">
                        <mat-label>{{ strings().label?.aiGroqApiKey || 'Groq API Key' }}</mat-label>
                        <input matInput type="password" name="apiKey" [(ngModel)]="apiKey"
                               [placeholder]="strings().label?.aiGroqApiKeyPlaceholder || 'gsk_...'" />
                    </mat-form-field>
                </div>
            </mat-dialog-content>

            <mat-dialog-actions class="p3xr-dialog-actions">
                <p3xr-dialog-cancel (cancel)="cancel()"></p3xr-dialog-cancel>
                <button mat-raised-button class="btn-primary" type="submit" [disabled]="saving">
                    <mat-icon>save</mat-icon>
                    {{ strings().intention?.save || 'Save' }}
                </button>
            </mat-dialog-actions>
        </form>
    `,
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AiSettingsDialogComponent {
    strings;
    apiKey = '';
    saving = false;

    constructor(
        @Inject(MatDialogRef) private dialogRef: MatDialogRef<AiSettingsDialogComponent>,
        @Inject(I18nService) private i18n: I18nService,
        @Inject(SocketService) private socket: SocketService,
        @Inject(CommonService) private common: CommonService,
        @Inject(ChangeDetectorRef) private cdr: ChangeDetectorRef,
        @Inject(RedisStateService) private state: RedisStateService,
    ) {
        this.strings = this.i18n.strings;
    }

    cancel(): void {
        this.dialogRef.close();
    }

    async save(): Promise<void> {
        this.saving = true;
        this.cdr.markForCheck();
        try {
            const key = this.apiKey.trim();

            if (key) {
                const validation = await this.socket.request({
                    action: 'ai/validate-groq-api-key',
                    payload: { apiKey: key },
                });
                if (!validation.valid) {
                    this.common.toast({ message: this.strings().label?.aiGroqApiKeyInvalid || 'Invalid Groq API key' });
                    return;
                }
            }

            await this.socket.request({
                action: 'ai/set-groq-api-key',
                payload: { apiKey: key, aiEnabled: this.state.cfg()?.aiEnabled !== false, aiUseOwnKey: this.state.cfg()?.aiUseOwnKey === true },
            });
            const cfg = { ...this.state.cfg(), groqApiKey: key || '' };
            this.state.cfg.set(cfg);
            this.common.toast({ message: this.strings().label?.aiGroqApiKeySaved || 'AI settings saved' });
            this.dialogRef.close();
        } catch (e: any) {
            this.common.generalHandleError(e);
        } finally {
            this.saving = false;
            this.cdr.markForCheck();
        }
    }
}

// src/vue/dialogs/AiSettingsDialog.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useDisplay } from 'vuetify'
import { useI18nStore } from '../stores/i18n'
import { useRedisStateStore } from '../stores/redis-state'
import { useCommonStore } from '../stores/common.store'
import { useOverlayStore } from '../stores/overlay.store'
import { request } from '../stores/socket.service'
import P3xrDialog from '../components/P3xrDialog.vue'

const props = defineProps<{ open: boolean }>()
const emit = defineEmits<{ close: [] }>()

const i18n = useI18nStore()
const strings = computed(() => i18n.strings)
const state = useRedisStateStore()
const common = useCommonStore()
const overlay = useOverlayStore()
const { width } = useDisplay()
const isWide = computed(() => width.value >= 600)

const apiKey = ref('')

watch(() => props.open, (v) => { if (v) apiKey.value = '' })

async function submit() {
    try {
        const trimmedKey = apiKey.value.trim()
        if (trimmedKey) {
            overlay.show({ message: strings.value?.title?.connectingRedis })
            let validation: any
            try {
                validation = await request({ action: 'ai/validate-groq-api-key', payload: { apiKey: trimmedKey } })
            } catch (e) { common.generalHandleError(e); return }
            finally { overlay.hide() }
            if (!validation.valid) {
                common.toast(strings.value?.label?.aiGroqApiKeyInvalid || 'Invalid Groq API key')
                return
            }
        }
        await request({
            action: 'ai/set-groq-api-key',
            payload: { apiKey: trimmedKey, aiEnabled: state.cfg?.aiEnabled !== false, aiUseOwnKey: state.cfg?.aiUseOwnKey === true },
        })
        state.cfg = { ...state.cfg, hasGroqApiKey: !!(trimmedKey && trimmedKey.startsWith('gsk_') && trimmedKey.length > 20) }
        common.toast(strings.value?.status?.saved)
        emit('close')
    } catch (e) { common.generalHandleError(e) }
}
</script>

<template>
    <P3xrDialog v-if="open" :open="true" :title="strings?.label?.aiSettings || 'AI Settings'" @close="emit('close')">
        <div style="margin-bottom: 16px; font-size: 14px; opacity: 0.8;">
            {{ strings?.label?.aiGroqApiKeyInfo }}
            <a href="https://console.groq.com" target="_blank" rel="noreferrer"
                style="color: inherit; text-decoration: underline;">console.groq.com</a>
        </div>
        <v-text-field
            v-model="apiKey"
            :label="strings?.label?.aiGroqApiKey"
            placeholder="gsk_..."
            type="password"
            variant="outlined"
            density="comfortable"
            hide-details
            autocomplete="off"
        />

        <template #actions>
            <v-btn variant="flat" color="warning" @click="emit('close')">
                <v-icon :class="{ 'mr-1': isWide }">mdi-close-circle</v-icon>
                <span v-if="isWide">{{ strings?.intention?.cancel }}</span>
                <v-tooltip v-if="!isWide" activator="parent" location="top">{{ strings?.intention?.cancel }}</v-tooltip>
            </v-btn>
            <v-btn variant="flat" color="primary" @click="submit">
                <v-icon class="mr-1">mdi-check</v-icon>
                <span>{{ strings?.intention?.save }}</span>
            </v-btn>
        </template>
    </P3xrDialog>
</template>
