// src/react/dialogs/AskAuthorizationDialog.tsx
import { useState, useEffect } from 'react'
import {
    Button, IconButton, Tooltip, TextField, useMediaQuery,
    InputAdornment, Box,
} from '@mui/material'
import { Done, Cancel, Visibility, VisibilityOff, Person, Lock, Shield } from '@mui/icons-material'
import { useCommonStore } from '../stores/common.store'
import { useI18nStore } from '../stores/i18n.store'
import P3xrDialog from '../components/P3xrDialog'

export default function AskAuthorizationDialog() {
    const { askAuthOpen, resolveAskAuth } = useCommonStore()
    const strings = useI18nStore(s => s.strings)
    const isWide = useMediaQuery('(min-width: 600px)')
    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')
    const [pwVisible, setPwVisible] = useState(false)

    useEffect(() => {
        if (askAuthOpen) {
            setUsername('')
            setPassword('')
            setPwVisible(false)
        }
    }, [askAuthOpen])

    if (!askAuthOpen) return null

    const handleOk = () => {
        resolveAskAuth?.({ username, password })
    }

    const handleCancel = () => {
        resolveAskAuth?.(null)
    }

    return (
        <P3xrDialog
            open
            onClose={handleCancel}
            title={<><Shield sx={{ mr: 1, verticalAlign: 'middle', fontSize: 20 }} />{strings?.label?.askAuth}</>}
            width="400px"
            actions={
                <>
                    {isWide ? (
                        <Button variant="contained" color="error" onClick={handleCancel}>
                            <Cancel fontSize="small" /><span style={{ marginLeft: 3 }}>{strings?.intention?.cancel}</span>
                        </Button>
                    ) : (
                        <Tooltip title={strings?.intention?.cancel} placement="top">
                            <IconButton color="error" onClick={handleCancel} sx={{ borderRadius: '4px' }}>
                                <Cancel fontSize="small" />
                            </IconButton>
                        </Tooltip>
                    )}
                    {isWide ? (
                        <Button variant="contained" color="primary" onClick={handleOk}>
                            <Done fontSize="small" /><span style={{ marginLeft: 3 }}>{strings?.intention?.ok}</span>
                        </Button>
                    ) : (
                        <Tooltip title={strings?.intention?.ok} placement="top">
                            <IconButton color="primary" onClick={handleOk} sx={{ borderRadius: '4px' }}>
                                <Done fontSize="small" />
                            </IconButton>
                        </Tooltip>
                    )}
                </>
            }
        >
            <Box sx={{ fontSize: 12, opacity: 0.7, mb: 0.5 }}>{strings?.label?.aclAuthHint}</Box>
            <TextField
                autoFocus fullWidth margin="dense"
                label={strings?.form?.connection?.label?.username}
                value={username}
                onChange={e => setUsername(e.target.value)}
                autoComplete="off"
                onKeyDown={e => e.key === 'Enter' && handleOk()}
                slotProps={{
                    input: {
                        startAdornment: (
                            <InputAdornment position="start"><Person fontSize="small" /></InputAdornment>
                        ),
                    },
                }}
            />
            <TextField
                fullWidth margin="dense"
                label={strings?.form?.connection?.label?.password}
                type={pwVisible ? 'text' : 'password'}
                value={password}
                onChange={e => setPassword(e.target.value)}
                autoComplete="off"
                onKeyDown={e => e.key === 'Enter' && handleOk()}
                slotProps={{
                    input: {
                        startAdornment: (
                            <InputAdornment position="start"><Lock fontSize="small" /></InputAdornment>
                        ),
                        endAdornment: (
                            <InputAdornment position="end">
                                <IconButton onClick={() => setPwVisible(!pwVisible)} size="small">
                                    {pwVisible ? <VisibilityOff fontSize="small" /> : <Visibility fontSize="small" />}
                                </IconButton>
                            </InputAdornment>
                        ),
                    },
                }}
            />
        </P3xrDialog>
    )
}

// src/vue/dialogs/AskAuthorizationDialog.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import P3xrDialog from '../components/P3xrDialog.vue'
import { useCommonStore } from '../stores/common.store'
import { useI18nStore } from '../stores/i18n'

const common = useCommonStore()
const strings = computed(() => useI18nStore().strings)

const username = ref('')
const password = ref('')
const pwVisible = ref(false)

watch(() => common.askAuthOpen, (open) => {
    if (open) {
        username.value = ''
        password.value = ''
        pwVisible.value = false
    }
})

function handleOk() {
    common.resolveAskAuth?.({ username: username.value, password: password.value })
}

function handleCancel() {
    common.resolveAskAuth?.(null)
}

function str(val: any, opts?: any): string {
    if (typeof val === 'function') return val(opts)
    return val ?? ''
}
</script>

<template>
    <P3xrDialog
        :open="common.askAuthOpen"
        :title="str(strings?.label?.askAuth)"
        icon="mdi-shield"
        width="400px"
        :full-screen-on-mobile="false"
        @close="handleCancel"
    >
        <div style="font-size: 12px; opacity: 0.7; margin-bottom: 8px;">{{ strings?.label?.aclAuthHint }}</div>
        <v-text-field
            v-model="username" autofocus
            :label="str(strings?.form?.connection?.label?.username)"
            autocomplete="off" density="comfortable" variant="outlined" hide-details class="mb-3"
            @keydown.enter="handleOk"
        >
            <template #prepend-inner>
                <v-icon size="20">mdi-account</v-icon>
            </template>
        </v-text-field>
        <v-text-field
            v-model="password"
            :label="str(strings?.form?.connection?.label?.password)"
            :type="pwVisible ? 'text' : 'password'"
            autocomplete="off" density="comfortable" variant="outlined" hide-details
            @keydown.enter="handleOk"
        >
            <template #prepend-inner>
                <v-icon size="20">mdi-lock</v-icon>
            </template>
            <template #append-inner>
                <v-icon size="20" style="cursor:pointer;" @click="pwVisible = !pwVisible">
                    {{ pwVisible ? 'mdi-eye-off' : 'mdi-eye' }}
                </v-icon>
            </template>
        </v-text-field>

        <template #actions>
            <v-btn color="error" variant="flat" @click="handleCancel">
                <v-icon size="20" class="mr-1">mdi-close-circle</v-icon>
                {{ str(strings?.intention?.cancel) }}
            </v-btn>
            <v-btn color="primary" variant="flat" @click="handleOk">
                <v-icon size="20" class="mr-1">mdi-check</v-icon>
                {{ str(strings?.intention?.ok) }}
            </v-btn>
        </template>
    </P3xrDialog>
</template>
