// src/ng/dialogs/ask-authorization-dialog.component.ts
import { Component, Inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatToolbarModule } from '@angular/material/toolbar';
import { DialogCancelButtonComponent } from '../components/dialog-cancel-button.component';
import { I18nService } from '../services/i18n.service';

/**
 * Ask Authorization dialog — Angular replacement for p3xrDialogAskAuthorization.
 * Simple username/password form. Returns { username, password } on submit.
 */
@Component({
    selector: 'p3xr-ask-authorization-dialog',
    standalone: true,
    imports: [
        CommonModule, FormsModule,
        MatDialogModule, MatFormFieldModule, MatInputModule,
        MatButtonModule, MatIconModule, MatToolbarModule,
        DialogCancelButtonComponent,
    ],
    template: `
        <form (ngSubmit)="submit()" novalidate>
            <mat-toolbar class="p3xr-dialog-toolbar p3xr-mat-layout-strong">
                <span mat-dialog-title class="p3xr-dialog-title">
                    <mat-icon style="margin-right: 8px; vertical-align: middle;">shield</mat-icon>
                    {{ strings().label?.askAuth }}
                </span>
                <button mat-icon-button type="button" (click)="cancel()">
                    <mat-icon>close</mat-icon>
                </button>
            </mat-toolbar>

            <mat-dialog-content class="p3xr-dialog-content">
                <div style="font-size: 12px; opacity: 0.7; margin-bottom: 8px;">
                    {{ strings().label?.aclAuthHint }}
                </div>
                <mat-form-field class="full-width">
                    <mat-label>{{ strings().form?.connection?.label?.username }}</mat-label>
                    <mat-icon matPrefix>person</mat-icon>
                    <input matInput name="username" type="text" [(ngModel)]="model.username" autocomplete="off" />
                </mat-form-field>

                <mat-form-field class="full-width">
                    <mat-label>{{ strings().form?.connection?.label?.password }}</mat-label>
                    <mat-icon matPrefix>lock</mat-icon>
                    <input matInput name="password" type="password" [(ngModel)]="model.password" autocomplete="off" />
                </mat-form-field>
            </mat-dialog-content>

            <mat-dialog-actions class="p3xr-dialog-actions">
                <p3xr-dialog-cancel (cancel)="cancel()"></p3xr-dialog-cancel>
                <button mat-raised-button class="btn-primary" type="submit">
                    <mat-icon>done</mat-icon>
                    {{ strings().intention?.ok }}
                </button>
            </mat-dialog-actions>
        </form>
    `,
    styles: [`
        .full-width { width: 100%; }
        .p3xr-dialog-content { min-width: 300px; }
    `],
})
export class AskAuthorizationDialogComponent {
    model = { username: '', password: '' };
    strings;

    constructor(
        @Inject(MatDialogRef) private dialogRef: MatDialogRef<AskAuthorizationDialogComponent>,
        @Inject(I18nService) private i18n: I18nService,
    ) {
        this.strings = this.i18n.strings;
    }

    submit(): void {
        this.dialogRef.close(this.model);
    }

    cancel(): void {
        this.dialogRef.close(undefined);
    }
}

// src/vue/dialogs/AskAuthorizationDialog.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import P3xrDialog from '../components/P3xrDialog.vue'
import { useCommonStore } from '../stores/common.store'
import { useI18nStore } from '../stores/i18n'

const common = useCommonStore()
const strings = computed(() => useI18nStore().strings)

const username = ref('')
const password = ref('')
const pwVisible = ref(false)

watch(() => common.askAuthOpen, (open) => {
    if (open) {
        username.value = ''
        password.value = ''
        pwVisible.value = false
    }
})

function handleOk() {
    common.resolveAskAuth?.({ username: username.value, password: password.value })
}

function handleCancel() {
    common.resolveAskAuth?.(null)
}

function str(val: any, opts?: any): string {
    if (typeof val === 'function') return val(opts)
    return val ?? ''
}
</script>

<template>
    <P3xrDialog
        :open="common.askAuthOpen"
        :title="str(strings?.label?.askAuth)"
        icon="mdi-shield"
        width="400px"
        :full-screen-on-mobile="false"
        @close="handleCancel"
    >
        <div style="font-size: 12px; opacity: 0.7; margin-bottom: 8px;">{{ strings?.label?.aclAuthHint }}</div>
        <v-text-field
            v-model="username" autofocus
            :label="str(strings?.form?.connection?.label?.username)"
            autocomplete="off" density="comfortable" variant="outlined" hide-details class="mb-3"
            @keydown.enter="handleOk"
        >
            <template #prepend-inner>
                <v-icon size="20">mdi-account</v-icon>
            </template>
        </v-text-field>
        <v-text-field
            v-model="password"
            :label="str(strings?.form?.connection?.label?.password)"
            :type="pwVisible ? 'text' : 'password'"
            autocomplete="off" density="comfortable" variant="outlined" hide-details
            @keydown.enter="handleOk"
        >
            <template #prepend-inner>
                <v-icon size="20">mdi-lock</v-icon>
            </template>
            <template #append-inner>
                <v-icon size="20" style="cursor:pointer;" @click="pwVisible = !pwVisible">
                    {{ pwVisible ? 'mdi-eye-off' : 'mdi-eye' }}
                </v-icon>
            </template>
        </v-text-field>

        <template #actions>
            <v-btn color="error" variant="flat" @click="handleCancel">
                <v-icon size="20" class="mr-1">mdi-close-circle</v-icon>
                {{ str(strings?.intention?.cancel) }}
            </v-btn>
            <v-btn color="primary" variant="flat" @click="handleOk">
                <v-icon size="20" class="mr-1">mdi-check</v-icon>
                {{ str(strings?.intention?.ok) }}
            </v-btn>
        </template>
    </P3xrDialog>
</template>
