// src/ng/dialogs/diff-dialog.component.ts
import { Component, Inject, ChangeDetectionStrategy, ViewEncapsulation, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MAT_DIALOG_DATA, MatDialogRef, MatDialogModule } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { BreakpointObserver } from '@angular/cdk/layout';
import { diffLines, Change } from 'diff';
import { I18nService } from '../services/i18n.service';
import { DialogCancelButtonComponent } from '../components/dialog-cancel-button.component';

export interface DiffDialogData {
    keyName: string;
    fieldName?: string;
    oldValue: string;
    newValue: string;
}

interface DiffBlock {
    type: 'added' | 'removed' | 'unchanged' | 'collapse';
    lines: string[];
    collapsedCount?: number;
    expanded?: boolean;
}

const CONTEXT_LINES = 3;

@Component({
    selector: 'p3xr-diff-dialog',
    standalone: true,
    imports: [
        CommonModule, MatDialogModule, MatButtonModule, MatIconModule,
        MatToolbarModule, MatTooltipModule, MatButtonToggleModule,
        DialogCancelButtonComponent,
    ],
    changeDetection: ChangeDetectionStrategy.OnPush,
    encapsulation: ViewEncapsulation.None,
    template: `
        <mat-toolbar class="p3xr-dialog-toolbar p3xr-mat-layout-strong">
            <span mat-dialog-title class="p3xr-dialog-title p3xr-dialog-title-with-icon" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                <mat-icon>difference</mat-icon>
                <span>{{ diffStrings().reviewChanges || 'Review changes' }}</span>
            </span>
            <span style="flex: 1;"></span>
            <mat-button-toggle-group [value]="mode()" (change)="mode.set($event.value)" class="p3xr-diff-toggle" [hideSingleSelectionIndicator]="true">
                <mat-button-toggle value="inline">{{ diffStrings().inline || 'Inline' }}</mat-button-toggle>
                <mat-button-toggle value="side-by-side">{{ diffStrings().sideBySide || 'Side by side' }}</mat-button-toggle>
            </mat-button-toggle-group>
            <span class="p3xr-diff-summary-header">
                <span class="p3xr-diff-count-add">+{{ additions() }}</span> {{ diffStrings().additions || 'additions' }},
                <span class="p3xr-diff-count-del">-{{ deletions() }}</span> {{ diffStrings().deletions || 'deletions' }}
            </span>
            <button mat-icon-button (click)="dialogRef.close(false)"><mat-icon>close</mat-icon></button>
        </mat-toolbar>

        <mat-dialog-content class="p3xr-dialog-content p3xr-diff-content" [class.p3xr-diff-sbs]="mode() === 'side-by-side'">
            @if (mode() === 'inline') {
                @for (block of blocks(); track $index) {
                    @if (block.type === 'collapse' && !block.expanded) {
                        <div class="p3xr-diff-collapse" (click)="expandBlock($index)">... {{ block.collapsedCount }} {{ diffStrings().unchangedLines || 'unchanged lines' }} ...</div>
                    } @else {
                        @for (line of block.lines; track $index) {
                            <div class="p3xr-diff-line" [class.p3xr-diff-added]="block.type === 'added'" [class.p3xr-diff-removed]="block.type === 'removed'" [class.p3xr-diff-unchanged]="block.type === 'unchanged' || block.type === 'collapse'">
                                <span class="p3xr-diff-prefix">{{ block.type === 'added' ? '+' : block.type === 'removed' ? '-' : ' ' }}</span>{{ line }}
                            </div>
                        }
                    }
                }
            } @else {
                <div class="p3xr-diff-side">
                    <div class="p3xr-diff-side-header">{{ diffStrings().before || 'Before' }}</div>
                    @for (block of blocks(); track $index) {
                        @if (block.type === 'collapse' && !block.expanded) {
                            <div class="p3xr-diff-collapse" (click)="expandBlock($index)">... {{ block.collapsedCount }} {{ diffStrings().unchangedLines || 'unchanged lines' }} ...</div>
                        } @else if (block.type !== 'added') {
                            @for (line of block.lines; track $index) {
                                <div class="p3xr-diff-line" [class.p3xr-diff-removed]="block.type === 'removed'" [class.p3xr-diff-unchanged]="block.type === 'unchanged' || block.type === 'collapse'">{{ line }}</div>
                            }
                        }
                    }
                </div>
                <div class="p3xr-diff-side">
                    <div class="p3xr-diff-side-header">{{ diffStrings().after || 'After' }}</div>
                    @for (block of blocks(); track $index) {
                        @if (block.type === 'collapse' && !block.expanded) {
                            <div class="p3xr-diff-collapse" (click)="expandBlock($index)">... {{ block.collapsedCount }} {{ diffStrings().unchangedLines || 'unchanged lines' }} ...</div>
                        } @else if (block.type !== 'removed') {
                            @for (line of block.lines; track $index) {
                                <div class="p3xr-diff-line" [class.p3xr-diff-added]="block.type === 'added'" [class.p3xr-diff-unchanged]="block.type === 'unchanged' || block.type === 'collapse'">{{ line }}</div>
                            }
                        }
                    }
                </div>
            }
        </mat-dialog-content>

        <mat-dialog-actions class="p3xr-dialog-actions">
            <p3xr-dialog-cancel (cancel)="dialogRef.close(false)"></p3xr-dialog-cancel>
            <button mat-raised-button class="btn-primary" (click)="dialogRef.close(true)"
                [matTooltip]="strings().intention?.save || 'Save'" [matTooltipDisabled]="isWide">
                <mat-icon>save</mat-icon>
                @if (isWide) { <span>{{ strings().intention?.save || 'Save' }}</span> }
            </button>
        </mat-dialog-actions>
    `,
    styles: [`
        .p3xr-diff-content {
            font-family: 'Roboto Mono', monospace;
            font-size: 13px;
            padding: 0 !important;
            min-height: 200px;
            max-height: 60vh;
            overflow: auto;
        }
        .p3xr-diff-sbs {
            display: grid;
            grid-template-columns: 1fr 1fr;
        }
        .p3xr-diff-side {
            overflow: auto;
            &:first-child { border-right: 1px solid rgba(128,128,128,0.2); }
        }
        .p3xr-diff-side-header {
            padding: 4px 8px;
            font-weight: 500;
            position: sticky;
            top: 0;
            z-index: 1;
            border-bottom: 1px solid rgba(128,128,128,0.2);
            background: var(--p3xr-content-bg, inherit);
        }
        .p3xr-diff-line {
            padding: 1px 8px;
            white-space: pre-wrap;
            word-break: break-all;
        }
        .p3xr-diff-prefix {
            display: inline-block;
            width: 16px;
            font-weight: 700;
            user-select: none;
        }
        .p3xr-diff-added { background: rgba(76,175,80,0.12); }
        .p3xr-diff-removed { background: rgba(244,67,54,0.12); }
        .p3xr-diff-unchanged { opacity: 0.6; }
        .p3xr-diff-collapse {
            padding: 4px 8px;
            opacity: 0.4;
            font-style: italic;
            cursor: pointer;
            &:hover { opacity: 0.7; }
        }
        .p3xr-diff-toggle {
            height: 28px;
            margin-right: 4px;
            border-radius: 4px !important;
            overflow: hidden;
            border: 1px solid rgba(255,255,255,0.3) !important;

            .mat-button-toggle {
                height: 28px;
                font-size: 12px;
                border: none !important;
                border-left: 1px solid rgba(255,255,255,0.3) !important;
                border-radius: 0 !important;
                background: transparent;
                color: rgba(255,255,255,0.7);
            }
            .mat-button-toggle:first-child {
                border-left: none !important;
            }
            .mat-button-toggle-checked {
                background: rgba(255,255,255,0.15) !important;
                color: rgba(255,255,255,0.95) !important;
            }
            .mat-button-toggle-button {
                height: 28px;
            }
            .mat-button-toggle-label-content {
                line-height: 28px !important;
                padding: 0 10px !important;
            }
            .mat-pseudo-checkbox,
            .mdc-button__icon {
                display: none !important;
            }
            .mat-button-toggle-button {
                padding: 0 !important;
            }
        }
        .p3xr-diff-summary-header {
            font-size: 12px; opacity: 0.8; white-space: nowrap; margin-left: 8px; margin-right: 4px;
        }
        .p3xr-diff-count-add { color: #81c784; font-weight: 700; }
        .p3xr-diff-count-del { color: #ef9a9a; font-weight: 700; }
    `],
})
export class DiffDialogComponent implements OnInit {
    readonly strings;
    readonly diffStrings;
    readonly mode = signal<'inline' | 'side-by-side'>('inline');
    readonly blocks = signal<DiffBlock[]>([]);
    isWide = true;

    private rawChanges: Change[];
    readonly additions;
    readonly deletions;

    constructor(
        @Inject(MAT_DIALOG_DATA) public data: DiffDialogData,
        @Inject(MatDialogRef) public dialogRef: MatDialogRef<DiffDialogComponent>,
        @Inject(I18nService) private i18n: I18nService,
        @Inject(BreakpointObserver) private breakpointObserver: BreakpointObserver,
    ) {
        this.strings = this.i18n.strings;
        this.diffStrings = computed(() => this.strings()?.diff || {});
        this.rawChanges = diffLines(data.oldValue, data.newValue);
        this.additions = computed(() => this.rawChanges.filter(c => c.added).reduce((n, c) => n + (c.value.split('\n').length - 1 || 1), 0));
        this.deletions = computed(() => this.rawChanges.filter(c => c.removed).reduce((n, c) => n + (c.value.split('\n').length - 1 || 1), 0));
    }

    ngOnInit(): void {
        this.blocks.set(this.buildBlocks());
        this.breakpointObserver.observe('(min-width: 600px)').subscribe(r => {
            this.isWide = r.matches;
        });
    }

    expandBlock(index: number): void {
        const updated = [...this.blocks()];
        const block = { ...updated[index] };
        block.expanded = true;
        block.type = 'unchanged';
        updated[index] = block;
        this.blocks.set(updated);
    }

    private buildBlocks(): DiffBlock[] {
        const blocks: DiffBlock[] = [];
        for (const change of this.rawChanges) {
            const lines = change.value.replace(/\n$/, '').split('\n');
            if (change.added) {
                blocks.push({ type: 'added', lines });
            } else if (change.removed) {
                blocks.push({ type: 'removed', lines });
            } else {
                if (lines.length <= CONTEXT_LINES * 2 + 1) {
                    blocks.push({ type: 'unchanged', lines });
                } else {
                    blocks.push({ type: 'unchanged', lines: lines.slice(0, CONTEXT_LINES) });
                    const collapsed = lines.slice(CONTEXT_LINES, -CONTEXT_LINES);
                    blocks.push({ type: 'collapse', lines: collapsed, collapsedCount: collapsed.length });
                    blocks.push({ type: 'unchanged', lines: lines.slice(-CONTEXT_LINES) });
                }
            }
        }
        return blocks;
    }
}

// src/vue/dialogs/DiffDialog.vue
<script setup lang="ts">
/**
 * DiffDialog — exact port of React DiffDialog.tsx
 * Inline / side-by-side diff view with collapsible context.
 */
import { ref, computed, watch } from 'vue'
import { useDisplay } from 'vuetify'
import { diffLines, type Change } from 'diff'
import { useI18nStore } from '../stores/i18n'
import P3xrDialog from '../components/P3xrDialog.vue'

interface DiffBlock {
    type: 'added' | 'removed' | 'unchanged' | 'collapse'
    lines: string[]
    collapsedCount?: number
}

const CONTEXT_LINES = 3

function buildBlocks(changes: Change[]): DiffBlock[] {
    const blocks: DiffBlock[] = []
    for (const change of changes) {
        const lines = change.value.replace(/\n$/, '').split('\n')
        if (change.added) {
            blocks.push({ type: 'added', lines })
        } else if (change.removed) {
            blocks.push({ type: 'removed', lines })
        } else {
            if (lines.length <= CONTEXT_LINES * 2 + 1) {
                blocks.push({ type: 'unchanged', lines })
            } else {
                blocks.push({ type: 'unchanged', lines: lines.slice(0, CONTEXT_LINES) })
                const collapsed = lines.slice(CONTEXT_LINES, -CONTEXT_LINES)
                blocks.push({ type: 'collapse', lines: collapsed, collapsedCount: collapsed.length })
                blocks.push({ type: 'unchanged', lines: lines.slice(-CONTEXT_LINES) })
            }
        }
    }
    return blocks
}

const props = defineProps<{
    open: boolean
    keyName: string
    fieldName?: string
    oldValue: string
    newValue: string
}>()

const emit = defineEmits<{
    confirm: []
    cancel: []
}>()

const i18n = useI18nStore()
const strings = computed(() => i18n.strings)
const d = computed(() => strings.value?.diff || {} as any)
const { width } = useDisplay()
const isWide = computed(() => width.value >= 600)

const mode = ref<'inline' | 'side-by-side'>('inline')
const expanded = ref<Set<number>>(new Set())

watch(() => props.open, (v) => {
    if (v) {
        mode.value = 'inline'
        expanded.value = new Set()
    }
})

const changes = computed(() => diffLines(String(props.oldValue ?? ''), String(props.newValue ?? '')))
const blocks = computed(() => buildBlocks(changes.value))
const additions = computed(() => changes.value.filter(c => c.added).reduce((n, c) => n + (c.value.split('\n').length - 1 || 1), 0))
const deletions = computed(() => changes.value.filter(c => c.removed).reduce((n, c) => n + (c.value.split('\n').length - 1 || 1), 0))

function toggleExpand(i: number) {
    const s = new Set(expanded.value)
    s.has(i) ? s.delete(i) : s.add(i)
    expanded.value = s
}

function lineClass(type: string) {
    if (type === 'added') return 'p3xr-diff-added'
    if (type === 'removed') return 'p3xr-diff-removed'
    return 'p3xr-diff-unchanged'
}

const title = computed(() => {
    const prefix = d.value.reviewChanges || 'Review changes'
    const field = props.fieldName ? `${props.fieldName} @ ` : ''
    return `${prefix} — ${field}${props.keyName}`
})
</script>

<template>
    <P3xrDialog v-if="open" :open="true" :title="title" width="800px" :content-padding="false" @close="emit('cancel')">
        <template #headerActions>
            <v-btn-toggle v-model="mode" mandatory density="compact" class="p3xr-diff-mode-toggle" style="margin-right: 4px;">
                <v-btn value="inline" size="x-small">{{ d.inline || 'Inline' }}</v-btn>
                <v-btn value="side-by-side" size="x-small">{{ d.sideBySide || 'Side by side' }}</v-btn>
            </v-btn-toggle>
            <span style="font-size: 12px; opacity: 0.8; margin-right: 4px; white-space: nowrap;">
                <span style="color: #81c784; font-weight: 700;">+{{ additions }}</span> {{ d.additions || 'additions' }},
                <span style="color: #ef9a9a; font-weight: 700;">-{{ deletions }}</span> {{ d.deletions || 'deletions' }}
            </span>
        </template>

        <div class="p3xr-diff-body" :class="{ 'p3xr-diff-side': mode === 'side-by-side' }">
            <!-- Inline mode -->
            <template v-if="mode === 'inline'">
                <div>
                    <template v-for="(block, i) in blocks" :key="i">
                        <div v-if="block.type === 'collapse' && !expanded.has(i)" class="p3xr-diff-collapse" @click="toggleExpand(i)">
                            ... {{ block.collapsedCount }} {{ d.unchangedLines || 'unchanged lines' }} ...
                        </div>
                        <template v-else>
                            <div v-for="(line, j) in block.lines" :key="`${i}-${j}`" :class="lineClass(block.type)" class="p3xr-diff-line">
                                <span class="p3xr-diff-prefix">{{ block.type === 'added' ? '+' : block.type === 'removed' ? '-' : ' ' }}</span>{{ line }}
                            </div>
                        </template>
                    </template>
                </div>
            </template>

            <!-- Side-by-side mode -->
            <template v-else>
                <div style="border-right: 1px solid rgba(var(--v-theme-on-surface), 0.12); overflow: auto;">
                    <div style="padding: 4px 8px; font-weight: 500; border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.12); position: sticky; top: 0; z-index: 1; background: rgb(var(--v-theme-surface));">
                        {{ d.before || 'Before' }}
                    </div>
                    <template v-for="(block, i) in blocks" :key="'l'+i">
                        <div v-if="block.type === 'collapse' && !expanded.has(i)" class="p3xr-diff-collapse" @click="toggleExpand(i)">
                            ... {{ block.collapsedCount }} {{ d.unchangedLines || 'unchanged lines' }} ...
                        </div>
                        <template v-else-if="block.type !== 'added'">
                            <div v-for="(line, j) in block.lines" :key="`l${i}-${j}`" :class="lineClass(block.type)" class="p3xr-diff-line">{{ line }}</div>
                        </template>
                    </template>
                </div>
                <div style="overflow: auto;">
                    <div style="padding: 4px 8px; font-weight: 500; border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.12); position: sticky; top: 0; z-index: 1; background: rgb(var(--v-theme-surface));">
                        {{ d.after || 'After' }}
                    </div>
                    <template v-for="(block, i) in blocks" :key="'r'+i">
                        <div v-if="block.type === 'collapse' && !expanded.has(i)" class="p3xr-diff-collapse" @click="toggleExpand(i)">
                            ... {{ block.collapsedCount }} {{ d.unchangedLines || 'unchanged lines' }} ...
                        </div>
                        <template v-else-if="block.type !== 'removed'">
                            <div v-for="(line, j) in block.lines" :key="`r${i}-${j}`" :class="lineClass(block.type)" class="p3xr-diff-line">{{ line }}</div>
                        </template>
                    </template>
                </div>
            </template>
        </div>

        <template #actions>
            <v-btn variant="flat" color="warning" @click="emit('cancel')">
                <v-icon :class="{ 'mr-1': isWide }">mdi-close-circle</v-icon>
                <span v-if="isWide">{{ strings?.intention?.cancel }}</span>
            </v-btn>
            <v-btn variant="flat" color="primary" @click="emit('confirm')">
                <v-icon :class="{ 'mr-1': isWide }">mdi-check</v-icon>
                <span v-if="isWide">{{ strings?.intention?.save }}</span>
            </v-btn>
        </template>
    </P3xrDialog>
</template>

<style>
.p3xr-diff-body { min-height: 200px; max-height: 60vh; overflow: auto; }
.p3xr-diff-side { display: grid; grid-template-columns: 1fr 1fr; }
.p3xr-diff-line { padding: 1px 8px; white-space: pre-wrap; word-break: break-all; font-family: 'Roboto Mono', monospace; font-size: 13px; }
.p3xr-diff-added { background-color: rgba(76,175,80,0.12); }
.p3xr-diff-removed { background-color: rgba(244,67,54,0.12); }
.p3xr-diff-unchanged { opacity: 0.6; }
.p3xr-diff-collapse { padding: 4px 8px; opacity: 0.4; font-style: italic; cursor: pointer; font-family: 'Roboto Mono', monospace; font-size: 13px; }
.p3xr-diff-collapse:hover { opacity: 0.7; }
.p3xr-diff-prefix { display: inline-block; width: 16px; font-weight: 700; user-select: none; }
.p3xr-diff-mode-toggle .v-btn { padding: 2px 12px !important; font-size: 12px !important; border-radius: 4px !important; text-transform: none !important; }
</style>
