// src/ng/dialogs/ttl-dialog.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatDialogModule, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatToolbarModule } from '@angular/material/toolbar';
import { DialogCancelButtonComponent } from '../components/dialog-cancel-button.component';
import { I18nService } from '../services/i18n.service';
import { CommonService } from '../services/common.service';
import { SettingsService } from '../services/settings.service';

import timestring from 'timestring';
import humanizeDuration from 'humanize-duration';

export interface TtlDialogData {
    model: { ttl: number };
}

/**
 * TTL dialog — Angular replacement for p3xrDialogTtl.
 * Edits TTL value with number input and human-readable timestring input.
 */
@Component({
    selector: 'p3xr-ttl-dialog',
    standalone: true,
    imports: [
        CommonModule, FormsModule,
        MatDialogModule, MatFormFieldModule, MatInputModule,
        MatButtonModule, MatIconModule, MatToolbarModule,
        DialogCancelButtonComponent,
    ],
    template: `
        <form (ngSubmit)="submit()" novalidate>
            <mat-toolbar class="p3xr-dialog-toolbar p3xr-mat-layout-strong">
                <span mat-dialog-title class="p3xr-dialog-title">
                    {{ strings().confirm?.ttl?.title }}
                </span>
                <button mat-icon-button type="button" (click)="cancel()">
                    <mat-icon>close</mat-icon>
                </button>
            </mat-toolbar>

            <mat-dialog-content class="p3xr-dialog-content">
                <div>{{ strings().confirm?.ttl?.textContent }}</div>

                <mat-form-field class="full-width">
                    <mat-label>{{ strings().confirm?.ttl?.placeholder }}</mat-label>
                    <input matInput type="number" name="ttl" [(ngModel)]="model.ttl" min="-1"
                           [placeholder]="strings().confirm?.ttl?.placeholderPlaceholder" />
                </mat-form-field>

                <mat-form-field class="full-width">
                    <mat-label>{{ strings().confirm?.ttl?.convertTextToTime }}</mat-label>
                    <input matInput name="convertTextToTime" [(ngModel)]="convertTextToTime"
                           (ngModelChange)="onTextTimeChange($event)"
                           [placeholder]="strings().confirm?.ttl?.convertTextToTimePlaceholder" />
                </mat-form-field>

                <button mat-button class="btn-accent p3xr-timestring-link" type="button" (click)="openTimestringNpm()">
                    https://www.npmjs.com/package/timestring
                </button>
            </mat-dialog-content>

            <mat-dialog-actions class="p3xr-dialog-actions">
                <p3xr-dialog-cancel (cancel)="cancel()"></p3xr-dialog-cancel>
                <button mat-raised-button class="btn-primary" type="submit">
                    <mat-icon>timer</mat-icon>
                    {{ strings().intention?.ttl }}
                </button>
            </mat-dialog-actions>
        </form>
    `,
    styles: [`
        .full-width { width: 100%; }
    `],
})
export class TtlDialogComponent implements OnInit {
    model: { ttl: number } = { ttl: -1 };
    convertTextToTime = '';
    strings;

    constructor(
        @Inject(MatDialogRef) private dialogRef: MatDialogRef<TtlDialogComponent>,
        @Inject(MAT_DIALOG_DATA) private data: TtlDialogData,
        @Inject(I18nService) private i18n: I18nService,
        @Inject(CommonService) private common: CommonService,
        @Inject(SettingsService) private settingsService: SettingsService,
    ) {
        this.strings = this.i18n.strings;
    }

    ngOnInit(): void {
        this.model = { ...this.data.model };
        if (typeof this.model.ttl === 'number' && this.model.ttl > 0) {
            try {
                const hdOpts = this.settingsService.getHumanizeDurationOptions();
                this.convertTextToTime = humanizeDuration(this.model.ttl * 1000, {
                    ...hdOpts,
                    delimiter: ' ',
                });
            } catch (e) {
                this.convertTextToTime = '';
            }
        }
    }

    onTextTimeChange(value: string): void {
        try {
            this.model.ttl = timestring(String(value), 's');
        } catch (e) {
            console.warn('timestring parse error', e);
        }
    }

    openTimestringNpm(): void {
        window.open('https://www.npmjs.com/package/timestring#keywords', '_blank');
    }

    submit(): void {
        if (isNaN(this.model.ttl)) {
            this.model.ttl = Math.round(this.model.ttl);
        }
        this.dialogRef.close({ model: this.model });
    }

    cancel(): void {
        this.dialogRef.close(undefined);
    }
}

// src/vue/dialogs/TtlDialog.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useDisplay } from 'vuetify'
import { useI18nStore } from '../stores/i18n'
import { useSettingsStore } from '../stores/settings'
import P3xrDialog from '../components/P3xrDialog.vue'
import humanizeDuration from 'humanize-duration'
import timestring from 'timestring'

const props = defineProps<{
    open: boolean
    ttl: number | string
}>()

const emit = defineEmits<{
    close: [result?: { model: { ttl: number } }]
}>()

const i18n = useI18nStore()
const settings = useSettingsStore()
const strings = computed(() => i18n.strings)
const { width } = useDisplay()
const isWide = computed(() => width.value >= 600)

const ttlValue = ref<number | string>(-1)
const textTime = ref('')

watch(() => props.open, (v) => {
    if (!v) return
    const t = props.ttl ?? -1
    ttlValue.value = t
    if (typeof t === 'number' && t > 0) {
        const hdOpts = settings.getHumanizeDurationOptions()
        textTime.value = humanizeDuration(t * 1000, { ...hdOpts, delimiter: ' ' })
    } else {
        textTime.value = ''
    }
})

function onTextTimeChange(value: string) {
    textTime.value = value
    try { ttlValue.value = timestring(String(value), 's') }
    catch { /* parse error */ }
}

function submit() {
    let t = Number(ttlValue.value)
    if (isNaN(t)) t = Math.round(t)
    emit('close', { model: { ttl: t } })
}

function cancel() {
    emit('close')
}
</script>

<template>
    <P3xrDialog v-if="open" :open="true" :title="strings?.confirm?.ttl?.title" width="600px" @close="cancel">
        <div style="margin-bottom: 16px;">{{ strings?.confirm?.ttl?.textContent }}</div>

        <v-text-field
            v-model.number="ttlValue"
            :label="strings?.confirm?.ttl?.placeholder"
            :placeholder="strings?.confirm?.ttl?.placeholderPlaceholder"
            type="number"
            :min="-1"
            variant="outlined"
            density="comfortable"
            hide-details
            class="mb-3"
        />

        <v-text-field
            v-model="textTime"
            :label="strings?.confirm?.ttl?.convertTextToTime"
            :placeholder="strings?.confirm?.ttl?.convertTextToTimePlaceholder"
            variant="outlined"
            density="comfortable"
            hide-details
            class="mb-3"
            @update:model-value="onTextTimeChange"
        />

        <v-btn variant="text" color="secondary" size="small" style="text-transform: none; margin-top: 4px;"
            @click="window.open('https://www.npmjs.com/package/timestring#keywords', '_blank')">
            https://www.npmjs.com/package/timestring
        </v-btn>

        <template #actions>
            <v-btn variant="flat" color="error" size="small" @click="cancel">
                <v-icon :class="{ 'mr-1': isWide }">mdi-close-circle</v-icon>
                <span v-if="isWide">{{ strings?.intention?.cancel }}</span>
                <v-tooltip v-if="!isWide" activator="parent" location="top">{{ strings?.intention?.cancel }}</v-tooltip>
            </v-btn>
            <v-btn variant="flat" color="primary" size="small" @click="submit">
                <v-icon class="mr-1">mdi-timer</v-icon>
                <span>{{ strings?.intention?.ttl }}</span>
            </v-btn>
        </template>
    </P3xrDialog>
</template>
