// src/react/dialogs/TtlDialog.tsx
import { useState, useEffect } from 'react'
import { TextField, Button, Box } from '@mui/material'
import { Timer, Cancel } from '@mui/icons-material'
import { useI18nStore } from '../stores/i18n.store'
import { useSettingsStore } from '../stores/settings.store'
import P3xrDialog from '../components/P3xrDialog'
import humanizeDuration from 'humanize-duration'
import timestring from 'timestring'

interface Props {
    open: boolean
    ttl: number | string
    onClose: (result?: { model: { ttl: number } }) => void
}

export default function TtlDialog({ open, ttl: initialTtl, onClose }: Props) {
    const strings = useI18nStore(s => s.strings)
    const [ttl, setTtl] = useState<number | string>(-1)
    const [textTime, setTextTime] = useState('')

    useEffect(() => {
        if (!open) return
        const t = initialTtl ?? -1
        setTtl(t)
        if (typeof t === 'number' && t > 0) {
            try {
                const hdOpts = useSettingsStore.getState().getHumanizeDurationOptions()
                setTextTime(humanizeDuration(t * 1000, { ...hdOpts, delimiter: ' ' }))
            } catch { setTextTime('') }
        } else {
            setTextTime('')
        }
    }, [open, initialTtl])

    const onTextTimeChange = (value: string) => {
        setTextTime(value)
        try { setTtl(timestring(String(value), 's')) }
        catch { /* parse error */ }
    }

    const submit = () => {
        let t = Number(ttl)
        if (isNaN(t)) t = Math.round(t)
        onClose({ model: { ttl: t } })
    }

    if (!open) return null

    return (
        <P3xrDialog open onClose={() => onClose()} width="600px"
            title={strings?.confirm?.ttl?.title}
            actions={
                <>
                    <Button variant="contained" color="error" size="small" onClick={() => onClose()}>
                        <Cancel fontSize="small" /><span style={{ marginLeft: 3 }}>{strings?.intention?.cancel}</span>
                    </Button>
                    <Button variant="contained" color="primary" size="small" onClick={submit}>
                        <Timer fontSize="small" /><span style={{ marginLeft: 3 }}>{strings?.intention?.ttl}</span>
                    </Button>
                </>
            }>
            <Box sx={{ mb: 2 }}>{strings?.confirm?.ttl?.textContent}</Box>

            <TextField fullWidth margin="dense" type="number"
                label={strings?.confirm?.ttl?.placeholder}
                value={ttl}
                onChange={e => setTtl(e.target.value === '' ? '' : Number(e.target.value))}
                placeholder={strings?.confirm?.ttl?.placeholderPlaceholder ?? '-1'}
                slotProps={{ htmlInput: { min: -1 } }}
            />

            <TextField fullWidth margin="dense"
                label={strings?.confirm?.ttl?.convertTextToTime}
                value={textTime}
                onChange={e => onTextTimeChange(e.target.value)}
                placeholder={strings?.confirm?.ttl?.convertTextToTimePlaceholder ?? '1h 30m'}
            />

            <Button variant="text" color="secondary" size="small" sx={{ mt: 1, textTransform: 'none' }}
                onClick={() => window.open('https://www.npmjs.com/package/timestring#keywords', '_blank')}>
                https://www.npmjs.com/package/timestring
            </Button>
        </P3xrDialog>
    )
}

// src/vue/dialogs/TtlDialog.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useDisplay } from 'vuetify'
import { useI18nStore } from '../stores/i18n'
import { useSettingsStore } from '../stores/settings'
import P3xrDialog from '../components/P3xrDialog.vue'
import humanizeDuration from 'humanize-duration'
import timestring from 'timestring'

const props = defineProps<{
    open: boolean
    ttl: number | string
}>()

const emit = defineEmits<{
    close: [result?: { model: { ttl: number } }]
}>()

const i18n = useI18nStore()
const settings = useSettingsStore()
const strings = computed(() => i18n.strings)
const { width } = useDisplay()
const isWide = computed(() => width.value >= 600)

const ttlValue = ref<number | string>(-1)
const textTime = ref('')

watch(() => props.open, (v) => {
    if (!v) return
    const t = props.ttl ?? -1
    ttlValue.value = t
    if (typeof t === 'number' && t > 0) {
        const hdOpts = settings.getHumanizeDurationOptions()
        textTime.value = humanizeDuration(t * 1000, { ...hdOpts, delimiter: ' ' })
    } else {
        textTime.value = ''
    }
})

function onTextTimeChange(value: string) {
    textTime.value = value
    try { ttlValue.value = timestring(String(value), 's') }
    catch { /* parse error */ }
}

function submit() {
    let t = Number(ttlValue.value)
    if (isNaN(t)) t = Math.round(t)
    emit('close', { model: { ttl: t } })
}

function cancel() {
    emit('close')
}
</script>

<template>
    <P3xrDialog v-if="open" :open="true" :title="strings?.confirm?.ttl?.title" width="600px" @close="cancel">
        <div style="margin-bottom: 16px;">{{ strings?.confirm?.ttl?.textContent }}</div>

        <v-text-field
            v-model.number="ttlValue"
            :label="strings?.confirm?.ttl?.placeholder"
            :placeholder="strings?.confirm?.ttl?.placeholderPlaceholder"
            type="number"
            :min="-1"
            variant="outlined"
            density="comfortable"
            hide-details
            class="mb-3"
        />

        <v-text-field
            v-model="textTime"
            :label="strings?.confirm?.ttl?.convertTextToTime"
            :placeholder="strings?.confirm?.ttl?.convertTextToTimePlaceholder"
            variant="outlined"
            density="comfortable"
            hide-details
            class="mb-3"
            @update:model-value="onTextTimeChange"
        />

        <v-btn variant="text" color="secondary" size="small" style="text-transform: none; margin-top: 4px;"
            @click="window.open('https://www.npmjs.com/package/timestring#keywords', '_blank')">
            https://www.npmjs.com/package/timestring
        </v-btn>

        <template #actions>
            <v-btn variant="flat" color="error" size="small" @click="cancel">
                <v-icon :class="{ 'mr-1': isWide }">mdi-close-circle</v-icon>
                <span v-if="isWide">{{ strings?.intention?.cancel }}</span>
                <v-tooltip v-if="!isWide" activator="parent" location="top">{{ strings?.intention?.cancel }}</v-tooltip>
            </v-btn>
            <v-btn variant="flat" color="primary" size="small" @click="submit">
                <v-icon class="mr-1">mdi-timer</v-icon>
                <span>{{ strings?.intention?.ttl }}</span>
            </v-btn>
        </template>
    </P3xrDialog>
</template>
