// src/react/pages/search/SearchPage.tsx
/**
 * Search page — exact port of Angular search.component.
 * RediSearch: index selection, query with AI fallback, results with paging,
 * index info, create/drop index.
 */
import { useState, useEffect, useCallback } from 'react'
import {
    Box, TextField, MenuItem, Select, FormControl, InputLabel, Button, Tooltip,
    List, ListItem, Divider, useMediaQuery, useTheme, FormControlLabel, Switch,
} from '@mui/material'
import { Search, Delete, Add, Remove, SkipPrevious, SkipNext, KeyboardArrowLeft, KeyboardArrowRight } from '@mui/icons-material'
import { parseRedisVersion } from '../../../core/redis-version'
import { useI18nStore } from '../../stores/i18n.store'
import { useRedisStateStore } from '../../stores/redis-state.store'
import { useCommonStore } from '../../stores/common.store'
import { useOverlayStore } from '../../stores/overlay.store'
import { request } from '../../stores/socket.service'
import P3xrAccordion from '../../components/P3xrAccordion'
import P3xrButton from '../../components/P3xrButton'

interface SchemaField { name: string; type: string; sortable: boolean }

export default function SearchPage() {
    const strings = useI18nStore(s => s.strings)
    const connection = useRedisStateStore(s => s.connection)
    const { toast, confirm, generalHandleError } = useCommonStore()
    const overlay = useOverlayStore()
    const isGtSm = useMediaQuery('(min-width: 960px)')
    const isReadonly = connection?.readonly === true

    const [indexes, setIndexes] = useState<string[]>([])
    const [selectedIndex, setSelectedIndex] = useState('')
    const [query, setQuery] = useState('*')
    const [offset, setOffset] = useState(0)
    const limit = 20
    const [total, setTotal] = useState(0)
    const [results, setResults] = useState<any[]>([])
    const [indexInfo, setIndexInfo] = useState<any>(null)
    const [searchDone, setSearchDone] = useState(false)
    const [aiLoading, setAiLoading] = useState(false)

    // Hybrid search (FT.HYBRID, Redis 8.4+)
    const [hybridMode, setHybridMode] = useState(false)
    const [vectorField, setVectorField] = useState('')
    const [vectorValues, setVectorValues] = useState('')
    const [vectorCount, setVectorCount] = useState(10)

    // Create index
    const [newIndexName, setNewIndexName] = useState('')
    const [newIndexPrefix, setNewIndexPrefix] = useState('')
    const [newIndexFields, setNewIndexFields] = useState<SchemaField[]>([{ name: '', type: 'TEXT', sortable: false }])

    const pages = Math.ceil(total / limit)
    const currentPage = Math.floor(offset / limit) + 1

    const getDocKeys = (doc: any) => Object.keys(doc).filter(k => k !== '_key')

    // --- Load indexes ---
    const loadIndexes = useCallback(async () => {
        try {
            const resp = await request({ action: 'search-list', payload: {} })
            setIndexes(resp.data)
            return resp.data as string[]
        } catch { return [] }
    }, [])

    const loadIndexInfo = useCallback(async (idx?: string) => {
        const index = idx || selectedIndex
        if (!index) return
        try {
            const resp = await request({ action: 'search-index-info', payload: { index } })
            setIndexInfo(resp.data)
        } catch (e) { generalHandleError(e) }
    }, [selectedIndex, generalHandleError])

    const doSearch = useCallback(async (off?: number) => {
        if (!selectedIndex || !query) return
        try {
            let resp: any
            if (hybridMode && vectorField && vectorValues) {
                const values = vectorValues.split(',').map(v => parseFloat(v.trim())).filter(v => !isNaN(v))
                resp = await request({
                    action: 'search-hybrid',
                    payload: { index: selectedIndex, query, vectorField, vectorValues: values, count: vectorCount, offset: off ?? offset, limit },
                })
            } else {
                resp = await request({
                    action: 'search-query',
                    payload: { index: selectedIndex, query, offset: off ?? offset, limit },
                })
            }
            setTotal(resp.data.total)
            setResults(resp.data.docs)
        } catch (e) {
            generalHandleError(e)
            setResults([]); setTotal(0)
        } finally { setSearchDone(true) }
    }, [selectedIndex, query, offset, generalHandleError])

    const handleAiQuery = useCallback(async (prompt: string) => {
        if (!prompt) return
        setAiLoading(true)
        try {
            const resp = await request({
                action: 'ai-redis-query',
                payload: { prompt, context: { indexes, schema: indexInfo } },
            })
            setQuery(resp.command || '*')
            if (resp.explanation) toast(resp.explanation)
            setOffset(0)
            // Search with new query
            const sr = await request({ action: 'search-query', payload: { index: selectedIndex, query: resp.command || '*', offset: 0, limit } })
            setTotal(sr.data.total); setResults(sr.data.docs); setSearchDone(true)
            await loadIndexInfo()
        } catch (e) { generalHandleError(e) }
        finally { setAiLoading(false) }
    }, [indexes, indexInfo, selectedIndex, toast, loadIndexInfo, generalHandleError])

    const handleSearchEnter = useCallback(async () => {
        const q = (query || '').trim()
        if (/^ai:\s*/i.test(q)) { await handleAiQuery(q.replace(/^ai:\s*/i, '').trim()); return }
        try {
            await Promise.all([doSearch(0), loadIndexInfo()])
        } catch {
            if (q.length > 2 && q !== '*' && /\s/.test(q)) {
                overlay.show()
                try { await handleAiQuery(q) } finally { overlay.hide() }
            }
        }
    }, [query, doSearch, loadIndexInfo, handleAiQuery, overlay])

    const pageAction = useCallback((action: string) => {
        let newOffset = offset
        switch (action) {
            case 'first': newOffset = 0; break
            case 'prev': newOffset = Math.max(0, offset - limit); break
            case 'next': newOffset = Math.min((pages - 1) * limit, offset + limit); break
            case 'last': newOffset = (pages - 1) * limit; break
        }
        setOffset(newOffset)
        doSearch(newOffset)
    }, [offset, pages, doSearch])

    const dropIndex = useCallback(async () => {
        if (!selectedIndex) return
        try {
            await confirm({ message: strings?.confirm?.dropIndex || 'Are you sure to drop this index?' })
            await request({ action: 'search-index-drop', payload: { index: selectedIndex } })
            toast(strings?.status?.indexDropped || 'Index dropped')
            setSelectedIndex(''); setResults([]); setTotal(0); setSearchDone(false); setIndexInfo(null)
            await loadIndexes()
        } catch (e: any) { if (e !== undefined) generalHandleError(e) }
    }, [selectedIndex, strings, confirm, toast, loadIndexes, generalHandleError])

    const addField = () => setNewIndexFields(f => [...f, { name: '', type: 'TEXT', sortable: false }])

    const confirmRemoveField = useCallback(async (index: number) => {
        try {
            await confirm({ message: (strings?.intention?.delete || 'Delete') + '?' })
            setNewIndexFields(f => f.filter((_, i) => i !== index))
        } catch (e: any) { if (e !== undefined) generalHandleError(e) }
    }, [strings, confirm, generalHandleError])

    const createIndex = useCallback(async () => {
        if (!newIndexName.trim()) return
        const schema = newIndexFields.filter(f => f.name.trim())
        if (schema.length === 0) return
        try {
            await request({
                action: 'search-index-create',
                payload: { name: newIndexName.trim(), prefix: newIndexPrefix.trim() || undefined, schema },
            })
            toast(strings?.status?.indexCreated || 'Index created')
            setNewIndexName(''); setNewIndexPrefix('')
            setNewIndexFields([{ name: '', type: 'TEXT', sortable: false }])
            await loadIndexes()
        } catch (e) { generalHandleError(e) }
    }, [newIndexName, newIndexPrefix, newIndexFields, strings, toast, loadIndexes, generalHandleError])

    // --- Init + refresh on connection change ---
    const connectionId = connection?.id
    useEffect(() => {
        setSelectedIndex('')
        setResults([])
        setTotal(0)
        setSearchDone(false)
        setIndexInfo(null)
        loadIndexes().then(idxs => {
            if (idxs.length > 0) {
                setSelectedIndex(idxs[0])
                loadIndexInfo(idxs[0])
            }
        })
    }, [connectionId]) // eslint-disable-line react-hooks/exhaustive-deps

    const onIndexChange = (idx: string) => {
        setSelectedIndex(idx)
        setOffset(0); setIndexInfo(null)
        loadIndexInfo(idx)
    }

    // --- Render ---
    const s = strings?.page?.search || {} as any

    const ActionBtn = ({ icon, label, color = 'primary' as const, onClick, disabled }: {
        icon: React.ReactNode; label: string; color?: 'primary' | 'secondary'; onClick: () => void; disabled?: boolean
    }) => isGtSm ? (
        <Button variant="contained" color={color} size="small" onClick={onClick} disabled={disabled} sx={{ gap: '3px' }}>
            {icon}<span>{label}</span>
        </Button>
    ) : (
        <Tooltip title={label} placement="top">
            <span>
                <Button variant="contained" color={color} onClick={onClick} disabled={disabled}
                    sx={{ minWidth: 40, width: 40, height: 40, p: 0, borderRadius: '4px' }}>
                    {icon}
                </Button>
            </span>
        </Tooltip>
    )

    return (
        <Box>
            {/* Search Query */}
            <P3xrAccordion title={s.title || 'Search'} accordionKey="search-query">
                <Box sx={{ p: 2 }}>
                    {indexes.length === 0 && (
                        <Box sx={{ opacity: 0.5 }}>{s.noIndex || 'No indexes found'}</Box>
                    )}
                    {indexes.length > 0 && (
                        <>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                                <FormControl fullWidth size="small">
                                    <InputLabel>{s.index || 'Index'}</InputLabel>
                                    <Select value={selectedIndex} label={s.index || 'Index'}
                                        onChange={e => onIndexChange(e.target.value)}>
                                        {indexes.map(idx => <MenuItem key={idx} value={idx}>{idx}</MenuItem>)}
                                    </Select>
                                </FormControl>
                                {!isReadonly && selectedIndex && (
                                    <Tooltip title={s.dropIndex || 'Drop Index'}>
                                        <Button variant="contained" color="error" onClick={dropIndex}
                                            sx={{ minWidth: 40, width: 40, height: 40, p: 0, borderRadius: '4px' }}>
                                            <Delete fontSize="small" />
                                        </Button>
                                    </Tooltip>
                                )}
                            </Box>
                            <TextField fullWidth size="small" sx={{ mt: 1 }} label={s.query || 'Query'}
                                value={query} onChange={e => setQuery(e.target.value)} disabled={aiLoading}
                                onKeyDown={e => { if (e.key === 'Enter') { setOffset(0); handleSearchEnter() } }} />

                            {parseRedisVersion(useRedisStateStore.getState().info?.server?.redis_version).isAtLeast(8, 4) && (
                                <>
                                    <FormControlLabel sx={{ mt: 1 }}
                                        control={<Switch checked={hybridMode} onChange={(_, v) => setHybridMode(v)} color="primary" />}
                                        label={s.hybridMode || 'Hybrid Search (FT.HYBRID)'} />
                                    {hybridMode && (
                                        <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mt: 1 }}>
                                            <TextField size="small" sx={{ flex: 1, minWidth: 150 }}
                                                label={s.vectorField || 'Vector Field'} placeholder="embedding"
                                                value={vectorField} onChange={e => setVectorField(e.target.value)} />
                                            <TextField size="small" sx={{ flex: 2, minWidth: 200 }}
                                                label={s.vectorValues || 'Vector Values'} placeholder="0.1, 0.2, 0.3, ..."
                                                value={vectorValues} onChange={e => setVectorValues(e.target.value)} />
                                            <TextField size="small" sx={{ width: 80 }} type="number"
                                                label="Count"
                                                value={vectorCount} onChange={e => setVectorCount(parseInt(e.target.value) || 10)} />
                                        </Box>
                                    )}
                                </>
                            )}

                            <Box sx={{ mt: 1, textAlign: 'right' }}>
                                <ActionBtn icon={<Search fontSize="small" />}
                                    label={aiLoading ? (strings?.label?.aiTranslating || 'Translating...') : (s.title || 'Search')}
                                    onClick={() => { setOffset(0); handleSearchEnter() }} disabled={aiLoading} />
                            </Box>
                        </>
                    )}
                </Box>
            </P3xrAccordion>

            {/* Results - empty */}
            {searchDone && total === 0 && (
                <>
                    <Box sx={{ mt: 1 }} />
                    <P3xrAccordion title={`${s.results || 'Results'} (0)`} accordionKey="search-results">
                        <Box sx={{ p: 2, opacity: 0.5 }}>{strings?.label?.noResults || 'No results'}</Box>
                    </P3xrAccordion>
                </>
            )}

            {/* Results - with data */}
            {(results.length > 0 || total > 0) && (
                <>
                    <Box sx={{ mt: 1 }} />
                    <P3xrAccordion title={`${s.results || 'Results'} (${total})`} accordionKey="search-results"
                        actions={pages > 1 ? (<>
                            <P3xrButton icon={<SkipPrevious sx={{ fontSize: 18 }} />} label="" color="inherit"
                                onClick={(e) => { e.stopPropagation(); pageAction('first') }} />
                            <P3xrButton icon={<KeyboardArrowLeft sx={{ fontSize: 18 }} />} label="" color="inherit"
                                onClick={(e) => { e.stopPropagation(); pageAction('prev') }} />
                            <Box component="span" sx={{ fontSize: 12, opacity: 0.7 }}>{currentPage} / {pages}</Box>
                            <P3xrButton icon={<KeyboardArrowRight sx={{ fontSize: 18 }} />} label="" color="inherit"
                                onClick={(e) => { e.stopPropagation(); pageAction('next') }} />
                            <P3xrButton icon={<SkipNext sx={{ fontSize: 18 }} />} label="" color="inherit"
                                onClick={(e) => { e.stopPropagation(); pageAction('last') }} />
                        </>) : undefined}>
                        <List disablePadding>
                            {results.map((doc: any) => (
                                <Box key={doc._key}>
                                    <ListItem sx={{ px: 2, py: 1 }}>
                                        <Box sx={{ display: 'flex', width: '100%', alignItems: 'center' }}>
                                            <Box sx={{ flex: 1 }}>
                                                <Box component="kbd" sx={{
                                                    px: '6px', py: '2px', borderRadius: '4px', fontSize: 11,
                                                    bgcolor: 'action.hover', fontFamily: "'Roboto Mono', monospace",
                                                }}>{doc._key}</Box>
                                            </Box>
                                            <Box sx={{ fontFamily: "'Roboto Mono', monospace", fontSize: 12 }}>
                                                {getDocKeys(doc).map((field, i) => (
                                                    <span key={field}>
                                                        {field}: {doc[field]}
                                                        {i < getDocKeys(doc).length - 1 && ' \u00B7 '}
                                                    </span>
                                                ))}
                                            </Box>
                                        </Box>
                                    </ListItem>
                                    <Divider />
                                </Box>
                            ))}
                        </List>
                    </P3xrAccordion>
                </>
            )}

            {/* Index Info */}
            {selectedIndex && indexInfo && (
                <>
                    <Box sx={{ mt: 1 }} />
                    <P3xrAccordion title={`${s.indexInfo || 'Index Info'}: ${selectedIndex}`} accordionKey="search-index-info"
                        actions={!isReadonly ? (
                            <P3xrButton icon={<Delete sx={{ fontSize: 18 }} />} label={s.dropIndex || 'Drop'} color="inherit"
                                onClick={(e) => { e.stopPropagation(); dropIndex() }} />
                        ) : undefined}>
                        <List disablePadding>
                            {getDocKeys(indexInfo).map(key => (
                                <Box key={key}>
                                    <ListItem sx={{ px: 2, py: 1 }}>
                                        <Box sx={{ display: 'flex', width: '100%' }}>
                                            <Box sx={{ flex: 1 }}>{key}</Box>
                                            <Box sx={{ fontFamily: "'Roboto Mono', monospace", fontSize: 12 }}>{JSON.stringify(indexInfo[key])}</Box>
                                        </Box>
                                    </ListItem>
                                    <Divider />
                                </Box>
                            ))}
                        </List>
                    </P3xrAccordion>
                </>
            )}

            {/* Create Index */}
            {!isReadonly && (
                <>
                    <Box sx={{ mt: 1 }} />
                    <P3xrAccordion title={s.createIndex || 'Create Index'} accordionKey="search-create-index">
                        <Box sx={{ p: 2 }}>
                            <TextField fullWidth size="small" label={s.indexName || 'Index Name'}
                                value={newIndexName} onChange={e => setNewIndexName(e.target.value)} />
                            <TextField fullWidth size="small" sx={{ mt: 1 }} label={s.prefix || 'Key Prefix (optional)'}
                                placeholder="e.g. doc:" value={newIndexPrefix} onChange={e => setNewIndexPrefix(e.target.value)} />

                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, my: 1 }}>
                                <strong>Schema</strong>
                                <Tooltip title="Add">
                                    <Button variant="contained" color="primary" onClick={addField}
                                        sx={{ minWidth: 40, width: 40, height: 40, p: 0, borderRadius: '4px' }}>
                                        <Add fontSize="small" />
                                    </Button>
                                </Tooltip>
                            </Box>

                            {newIndexFields.map((field, i) => (
                                <Box key={i} sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.5, flexWrap: 'wrap' }}>
                                    <TextField size="small" sx={{ flex: 1, minWidth: 120 }} label={s.fieldName || 'Field Name'}
                                        value={field.name} onChange={e => {
                                            const f = [...newIndexFields]; f[i] = { ...f[i], name: e.target.value }; setNewIndexFields(f)
                                        }} />
                                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexShrink: 0 }}>
                                        <FormControl size="small" sx={{ width: 130 }}>
                                            <InputLabel>{strings?.label?.type || 'Type'}</InputLabel>
                                            <Select value={field.type} label={strings?.label?.type || 'Type'}
                                                onChange={e => {
                                                    const f = [...newIndexFields]; f[i] = { ...f[i], type: e.target.value }; setNewIndexFields(f)
                                                }}>
                                                {['TEXT', 'NUMERIC', 'TAG', 'GEO', 'VECTOR'].map(t =>
                                                    <MenuItem key={t} value={t}>{t}</MenuItem>
                                                )}
                                            </Select>
                                        </FormControl>
                                        <Tooltip title={strings?.intention?.delete || 'Delete'}>
                                            <span>
                                                <Button variant="contained" color="error" onClick={() => confirmRemoveField(i)}
                                                    disabled={newIndexFields.length <= 1}
                                                    sx={{ minWidth: 40, width: 40, height: 40, p: 0, borderRadius: '4px' }}>
                                                    <Remove fontSize="small" />
                                                </Button>
                                            </span>
                                        </Tooltip>
                                    </Box>
                                </Box>
                            ))}

                            <Box sx={{ mt: 1, textAlign: 'right' }}>
                                <ActionBtn icon={<Add fontSize="small" />} label={s.createIndex || 'Create Index'}
                                    color="secondary" onClick={createIndex} disabled={!newIndexName.trim()} />
                            </Box>
                        </Box>
                    </P3xrAccordion>
                </>
            )}

            <Box sx={{ height: 64 }} />
        </Box>
    )
}

// src/vue/pages/search/SearchPage.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useDisplay } from 'vuetify'
import P3xrAccordion from '../../components/P3xrAccordion.vue'
import P3xrButton from '../../components/P3xrButton.vue'
import { useI18nStore } from '../../stores/i18n'
import { useRedisStateStore } from '../../stores/redis-state'
import { useCommonStore } from '../../stores/common'
import { useOverlayStore } from '../../stores/overlay'
import { request } from '../../stores/socket.service'
import { parseRedisVersion } from '../../../core/redis-version'

const i18n = useI18nStore()
const state = useRedisStateStore()
const common = useCommonStore()
const overlay = useOverlayStore()
const { width: displayWidth } = useDisplay()
const isGtSm = computed(() => displayWidth.value >= 960)

const strings = computed(() => i18n.strings)
const s = computed(() => strings.value?.page?.search || {} as any)
const isReadonly = computed(() => state.connection?.readonly === true)

const indexes = ref<string[]>([])
const selectedIndex = ref('')
const query = ref('*')
const offset = ref(0)
const limit = 20
const total = ref(0)
const results = ref<any[]>([])
const indexInfo = ref<any>(null)
const searchDone = ref(false)
const aiLoading = ref(false)

// Hybrid search
const hybridMode = ref(false)
const vectorField = ref('')
const vectorValues = ref('')
const vectorCount = ref(10)

// Create index
const newIndexName = ref('')
const newIndexPrefix = ref('')
const newIndexFields = ref<{ name: string; type: string; sortable: boolean }[]>([{ name: '', type: 'TEXT', sortable: false }])

const pages = computed(() => Math.ceil(total.value / limit))
const currentPage = computed(() => Math.floor(offset.value / limit) + 1)

function getDocKeys(doc: any) { return Object.keys(doc).filter(k => k !== '_key') }

async function loadIndexes() {
    try {
        const resp = await request({ action: 'search/list', payload: {} })
        indexes.value = resp.data
        return resp.data as string[]
    } catch { return [] }
}

async function loadIndexInfo(idx?: string) {
    const index = idx || selectedIndex.value
    if (!index) return
    try {
        const resp = await request({ action: 'search/index-info', payload: { index } })
        indexInfo.value = resp.data
    } catch (e) { common.generalHandleError(e) }
}

async function doSearch(off?: number) {
    if (!selectedIndex.value || !query.value) return
    try {
        let resp: any
        if (hybridMode.value && vectorField.value && vectorValues.value) {
            const values = vectorValues.value.split(',').map(v => parseFloat(v.trim())).filter(v => !isNaN(v))
            resp = await request({
                action: 'search/hybrid',
                payload: { index: selectedIndex.value, query: query.value, vectorField: vectorField.value, vectorValues: values, count: vectorCount.value, offset: off ?? offset.value, limit },
            })
        } else {
            resp = await request({
                action: 'search/query',
                payload: { index: selectedIndex.value, query: query.value, offset: off ?? offset.value, limit },
            })
        }
        total.value = resp.data.total
        results.value = resp.data.docs
    } catch (e) {
        common.generalHandleError(e)
        results.value = []; total.value = 0
    } finally { searchDone.value = true }
}

async function handleAiQuery(prompt: string) {
    if (!prompt) return
    aiLoading.value = true
    try {
        const resp = await request({
            action: 'ai/redis-query',
            payload: { prompt, context: { indexes: indexes.value, schema: indexInfo.value } },
        })
        query.value = resp.command || '*'
        if (resp.explanation) common.toast(resp.explanation)
        offset.value = 0
        const sr = await request({ action: 'search/query', payload: { index: selectedIndex.value, query: resp.command || '*', offset: 0, limit } })
        total.value = sr.data.total; results.value = sr.data.docs; searchDone.value = true
        await loadIndexInfo()
    } catch (e) { common.generalHandleError(e) }
    finally { aiLoading.value = false }
}

async function handleSearchEnter() {
    const q = (query.value || '').trim()
    if (/^ai:\s*/i.test(q)) { await handleAiQuery(q.replace(/^ai:\s*/i, '').trim()); return }
    try {
        await Promise.all([doSearch(0), loadIndexInfo()])
    } catch {
        if (q.length > 2 && q !== '*' && /\s/.test(q)) {
            overlay.show()
            try { await handleAiQuery(q) } finally { overlay.hide() }
        }
    }
}

function pageAction(action: string) {
    let newOffset = offset.value
    switch (action) {
        case 'first': newOffset = 0; break
        case 'prev': newOffset = Math.max(0, offset.value - limit); break
        case 'next': newOffset = Math.min((pages.value - 1) * limit, offset.value + limit); break
        case 'last': newOffset = (pages.value - 1) * limit; break
    }
    offset.value = newOffset
    doSearch(newOffset)
}

async function dropIndex() {
    if (!selectedIndex.value) return
    try {
        await common.confirm({ message: strings.value?.confirm?.dropIndex || 'Are you sure to drop this index?' })
        await request({ action: 'search/index-drop', payload: { index: selectedIndex.value } })
        common.toast(strings.value?.status?.indexDropped || 'Index dropped')
        selectedIndex.value = ''; results.value = []; total.value = 0; searchDone.value = false; indexInfo.value = null
        await loadIndexes()
    } catch (e: any) { if (e !== undefined) common.generalHandleError(e) }
}

function addField() { newIndexFields.value.push({ name: '', type: 'TEXT', sortable: false }) }

async function confirmRemoveField(index: number) {
    try {
        await common.confirm({ message: (strings.value?.intention?.delete || 'Delete') + '?' })
        newIndexFields.value.splice(index, 1)
    } catch (e: any) { if (e !== undefined) common.generalHandleError(e) }
}

async function createIndex() {
    if (!newIndexName.value.trim()) return
    const schema = newIndexFields.value.filter(f => f.name.trim())
    if (schema.length === 0) return
    try {
        await request({
            action: 'search/index-create',
            payload: { name: newIndexName.value.trim(), prefix: newIndexPrefix.value.trim() || undefined, schema },
        })
        common.toast(strings.value?.status?.indexCreated || 'Index created')
        newIndexName.value = ''; newIndexPrefix.value = ''
        newIndexFields.value = [{ name: '', type: 'TEXT', sortable: false }]
        await loadIndexes()
    } catch (e) { common.generalHandleError(e) }
}

function onIndexChange(idx: string) {
    selectedIndex.value = idx
    offset.value = 0; indexInfo.value = null
    loadIndexInfo(idx)
}

// Init on connection change
watch(() => state.connection?.id, () => {
    selectedIndex.value = ''; results.value = []; total.value = 0
    searchDone.value = false; indexInfo.value = null
    loadIndexes().then(idxs => {
        if (idxs.length > 0) { selectedIndex.value = idxs[0]; loadIndexInfo(idxs[0]) }
    })
}, { immediate: true })

const supportsHybrid = computed(() => {
    const ver = state.info?.server?.redis_version
    return ver ? parseRedisVersion(ver).isAtLeast(8, 4) : false
})
</script>

<template>
    <div>
        <!-- Search Query -->
        <P3xrAccordion :title="s.title || 'Search'" accordion-key="search-query">
            <div style="padding: 16px;">
                <div v-if="indexes.length === 0" style="opacity: 0.5;">{{ s.noIndex || 'No indexes found' }}</div>
                <template v-if="indexes.length > 0">
                    <div style="display: flex; align-items: center; gap: 8px;">
                        <v-select v-model="selectedIndex" :items="indexes" :label="s.index || 'Index'"
                            density="compact" variant="outlined" hide-details @update:model-value="onIndexChange" />
                        <v-tooltip v-if="!isReadonly && selectedIndex" :text="s.dropIndex || 'Drop Index'" location="top">
                            <template #activator="{ props: tp }">
                                <v-btn v-bind="tp" color="error" variant="flat"
                                    style="min-width: 40px; width: 40px; height: 40px; padding: 0; border-radius: 4px;"
                                    @click="dropIndex">
                                    <v-icon size="small">mdi-delete</v-icon>
                                </v-btn>
                            </template>
                        </v-tooltip>
                    </div>
                    <v-text-field v-model="query" :label="s.query || 'Query'" density="compact" variant="outlined"
                        hide-details :disabled="aiLoading" style="margin-top: 8px;"
                        @keydown.enter="offset = 0; handleSearchEnter()" />

                    <!-- Hybrid search (Redis 8.4+) -->
                    <template v-if="supportsHybrid">
                        <v-switch v-model="hybridMode" :label="s.hybridMode || 'Hybrid Search (FT.HYBRID)'"
                            color="primary" style="margin-top: 8px;" />
                        <div v-if="hybridMode" style="display: flex; gap: 8px; flex-wrap: wrap; margin-top: 8px;">
                            <v-text-field v-model="vectorField" :label="s.vectorField || 'Vector Field'" placeholder="embedding"
                                density="compact" variant="outlined" hide-details style="flex: 1; min-width: 150px;" />
                            <v-text-field v-model="vectorValues" :label="s.vectorValues || 'Vector Values'" placeholder="0.1, 0.2, 0.3, ..."
                                density="compact" variant="outlined" hide-details style="flex: 2; min-width: 200px;" />
                            <v-text-field v-model.number="vectorCount" label="Count" type="number"
                                density="compact" variant="outlined" hide-details style="width: 80px; flex: none;" />
                        </div>
                    </template>

                    <div style="margin-top: 8px; text-align: right;">
                        <v-btn v-if="isGtSm" color="primary" variant="flat" size="small" :disabled="aiLoading"
                            style="gap: 3px;" @click="offset = 0; handleSearchEnter()">
                            <v-icon size="small">mdi-magnify</v-icon>
                            <span>{{ aiLoading ? (strings?.label?.aiTranslating || 'Translating...') : (s.title || 'Search') }}</span>
                        </v-btn>
                        <v-tooltip v-else :text="s.title || 'Search'" location="top">
                            <template #activator="{ props: tp }">
                                <v-btn v-bind="tp" color="primary" variant="flat" :disabled="aiLoading"
                                    style="min-width: 40px; width: 40px; height: 40px; padding: 0; border-radius: 4px;"
                                    @click="offset = 0; handleSearchEnter()">
                                    <v-icon size="small">mdi-magnify</v-icon>
                                </v-btn>
                            </template>
                        </v-tooltip>
                    </div>
                </template>
            </div>
        </P3xrAccordion>

        <!-- Results - empty -->
        <template v-if="searchDone && total === 0">
            <div style="margin-top: 8px;" />
            <P3xrAccordion :title="`${s.results || 'Results'} (0)`" accordion-key="search-results">
                <div style="padding: 16px; opacity: 0.5;">{{ strings?.label?.noResults || 'No results' }}</div>
            </P3xrAccordion>
        </template>

        <!-- Results - with data -->
        <template v-if="results.length > 0 || total > 0">
            <div style="margin-top: 8px;" />
            <P3xrAccordion :title="`${s.results || 'Results'} (${total})`" accordion-key="search-results">
                <template v-if="pages > 1" #actions>
                    <P3xrButton icon="mdi-skip-previous" label="" color="inherit" @click.stop="pageAction('first')" />
                    <P3xrButton icon="mdi-chevron-left" label="" color="inherit" @click.stop="pageAction('prev')" />
                    <span style="font-size: 12px; opacity: 0.7;">{{ currentPage }} / {{ pages }}</span>
                    <P3xrButton icon="mdi-chevron-right" label="" color="inherit" @click.stop="pageAction('next')" />
                    <P3xrButton icon="mdi-skip-next" label="" color="inherit" @click.stop="pageAction('last')" />
                </template>
                <v-list density="compact" class="pa-0">
                    <template v-for="doc in results" :key="doc._key">
                        <v-list-item style="padding: 8px 16px;">
                            <div style="display: flex; width: 100%; align-items: center;">
                                <div style="flex: 1;">
                                    <kbd style="padding: 2px 6px; border-radius: 4px; font-size: 11px; background: rgba(128,128,128,0.1); font-family: 'Roboto Mono', monospace;">{{ doc._key }}</kbd>
                                </div>
                                <div style="font-family: 'Roboto Mono', monospace; font-size: 12px;">
                                    <template v-for="(field, i) in getDocKeys(doc)" :key="field">
                                        {{ field }}: {{ doc[field] }}<template v-if="i < getDocKeys(doc).length - 1"> &middot; </template>
                                    </template>
                                </div>
                            </div>
                        </v-list-item>
                        <v-divider />
                    </template>
                </v-list>
            </P3xrAccordion>
        </template>

        <!-- Index Info -->
        <template v-if="selectedIndex && indexInfo">
            <div style="margin-top: 8px;" />
            <P3xrAccordion :title="`${s.indexInfo || 'Index Info'}: ${selectedIndex}`" accordion-key="search-index-info">
                <template v-if="!isReadonly" #actions>
                    <P3xrButton icon="mdi-delete" :label="s.dropIndex || 'Drop'" color="inherit" @click.stop="dropIndex" />
                </template>
                <v-list density="compact" class="pa-0">
                    <template v-for="key in getDocKeys(indexInfo)" :key="key">
                        <v-list-item style="padding: 8px 16px;">
                            <div style="display: flex; width: 100%;">
                                <div style="flex: 1;">{{ key }}</div>
                                <div style="font-family: 'Roboto Mono', monospace; font-size: 12px;">{{ JSON.stringify(indexInfo[key]) }}</div>
                            </div>
                        </v-list-item>
                        <v-divider />
                    </template>
                </v-list>
            </P3xrAccordion>
        </template>

        <!-- Create Index -->
        <template v-if="!isReadonly">
            <div style="margin-top: 8px;" />
            <P3xrAccordion :title="s.createIndex || 'Create Index'" accordion-key="search-create-index">
                <div style="padding: 16px;">
                    <v-text-field v-model="newIndexName" :label="s.indexName || 'Index Name'"
                        density="compact" variant="outlined" hide-details />
                    <v-text-field v-model="newIndexPrefix" :label="s.prefix || 'Key Prefix (optional)'" placeholder="e.g. doc:"
                        density="compact" variant="outlined" hide-details style="margin-top: 8px;" />

                    <div style="display: flex; align-items: center; gap: 8px; margin: 8px 0;">
                        <strong>Schema</strong>
                        <v-tooltip text="Add" location="top">
                            <template #activator="{ props: tp }">
                                <v-btn v-bind="tp" color="primary" variant="flat"
                                    style="min-width: 40px; width: 40px; height: 40px; padding: 0; border-radius: 4px;"
                                    @click="addField">
                                    <v-icon size="small">mdi-plus</v-icon>
                                </v-btn>
                            </template>
                        </v-tooltip>
                    </div>

                    <div v-for="(field, i) in newIndexFields" :key="i" style="display: flex; align-items: center; gap: 8px; margin-bottom: 4px; flex-wrap: wrap;">
                        <v-text-field v-model="field.name" :label="s.fieldName || 'Field Name'"
                            density="compact" variant="outlined" hide-details style="flex: 1; min-width: 120px;" />
                        <div style="display: flex; align-items: center; gap: 8px; flex-shrink: 0;">
                            <v-select v-model="field.type" :items="['TEXT', 'NUMERIC', 'TAG', 'GEO', 'VECTOR']"
                                :label="strings?.label?.type || 'Type'"
                                density="compact" variant="outlined" hide-details style="width: 130px;" />
                            <v-tooltip :text="strings?.intention?.delete || 'Delete'" location="top">
                                <template #activator="{ props: tp }">
                                    <v-btn v-bind="tp" color="error" variant="flat" :disabled="newIndexFields.length <= 1"
                                        style="min-width: 40px; width: 40px; height: 40px; padding: 0; border-radius: 4px;"
                                        @click="confirmRemoveField(i)">
                                        <v-icon size="small">mdi-minus</v-icon>
                                    </v-btn>
                                </template>
                            </v-tooltip>
                        </div>
                    </div>

                    <div style="margin-top: 8px; text-align: right;">
                        <v-btn v-if="isGtSm" color="secondary" variant="flat" size="small" :disabled="!newIndexName.trim()"
                            style="gap: 3px;" @click="createIndex">
                            <v-icon size="small">mdi-plus</v-icon>
                            <span>{{ s.createIndex || 'Create Index' }}</span>
                        </v-btn>
                        <v-tooltip v-else :text="s.createIndex || 'Create Index'" location="top">
                            <template #activator="{ props: tp }">
                                <v-btn v-bind="tp" color="secondary" variant="flat" :disabled="!newIndexName.trim()"
                                    style="min-width: 40px; width: 40px; height: 40px; padding: 0; border-radius: 4px;"
                                    @click="createIndex">
                                    <v-icon size="small">mdi-plus</v-icon>
                                </v-btn>
                            </template>
                        </v-tooltip>
                    </div>
                </div>
            </P3xrAccordion>
        </template>

        <div style="height: 64px;" />
    </div>
</template>
