// src/ng/pages/database/key/key-hash.component.ts
import { Component, Inject, OnInit, OnChanges, OnDestroy, SimpleChanges, ChangeDetectorRef, CUSTOM_ELEMENTS_SCHEMA, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { BreakpointObserver } from '@angular/cdk/layout';

import { I18nService } from '../../../services/i18n.service';
import { SocketService } from '../../../services/socket.service';
import { CommonService } from '../../../services/common.service';
import { JsonViewDialogService } from '../../../dialogs/json-view-dialog.service';
import { KeyNewOrSetDialogService } from '../../../dialogs/key-new-or-set-dialog.service';
import { MainCommandService } from '../../../services/main-command.service';
import { RedisStateService } from '../../../services/redis-state.service';
import { SettingsService } from '../../../services/settings.service';
import { KeyTypeBase } from './key-type-base';
import { HexMonitorComponent } from './hex-monitor.component';
import { KeyPaging } from './key-paging';
import { KeyPagerInlineComponent } from './key-pager-inline.component';
import { TtlDialogService } from '../../../dialogs/ttl-dialog.service';
import humanizeDuration from 'humanize-duration';

@Component({
    selector: 'p3xr-key-hash',
    standalone: true,
    imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatTooltipModule, KeyPagerInlineComponent, HexMonitorComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './key-hash.component.html',
    encapsulation: ViewEncapsulation.None,
})
export class KeyHashComponent extends KeyTypeBase implements OnInit, OnChanges, OnDestroy {
    paging: KeyPaging;
    pagedItems: Array<{ key: string; value: any }> = [];
    fieldTtls: Record<string, number> = {};
    private fieldTtlsFetchedAt = 0;
    private ttlCountdownInterval: any = null;

    constructor(
        @Inject(I18nService) i18n: I18nService,
        @Inject(SocketService) socket: SocketService,
        @Inject(CommonService) common: CommonService,
        @Inject(JsonViewDialogService) jsonViewDialog: JsonViewDialogService,
        @Inject(KeyNewOrSetDialogService) keyNewOrSetDialog: KeyNewOrSetDialogService,
        @Inject(BreakpointObserver) breakpointObserver: BreakpointObserver,
        @Inject(MainCommandService) cmd: MainCommandService,
        @Inject(ChangeDetectorRef) cdr: ChangeDetectorRef,
        @Inject(RedisStateService) redisState: RedisStateService,
        @Inject(SettingsService) settingsService: SettingsService,
        @Inject(TtlDialogService) private ttlDialog: TtlDialogService,
    ) {
        super(i18n, socket, common, jsonViewDialog, keyNewOrSetDialog, breakpointObserver, cmd, cdr, redisState, settingsService);
        this.paging = new KeyPaging({ settingsService });
    }

    ngOnInit(): void { this.updatePaging(); this.loadFieldTtls(); }
    ngOnChanges(changes: SimpleChanges): void {
        if (changes['p3xrValue']) { this.updatePaging(); this.loadFieldTtls(); }
    }

    updatePaging(): void {
        if (!this.p3xrValue) return;
        this.paging.figurePaging(Object.keys(this.p3xrValue).length);
        this.updatePagedItems();
    }

    updatePagedItems(): void {
        if (!this.p3xrValue) { this.pagedItems = []; return; }
        const keys = Object.keys(this.p3xrValue);
        this.pagedItems = keys.slice(this.paging.startIndex, this.paging.endIndex)
            .map(k => ({ key: k, value: this.p3xrValue[k] }));
    }

    async addHash(event: Event): Promise<void> {
        try {
            await this.keyNewOrSetDialog.show({ $event: event, type: 'append', model: { type: 'hash', key: this.p3xrKey } });
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    async deleteHashKey(hashKey: string, event: Event): Promise<void> {
        try {
            await this.common.confirm({ message: this.i18n.strings().confirm?.deleteHashKey });
            await this.socket.request({ action: 'key-hash-delete-field', payload: { key: this.p3xrKey, hashKey } });
            this.common.toast(this.i18n.strings().status?.deletedHashKey);
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    async editValue(hashKey: string, value: any, event: Event): Promise<void> {
        try {
            const editValue = typeof value === 'string' && value.length >= this.maxValueAsBuffer
                ? this.p3xrValueBuffer[hashKey] : value;
            await this.keyNewOrSetDialog.show({
                $event: event, type: 'edit',
                model: { type: 'hash', key: this.p3xrKey, hashKey, value: editValue },
            });
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    ngOnDestroy(): void {
        this.clearTtlCountdown();
    }

    private clearTtlCountdown(): void {
        if (this.ttlCountdownInterval) {
            clearInterval(this.ttlCountdownInterval);
            this.ttlCountdownInterval = null;
        }
    }

    private startTtlCountdown(): void {
        this.clearTtlCountdown();
        const hasAnyTtl = Object.values(this.fieldTtls).some(t => t > 0);
        if (!hasAnyTtl) return;
        this.ttlCountdownInterval = setInterval(() => {
            // Check if any field just expired — refresh the key view
            const anyExpired = Object.keys(this.fieldTtls).some(f => {
                const ttl = this.fieldTtls[f];
                if (!ttl || ttl <= 0) return false;
                const elapsed = Math.floor((Date.now() - this.fieldTtlsFetchedAt) / 1000);
                return ttl - elapsed <= 0;
            });
            if (anyExpired) {
                this.clearTtlCountdown();
                this.refreshKey();
                return;
            }
            this.cdr.markForCheck();
        }, 1000);
    }

    private getRemainingFieldTtl(field: string): number {
        const ttl = this.fieldTtls[field];
        if (!ttl || ttl <= 0) return -1;
        const elapsed = Math.floor((Date.now() - this.fieldTtlsFetchedAt) / 1000);
        const remaining = ttl - elapsed;
        return remaining > 0 ? remaining : -1;
    }

    async loadFieldTtls(): Promise<void> {
        if (!this.redisState.redisVersion().isAtLeast(8, 0) || !this.pagedItems.length) return;
        try {
            const fields = this.pagedItems.map(item => item.key);
            if (fields.length === 0) return;
            const response = await this.socket.request({
                action: 'hash-field-ttls',
                payload: { key: this.p3xrKey, fields },
            });
            this.fieldTtls = (response as any).fieldTtls || {};
            this.fieldTtlsFetchedAt = Date.now();
            this.startTtlCountdown();
            this.cdr.markForCheck();
        } catch {
            this.fieldTtls = {};
        }
    }

    getFieldTtlColor(field: string): string {
        const remaining = this.getRemainingFieldTtl(field);
        if (remaining <= 0) return '';
        if (remaining < 300) return 'var(--mat-sys-error, #f44336)';
        if (remaining < 3600) return 'var(--mat-sys-tertiary, #ff9800)';
        return '#4caf50';
    }

    isFieldTtlPulsing(field: string): boolean {
        const remaining = this.getRemainingFieldTtl(field);
        return remaining > 0 && remaining < 30;
    }

    hasFieldTtl(field: string): boolean {
        return this.getRemainingFieldTtl(field) > 0;
    }

    formatFieldTtl(field: string): string {
        const remaining = this.getRemainingFieldTtl(field);
        if (remaining <= 0) return '';
        const hdOpts = this.settingsService.getHumanizeDurationOptions();
        return humanizeDuration(remaining * 1000, { ...hdOpts, largest: 2, round: true, delimiter: ' ' });
    }

    async setFieldTtl(hashKey: string, event: Event): Promise<void> {
        try {
            // Get current field TTL
            const ttlResponse = await this.socket.request({
                action: 'hash-field-ttl-get',
                payload: { key: this.p3xrKey, field: hashKey },
            });
            const currentTtl = ttlResponse.ttl ?? -1;
            const result = await this.ttlDialog.show({ $event: event, model: { ttl: currentTtl } });
            await this.socket.request({
                action: 'hash-field-ttl',
                payload: { key: this.p3xrKey, field: hashKey, ttl: result.model.ttl },
            });
            this.common.toast(`${hashKey}: TTL ${result.model.ttl === -1 ? 'removed' : result.model.ttl + 's'}`);
            this.loadFieldTtls();
        } catch (e: any) {
            if (e !== undefined) this.common.generalHandleError(e);
        }
    }

    copyItem(value: any): void { this.copy(value); }
    showJsonItem(value: any, event: Event): void { this.showJson(value, event); }
    downloadItem(hashKey: string): void { this.downloadBuffer(this.p3xrValueBuffer[hashKey], `${this.p3xrKey}-${hashKey}.bin`); }
}

<p3xr-key-pager-inline [paging]="paging" (pageChanged)="updatePagedItems(); loadFieldTtls()"></p3xr-key-pager-inline>

<div class="p3xr-key-type-table">
    <div class="p3xr-key-type-header">
        <span style="flex: 20%">{{ strings?.page?.key?.hash?.table?.hashkey || 'Hash Key' }}</span>
        <span style="flex: 60%">{{ strings?.page?.key?.hash?.table?.value || 'Value' }}</span>
        <span style="flex: 20%; text-align: right">
            @if (!isReadonly) {
                <button mat-icon-button (click)="addHash($event)" matTooltip="Add">
                    <mat-icon svgIcon="add"></mat-icon>
                </button>
            }
        </span>
    </div>

    @for (item of pagedItems; track item.key) {
        <div class="p3xr-key-type-row">
            <span class="p3xr-key-col" style="flex: 20%; cursor: pointer" (click)="editValue(item.key, item.value, $event)">{{ item.key }}</span>
            <span class="p3xr-value-col" [class.p3xr-pre]="valueFormat !== 'hex'" style="flex: 60%; cursor: pointer" (click)="editValue(item.key, item.value, $event)">@if (valueFormat === 'hex') {<p3xr-hex-monitor [value]="truncateDisplay(item.value)" [truncated]="isTruncated(item.value)"></p3xr-hex-monitor>} @else {{{ truncateDisplay(formatValue(item.value)) }}@if (isTruncated(item.value)) {<span style="opacity: 0.5;">...</span>}}</span>
            <span style="flex: 20%; text-align: right" class="p3xr-key-type-row-actions">
                @if (!isReadonly && redisState.redisVersion().isAtLeast(8, 0)) {
                    <mat-icon [style.color]="getFieldTtlColor(item.key) || null"
                              [style.opacity]="hasFieldTtl(item.key) ? 0.7 : 0.3"
                              [class.p3xr-tree-ttl-pulse]="isFieldTtlPulsing(item.key)"
                              (click)="setFieldTtl(item.key, $event)"
                              [matTooltip]="hasFieldTtl(item.key) ? ('TTL: ' + formatFieldTtl(item.key)) : (strings?.intention?.ttl || 'Set TTL')">schedule</mat-icon>
                }
                @if (!isReadonly) {
                    <mat-icon class="icon-warn" (click)="deleteHashKey(item.key, $event)" matTooltip="Delete">delete</mat-icon>
                }
                <mat-icon class="icon-accent" (click)="showJsonItem(item.value, $event)" matTooltip="JSON">account_tree</mat-icon>
                <mat-icon class="icon-accent" (click)="copyItem(item.value)" matTooltip="Copy">content_copy</mat-icon>
                <mat-icon class="icon-accent" (click)="downloadItem(item.key)" matTooltip="Download">download</mat-icon>
                @if (!isReadonly) {
                    <mat-icon class="icon-primary" (click)="editValue(item.key, item.value, $event)" matTooltip="Edit">edit</mat-icon>
                }
            </span>
        </div>
    }
</div>

// src/react/pages/database/key/KeyHash.tsx
/**
 * Hash key type renderer — exact port of Angular key-hash.component.
 * Table with hashkey + value, paging, add/delete/edit/copy/json/download per row.
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import { Box, Tooltip } from '@mui/material'
import { Delete, TableChart, ContentCopy, Download, Edit, Add, Schedule as ScheduleIcon } from '@mui/icons-material'
import { useTheme } from '@mui/material'
import { useI18nStore } from '../../../stores/i18n.store'
import { useRedisStateStore } from '../../../stores/redis-state.store'
import { parseRedisVersion } from '../../../../core/redis-version'
import { useCommonStore } from '../../../stores/common.store'
import { useSettingsStore } from '../../../stores/settings.store'
import humanizeDuration from 'humanize-duration'
import { request } from '../../../stores/socket.service'
import { KeyTypeProps, createPaging, rePaging, Paging, formatValue, truncateDisplay, isTruncated, copyValue, downloadBuffer } from './key-type-base'
import HexMonitor from './HexMonitor'
import KeyPagerInline from './KeyPagerInline'
import KeyNewOrSetDialog from '../../../dialogs/KeyNewOrSetDialog'
import JsonViewDialog from '../../../dialogs/JsonViewDialog'
import TtlDialog from '../../../dialogs/TtlDialog'

export default function KeyHash({ response, value, valueBuffer, keyName, valueFormat, onRefresh }: KeyTypeProps) {
    const strings = useI18nStore(s => s.strings)
    const connection = useRedisStateStore(s => s.connection)
    const { toast, confirm, generalHandleError } = useCommonStore()
    const muiTheme = useTheme()
    const isReadonly = connection?.readonly === true
    const isDark = muiTheme.palette.mode === 'dark'

    const [paging, setPaging] = useState<Paging>(() => createPaging(value ? Object.keys(value).length : 0))
    const [pagedItems, setPagedItems] = useState<Array<{ key: string; value: any }>>([])
    const [editDialogOpen, setEditDialogOpen] = useState(false)
    const [editDialogData, setEditDialogData] = useState<any>(null)
    const [jsonViewOpen, setJsonViewOpen] = useState(false)
    const [jsonViewValue, setJsonViewValue] = useState('')
    const [ttlDialogOpen, setTtlDialogOpen] = useState(false)
    const [ttlDialogField, setTtlDialogField] = useState('')
    const [ttlDialogValue, setTtlDialogValue] = useState(-1)
    const [fieldTtls, setFieldTtls] = useState<Record<string, number>>({})
    const fieldTtlsFetchedAtRef = useRef(0)
    const [tick, setTick] = useState(0)
    const onRefreshRef = useRef(onRefresh)
    onRefreshRef.current = onRefresh

    const loadFieldTtls = useCallback(async (items?: Array<{ key: string; value: any }>) => {
        if (!value || !parseRedisVersion(useRedisStateStore.getState().info?.server?.redis_version).isAtLeast(8, 0)) return
        try {
            const fields = (items || pagedItems).map(item => item.key)
            if (fields.length === 0) return
            const res = await request({ action: 'hash-field/ttls', payload: { key: keyName, fields } })
            setFieldTtls(res.fieldTtls || {})
            fieldTtlsFetchedAtRef.current = Date.now()
        } catch { setFieldTtls({}) }
    }, [value, keyName, pagedItems])

    // Inject pulse keyframes once
    useEffect(() => {
        if (document.getElementById('p3xr-hash-ttl-pulse-css')) return
        const style = document.createElement('style')
        style.id = 'p3xr-hash-ttl-pulse-css'
        style.textContent = '@keyframes p3xr-hash-ttl-pulse { 0%, 100% { opacity: 0.3; } 50% { opacity: 1; } }'
        document.head.appendChild(style)
    }, [])

    // 1-second tick for live countdown
    useEffect(() => {
        if (!Object.values(fieldTtls).some(t => t > 0)) return
        const id = setInterval(() => {
            // Check for expired fields
            const elapsed = Math.floor((Date.now() - fieldTtlsFetchedAtRef.current) / 1000)
            const anyExpired = Object.values(fieldTtls).some(t => t > 0 && t - elapsed <= 0)
            if (anyExpired) { clearInterval(id); onRefreshRef.current(); return }
            setTick(t => t + 1)
        }, 1000)
        return () => clearInterval(id)
    }, [fieldTtls])

    useEffect(() => {
        if (!value) return
        const keys = Object.keys(value)
        const p = rePaging(paging, keys.length)
        setPaging(p)
        const items = keys.slice(p.startIndex, p.endIndex).map(k => ({ key: k, value: value[k] }))
        setPagedItems(items)
        loadFieldTtls(items)
    }, [value])

    const updatePagedItems = useCallback((p: Paging) => {
        setPaging(p)
        if (!value) { setPagedItems([]); return }
        const keys = Object.keys(value)
        const items = keys.slice(p.startIndex, p.endIndex).map(k => ({ key: k, value: value[k] }))
        setPagedItems(items)
        loadFieldTtls(items)
    }, [value, loadFieldTtls])

    const addHash = useCallback(() => {
        setEditDialogData({ type: 'append', model: { type: 'hash', key: keyName } })
        setEditDialogOpen(true)
    }, [keyName])

    const deleteHashKey = useCallback(async (hashKey: string) => {
        try {
            await confirm({ message: strings?.confirm?.deleteHashKey ?? strings?.confirm?.areYouSure ?? 'Are you sure?' })
            await request({ action: 'key/hash-delete-field', payload: { key: keyName, hashKey } })
            toast(strings?.status?.deletedHashKey)
            onRefresh()
        } catch (e) { generalHandleError(e) }
    }, [keyName, strings, confirm, toast, onRefresh, generalHandleError])

    const editValue = useCallback((hashKey: string, val: any) => {
        const editVal = typeof val === 'string' && val.length >= (useRedisStateStore.getState() as any).maxValueAsBuffer
            ? valueBuffer?.[hashKey] : val
        setEditDialogData({ type: 'edit', model: { type: 'hash', key: keyName, hashKey, value: editVal } })
        setEditDialogOpen(true)
    }, [keyName, valueBuffer])

    const handleEditClose = useCallback((result?: any) => {
        setEditDialogOpen(false)
        setEditDialogData(null)
        if (result) onRefresh()
    }, [onRefresh])

    const setFieldTtl = useCallback(async (hashKey: string) => {
        try {
            const res = await request({ action: 'hash-field/ttl-get', payload: { key: keyName, field: hashKey } })
            setTtlDialogField(hashKey)
            setTtlDialogValue(res.ttl ?? -1)
            setTtlDialogOpen(true)
        } catch (e) { generalHandleError(e) }
    }, [keyName, generalHandleError])

    const handleTtlClose = useCallback(async (result?: { model: { ttl: number } }) => {
        setTtlDialogOpen(false)
        if (!result) return
        try {
            await request({ action: 'hash-field/ttl', payload: { key: keyName, field: ttlDialogField, ttl: result.model.ttl } })
            toast(`${ttlDialogField}: TTL ${result.model.ttl === -1 ? 'removed' : result.model.ttl + 's'}`)
            loadFieldTtls()
        } catch (e) { generalHandleError(e) }
    }, [keyName, ttlDialogField, toast, generalHandleError, loadFieldTtls])

    const getRemaining = (field: string): number => {
        void tick
        const ttl = fieldTtls[field]
        if (!ttl || ttl <= 0) return -1
        const elapsed = Math.floor((Date.now() - fieldTtlsFetchedAtRef.current) / 1000)
        const r = ttl - elapsed
        return r > 0 ? r : -1
    }

    const getFieldTtlColor = (field: string): string => {
        const r = getRemaining(field)
        if (r <= 0) return ''
        if (r < 300) return '#f44336'
        if (r < 3600) return '#ff9800'
        return '#4caf50'
    }

    const isFieldTtlPulsing = (field: string): boolean => getRemaining(field) > 0 && getRemaining(field) < 30

    const hasFieldTtl = (field: string): boolean => getRemaining(field) > 0

    const formatFieldTtl = (field: string): string => {
        const remaining = getRemaining(field)
        if (remaining <= 0) return ''
        const hdOpts = useSettingsStore.getState().getHumanizeDurationOptions()
        return humanizeDuration(remaining * 1000, { ...hdOpts, largest: 2, round: true, delimiter: ' ' })
    }

    const hoverBg = isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)'
    const oddBg = isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'
    const listBorder = isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.06)'
    const iconSx = (color: string) => ({ fontSize: 18, cursor: 'pointer', mx: '2px', opacity: 0.7, color, '&:hover': { opacity: 1 } })

    return (
        <Box>
            <KeyPagerInline paging={paging} onPageChange={updatePagedItems} />
            <Box>
                <Box sx={{
                    display: 'flex', alignItems: 'center', gap: 1, px: 2, py: 1, fontWeight: 'bold',
                    bgcolor: muiTheme.palette.primary.main, color: muiTheme.palette.primary.contrastText,
                    borderBottom: `2px solid ${listBorder}`,
                }}>
                    <Box component="span" sx={{ flex: '20%' }}>{strings?.page?.key?.hash?.table?.hashkey ?? 'Hash Key'}</Box>
                    <Box component="span" sx={{ flex: '60%' }}>{strings?.page?.key?.hash?.table?.value ?? 'Value'}</Box>
                    <Box component="span" sx={{ flex: '20%', textAlign: 'right', display: 'flex', justifyContent: 'flex-end', alignItems: 'center' }}>
                        {!isReadonly && (
                            <Tooltip title={strings?.intention?.add}><Add sx={{ cursor: 'pointer', color: 'inherit' }} onClick={addHash} /></Tooltip>
                        )}
                    </Box>
                </Box>

                {pagedItems.map((item, i) => (
                    <Box key={item.key} sx={{
                        display: 'flex', alignItems: 'flex-start', gap: 1, px: 2, py: '6px',
                        borderBottom: `1px solid ${listBorder}`,
                        bgcolor: i % 2 === 0 ? oddBg : 'transparent',
                        '&:hover': { bgcolor: `${hoverBg} !important` },
                    }}>
                        <Box component="span" sx={{ flex: '20%', cursor: 'pointer', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', userSelect: 'text' }}
                            onClick={() => editValue(item.key, item.value)}>{item.key}</Box>
                        <Box component="span" sx={{
                            flex: '60%', cursor: 'pointer', overflow: 'auto', maxHeight: 200,
                            ...(valueFormat !== 'hex' ? { whiteSpace: 'pre-wrap', wordBreak: 'break-all', fontFamily: "'Roboto Mono', monospace" } : {}),
                            userSelect: 'text',
                        }} onClick={() => editValue(item.key, item.value)}>
                            {valueFormat === 'hex'
                                ? <HexMonitor value={truncateDisplay(item.value)} truncated={isTruncated(item.value)} />
                                : <>{truncateDisplay(formatValue(item.value, valueFormat))}{isTruncated(item.value) && <span style={{ opacity: 0.5 }}>...</span>}</>}
                        </Box>
                        <Box component="span" sx={{ flex: '20%', textAlign: 'right', whiteSpace: 'nowrap' }}>
                            {!isReadonly && parseRedisVersion(useRedisStateStore.getState().info?.server?.redis_version).isAtLeast(8, 0) && (
                                <Tooltip title={hasFieldTtl(item.key) ? `TTL: ${formatFieldTtl(item.key)}` : (strings?.intention?.ttl || 'Set TTL')}>
                                    <ScheduleIcon
                                        style={{
                                            fontSize: 18, cursor: 'pointer', marginLeft: 2, marginRight: 2,
                                            color: getFieldTtlColor(item.key) || undefined,
                                            opacity: hasFieldTtl(item.key) ? 0.7 : 0.3,
                                            animation: isFieldTtlPulsing(item.key) ? 'p3xr-hash-ttl-pulse 1s infinite' : 'none',
                                        }}
                                        onClick={() => setFieldTtl(item.key)} />
                                </Tooltip>
                            )}
                            {!isReadonly && <Tooltip title={strings?.intention?.delete}><Delete sx={iconSx('error.main')} onClick={() => deleteHashKey(item.key)} /></Tooltip>}
                            <Tooltip title={strings?.intention?.jsonViewShow}><TableChart sx={iconSx('secondary.main')} onClick={() => { setJsonViewValue(String(item.value ?? '')); setJsonViewOpen(true) }} /></Tooltip>
                            <Tooltip title={strings?.intention?.copy}><ContentCopy sx={iconSx('secondary.main')} onClick={() => copyValue(item.value)} /></Tooltip>
                            <Tooltip title={strings?.intention?.downloadBuffer}><Download sx={iconSx('secondary.main')} onClick={() => downloadBuffer(valueBuffer?.[item.key], keyName, `${keyName}-${item.key}.bin`)} /></Tooltip>
                            {!isReadonly && <Tooltip title={strings?.intention?.edit}><Edit sx={iconSx('primary.main')} onClick={() => editValue(item.key, item.value)} /></Tooltip>}
                        </Box>
                    </Box>
                ))}
            </Box>

            <KeyNewOrSetDialog open={editDialogOpen} data={editDialogData} onClose={handleEditClose} />
            <JsonViewDialog open={jsonViewOpen} value={jsonViewValue} onClose={() => setJsonViewOpen(false)} />
            <TtlDialog open={ttlDialogOpen} ttl={ttlDialogValue} onClose={handleTtlClose} />
        </Box>
    )
}
