// src/vue/pages/database/key/KeyJson.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useDisplay } from 'vuetify'
import JsonTreeNode, { type JsonNode } from '../../../components/JsonTreeNode.vue'
import JsonEditorDialog from '../../../dialogs/JsonEditorDialog.vue'
import DiffDialog from '../../../dialogs/DiffDialog.vue'
import { useI18nStore } from '../../../stores/i18n'
import { useRedisStateStore } from '../../../stores/redis-state'
import { useSettingsStore } from '../../../stores/settings'
import { useCommonStore } from '../../../stores/common'
import { useOverlayStore } from '../../../stores/overlay'
import { useThemeStore } from '../../../stores/theme'
import { storeToRefs } from 'pinia'
import { request } from '../../../stores/socket.service'
import { truncateDisplay, copyToClipboard, str } from './key-type-base'

function jsonToNode(key: string, value: any): JsonNode {
    if (value === null) return { key, value: null, type: 'null' }
    if (Array.isArray(value)) { const c = value.map((item, i) => jsonToNode(String(i), item)); return { key, value, type: 'array', children: c, childCount: c.length } }
    if (typeof value === 'object') { const c = Object.keys(value).map(k => jsonToNode(k, value[k])); return { key, value, type: 'object', children: c, childCount: c.length } }
    return { key, value, type: typeof value as any }
}

const props = defineProps<{ response: any; value: any; valueBuffer: any; keyName: string; valueFormat: string }>()
const emit = defineEmits<{ refresh: [] }>()
const strings = computed(() => useI18nStore().strings)
const isReadonly = computed(() => useRedisStateStore().connection?.readonly === true)
const { themeKey } = storeToRefs(useThemeStore())
const isDark = computed(() => ['dark', 'darkNeu', 'darkoBluo', 'matrix'].includes(themeKey.value))
const settings = useSettingsStore()
const common = useCommonStore()
const overlay = useOverlayStore()
const { width } = useDisplay()
const isGtSm = computed(() => width.value >= 960)

const jsonObj = ref<any>(undefined)
const treeWrap = ref(true)
const expandedKeys = ref<Set<string>>(new Set())
const editorOpen = ref(false)
const diffOpen = ref(false)
const diffOldValue = ref('')
const diffNewValue = ref('')
let diffResolve: ((v: boolean) => void) | null = null

const rootLabel = computed(() => strings.value?.label?.tree ?? 'root')
const tree = computed(() => jsonObj.value !== undefined ? jsonToNode(rootLabel.value, jsonObj.value) : null)

watch(() => props.value, () => {
    try {
        jsonObj.value = typeof props.value === 'string' ? JSON.parse(props.value) : props.value
        expandedKeys.value = new Set([`0-${rootLabel.value}`])
    } catch { jsonObj.value = undefined }
}, { immediate: true })

function toggleExpand(path: string) { const s = new Set(expandedKeys.value); s.has(path) ? s.delete(path) : s.add(path); expandedKeys.value = s }

function expandAll() {
    if (jsonObj.value === undefined) return
    const keys = new Set<string>()
    const collect = (node: JsonNode, level: number) => { const p = `${level}-${node.key}`; if (node.type === 'object' || node.type === 'array') { keys.add(p); node.children?.forEach(c => collect(c, level + 1)) } }
    collect(jsonToNode(rootLabel.value, jsonObj.value), 0)
    expandedKeys.value = keys
}
function collapseAll() { expandedKeys.value = new Set([`0-${rootLabel.value}`]) }

function copyVal() { copyToClipboard(String(props.value ?? '')) }
function downloadJson() {
    const blob = new Blob([props.value], { type: 'application/json' })
    const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${props.keyName}.json`; a.click(); URL.revokeObjectURL(url)
}

async function handleEditorClose(result?: { obj: string } | null) {
    editorOpen.value = false
    if (!result?.obj) return
    const oldVal = props.value
    const val = typeof result.obj === 'string' ? result.obj : JSON.stringify(result.obj)
    overlay.show()
    try {
        await request({ action: 'key/json-set', payload: { key: props.keyName, path: '$', value: val } })
        emit('refresh'); overlay.hide()
        if (settings.undoEnabled && oldVal !== val) {
            const undo = await common.toastWithUndo(str(strings.value?.status?.set))
            if (undo) { overlay.show({ message: 'Undo...' }); await request({ action: 'key/json-set', payload: { key: props.keyName, path: '$', value: oldVal } }); emit('refresh'); overlay.hide(); common.toast(str(strings.value?.status?.reverted)) }
        }
    } catch (e) { common.generalHandleError(e); overlay.hide() }
}
</script>

<template>
    <div>
        <div class="p3xr-key-type-actions">
            <!-- Copy -->
            <v-btn v-if="isGtSm" variant="flat" color="secondary" @click="copyVal()" style="gap:3px;"><v-icon size="small">mdi-content-copy</v-icon><span>{{ str(strings?.intention?.copy) }}</span></v-btn>
            <v-tooltip v-else :text="str(strings?.intention?.copy)" location="top"><template #activator="{ props: tp }"><v-btn v-bind="tp" variant="flat" color="secondary" @click="copyVal()" style="min-width:40px;width:40px;height:40px;padding:0;border-radius:4px;"><v-icon size="small">mdi-content-copy</v-icon></v-btn></template></v-tooltip>
            <!-- Download -->
            <v-btn v-if="isGtSm" variant="flat" color="secondary" @click="downloadJson()" style="gap:3px;"><v-icon size="small">mdi-download</v-icon><span>{{ str(strings?.intention?.downloadJson) }}</span></v-btn>
            <v-tooltip v-else :text="str(strings?.intention?.downloadJson)" location="top"><template #activator="{ props: tp }"><v-btn v-bind="tp" variant="flat" color="secondary" @click="downloadJson()" style="min-width:40px;width:40px;height:40px;padding:0;border-radius:4px;"><v-icon size="small">mdi-download</v-icon></v-btn></template></v-tooltip>
            <!-- Expand All -->
            <v-btn v-if="isGtSm" variant="flat" color="secondary" @click="expandAll()" style="gap:3px;"><v-icon size="small">mdi-unfold-more-horizontal</v-icon><span>{{ str(strings?.page?.treeControls?.expandAll) }}</span></v-btn>
            <v-tooltip v-else :text="str(strings?.page?.treeControls?.expandAll)" location="top"><template #activator="{ props: tp }"><v-btn v-bind="tp" variant="flat" color="secondary" @click="expandAll()" style="min-width:40px;width:40px;height:40px;padding:0;border-radius:4px;"><v-icon size="small">mdi-unfold-more-horizontal</v-icon></v-btn></template></v-tooltip>
            <!-- Collapse All -->
            <v-btn v-if="isGtSm" variant="flat" color="secondary" @click="collapseAll()" style="gap:3px;"><v-icon size="small">mdi-unfold-less-horizontal</v-icon><span>{{ str(strings?.page?.treeControls?.collapseAll) }}</span></v-btn>
            <v-tooltip v-else :text="str(strings?.page?.treeControls?.collapseAll)" location="top"><template #activator="{ props: tp }"><v-btn v-bind="tp" variant="flat" color="secondary" @click="collapseAll()" style="min-width:40px;width:40px;height:40px;padding:0;border-radius:4px;"><v-icon size="small">mdi-unfold-less-horizontal</v-icon></v-btn></template></v-tooltip>
            <!-- Wrap toggle -->
            <v-btn v-if="isGtSm" variant="flat" color="secondary" @click="treeWrap = !treeWrap" style="gap:3px;"><v-icon size="small">{{ treeWrap ? 'mdi-wrap' : 'mdi-wrap-disabled' }}</v-icon><span>{{ treeWrap ? str(strings?.intention?.unwrap) : str(strings?.intention?.wrap) }}</span></v-btn>
            <v-tooltip v-else :text="treeWrap ? str(strings?.intention?.unwrap) : str(strings?.intention?.wrap)" location="top"><template #activator="{ props: tp }"><v-btn v-bind="tp" variant="flat" color="secondary" @click="treeWrap = !treeWrap" style="min-width:40px;width:40px;height:40px;padding:0;border-radius:4px;"><v-icon size="small">{{ treeWrap ? 'mdi-wrap' : 'mdi-wrap-disabled' }}</v-icon></v-btn></template></v-tooltip>
            <!-- Edit (JSON Editor) -->
            <template v-if="!isReadonly">
                <v-btn v-if="isGtSm" variant="flat" color="primary" @click="editorOpen = true" style="gap:3px;"><v-icon size="small">mdi-pencil</v-icon><span>{{ str(strings?.intention?.jsonViewEditor) }}</span></v-btn>
                <v-tooltip v-else :text="str(strings?.intention?.jsonViewEditor)" location="top"><template #activator="{ props: tp }"><v-btn v-bind="tp" variant="flat" color="primary" @click="editorOpen = true" style="min-width:40px;width:40px;height:40px;padding:0;border-radius:4px;"><v-icon size="small">mdi-pencil</v-icon></v-btn></template></v-tooltip>
            </template>
        </div>

        <div class="p3xr-key-type-content" style="overflow:auto;">
            <JsonTreeNode v-if="tree" :node="tree" :level="0" :expanded-keys="expandedKeys" :is-dark="isDark" @toggle="toggleExpand" />
            <div v-else style="font-family:'Roboto Mono',monospace;white-space:pre-wrap;word-break:break-all;">{{ truncateDisplay(value) }}</div>
        </div>

        <JsonEditorDialog :open="editorOpen" :value="String(value ?? '')" hide-format-save @close="handleEditorClose" />
        <DiffDialog :open="diffOpen" :key-name="keyName" :old-value="diffOldValue" :new-value="diffNewValue"
            @confirm="diffOpen = false; diffResolve?.(true)" @cancel="diffOpen = false; diffResolve?.(false)" />
    </div>
</template>

<style scoped>
.p3xr-key-type-actions { display: flex; flex-wrap: wrap; justify-content: flex-end; align-items: center; gap: 8px; padding: 4px 8px; }
.p3xr-key-type-content { padding: 8px 16px 24px; }
</style>

// src/react/pages/database/key/KeyJson.tsx
/**
 * JSON (ReJSON) key type renderer — exact port of Angular key-json.component.
 * Inline JSON tree view with expand/collapse, wrap toggle, copy, download, edit.
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import { Box, Button, Tooltip, useMediaQuery, useTheme as useMuiTheme } from '@mui/material'
import {
    ContentCopy, Download, UnfoldMore, UnfoldLess, WrapText, Notes, Edit,
    ExpandMore, ChevronRight,
} from '@mui/icons-material'
import { useI18nStore } from '../../../stores/i18n.store'
import { useRedisStateStore } from '../../../stores/redis-state.store'
import { useCommonStore } from '../../../stores/common.store'
import { useSettingsStore } from '../../../stores/settings.store'
import { useOverlayStore } from '../../../stores/overlay.store'
import { request } from '../../../stores/socket.service'
import { trackPage } from '../../../stores/analytics'
import { KeyTypeProps, truncateDisplay, copyValue } from './key-type-base'
import JsonEditorDialog from '../../../dialogs/JsonEditorDialog'
import DiffDialog from '../../../dialogs/DiffDialog'

// --- Inline JSON Tree (reused from JsonViewDialog pattern) ---

interface JsonNode {
    key: string; value: any; type: 'object' | 'array' | 'string' | 'number' | 'boolean' | 'null'
    children?: JsonNode[]; childCount?: number
}

function jsonToNode(key: string, value: any): JsonNode {
    if (value === null) return { key, value: null, type: 'null' }
    if (Array.isArray(value)) {
        const children = value.map((item, i) => jsonToNode(String(i), item))
        return { key, value, type: 'array', children, childCount: children.length }
    }
    if (typeof value === 'object') {
        const children = Object.keys(value).map(k => jsonToNode(k, value[k]))
        return { key, value, type: 'object', children, childCount: children.length }
    }
    return { key, value, type: typeof value as any }
}

function formatDisplay(node: JsonNode): string {
    if (node.type === 'null') return 'null'
    if (node.type === 'string') return `"${node.value}"`
    return String(node.value)
}

function useJsonColors() {
    const { palette } = useMuiTheme()
    const isDark = palette.mode === 'dark'
    return {
        key: isDark ? 'white' : 'black',
        string: palette.secondary.main,
        number: palette.primary.main,
        boolean: palette.error.main,
        null: isDark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)',
    }
}

function TreeNode({ node, level, expandedKeys, toggleExpand, wrap }: {
    node: JsonNode; level: number; expandedKeys: Set<string>; toggleExpand: (p: string) => void; wrap: boolean
}) {
    const colors = useJsonColors()
    const path = `${level}-${node.key}`
    const isExpandable = node.type === 'object' || node.type === 'array'
    const isExpanded = expandedKeys.has(path)
    const valueColor = isExpandable ? undefined : (colors as any)[node.type] ?? 'inherit'

    return (
        <>
            <Box sx={{
                display: 'flex', alignItems: 'flex-start', minHeight: 24, lineHeight: 1.6,
                pl: `${level * 20}px`, fontFamily: "'Roboto Mono', monospace", fontSize: 13,
            }}>
                {isExpandable ? (
                    <Box component="span" onClick={() => toggleExpand(path)} sx={{
                        width: 24, height: 24, display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                        cursor: 'pointer', flexShrink: 0, opacity: 0.6,
                    }}>
                        {isExpanded ? <ExpandMore sx={{ fontSize: 18 }} /> : <ChevronRight sx={{ fontSize: 18 }} />}
                    </Box>
                ) : (
                    <Box sx={{ width: 24, height: 24, flexShrink: 0 }} />
                )}
                <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: '6px', flex: 1, minWidth: 0, flexWrap: 'nowrap' }}>
                    <Box component="span" sx={{ flexShrink: 0, whiteSpace: 'nowrap' }}>
                        <Box component="span" sx={{ fontWeight: 'bold', color: colors.key }}>{node.key}</Box>
                        <Box component="span" sx={{ opacity: 0.6 }}>:</Box>
                    </Box>
                    {isExpandable ? (
                        !isExpanded ? (
                            <>
                                <Box component="span" sx={{ opacity: 0.5 }}>{node.type === 'array' ? '[' : '{'}</Box>
                                <Box component="span" sx={{ opacity: 0.4 }}>...</Box>
                                <Box component="span" sx={{ opacity: 0.5 }}>{node.type === 'array' ? ']' : '}'}</Box>
                                <Box component="span" sx={{ opacity: 0.4, fontSize: 11, ml: '4px' }}>({node.childCount})</Box>
                            </>
                        ) : null
                    ) : (
                        <Box component="span" sx={{
                            wordBreak: wrap ? 'break-word' : 'normal',
                            whiteSpace: wrap ? 'normal' : 'nowrap',
                            minWidth: 0, color: valueColor,
                            fontStyle: node.type === 'null' ? 'italic' : 'normal',
                        }}>
                            {formatDisplay(node)}
                        </Box>
                    )}
                </Box>
            </Box>
            {isExpandable && isExpanded && node.children?.map((child, i) => (
                <TreeNode key={`${child.key}-${i}`} node={child} level={level + 1}
                    expandedKeys={expandedKeys} toggleExpand={toggleExpand} wrap={wrap} />
            ))}
        </>
    )
}

// --- Main component ---

export default function KeyJson({ response, value, valueBuffer, keyName, valueFormat, onRefresh }: KeyTypeProps) {
    const strings = useI18nStore(s => s.strings)
    const connection = useRedisStateStore(s => s.connection)
    const { toast, generalHandleError } = useCommonStore()
    const overlay = useOverlayStore()
    const isGtSm = useMediaQuery('(min-width: 960px)')
    const isReadonly = connection?.readonly === true

    const [jsonObj, setJsonObj] = useState<any>(undefined)
    const [treeWrap, setTreeWrap] = useState(true)
    const [expandedKeys, setExpandedKeys] = useState<Set<string>>(new Set())
    const [editorOpen, setEditorOpen] = useState(false)
    const [diffOpen, setDiffOpen] = useState(false)
    const [diffData, setDiffData] = useState({ oldValue: '', newValue: '' })
    const diffResolveRef = useRef<((v: boolean) => void) | null>(null)

    const rootLabel = strings?.label?.tree ?? 'root'

    useEffect(() => {
        try {
            const obj = JSON.parse(value)
            setJsonObj(obj)
            setExpandedKeys(new Set([`0-${rootLabel}`]))
        } catch {
            setJsonObj(undefined)
        }
    }, [value, rootLabel])

    const toggleExpand = useCallback((path: string) => {
        setExpandedKeys(prev => {
            const next = new Set(prev)
            if (next.has(path)) next.delete(path); else next.add(path)
            return next
        })
    }, [])

    const expandAll = useCallback(() => {
        if (jsonObj === undefined) return
        const tree = jsonToNode(rootLabel, jsonObj)
        const keys = new Set<string>()
        const collect = (node: JsonNode, level: number) => {
            const path = `${level}-${node.key}`
            if (node.type === 'object' || node.type === 'array') {
                keys.add(path)
                node.children?.forEach(c => collect(c, level + 1))
            }
        }
        collect(tree, 0)
        setExpandedKeys(keys)
    }, [jsonObj, rootLabel])

    const collapseAll = useCallback(() => {
        setExpandedKeys(new Set([`0-${rootLabel}`]))
    }, [rootLabel])

    const copyVal = useCallback(() => copyValue(value), [value])

    const downloadJsonFile = useCallback(() => {
        const blob = new Blob([value], { type: 'application/json' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url; a.download = `${keyName}.json`; a.click()
        URL.revokeObjectURL(url)
    }, [value, keyName])

    const showDiff = useCallback((oldValue: string, newValue: string): Promise<boolean> => {
        if (!useSettingsStore.getState().showDiffBeforeSave) return Promise.resolve(true)
        if (oldValue === newValue) return Promise.resolve(true)
        setDiffData({ oldValue, newValue })
        setDiffOpen(true)
        return new Promise(resolve => { diffResolveRef.current = resolve })
    }, [])

    const handleEditorClose = useCallback(async (result?: { obj: string } | null) => {
        setEditorOpen(false)
        if (!result?.obj) return
        const oldVal = value
        try {
            const val = typeof result.obj === 'string' ? result.obj : JSON.stringify(result.obj)
            overlay.show()
            await request({ action: 'key-json-set', payload: { key: keyName, path: '$', value: val } })
            trackPage('/key-json-set')
            onRefresh()
            overlay.hide()

            const settings = useSettingsStore.getState()
            if (settings.undoEnabled && oldVal !== undefined && oldVal !== val) {
                const undoClicked = await useCommonStore.getState().toastWithUndo(strings?.status?.set || 'Saved')
                if (undoClicked) {
                    overlay.show({ message: 'Undo...' })
                    await request({ action: 'key-json-set', payload: { key: keyName, path: '$', value: oldVal } })
                    onRefresh()
                    overlay.hide()
                    useCommonStore.getState().toast(strings?.status?.reverted || 'Reverted')
                }
            }
        } catch (e) { if (e) generalHandleError(e); overlay.hide() }
    }, [keyName, strings, value, onRefresh, generalHandleError])

    const Btn = ({ icon, label, color = 'secondary' as const, onClick }: {
        icon: React.ReactNode; label: string; color?: 'primary' | 'secondary'; onClick: () => void
    }) => isGtSm ? (
        <Button variant="contained" color={color} size="small" onClick={onClick} sx={{ gap: '3px' }}>
            {icon}<span>{label}</span>
        </Button>
    ) : (
        <Tooltip title={label} placement="top">
            <Button variant="contained" color={color} onClick={onClick}
                sx={{ minWidth: 40, width: 40, height: 40, p: 0, borderRadius: '4px' }}>
                {icon}
            </Button>
        </Tooltip>
    )

    const tree = jsonObj !== undefined ? jsonToNode(rootLabel, jsonObj) : null

    return (
        <Box>
            <Box className="p3xr-key-type-actions">
                <Btn icon={<ContentCopy fontSize="small" />} label={strings?.intention?.copy} onClick={copyVal} />
                <Btn icon={<Download fontSize="small" />} label={strings?.intention?.downloadJson ?? 'Download JSON'} onClick={downloadJsonFile} />
                <Btn icon={<UnfoldMore fontSize="small" />} label={strings?.page?.treeControls?.expandAll} onClick={expandAll} />
                <Btn icon={<UnfoldLess fontSize="small" />} label={strings?.page?.treeControls?.collapseAll} onClick={collapseAll} />
                <Btn icon={treeWrap ? <WrapText fontSize="small" /> : <Notes fontSize="small" />}
                    label={treeWrap ? (strings?.intention?.unwrap ?? 'Unwrap') : (strings?.intention?.wrap ?? 'Wrap')}
                    onClick={() => setTreeWrap(w => !w)} />
                {!isReadonly && (
                    <Btn icon={<Edit fontSize="small" />} label={strings?.intention?.jsonViewEditor} color="primary" onClick={() => setEditorOpen(true)} />
                )}
            </Box>

            <Box className="p3xr-key-type-content" sx={{ overflow: 'auto' }}>
                {tree ? (
                    <TreeNode node={tree} level={0} expandedKeys={expandedKeys} toggleExpand={toggleExpand} wrap={treeWrap} />
                ) : (
                    <Box className="p3xr-pre">{truncateDisplay(value)}</Box>
                )}
            </Box>

            <JsonEditorDialog open={editorOpen} value={String(value ?? '')} hideFormatSave onClose={handleEditorClose} />

            <DiffDialog open={diffOpen} keyName={keyName}
                oldValue={diffData.oldValue} newValue={diffData.newValue}
                onConfirm={() => { setDiffOpen(false); diffResolveRef.current?.(true) }}
                onCancel={() => { setDiffOpen(false); diffResolveRef.current?.(false) }} />
        </Box>
    )
}
