// src/ng/pages/database/key/key-pager-inline.component.ts
import { Component, Inject, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatTooltipModule } from '@angular/material/tooltip';
import { P3xrInputComponent } from '../../../components/p3xr-input.component';
import { I18nService } from '../../../services/i18n.service';
import { KeyPaging } from './key-paging';

@Component({
    selector: 'p3xr-key-pager-inline',
    standalone: true,
    imports: [CommonModule, FormsModule, MatTooltipModule, P3xrInputComponent],
    template: `
        @if (paging.pages > 1) {
            <div class="p3xr-key-pager-inline">
                <button class="p3xr-key-pager-btn" type="button"
                    (click)="paging.pager('first'); pageChanged.emit()"
                    [matTooltip]="strings?.page?.treeControls?.pager?.first ?? 'First'">
                    <span class="material-icons">skip_previous</span>
                </button>
                <button class="p3xr-key-pager-btn" type="button"
                    (click)="paging.pager('prev'); pageChanged.emit()"
                    [matTooltip]="strings?.page?.treeControls?.pager?.prev ?? 'Previous'">
                    <span class="material-icons">keyboard_arrow_left</span>
                </button>

                <p3xr-ng-input class="p3xr-key-pager-input"
                    type="number"
                    step="1"
                    min="1"
                    [max]="'' + paging.pages"
                    [ngModel]="paging.page"
                    (ngModelChange)="onPageChange($event)">
                </p3xr-ng-input>
                <span class="p3xr-key-pager-text">/ {{ paging.pages }}</span>

                <button class="p3xr-key-pager-btn" type="button"
                    (click)="paging.pager('next'); pageChanged.emit()"
                    [matTooltip]="strings?.page?.treeControls?.pager?.next ?? 'Next'">
                    <span class="material-icons">keyboard_arrow_right</span>
                </button>
                <button class="p3xr-key-pager-btn" type="button"
                    (click)="paging.pager('last'); pageChanged.emit()"
                    [matTooltip]="strings?.page?.treeControls?.pager?.last ?? 'Last'">
                    <span class="material-icons">skip_next</span>
                </button>
            </div>
        }
    `,
    styles: [`
        .p3xr-key-pager-inline {
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 4px 0;
        }

        .p3xr-key-pager-btn {
            background: none;
            border: none;
            color: var(--p3xr-input-border-color, var(--p3xr-border-color));
            cursor: pointer;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            height: 28px;
            width: 28px;
            margin: 0;
            padding: 0;
        }

        .p3xr-key-pager-btn:focus {
            outline: none;
        }

        .p3xr-key-pager-btn .material-icons {
            font-size: 24px;
        }

        :host ::ng-deep p3xr-ng-input.p3xr-key-pager-input {
            vertical-align: middle !important;
            width: 64px;
            margin: 0 4px;
        }

        .p3xr-key-pager-text {
            margin: 0 4px;
            color: var(--p3xr-input-color, inherit);
        }
    `],
})
export class KeyPagerInlineComponent {
    @Input() paging!: KeyPaging;
    @Output() pageChanged = new EventEmitter<void>();

    constructor(@Inject(I18nService) private i18n: I18nService) {}

    get strings() { return this.i18n.strings(); }

    onPageChange(value: any): void {
        this.paging.page = value;
        this.paging.pageChange();
        this.pageChanged.emit();
    }
}

// src/react/pages/database/key/KeyPagerInline.tsx
/**
 * Inline pager for key type renderers — exact port of Angular key-pager-inline.component.
 */
import { Box, Tooltip } from '@mui/material'
import { SkipPrevious, KeyboardArrowLeft, KeyboardArrowRight, SkipNext } from '@mui/icons-material'
import { useTheme } from '@mui/material'
import { useI18nStore } from '../../../stores/i18n.store'
import { Paging, pagerAction, pageChange } from './key-type-base'

interface Props {
    paging: Paging
    onPageChange: (paging: Paging) => void
}

export default function KeyPagerInline({ paging, onPageChange }: Props) {
    const strings = useI18nStore(s => s.strings)
    const muiTheme = useTheme()

    if (paging.pages <= 1) return null

    const btnStyle: React.CSSProperties = {
        background: 'none', border: 'none', cursor: 'pointer',
        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        height: 28, width: 28, margin: 0, padding: 0,
        color: muiTheme.p3xr.inputBorderColor,
    }

    const action = (a: string) => onPageChange(pagerAction(paging, a))

    return (
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', py: '4px' }}>
            <Tooltip title={strings?.page?.treeControls?.pager?.first} placement="top">
                <button style={btnStyle} onClick={() => action('first')}>
                    <SkipPrevious sx={{ fontSize: 24 }} />
                </button>
            </Tooltip>
            <Tooltip title={strings?.page?.treeControls?.pager?.prev} placement="top">
                <button style={btnStyle} onClick={() => action('prev')}>
                    <KeyboardArrowLeft sx={{ fontSize: 24 }} />
                </button>
            </Tooltip>
            <input type="number" step={1} min={1} max={paging.pages}
                value={paging.page}
                onChange={e => {
                    const v = parseInt(e.target.value, 10)
                    if (!isNaN(v)) onPageChange(pageChange(paging, v))
                }}
                className="p3xr-pager-input"
                style={{
                    width: 64, margin: '0 4px', verticalAlign: 'middle',
                    textAlign: 'center', padding: 0,
                    boxSizing: 'border-box', borderStyle: 'solid', borderWidth: 2,
                    borderColor: muiTheme.p3xr.inputBorderColor,
                    background: muiTheme.p3xr.inputBg, color: muiTheme.p3xr.inputColor,
                    outline: 'none', fontFamily: "'Roboto Mono', monospace", fontSize: 12,
                    MozAppearance: 'textfield' as any,
                }}
            />
            <span style={{ margin: '0 4px', color: muiTheme.p3xr.inputColor }}>/ {paging.pages}</span>
            <Tooltip title={strings?.page?.treeControls?.pager?.next} placement="top">
                <button style={btnStyle} onClick={() => action('next')}>
                    <KeyboardArrowRight sx={{ fontSize: 24 }} />
                </button>
            </Tooltip>
            <Tooltip title={strings?.page?.treeControls?.pager?.last} placement="top">
                <button style={btnStyle} onClick={() => action('last')}>
                    <SkipNext sx={{ fontSize: 24 }} />
                </button>
            </Tooltip>
        </Box>
    )
}
