// src/ng/pages/database/key/key-probabilistic.component.ts
import { Component, Inject, OnInit, OnChanges, OnDestroy, SimpleChanges, ChangeDetectorRef, CUSTOM_ELEMENTS_SCHEMA, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatListModule } from '@angular/material/list';
import { MatDividerModule } from '@angular/material/divider';
import { BreakpointObserver } from '@angular/cdk/layout';
import { I18nService } from '../../../services/i18n.service';
import { SocketService } from '../../../services/socket.service';
import { CommonService } from '../../../services/common.service';
import { JsonViewDialogService } from '../../../dialogs/json-view-dialog.service';
import { KeyNewOrSetDialogService } from '../../../dialogs/key-new-or-set-dialog.service';
import { MainCommandService } from '../../../services/main-command.service';
import { RedisStateService } from '../../../services/redis-state.service';
import { SettingsService } from '../../../services/settings.service';
import { KeyTypeBase } from './key-type-base';
import { P3xrAccordionComponent } from '../../../components/p3xr-accordion.component';
import { P3xrButtonComponent } from '../../../components/p3xr-button.component';

@Component({
    selector: 'p3xr-key-probabilistic',
    standalone: true,
    imports: [
        CommonModule, FormsModule,
        MatButtonModule, MatIconModule, MatTooltipModule,
        MatFormFieldModule, MatInputModule,
        MatListModule, MatDividerModule,
        P3xrAccordionComponent, P3xrButtonComponent,
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './key-probabilistic.component.html',
    encapsulation: ViewEncapsulation.None,
})
export class KeyProbabilisticComponent extends KeyTypeBase implements OnInit, OnChanges, OnDestroy {

    infoItems: Array<{ key: string; value: any }> = [];
    topkItems: Array<{ item: string; count: number }> = [];

    itemInput = '';
    incrementInput = 1;
    quantileInput = 0.5;

    autoRefresh = false;
    private autoRefreshInterval: any = null;
    readonly = false;

    constructor(
        @Inject(I18nService) i18n: I18nService,
        @Inject(SocketService) socket: SocketService,
        @Inject(CommonService) common: CommonService,
        @Inject(JsonViewDialogService) jsonViewDialog: JsonViewDialogService,
        @Inject(KeyNewOrSetDialogService) keyNewOrSetDialog: KeyNewOrSetDialogService,
        @Inject(BreakpointObserver) breakpointObserver: BreakpointObserver,
        @Inject(MainCommandService) cmd: MainCommandService,
        @Inject(ChangeDetectorRef) cdr: ChangeDetectorRef,
        @Inject(RedisStateService) redisState: RedisStateService,
        @Inject(SettingsService) settingsService: SettingsService,
    ) {
        super(i18n, socket, common, jsonViewDialog, keyNewOrSetDialog, breakpointObserver, cmd, cdr, redisState, settingsService);
    }

    get strings() {
        return this.i18n.strings;
    }

    get type(): string {
        return this.p3xrResponse?.type || '';
    }

    ngOnInit() {
        this.readonly = this.redisState.connection()?.readonly === true;
        this.parseInfo();
        if (this.type === 'topk') {
            this.loadTopkList();
        }
    }

    ngOnChanges(changes: SimpleChanges) {
        if (changes['p3xrValue']) {
            this.parseInfo();
        }
    }

    ngOnDestroy() {
        this.stopAutoRefresh();
        this.destroyBase();
    }

    toggleAutoRefresh(): void {
        this.autoRefresh = !this.autoRefresh;
        if (this.autoRefresh) {
            this.startAutoRefresh();
        } else {
            this.stopAutoRefresh();
        }
        this.cdr.markForCheck();
    }

    private startAutoRefresh(): void {
        this.stopAutoRefresh();
        this.autoRefreshInterval = setInterval(() => {
            this.refresh();
        }, 10000);
    }

    private stopAutoRefresh(): void {
        if (this.autoRefreshInterval) {
            clearInterval(this.autoRefreshInterval);
            this.autoRefreshInterval = null;
        }
    }

    private parseInfo() {
        this.infoItems = [];
        try {
            const val = this.p3xrValue;
            let info: any;
            if (typeof val === 'object' && val !== null && !ArrayBuffer.isView(val)) {
                info = val;
            } else if (typeof val === 'string') {
                info = JSON.parse(val);
            } else if (ArrayBuffer.isView(val)) {
                info = JSON.parse(new TextDecoder().decode(val as any));
            }
            if (info && typeof info === 'object') {
                this.infoItems = Object.entries(info).map(([key, value]) => ({ key, value }));
            }
        } catch {
            // ignore parse errors
        }
    }

    async addItem() {
        if (!this.itemInput.trim()) return;
        try {
            await this.socket.request({
                action: 'probabilistic/add',
                payload: {
                    key: this.p3xrKey,
                    type: this.type,
                    item: this.itemInput.trim(),
                    increment: this.incrementInput,
                },
            });
            this.common.toast(this.strings()?.page?.key?.probabilistic?.addedSuccessfully || 'Item added successfully');
            this.itemInput = '';
            this.refresh();
        } catch (e: any) {
            this.common.toast(e.message || 'Error');
        }
        this.cdr.markForCheck();
    }

    async checkItem() {
        if (!this.itemInput.trim()) return;
        try {
            const response = await this.socket.request({
                action: 'probabilistic/check',
                payload: {
                    key: this.p3xrKey,
                    type: this.type,
                    item: this.itemInput.trim(),
                },
            });
            const strings = this.strings();
            const exists = (response as any).result === 1;
            this.common.toast(`"${this.itemInput}" — ${exists
                ? (strings?.page?.key?.probabilistic?.exists || 'Exists')
                : (strings?.page?.key?.probabilistic?.doesNotExist || 'Does not exist')}`);
        } catch (e: any) {
            this.common.toast(e.message || 'Error');
        }
        this.cdr.markForCheck();
    }

    async deleteItem() {
        if (!this.itemInput.trim()) return;
        try {
            await this.common.confirm({
                message: this.strings()?.confirm?.delete || 'Delete?',
            });
            await this.socket.request({
                action: 'probabilistic/delete',
                payload: {
                    key: this.p3xrKey,
                    type: this.type,
                    item: this.itemInput.trim(),
                },
            });
            this.common.toast(this.strings()?.page?.key?.probabilistic?.deletedSuccessfully || 'Item deleted successfully');
            this.itemInput = '';
            this.refresh();
        } catch (e: any) {
            if (e?.message) this.common.toast(e.message);
        }
        this.cdr.markForCheck();
    }

    async queryItem() {
        if (!this.itemInput.trim()) return;
        try {
            const response = await this.socket.request({
                action: 'probabilistic/check',
                payload: {
                    key: this.p3xrKey,
                    type: this.type,
                    item: this.itemInput.trim(),
                },
            });
            const count = Array.isArray((response as any).result) ? (response as any).result[0] : (response as any).result;
            this.common.toast(`"${this.itemInput}" — ${this.strings()?.page?.key?.probabilistic?.topkCount || 'Count'}: ${count}`);
        } catch (e: any) {
            this.common.toast(e.message || 'Error');
        }
        this.cdr.markForCheck();
    }

    async queryQuantile() {
        try {
            const response = await this.socket.request({
                action: 'probabilistic/check',
                payload: {
                    key: this.p3xrKey,
                    type: this.type,
                    quantile: this.quantileInput,
                },
            });
            const strings = this.strings();
            const result = Array.isArray((response as any).result) ? (response as any).result[0] : (response as any).result;
            this.common.toast(`${strings?.page?.key?.probabilistic?.quantile || 'Quantile'} ${this.quantileInput} = ${result}`);
        } catch (e: any) {
            this.common.toast(e.message || 'Error');
        }
        this.cdr.markForCheck();
    }

    async resetTdigest() {
        try {
            await this.common.confirm({
                message: this.strings()?.page?.key?.probabilistic?.resetConfirm || 'Reset all data in this T-Digest?',
            });
            await this.socket.request({
                action: 'probabilistic/delete',
                payload: {
                    key: this.p3xrKey,
                    type: 'tdigest',
                },
            });
            this.common.toast('Reset');
            this.refresh();
        } catch (e: any) {
            if (e?.message) this.common.toast(e.message);
        }
        this.cdr.markForCheck();
    }

    async loadTopkList() {
        try {
            const response = await this.socket.request({
                action: 'probabilistic/check',
                payload: {
                    key: this.p3xrKey,
                    type: 'topk',
                },
            });
            this.topkItems = (response as any).result || [];
        } catch {
            this.topkItems = [];
        }
        this.cdr.markForCheck();
    }

    refresh() {
        this.cmd.refreshKey$.next();
        if (this.type === 'topk') {
            this.loadTopkList();
        }
    }
}

<div class="p3xr-key-type-content">

    <!-- INFO -->
    <br />
    <p3xr-ng-accordion [title]="strings()?.page?.key?.probabilistic?.info || 'Info'" accordionKey="prob-info">
        <div actions>
            <p3xr-ng-button
                (click)="toggleAutoRefresh(); $event.stopPropagation()"
                [label]="strings()?.label?.autoRefresh || 'Auto'"
                [mdIcon]="autoRefresh ? 'check_box' : 'check_box_outline_blank'"
                [breakpoint]="1280">
            </p3xr-ng-button>
            @if (!autoRefresh) {
                <p3xr-ng-button
                    (click)="refresh(); $event.stopPropagation()"
                    [label]="strings()?.intention?.refresh || 'Refresh'"
                    mdIcon="refresh"
                    [breakpoint]="1280">
                </p3xr-ng-button>
            }
        </div>
        <div content>
            <mat-list>
                @for (item of infoItems; track item.key; let last = $last) {
                    <mat-list-item>
                        <div style="display: flex; width: 100%;">
                            <span class="p3xr-settings-label" style="flex: 1;">{{ item.key }}</span>
                            <span class="p3xr-settings-value">{{ item.value }}</span>
                        </div>
                    </mat-list-item>
                    @if (!last) { <mat-divider></mat-divider> }
                }
            </mat-list>
        </div>
    </p3xr-ng-accordion>

    <!-- ACTIONS -->
    <br />
    <p3xr-ng-accordion [title]="(p3xrResponse.type === 'topk' ? (strings()?.page?.key?.probabilistic?.topkList || 'Top Items') : (strings()?.page?.key?.probabilistic?.addItem || 'Actions'))" accordionKey="prob-actions">
        <div content>
            <div style="padding: 16px;">
            <div class="p3xr-timeseries-controls">
                @if (p3xrResponse.type === 'tdigest') {
                    <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic">
                        <mat-label>{{ strings()?.form?.key?.field?.value || 'Value' }}</mat-label>
                        <input matInput type="number" [(ngModel)]="itemInput" (keydown.enter)="addItem()" />
                    </mat-form-field>
                } @else {
                    <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic" style="flex: 1; min-width: 200px;">
                        <mat-label>{{ strings()?.page?.key?.probabilistic?.item || 'Item' }}</mat-label>
                        <input matInput [(ngModel)]="itemInput" (keydown.enter)="addItem()" />
                    </mat-form-field>
                }

                @if (p3xrResponse.type === 'cms') {
                    <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic" style="max-width: 120px;">
                        <mat-label>{{ strings()?.form?.key?.field?.increment || 'Increment' }}</mat-label>
                        <input matInput type="number" [(ngModel)]="incrementInput" />
                    </mat-form-field>
                }

                @if (p3xrResponse.type === 'tdigest') {
                    <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic" style="max-width: 120px;">
                        <mat-label>{{ strings()?.page?.key?.probabilistic?.quantile || 'Quantile' }}</mat-label>
                        <input matInput type="number" step="0.1" [(ngModel)]="quantileInput" (keydown.enter)="queryQuantile()" />
                    </mat-form-field>
                }

                @if (!readonly) {
                    @if (isGtSm) {
                        <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="addItem()">
                            <mat-icon svgIcon="add"></mat-icon>
                            <span>{{ strings()?.intention?.add || 'Add' }}</span>
                        </button>
                    } @else {
                        <button mat-mini-fab class="btn-primary" type="button" (click)="addItem()"
                                [matTooltip]="strings()?.intention?.add ?? 'Add'" matTooltipPosition="above">
                            <mat-icon svgIcon="add"></mat-icon>
                        </button>
                    }
                }

                @if (p3xrResponse.type === 'bloom' || p3xrResponse.type === 'cuckoo') {
                    @if (isGtSm) {
                        <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="checkItem()">
                            <mat-icon svgIcon="search"></mat-icon>
                            <span>{{ strings()?.page?.key?.probabilistic?.checkItem || 'Check' }}</span>
                        </button>
                    } @else {
                        <button mat-mini-fab class="btn-primary" type="button" (click)="checkItem()"
                                [matTooltip]="strings()?.page?.key?.probabilistic?.checkItem ?? 'Check'" matTooltipPosition="above">
                            <mat-icon svgIcon="search"></mat-icon>
                        </button>
                    }
                }

                @if (p3xrResponse.type === 'cuckoo' && !readonly) {
                    @if (isGtSm) {
                        <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="deleteItem()">
                            <mat-icon svgIcon="delete"></mat-icon>
                            <span>{{ strings()?.intention?.delete || 'Delete' }}</span>
                        </button>
                    } @else {
                        <button mat-mini-fab class="btn-primary" type="button" (click)="deleteItem()"
                                [matTooltip]="strings()?.intention?.delete ?? 'Delete'" matTooltipPosition="above">
                            <mat-icon svgIcon="delete"></mat-icon>
                        </button>
                    }
                }

                @if (p3xrResponse.type === 'cms') {
                    @if (isGtSm) {
                        <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="queryItem()">
                            <mat-icon svgIcon="search"></mat-icon>
                            <span>{{ strings()?.page?.key?.probabilistic?.queryCount || 'Query' }}</span>
                        </button>
                    } @else {
                        <button mat-mini-fab class="btn-primary" type="button" (click)="queryItem()"
                                [matTooltip]="strings()?.page?.key?.probabilistic?.queryCount ?? 'Query'" matTooltipPosition="above">
                            <mat-icon svgIcon="search"></mat-icon>
                        </button>
                    }
                }

                @if (p3xrResponse.type === 'tdigest') {
                    @if (isGtSm) {
                        <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="queryQuantile()">
                            <mat-icon svgIcon="bar_chart"></mat-icon>
                            <span>{{ strings()?.page?.key?.probabilistic?.quantile || 'Quantile' }}</span>
                        </button>
                    } @else {
                        <button mat-mini-fab class="btn-primary" type="button" (click)="queryQuantile()"
                                [matTooltip]="strings()?.page?.key?.probabilistic?.quantile ?? 'Quantile'" matTooltipPosition="above">
                            <mat-icon svgIcon="bar_chart"></mat-icon>
                        </button>
                    }
                }

                @if (p3xrResponse.type === 'tdigest' && !readonly) {
                    @if (isGtSm) {
                        <button mat-raised-button class="btn-warn p3xr-action-btn" type="button" (click)="resetTdigest()">
                            <mat-icon svgIcon="undo"></mat-icon>
                            <span>Reset</span>
                        </button>
                    } @else {
                        <button mat-mini-fab class="btn-warn" type="button" (click)="resetTdigest()"
                                matTooltip="Reset" matTooltipPosition="above">
                            <mat-icon svgIcon="undo"></mat-icon>
                        </button>
                    }
                }
            </div>

            </div>
            <!-- TOPK ITEMS LIST -->
            @if (p3xrResponse.type === 'topk' && topkItems.length > 0) {
                <mat-divider></mat-divider>
                <mat-list>
                    @for (entry of topkItems; track entry.item; let last = $last) {
                        <mat-list-item>
                            <div style="display: flex; width: 100%;">
                                <span class="p3xr-settings-label" style="flex: 1;">{{ entry.item }}</span>
                                <span class="p3xr-settings-value">{{ entry.count }}</span>
                            </div>
                        </mat-list-item>
                        @if (!last) { <mat-divider></mat-divider> }
                    }
                </mat-list>
            }
        </div>
    </p3xr-ng-accordion>

</div>

// src/react/pages/database/key/KeyProbabilistic.tsx
import { useState, useEffect, useRef } from 'react'
import { Box, TextField, List, ListItem, Divider } from '@mui/material'
import { Add, Search, Delete, Refresh, BarChart, Undo, CheckBox, CheckBoxOutlineBlank } from '@mui/icons-material'
import { useI18nStore } from '../../../stores/i18n.store'
import { useRedisStateStore } from '../../../stores/redis-state.store'
import { useCommonStore } from '../../../stores/common.store'
import { request } from '../../../stores/socket.service'
import { KeyTypeProps } from './key-type-base'
import P3xrAccordion from '../../../components/P3xrAccordion'
import P3xrButton from '../../../components/P3xrButton'

export default function KeyProbabilistic({ response, value, keyName, onRefresh }: KeyTypeProps) {
    const strings = useI18nStore(s => s.strings)
    const connection = useRedisStateStore(s => s.connection)
    const { toast, confirm } = useCommonStore()
    const readonly = connection?.readonly === true

    const type = response?.type || ''

    const [itemInput, setItemInput] = useState('')
    const [incrementInput, setIncrementInput] = useState(1)
    const [quantileInput, setQuantileInput] = useState(0.5)
    const [topkItems, setTopkItems] = useState<Array<{ item: string; count: number }>>([])
    const [autoRefresh, setAutoRefresh] = useState(false)
    const autoRefreshRef = useRef<any>(null)

    useEffect(() => {
        if (autoRefresh) {
            autoRefreshRef.current = setInterval(() => { onRefresh(); if (type === 'topk') loadTopkList() }, 10000)
        } else {
            clearInterval(autoRefreshRef.current)
        }
        return () => clearInterval(autoRefreshRef.current)
    }, [autoRefresh])

    // Parse info directly from value — no effect needed, computed on render
    const infoItems = (() => {
        try {
            let info: any
            if (typeof value === 'object' && value !== null && !ArrayBuffer.isView(value)) {
                info = value
            } else if (typeof value === 'string') {
                info = JSON.parse(value)
            } else if (ArrayBuffer.isView(value)) {
                info = JSON.parse(new TextDecoder().decode(value))
            }
            if (info && typeof info === 'object') {
                return Object.entries(info).map(([key, value]) => ({ key, value }))
            }
        } catch {}
        return []
    })()

    useEffect(() => {
        if (type === 'topk') loadTopkList()
    }, [type])

    async function addItem() {
        if (!itemInput.trim()) return
        try {
            await request({
                action: 'probabilistic/add',
                payload: { key: keyName, type, item: itemInput.trim(), increment: incrementInput },
            })
            toast(strings?.page?.key?.probabilistic?.addedSuccessfully || 'Item added successfully')
            setItemInput('')
            onRefresh()
            if (type === 'topk') loadTopkList()
        } catch (e: any) {
            toast(e.message || 'Error')
        }
    }

    async function checkItem() {
        if (!itemInput.trim()) return
        try {
            const resp: any = await request({
                action: 'probabilistic/check',
                payload: { key: keyName, type, item: itemInput.trim() },
            })
            const exists = resp.result === 1
            toast(`"${itemInput}" — ${exists
                ? (strings?.page?.key?.probabilistic?.exists || 'Exists')
                : (strings?.page?.key?.probabilistic?.doesNotExist || 'Does not exist')}`)
        } catch (e: any) {
            toast(e.message || 'Error')
        }
    }

    async function deleteItem() {
        if (!itemInput.trim()) return
        try {
            await confirm({ message: strings?.confirm?.delete || 'Delete?' })
            await request({
                action: 'probabilistic/delete',
                payload: { key: keyName, type, item: itemInput.trim() },
            })
            toast(strings?.page?.key?.probabilistic?.deletedSuccessfully || 'Item deleted successfully')
            setItemInput('')
            onRefresh()
        } catch (e: any) {
            if (e?.message) toast(e.message)
        }
    }

    async function queryItem() {
        if (!itemInput.trim()) return
        try {
            const resp: any = await request({
                action: 'probabilistic/check',
                payload: { key: keyName, type, item: itemInput.trim() },
            })
            const count = Array.isArray(resp.result) ? resp.result[0] : resp.result
            toast(`"${itemInput}" — ${strings?.page?.key?.probabilistic?.topkCount || 'Count'}: ${count}`)
        } catch (e: any) {
            toast(e.message || 'Error')
        }
    }

    async function queryQuantile() {
        try {
            const resp: any = await request({
                action: 'probabilistic/check',
                payload: { key: keyName, type, quantile: quantileInput },
            })
            const result = Array.isArray(resp.result) ? resp.result[0] : resp.result
            toast(`${strings?.page?.key?.probabilistic?.quantile || 'Quantile'} ${quantileInput} = ${result}`)
        } catch (e: any) {
            toast(e.message || 'Error')
        }
    }

    async function resetTdigest() {
        try {
            await confirm({ message: strings?.page?.key?.probabilistic?.resetConfirm || 'Reset all data in this T-Digest?' })
            await request({
                action: 'probabilistic/delete',
                payload: { key: keyName, type: 'tdigest' },
            })
            toast('Reset')
            onRefresh()
        } catch (e: any) {
            if (e?.message) toast(e.message)
        }
    }

    async function loadTopkList() {
        try {
            const resp: any = await request({
                action: 'probabilistic/check',
                payload: { key: keyName, type: 'topk' },
            })
            setTopkItems(resp.result || [])
        } catch {
            setTopkItems([])
        }
    }

    return (
        <Box className="p3xr-key-type-content">
            {/* INFO */}
            <br />
            <P3xrAccordion
                title={strings?.page?.key?.probabilistic?.info || 'Info'}
                accordionKey="prob-info"
                actions={<>
                    <P3xrButton
                        icon={autoRefresh ? <CheckBox sx={{ fontSize: 18 }} /> : <CheckBoxOutlineBlank sx={{ fontSize: 18 }} />}
                        label={strings?.label?.autoRefresh || 'Auto'} breakpoint={1280}
                        onClick={(e) => { e.stopPropagation(); setAutoRefresh(v => !v) }} />
                    {!autoRefresh && (
                        <P3xrButton icon={<Refresh sx={{ fontSize: 18 }} />} label={strings?.intention?.refresh || 'Refresh'}
                            breakpoint={1280}
                            onClick={(e) => { e.stopPropagation(); onRefresh(); if (type === 'topk') loadTopkList() }} />
                    )}
                </>}
            >
                <List disablePadding>
                    {infoItems.map((item, i) => (
                        <Box key={item.key}>
                            <ListItem>
                                <Box sx={{ display: 'flex', width: '100%' }}>
                                    <span className="p3xr-settings-label" style={{ flex: 1 }}>{item.key}</span>
                                    <span className="p3xr-settings-value">{String(item.value)}</span>
                                </Box>
                            </ListItem>
                            {i < infoItems.length - 1 && <Divider />}
                        </Box>
                    ))}
                </List>
            </P3xrAccordion>

            {/* ACTIONS */}
            <br />
            <P3xrAccordion
                title={type === 'topk'
                    ? (strings?.page?.key?.probabilistic?.topkList || 'Top Items')
                    : (strings?.page?.key?.probabilistic?.addItem || 'Actions')}
                accordionKey="prob-actions"
            >
                <Box>
                    <Box sx={{ p: 2 }}>
                    <Box sx={{ display: 'flex', flexWrap: 'wrap', alignItems: 'flex-start', gap: 1.5, py: 1 }}>
                        {type === 'tdigest' ? (
                            <TextField size="small" type="number" margin="none"
                                className="p3xr-timeseries-field"
                                label={strings?.form?.key?.field?.value || 'Value'}
                                value={itemInput}
                                onChange={e => setItemInput(e.target.value)}
                                onKeyUp={e => e.key === 'Enter' && addItem()} />
                        ) : (
                            <TextField size="small" margin="none"
                                className="p3xr-timeseries-field"
                                sx={{ flex: 1, minWidth: 200 }}
                                label={strings?.page?.key?.probabilistic?.item || 'Item'}
                                value={itemInput}
                                onChange={e => setItemInput(e.target.value)}
                                onKeyUp={e => e.key === 'Enter' && addItem()} />
                        )}

                        {type === 'cms' && (
                            <TextField size="small" type="number" margin="none"
                                className="p3xr-timeseries-field"
                                sx={{ maxWidth: 120 }}
                                label={strings?.form?.key?.field?.increment || 'Increment'}
                                value={incrementInput}
                                onChange={e => setIncrementInput(parseInt(e.target.value) || 1)} />
                        )}

                        {type === 'tdigest' && (
                            <TextField size="small" type="number" margin="none"
                                slotProps={{ htmlInput: { step: 0.1 } }}
                                className="p3xr-timeseries-field"
                                sx={{ maxWidth: 120 }}
                                label={strings?.page?.key?.probabilistic?.quantile || 'Quantile'}
                                value={quantileInput}
                                onChange={e => setQuantileInput(parseFloat(e.target.value) || 0.5)}
                                onKeyUp={e => e.key === 'Enter' && queryQuantile()} />
                        )}

                        {!readonly && (
                            <P3xrButton icon={<Add fontSize="small" />} label={strings?.intention?.add || 'Add'}
                                raised color="primary" onClick={addItem} />
                        )}

                        {(type === 'bloom' || type === 'cuckoo') && (
                            <P3xrButton icon={<Search fontSize="small" />} label={strings?.page?.key?.probabilistic?.checkItem || 'Check'}
                                raised color="primary" onClick={checkItem} />
                        )}

                        {type === 'cuckoo' && !readonly && (
                            <P3xrButton icon={<Delete fontSize="small" />} label={strings?.intention?.delete || 'Delete'}
                                raised color="primary" onClick={deleteItem} />
                        )}

                        {type === 'cms' && (
                            <P3xrButton icon={<Search fontSize="small" />} label={strings?.page?.key?.probabilistic?.queryCount || 'Query'}
                                raised color="primary" onClick={queryItem} />
                        )}

                        {type === 'tdigest' && (
                            <P3xrButton icon={<BarChart fontSize="small" />} label={strings?.page?.key?.probabilistic?.quantile || 'Quantile'}
                                raised color="primary" onClick={queryQuantile} />
                        )}

                        {type === 'tdigest' && !readonly && (
                            <P3xrButton icon={<Undo fontSize="small" />} label="Reset"
                                raised color="warning" onClick={resetTdigest} />
                        )}
                    </Box>

                    </Box>
                    {/* TOPK ITEMS LIST */}
                    {type === 'topk' && topkItems.length > 0 && (
                        <>
                        <Divider />
                        <List disablePadding>
                            {topkItems.map((entry, i) => (
                                <Box key={i}>
                                    <ListItem>
                                        <Box sx={{ display: 'flex', width: '100%' }}>
                                            <span className="p3xr-settings-label" style={{ flex: 1 }}>{entry.item}</span>
                                            <span className="p3xr-settings-value">{entry.count}</span>
                                        </Box>
                                    </ListItem>
                                    {i < topkItems.length - 1 && <Divider />}
                                </Box>
                            ))}
                        </List>
                        </>
                    )}
                </Box>
            </P3xrAccordion>
        </Box>
    )
}
