// src/react/components/P3xrDialog.tsx
import { ReactNode } from 'react'
import {
    Dialog, DialogContent, DialogActions, AppBar, Toolbar,
    IconButton, Box, useMediaQuery,
} from '@mui/material'
import { Close } from '@mui/icons-material'
import { useTheme } from '@mui/material'
import { useThemeStore } from '../stores/theme.store'

/**
 * Shared dialog helper — matches Angular p3xr-dialog-toolbar / p3xr-dialog-content / p3xr-dialog-actions exactly.
 *
 * Header: strongBg, 48px, padding 0 8px
 * Content: contentBg (background.paper), padding 16px, scrollable
 * Footer: accordionBg, padding 8px, gap 8px, right-aligned (Matrix: #0a2e0d)
 */
interface P3xrDialogProps {
    open: boolean
    onClose: () => void
    title: ReactNode
    children: ReactNode
    actions?: ReactNode
    headerActions?: ReactNode
    fullScreenOnMobile?: boolean
    width?: string
    maxWidth?: string | false
    scroll?: 'paper' | 'body'
    contentPadding?: boolean
    height?: string
}

export default function P3xrDialog({
    open, onClose, title, children, actions, headerActions, contentPadding = true, height,
    fullScreenOnMobile = true,
    width = '75vw',
    maxWidth,
    scroll = 'paper',
}: P3xrDialogProps) {
    const muiTheme = useTheme()
    const themeKey = useThemeStore(s => s.themeKey)
    const isSmall = useMediaQuery('(max-width: 599px)')
    const fullScreen = fullScreenOnMobile && isSmall

    // Matrix theme: dialog footer uses dark green instead of bright green accordionBg
    const footerBg = themeKey === 'matrix' ? '#0a2e0d' : muiTheme.p3xr.accordionBg

    return (
        <Dialog
            open={open}
            onClose={onClose}
            scroll={scroll}
            fullScreen={fullScreen}
            maxWidth={maxWidth ?? false}
            slotProps={{ paper: { sx: {
                ...(!fullScreen && { width, maxWidth: width }),
                ...(height && !fullScreen && { height }),
                maxHeight: 'calc(100vh - 64px)',
                display: 'flex',
                flexDirection: 'column',
                overflow: 'hidden',
            }}}}
        >
            {/* Header — strongBg, 48px, matches .p3xr-dialog-toolbar */}
            <AppBar position="static" sx={{
                backgroundColor: `${muiTheme.p3xr.strongBg} !important`,
                backgroundImage: 'none !important',
                color: 'rgba(255,255,255,0.87) !important',
                flexShrink: 0,
                boxShadow: 'none',
            }}>
                <Toolbar variant="dense" disableGutters sx={{
                    minHeight: '48px !important', height: 48, maxHeight: 48,
                    px: 1,
                }}>
                    <Box sx={{
                        flex: '1 1 auto', height: '100%',
                        display: 'flex', alignItems: 'center',
                        lineHeight: '28px', fontSize: 16, fontWeight: 500,
                        pl: 1,
                        overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                    }}>
                        {title}
                    </Box>
                    {headerActions}
                    <IconButton color="inherit" onClick={onClose} size="small" sx={{ m: 0 }}>
                        <Close />
                    </IconButton>
                </Toolbar>
            </AppBar>

            {/* Content — contentBg, padding 16px, matches .p3xr-dialog-content */}
            <DialogContent sx={{
                flex: '1 1 auto',
                minHeight: 0,
                overflow: 'auto',
                p: contentPadding ? 2 : 0,
                bgcolor: muiTheme.palette.background.paper,
                backgroundImage: 'none',
                color: muiTheme.palette.text.primary,
            }}>
                {children}
            </DialogContent>

            {/* Footer — accordionBg, matches .p3xr-dialog-actions */}
            {actions && (
                <DialogActions sx={{
                    flexShrink: 0,
                    bgcolor: footerBg,
                    gap: 1,
                    px: 1,
                    py: 1,
                    justifyContent: 'flex-end',
                    '& .MuiButton-root': {
                        m: 0, minWidth: 0, whiteSpace: 'nowrap',
                        pl: '10px', pr: '8px',
                        letterSpacing: '0.01em',
                    },
                }}>
                    {actions}
                </DialogActions>
            )}
        </Dialog>
    )
}

// src/vue/components/P3xrDialog.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useDisplay } from 'vuetify'
import { storeToRefs } from 'pinia'
import { useThemeStore } from '../stores/theme'

const props = withDefaults(defineProps<{
    open: boolean
    title: string
    icon?: string
    fullScreenOnMobile?: boolean
    width?: string
    contentPadding?: boolean
    height?: string
}>(), {
    fullScreenOnMobile: true,
    width: '75vw',
    contentPadding: true,
})

const emit = defineEmits<{ close: [] }>()

const { width: displayWidth } = useDisplay()
const { themeKey } = storeToRefs(useThemeStore())
const isSmall = computed(() => displayWidth.value < 600)
const fullScreen = computed(() => props.fullScreenOnMobile && isSmall.value)

// Exact toolbar colors per theme (strongBg from React themes)
const STRONG_BG: Record<string, string> = {
    enterprise: '#212121', light: '#263238', redis: '#b71c1c',
    dark: '#212121', darkNeu: '#263238', darkoBluo: '#1a237e',
    matrix: '#33691e',
}
const ACCORDION_BG: Record<string, string> = {
    enterprise: '#9e9e9e', light: '#b0bec5', redis: '#ef9a9a',
    dark: '#9e9e9e', darkNeu: '#90a4ae', darkoBluo: '#3f51b5',
    matrix: '#76ff03',
}

const headerBg = computed(() => STRONG_BG[themeKey.value])
// Matrix dialog footer uses dark green, not bright green
const footerBg = computed(() => themeKey.value === 'matrix' ? '#0a2e0d' : (ACCORDION_BG[themeKey.value]))
</script>

<template>
    <v-dialog
        :model-value="open"
        @update:model-value="(v: boolean) => { if (!v) emit('close') }"
        :fullscreen="fullScreen"
        :max-width="fullScreen ? undefined : width"
        :width="fullScreen ? undefined : width"
        scrollable
    >
        <v-card :style="{ maxHeight: fullScreen ? undefined : 'calc(100vh - 64px)', display: 'flex', flexDirection: 'column', overflow: 'hidden', ...(height && !fullScreen ? { height } : {}) }">
            <!-- Header — strongBg, 48px -->
            <v-toolbar
                density="compact"
                :style="{ backgroundColor: headerBg, color: 'rgba(255,255,255,0.87)', flexShrink: 0, boxShadow: 'none', height: '48px', minHeight: '48px', maxHeight: '48px' }"
            >
                <div style="flex: 1; display: flex; align-items: center; height: 100%; padding-left: 12px; font-size: 16px; font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                    <v-icon v-if="icon" size="20" style="margin-right: 8px;">{{ icon }}</v-icon>
                    {{ title }}
                </div>
                <slot name="headerActions" />
                <v-btn icon variant="text" color="inherit" size="small" @click="emit('close')" style="margin: 0;">
                    <v-icon>mdi-close</v-icon>
                </v-btn>
            </v-toolbar>

            <!-- Content — scrollable -->
            <v-card-text :style="{ flex: '1 1 auto', minHeight: 0, overflow: 'auto', padding: contentPadding ? '16px' : '0' }">
                <slot />
            </v-card-text>

            <!-- Footer — accordionBg -->
            <v-card-actions v-if="$slots.actions" :style="{ flexShrink: 0, backgroundColor: footerBg, gap: '8px', padding: '8px', justifyContent: 'flex-end' }">
                <slot name="actions" />
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>
