// src/vue/pages/database/DatabasePage.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, useTemplateRef } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useDisplay } from 'vuetify'
import { storeToRefs } from 'pinia'
import { useI18nStore } from '../../stores/i18n'
import { useRedisStateStore } from '../../stores/redis-state'
import { useThemeStore } from '../../stores/theme'
import { useMainCommandStore, onCommandEvent } from '../../stores/main-command'
import { navigateTo } from '../../stores/navigation.store'
import KeyNewOrSetDialog from '../../dialogs/KeyNewOrSetDialog.vue'
import type { KeyNewOrSetData } from '../../dialogs/KeyNewOrSetDialog.vue'
import DatabaseHeader from './DatabaseHeader.vue'
import DatabaseTreeControls from './DatabaseTreeControls.vue'
import DatabaseTree from './DatabaseTree.vue'

const RESIZE_MIN_WIDTH = 315
const PANEL_WIDTH_KEY = 'p3xr-database-panel-width'

const router = useRouter()
const route = useRoute()
const i18n = useI18nStore()
const state = useRedisStateStore()
const { themeKey } = storeToRefs(useThemeStore())
const { width: displayWidth } = useDisplay()

const strings = computed(() => i18n.strings)
const isXs = computed(() => displayWidth.value < 600)
const cmd = useMainCommandStore()
const hasConnection = computed(() => !!state.connection)

// --- Key New/Edit dialog ---
const keyDialogOpen = ref(false)
const keyDialogData = ref<KeyNewOrSetData | null>(null)
const keyDialogUnsubs: Array<() => void> = []

function openKeyDialog(options: any) {
    keyDialogData.value = {
        type: options.type,
        node: options.node,
        model: options.model,
    }
    keyDialogOpen.value = true
}

async function handleKeyDialogClose(result?: any) {
    keyDialogOpen.value = false
    keyDialogData.value = null
    if (result) {
        state.redisChanged = true
        await cmd.refresh({ force: true })
    }
}

// Panel resize state
function getInitialWidth(): number {
    const saved = localStorage.getItem(PANEL_WIDTH_KEY)
    if (saved) {
        const w = parseInt(saved, 10)
        if (!isNaN(w) && w >= RESIZE_MIN_WIDTH) return w
    }
    return RESIZE_MIN_WIDTH
}
const leftWidth = ref(getInitialWidth())
const isDragging = ref(false)
const isHovering = ref(false)
const containerEl = ref<HTMLDivElement>()

// Accordion colors for header/resizer (same as P3xrAccordion)
const ACCORDION_BG: Record<string, string> = {
    enterprise: '#9e9e9e', light: '#b0bec5', redis: '#ef9a9a',
    dark: '#9e9e9e', darkNeu: '#90a4ae', darkoBluo: '#3f51b5',
    matrix: '#76ff03',
}
const resizerBg = computed(() => ACCORDION_BG[themeKey.value])

const isDark = computed(() => document.body.classList.contains('p3xr-theme-dark'))
const resizerFilter = computed(() => {
    if (isDragging.value) return isDark.value ? 'brightness(1.6)' : 'brightness(0.7)'
    if (isHovering.value) return isDark.value ? 'brightness(1.3)' : 'brightness(0.85)'
    return 'none'
})

// Redirect to statistics on bare /database + listen for key-new event
onMounted(() => {
    state.currentPage = 'database'
    if (state.connection) {
        const path = route.path
        if (path === '/database' || path === '/database/') {
            navigateTo('database.statistics')
        }
    }
    keyDialogUnsubs.push(onCommandEvent('key-new', (options: any) => openKeyDialog(options)))
})

// --- Drag resize ---
// Cursor is forced via a dynamically-injected <style> element. Static CSS
// rules can't reliably beat inline `style="cursor:pointer"` on tree list
// items once Vuetify/CSS layers are in play, but a late-appended <style>
// with `*, *::before, *::after { cursor: X !important }` always wins.
let dragStyleEl: HTMLStyleElement | null = null

function applyDragCursor(cursor: 'ew-resize' | 'not-allowed') {
    if (!dragStyleEl) {
        dragStyleEl = document.createElement('style')
        dragStyleEl.setAttribute('data-p3xr-database-drag', '')
        document.head.appendChild(dragStyleEl)
    }
    dragStyleEl.textContent = `*, *::before, *::after { cursor: ${cursor} !important; }`
}

function clearDragCursor() {
    dragStyleEl?.remove()
    dragStyleEl = null
}

function handleMouseDown(e: MouseEvent) {
    e.preventDefault()
    isDragging.value = true
    applyDragCursor('ew-resize')
    document.body.classList.add('p3xr-not-selectable')
}

let lastDragWidth = RESIZE_MIN_WIDTH

function onMouseMove(e: MouseEvent) {
    if (!isDragging.value) return
    const container = containerEl.value
    if (!container) return
    const rect = container.getBoundingClientRect()
    const newWidth = e.clientX - rect.left
    if (newWidth < RESIZE_MIN_WIDTH || newWidth > rect.width - RESIZE_MIN_WIDTH) {
        applyDragCursor('not-allowed')
        return
    }
    applyDragCursor('ew-resize')
    lastDragWidth = newWidth
    leftWidth.value = newWidth
}

function onMouseUp() {
    if (!isDragging.value) return
    isDragging.value = false
    clearDragCursor()
    document.body.classList.remove('p3xr-not-selectable')
    if (lastDragWidth >= RESIZE_MIN_WIDTH) {
        localStorage.setItem(PANEL_WIDTH_KEY, String(lastDragWidth))
    }
}

onMounted(() => {
    document.addEventListener('mousemove', onMouseMove)
    document.addEventListener('mouseup', onMouseUp)
})
onUnmounted(() => {
    document.removeEventListener('mousemove', onMouseMove)
    document.removeEventListener('mouseup', onMouseUp)
    clearDragCursor()
    keyDialogUnsubs.forEach(fn => fn())
})

// Bottom console is now in the global drawer (ConsoleDrawer.vue at the Layout level)
</script>

<template>
    <div class="p3xr-database-root" :style="{ borderColor: resizerBg }">
        <DatabaseHeader />

        <div class="p3xr-database-body">
            <template v-if="hasConnection">
                <!-- Mobile layout -->
                <div v-if="isXs" class="p3xr-database-mobile">
                    <div class="p3xr-database-mobile-tree-controls">
                        <DatabaseTreeControls />
                    </div>
                    <div class="p3xr-database-mobile-tree">
                        <DatabaseTree />
                    </div>
                    <div class="p3xr-database-mobile-content">
                        <router-view />
                    </div>
                </div>

                <!-- Desktop layout -->
                <div v-else ref="containerEl" class="p3xr-database-desktop" :class="{ 'p3xr-not-selectable': isDragging }">
                    <!-- Main content: tree + resizer + outlet -->
                    <div class="p3xr-database-main">
                        <!-- Left: tree controls + tree -->
                        <div class="p3xr-database-left" :style="{ width: leftWidth + 'px', minWidth: RESIZE_MIN_WIDTH + 'px' }">
                            <DatabaseTreeControls />
                            <div class="p3xr-database-tree-area">
                                <DatabaseTree />
                            </div>
                        </div>

                        <!-- Resizer -->
                        <div
                            class="p3xr-database-resizer"
                            :style="{ backgroundColor: resizerBg, filter: resizerFilter }"
                            @mousedown="handleMouseDown"
                            @mouseenter="isHovering = true"
                            @mouseleave="isHovering = false"
                        />

                        <!-- Right: key viewer / statistics -->
                        <div class="p3xr-database-right">
                            <router-view />
                        </div>
                    </div>
                </div>
            </template>
        </div>

        <!-- Key New/Edit Dialog -->
        <KeyNewOrSetDialog :open="keyDialogOpen" :data="keyDialogData" @close="handleKeyDialogClose" />
    </div>
</template>

<style scoped>
.p3xr-database-root {
    display: flex;
    flex-direction: column;
    flex: 1;
    min-height: 0;
    border-radius: 4px;
    border: 1px solid;
    overflow: hidden;
}

.p3xr-database-body {
    flex: 1;
    min-height: 0;
    background-color: rgb(var(--v-theme-surface));
    color: rgb(var(--v-theme-on-surface));
    overflow: hidden;
    display: flex;
    flex-direction: column;
}

/* Desktop layout */
.p3xr-database-desktop {
    display: flex;
    flex-direction: column;
    flex: 1;
    min-height: 0;
}

.p3xr-database-main {
    display: flex;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.p3xr-database-left {
    flex-shrink: 0;
    display: flex;
    flex-direction: column;
    overflow: hidden;
}

.p3xr-database-tree-area {
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.p3xr-database-resizer {
    width: 5px;
    flex-shrink: 0;
    cursor: ew-resize;
    transition: filter 0.15s ease;
    z-index: 8;
}

.p3xr-database-right {
    flex: 1;
    overflow: auto;
}

.p3xr-database-console-panel {
    flex-shrink: 0;
    border-top: 1px solid rgba(var(--v-border-color), 0.16);
    overflow: hidden;
    box-sizing: border-box;
    z-index: 9;
}

/* Mobile layout */
.p3xr-database-mobile {
    display: flex;
    flex-direction: column;
    min-height: 100%;
    overflow-x: hidden;
}

.p3xr-database-mobile-tree-controls {
    flex: 0 0 auto;
}

.p3xr-database-mobile-tree {
    flex: 1 1 auto;
    min-height: 0;
    height: 20vh;
    min-height: 100px;
    overflow: auto;
}

.p3xr-database-mobile-content {
    flex: 1;
}

.p3xr-database-mobile-console {
    height: 33vh;
    min-height: 220px;
    margin-top: auto;
    border-top: 1px solid rgba(var(--v-border-color), 0.16);
    overflow-x: hidden;
}
</style>

<style>
.p3xr-not-selectable {
    user-select: none !important;
}
</style>

// src/react/pages/database/DatabasePage.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { Box, useMediaQuery } from '@mui/material'
import { useTheme } from '@mui/material'
import { Outlet } from 'react-router-dom'
import { useRedisStateStore } from '../../stores/redis-state.store'
import { navigateTo } from '../../stores/navigation.store'
import DatabaseHeader from './DatabaseHeader'
import DatabaseTreeControls from './DatabaseTreeControls'
import DatabaseTree from './DatabaseTree'

const RESIZE_MIN_WIDTH = 315
const PANEL_WIDTH_KEY = 'p3xr-database-panel-width'

export default function DatabasePage() {
    const connection = useRedisStateStore(s => s.connection)
    const setCurrentPage = useRedisStateStore(s => s.setCurrentPage)
    const muiTheme = useTheme()
    const isXs = useMediaQuery('(max-width: 599px)')

    const hasConnection = !!connection

    // Resize state — load saved width from localStorage
    const [leftWidth, setLeftWidth] = useState(() => {
        const saved = localStorage.getItem(PANEL_WIDTH_KEY)
        if (saved) {
            const width = parseInt(saved, 10)
            if (!isNaN(width) && width >= RESIZE_MIN_WIDTH) {
                return width
            }
        }
        return RESIZE_MIN_WIDTH
    })
    const [isDragging, setIsDragging] = useState(false)
    const [isHovering, setIsHovering] = useState(false)
    const containerRef = useRef<HTMLDivElement>(null)
    const dragStyleElRef = useRef<HTMLStyleElement | null>(null)

    // Force cursor during drag via a dynamically-injected <style>. Static
    // CSS rules can't reliably beat inline `style="cursor:pointer"` on tree
    // list items once Material's CSS layers are in play, but a late-appended
    // <style> with `*, *::before, *::after { cursor: X !important }` always wins.
    const applyDragCursor = useCallback((cursor: 'ew-resize' | 'not-allowed') => {
        let el = dragStyleElRef.current
        if (!el) {
            el = document.createElement('style')
            el.setAttribute('data-p3xr-database-drag', '')
            document.head.appendChild(el)
            dragStyleElRef.current = el
        }
        el.textContent = `*, *::before, *::after { cursor: ${cursor} !important; }`
    }, [])

    const clearDragCursor = useCallback(() => {
        dragStyleElRef.current?.remove()
        dragStyleElRef.current = null
    }, [])

    // Set page context — used by the global console drawer + AI prompt payload
    useEffect(() => {
        setCurrentPage('database')
    }, [setCurrentPage])

    // Redirect to statistics on bare /database
    useEffect(() => {
        if (!connection) return
        const path = location.pathname.replace(/^\/react/, '')
        if (path === '/database' || path === '/database/') {
            navigateTo('database.statistics')
        }
    }, [connection])

    // --- Drag resize handler ---
    const handleMouseDown = useCallback((e: React.MouseEvent) => {
        e.preventDefault()
        setIsDragging(true)
        applyDragCursor('ew-resize')
        document.body.classList.add('p3xr-not-selectable')
    }, [applyDragCursor])

    useEffect(() => {
        if (!isDragging) return
        let lastWidth = RESIZE_MIN_WIDTH
        const handleMouseMove = (e: MouseEvent) => {
            const container = containerRef.current
            if (!container) return
            const rect = container.getBoundingClientRect()
            const newWidth = e.clientX - rect.left
            if (newWidth < RESIZE_MIN_WIDTH || newWidth > rect.width - RESIZE_MIN_WIDTH) {
                applyDragCursor('not-allowed')
                return
            }
            applyDragCursor('ew-resize')
            lastWidth = newWidth
            setLeftWidth(newWidth)
        }
        const handleMouseUp = () => {
            setIsDragging(false)
            clearDragCursor()
            document.body.classList.remove('p3xr-not-selectable')
            if (lastWidth >= RESIZE_MIN_WIDTH) {
                localStorage.setItem(PANEL_WIDTH_KEY, String(lastWidth))
            }
        }
        document.addEventListener('mousemove', handleMouseMove)
        document.addEventListener('mouseup', handleMouseUp)
        return () => {
            document.removeEventListener('mousemove', handleMouseMove)
            document.removeEventListener('mouseup', handleMouseUp)
        }
    }, [isDragging, applyDragCursor, clearDragCursor])

    const isDark = muiTheme.palette.mode === 'dark'
    const resizerFilter = isDragging
        ? (isDark ? 'brightness(1.6)' : 'brightness(0.7)')
        : isHovering
            ? (isDark ? 'brightness(1.3)' : 'brightness(0.85)')
            : 'none'

    return (
        <Box sx={{
            borderRadius: '4px',
            border: '1px solid',
            borderColor: (muiTheme as any).p3xr?.accordionBg,
            overflow: 'hidden',
            flex: 1,
            minHeight: 0,
            display: 'flex',
            flexDirection: 'column',
        }}>
            <DatabaseHeader />

            <Box sx={{
                flex: 1, minHeight: 0,
                bgcolor: 'background.paper',
                color: 'text.primary',
                overflow: 'hidden',
                position: 'relative',
                display: 'flex',
                flexDirection: 'column',
            }}>
                {hasConnection && (
                    isXs ? (
                        /* Mobile: tree controls + tree + viewer — console lives globally in layout drawer */
                        <Box sx={{
                            display: 'flex', flexDirection: 'column',
                            minHeight: '100%', overflowX: 'hidden',
                        }}>
                            <Box sx={{ flex: 1 }}>
                                <DatabaseTreeControls />
                            </Box>
                            <Box sx={{
                                flex: '1 1 auto', minHeight: 100,
                                height: '20vh',
                                overflowY: 'auto', overflowX: 'auto',
                            }}>
                                <DatabaseTree />
                            </Box>
                            <Box sx={{ flex: 1 }}>
                                <Outlet />
                            </Box>
                        </Box>
                    ) : (
                        /* Desktop: split pane tree ← → viewer. Global console drawer handles the bottom. */
                        <Box ref={containerRef} sx={{
                            display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0,
                            userSelect: isDragging ? 'none' : undefined,
                        }}>
                            <Box sx={{ display: 'flex', flex: 1, minHeight: 0, overflow: 'hidden' }}>
                                <Box sx={{
                                    width: leftWidth, minWidth: RESIZE_MIN_WIDTH,
                                    flexShrink: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden',
                                }}>
                                    <DatabaseTreeControls />
                                    <Box sx={{ flex: 1, minHeight: 0, overflow: 'hidden' }}>
                                        <DatabaseTree />
                                    </Box>
                                </Box>

                                <Box
                                    onMouseDown={handleMouseDown}
                                    onMouseEnter={() => setIsHovering(true)}
                                    onMouseLeave={() => setIsHovering(false)}
                                    sx={{
                                        width: 5, flexShrink: 0, cursor: 'ew-resize',
                                        bgcolor: (muiTheme as any).p3xr?.accordionBg,
                                        filter: resizerFilter,
                                        transition: 'filter 0.15s ease',
                                        zIndex: 8,
                                    }}
                                />

                                <Box sx={{ flex: 1, overflow: 'auto' }}>
                                    <Outlet />
                                </Box>
                            </Box>
                        </Box>
                    )
                )}
            </Box>
        </Box>
    )
}
