// src/vue/pages/database/DatabaseKeyPage.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, defineAsyncComponent } from 'vue'
import { useRoute } from 'vue-router'
import { useDisplay } from 'vuetify'
import { storeToRefs } from 'pinia'
import TtlDialog from '../../dialogs/TtlDialog.vue'
import { useI18nStore } from '../../stores/i18n'
import { useRedisStateStore } from '../../stores/redis-state'
import { useSettingsStore } from '../../stores/settings'
import { useCommonStore } from '../../stores/common'
import { useThemeStore } from '../../stores/theme'
import { useMainCommandStore, onCommandEvent } from '../../stores/main-command'
import { request } from '../../stores/socket.service'
import { navigateTo } from '../../stores/navigation.store'
import { decodeValue, str, calculateSize } from './key/key-type-base'
import humanizeDuration from 'humanize-duration'

// Lazy-load key type renderers
const KeyString = defineAsyncComponent(() => import('./key/KeyString.vue'))
const KeyHash = defineAsyncComponent(() => import('./key/KeyHash.vue'))
const KeyList = defineAsyncComponent(() => import('./key/KeyList.vue'))
const KeySet = defineAsyncComponent(() => import('./key/KeySet.vue'))
const KeyZset = defineAsyncComponent(() => import('./key/KeyZset.vue'))
const KeyJson = defineAsyncComponent(() => import('./key/KeyJson.vue'))
const KeyStream = defineAsyncComponent(() => import('./key/KeyStream.vue'))
const KeyTimeseries = defineAsyncComponent(() => import('./key/KeyTimeseries.vue'))
const KeyProbabilistic = defineAsyncComponent(() => import('./key/KeyProbabilistic.vue'))
const KeyVectorset = defineAsyncComponent(() => import('./key/KeyVectorset.vue'))
const KeyArray = defineAsyncComponent(() => import('./key/KeyArray.vue'))

const route = useRoute()
const { width: displayWidth } = useDisplay()
const i18n = useI18nStore()
const state = useRedisStateStore()
const settings = useSettingsStore()
const common = useCommonStore()
const cmd = useMainCommandStore()
const { themeKey } = storeToRefs(useThemeStore())

const strings = computed(() => i18n.strings)
// isGtSm — (min-width: 960px) per guidelines-responsive-buttons.md
const isGtSm = computed(() => displayWidth.value >= 960)
const isReadonly = computed(() => state.connection?.readonly === true)
const isDark = computed(() => ['dark', 'darkNeu', 'darkoBluo', 'matrix'].includes(themeKey.value))

// Key state
const loading = ref(true)
const keyName = ref('')
const response = ref<any>(null)
const keyValue = ref<any>(null)
const keyValueBuffer = ref<any>(null)
const keyType = ref('')
const ttl = ref(-1)
const valueFormat = ref<'raw' | 'json' | 'hex' | 'base64'>('raw')
const keySize = ref(0)
const ttlDialogOpen = ref(false)

let ttlInterval: any = null
let wasExpiring = false
const unsubs: Array<() => void> = []

// --- Key loading ---
async function loadKey(key: string) {
    if (!key) {
        loading.value = false
        return
    }
    loading.value = true
    try {
        const resp = await request({ action: 'key/get', payload: { key } })

        if (resp.ttl === -2) {
            common.toast(str(strings.value?.status?.keyIsNotExisting, { key }))
            navigateTo('database.statistics')
            return
        }

        response.value = resp
        keyType.value = resp.type || ''
        ttl.value = resp.ttl ?? -1

        const decoded = decodeValue(resp.value, resp.valueBuffer, resp.type)
        keyValue.value = decoded.value
        keyValueBuffer.value = decoded.valueBuffer
        keySize.value = calculateSize(resp)

        wasExpiring = ttl.value > -1
        startTtlCountdown()
        injectHighlightStyle(key)
    } catch (e) {
        common.generalHandleError(e)
    } finally {
        loading.value = false
    }
}

// --- TTL countdown (decrements every second, template is reactive) ---
function startTtlCountdown() {
    if (ttlInterval) clearInterval(ttlInterval)
    if (ttl.value <= -1) return
    ttlInterval = setInterval(() => {
        ttl.value--
        if (ttl.value < -1 || (wasExpiring && ttl.value < 1)) {
            clearInterval(ttlInterval)
            ttlInterval = null
            common.toast(str(strings.value?.status?.keyIsNotExisting, { key: keyName.value }))
            state.redisChanged = true
            navigateTo('database.statistics')
        }
    }, 1000)
}

// Humanized TTL — recomputes every second as ttl ref changes
const humanizedTtl = computed(() => {
    if (ttl.value <= -1) return ''
    const hdOpts = settings.getHumanizeDurationOptions()
    return humanizeDuration(ttl.value * 1000, { ...hdOpts, delimiter: ' ' })
})

// --- Tree highlight ---
function injectHighlightStyle(key: string) {
    const id = 'p3xr-theme-styles-tree-key'
    let styleEl = document.getElementById(id) as HTMLStyleElement
    if (!styleEl) {
        styleEl = document.createElement('style')
        styleEl.id = id
        document.head.appendChild(styleEl)
    }
    const escapedKey = key.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
    const bg = isDark.value ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.15)'
    styleEl.textContent = `[data-p3xr-tree-key="${escapedKey}"] .p3xr-database-tree-node-label { background-color: ${bg}; border-radius: 3px; padding: 0 4px; }`
}

function removeHighlightStyle() {
    document.getElementById('p3xr-theme-styles-tree-key')?.remove()
}

// --- Actions ---
async function deleteKey() {
    try {
        await common.confirm({ message: str(strings.value?.confirm?.deleteKey) })
        await request({ action: 'key/delete', payload: { key: keyName.value } })
        common.toast(str(strings.value?.status?.deletedKey, { key: keyName.value }))
        state.redisChanged = true
        navigateTo('database.statistics')
        await cmd.refresh({ force: true })
    } catch (e) {
        if (e !== undefined) common.generalHandleError(e)
    }
}

async function renameKey() {
    try {
        const newKey = await common.prompt({
            title: str(strings.value?.confirm?.rename?.title),
            placeholder: str(strings.value?.confirm?.rename?.placeholder),
            initialValue: keyName.value,
            okLabel: str(strings.value?.intention?.rename),
            cancelLabel: str(strings.value?.intention?.cancel),
        })
        await request({ action: 'key/rename', payload: { key: keyName.value, keyNew: newKey } })
        common.toast(str(strings.value?.status?.renamedKey))
        state.redisChanged = true
        await cmd.refresh({ force: true })
        navigateTo('database.key', { key: newKey })
    } catch (e) {
        if (e !== undefined) common.generalHandleError(e)
    }
}

// TTL — opens TtlDialog (matching React TtlDialog pattern)
function setTtl() {
    ttlDialogOpen.value = true
}

async function handleTtlClose(result?: { model: { ttl: number } }) {
    ttlDialogOpen.value = false
    if (!result) return
    try {
        const ttlVal = result.model.ttl
        const ttlStr = String(ttlVal).trim()
        if (ttlStr === '' || ttlVal == null) {
            // Empty = persist (remove TTL)
            await request({ action: 'key/persist', payload: { key: keyName.value } })
            await cmd.refresh({ force: true })
            await loadKey(keyName.value)
            common.toast(str(strings.value?.status?.persisted))
        } else if (!/^-?\d+$/.test(ttlStr)) {
            common.toast(str(strings.value?.status?.notInteger))
        } else {
            // Set expiry
            await request({ action: 'key/expire', payload: { key: keyName.value, ttl: parseInt(ttlStr) } })
            await cmd.refresh({ force: true })
            await loadKey(keyName.value)
            common.toast(str(strings.value?.status?.ttlChanged))
        }
    } catch (e) {
        common.generalHandleError(e)
    }
}

function addKey(e: Event) { cmd.addKey({ event: e, node: { key: keyName.value } }) }

async function refresh() { await loadKey(keyName.value) }

// --- Action button definitions (data-driven, replaces P3xrButton) ---
const actionButtons = computed(() => {
    const list: { icon: string; label: string; color: string; click: (e?: Event) => void }[] = []
    if (!isReadonly.value) {
        list.push({ icon: 'mdi-plus', label: str(strings.value?.intention?.addKey), color: 'secondary', click: (e) => addKey(e!) })
        list.push({ icon: 'mdi-delete', label: str(strings.value?.intention?.delete), color: 'error', click: () => deleteKey() })
        list.push({ icon: 'mdi-timer', label: str(strings.value?.intention?.ttl), color: 'primary', click: () => setTtl() })
        list.push({ icon: 'mdi-fingerprint', label: str(strings.value?.intention?.rename), color: 'primary', click: () => renameKey() })
    }
    list.push({ icon: 'mdi-refresh', label: str(strings.value?.intention?.reloadKey), color: 'secondary', click: () => refresh() })
    return list
})

// --- Type component map ---
const typeComponentMap: Record<string, any> = {
    string: KeyString, hash: KeyHash, list: KeyList, set: KeySet,
    zset: KeyZset, 'ReJSON-RL': KeyJson, json: KeyJson, stream: KeyStream,
    'TSDB-TYPE': KeyTimeseries, timeseries: KeyTimeseries,
    bloom: KeyProbabilistic, cuckoo: KeyProbabilistic, topk: KeyProbabilistic, cms: KeyProbabilistic, tdigest: KeyProbabilistic,
    vectorset: KeyVectorset, array: KeyArray,
}
const keyComponent = computed(() => typeComponentMap[keyType.value] || null)

const showFormatToggle = computed(() => {
    const t = keyType.value
    return t && !['ReJSON-RL', 'json', 'TSDB-TYPE', 'timeseries'].includes(t) &&
        !t.startsWith('MBbloom') && !t.startsWith('TopK') && !t.startsWith('CMSk') &&
        !t.startsWith('TDigest') && t !== 'vectorset'
})

// --- Lifecycle ---
onMounted(() => {
    const key = decodeURIComponent(route.params.key as string || '')
    keyName.value = key
    loadKey(key)
    unsubs.push(onCommandEvent('refresh-key', () => refresh()))
})

watch(() => route.params.key, (newKey) => {
    if (!newKey) return
    const key = decodeURIComponent(newKey as string)
    keyName.value = key
    loadKey(key)
})

watch(isDark, () => { if (keyName.value) injectHighlightStyle(keyName.value) })

onUnmounted(() => {
    if (ttlInterval) clearInterval(ttlInterval)
    removeHighlightStyle()
    unsubs.forEach(fn => fn())
})
</script>

<template>
    <!-- Loading — centered spinner -->
    <div v-if="loading" class="p3xr-key-loading">
        <v-progress-circular indeterminate :size="40" />
    </div>

    <div v-else-if="response">
        <!-- Action buttons — direct ActionBtn pattern per guidelines-responsive-buttons.md -->
        <div class="p3xr-key-actions">
            <template v-for="btn in actionButtons" :key="btn.icon">
                <!-- Wide (>=960px): contained button with icon + text -->
                <v-btn v-if="isGtSm" variant="flat" :color="btn.color" @click="btn.click($event)">
                    <v-icon size="small">{{ btn.icon }}</v-icon>
                    <span>{{ btn.label }}</span>
                </v-btn>
                <!-- Narrow (<960px): 40x40 square with tooltip (React ActionBtn narrow) -->
                <v-tooltip v-else :text="btn.label" location="top">
                    <template #activator="{ props: tp }">
                        <v-btn v-bind="tp" variant="flat" :color="btn.color" @click="btn.click($event)"
                            style="min-width: 40px; width: 40px; height: 40px; padding: 0; border-radius: 4px;">
                            <v-icon size="small">{{ btn.icon }}</v-icon>
                        </v-btn>
                    </template>
                </v-tooltip>
            </template>
        </div>

        <!-- Key info rows — React: space-between, baseline, px:16 py:12, themed borders -->
        <div class="p3xr-key-info">
            <!-- Key name — always clickable -->
            <div class="p3xr-key-info-row p3xr-key-clickable" @click="renameKey()">
                <strong class="p3xr-key-label">{{ str(strings?.page?.key?.label?.key) }}:</strong>
                <span class="p3xr-key-value p3xr-key-ellipsis" :title="keyName">{{ keyName }}</span>
            </div>

            <!-- TTL — always clickable, seconds countdown + humanized duration -->
            <div class="p3xr-key-info-row p3xr-key-clickable" @click="setTtl()">
                <strong class="p3xr-key-label">{{ str(strings?.page?.key?.label?.ttl) }}:</strong>
                <span v-if="ttl === -1" class="p3xr-key-value">{{ str(strings?.page?.key?.label?.ttlNotExpire) }}</span>
                <div v-else class="p3xr-ttl-column">
                    <span>{{ ttl }}</span>
                    <span class="p3xr-ttl-humanized">{{ humanizedTtl }}</span>
                </div>
            </div>

            <!-- Type -->
            <div class="p3xr-key-info-row">
                <strong class="p3xr-key-label">{{ str(strings?.page?.key?.label?.type) }}:</strong>
                <span class="p3xr-key-value">{{ strings?.redisTypes?.[keyType] || keyType }}</span>
            </div>

            <!-- Encoding -->
            <div class="p3xr-key-info-row">
                <strong class="p3xr-key-label">{{ str(strings?.page?.key?.label?.encoding) }}:</strong>
                <span class="p3xr-key-value">{{ response.encoding }}</span>
            </div>

            <!-- Compression — colored badges -->
            <div v-if="response.compression" class="p3xr-key-info-row">
                <strong class="p3xr-key-label">{{ str(strings?.page?.key?.label?.compression) }}:</strong>
                <span class="p3xr-key-value p3xr-compression-badges">
                    <span class="p3xr-badge p3xr-badge-algo">{{ response.compression.algorithm?.toUpperCase() }}</span>
                    <span class="p3xr-badge" :class="response.compression.ratio >= 0 ? 'p3xr-badge-positive' : 'p3xr-badge-negative'">
                        {{ response.compression.ratio >= 0 ? '' : '-' }}{{ Math.abs(response.compression.ratio) }}%
                    </span>
                </span>
            </div>

            <!-- Length/Size — React format: (prettyBytes) raw bytes, N items -->
            <div class="p3xr-key-info-row">
                <strong class="p3xr-key-label">{{ str(strings?.page?.key?.label?.length) }}:</strong>
                <span class="p3xr-key-value">
                    <span v-if="keySize >= 1024" class="p3xr-size-pretty">({{ settings.prettyBytes(keySize) }})&nbsp;</span>{{ keySize }}&nbsp;{{ str(strings?.page?.key?.label?.lengthString) }}<span v-if="response.length">, {{ response.length }} {{ str(strings?.page?.key?.label?.lengthItem) }}</span>
                </span>
            </div>

            <!-- Format toggle — React ToggleButtonGroup style -->
            <div v-if="showFormatToggle" class="p3xr-key-info-row p3xr-format-row">
                <strong class="p3xr-key-label p3xr-format-label">{{ str(strings?.label?.format) }}:</strong>
                <v-btn-toggle v-model="valueFormat" mandatory class="p3xr-format-toggle" density="compact">
                    <v-btn value="raw">Raw</v-btn>
                    <v-btn value="json">JSON</v-btn>
                    <v-btn value="hex">Hex</v-btn>
                    <v-btn value="base64">Base64</v-btn>
                </v-btn-toggle>
            </div>
        </div>

        <!-- Type-specific renderer -->
        <component v-if="keyComponent" :is="keyComponent"
            :response="response" :value="keyValue" :value-buffer="keyValueBuffer"
            :key-name="keyName" :value-format="valueFormat" @refresh="refresh()" />
        <div v-else class="p3xr-key-unsupported">
            {{ strings?.page?.key?.probabilistic?.noItems }}
        </div>

        <!-- TTL Dialog (matching React TtlDialog) -->
        <TtlDialog :open="ttlDialogOpen" :ttl="ttl === -1 ? '' : ttl" @close="handleTtlClose" />
    </div>
</template>

<style scoped>
/* Loading — centered spinner */
.p3xr-key-loading {
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100%;
    padding: 32px;
}

/* Action buttons — right-aligned row (React: flex-end, gap:8, px:8, py:4) */
.p3xr-key-actions {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-end;
    align-items: center;
    gap: 8px;
    padding: 4px 8px;
}

/* Info container — top border separates from action buttons */
.p3xr-key-info {
    border-top: 1px solid rgba(var(--v-theme-on-surface), 0.12);
}

/* Info rows — React: px:16 py:12 space-between baseline, bottom border */
.p3xr-key-info-row {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    padding: 12px 16px;
    border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.12);
}

/* Clickable rows (Key, TTL) — always clickable */
.p3xr-key-clickable {
    cursor: pointer;
}
.p3xr-key-clickable:hover {
    background-color: rgba(var(--v-theme-on-surface), 0.1);
}

/* Labels — bold with colon, nowrap, 16px right margin */
.p3xr-key-label {
    white-space: nowrap;
    margin-right: 16px;
}

/* Values — right-aligned, selectable text */
.p3xr-key-value {
    text-align: right;
    overflow: hidden;
    text-overflow: ellipsis;
    user-select: text;
}

/* Key name — word-break for long keys */
.p3xr-key-ellipsis {
    min-width: 0;
    word-break: break-all;
}

/* TTL column — seconds on top, humanized duration below */
.p3xr-ttl-column {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
}
.p3xr-ttl-humanized {
    opacity: 0.5;
    font-size: 0.85em;
    font-weight: normal;
}

/* Compression badges — inline colored pills */
.p3xr-compression-badges {
    display: inline-flex;
    align-items: center;
    gap: 6px;
}
.p3xr-badge {
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 11px;
    font-weight: bold;
    letter-spacing: 0.5px;
}
.p3xr-badge-algo {
    background-color: rgb(var(--v-theme-secondary));
    color: rgb(var(--v-theme-on-secondary));
}
.p3xr-badge-positive {
    background-color: rgb(var(--v-theme-success));
    color: rgb(var(--v-theme-on-success));
}
.p3xr-badge-negative {
    background-color: rgb(var(--v-theme-error));
    color: rgb(var(--v-theme-on-error));
}

/* Size pretty bytes — dimmed prefix */
.p3xr-size-pretty {
    opacity: 0.5;
}

/* Format toggle row — center-aligned (not baseline) */
.p3xr-format-row {
    align-items: center;
}
.p3xr-format-label {
    flex: 1;
}

/* Format toggle — React ToggleButtonGroup style */
.p3xr-format-toggle {
    border-radius: 4px;
    overflow: hidden;
    border: thin solid rgba(var(--v-border-color), var(--v-border-opacity));
}
.p3xr-format-toggle :deep(.v-btn) {
    height: 32px !important;
    font-size: 13px !important;
    padding: 0 12px !important;
    border-radius: 0 !important;
    text-transform: none !important;
    letter-spacing: normal !important;
}
.p3xr-format-toggle :deep(.v-btn .v-btn__content) {
    text-transform: none !important;
    letter-spacing: normal !important;
    border: none !important;
    border-left: thin solid rgba(var(--v-border-color), var(--v-border-opacity)) !important;
}
.p3xr-format-toggle :deep(.v-btn--active) {
    background-color: rgba(var(--v-theme-primary), 0.25) !important;
    color: rgb(var(--v-theme-primary)) !important;
}
.p3xr-format-toggle :deep(.v-btn__overlay),
.p3xr-format-toggle :deep(.v-btn__underlay) {
    border-radius: 0 !important;
}
.p3xr-format-toggle :deep(.v-btn:first-child) {
    border-radius: 4px 0 0 4px !important;
    border-left: none;
}
.p3xr-format-toggle :deep(.v-btn:last-child) {
    border-radius: 0 4px 4px 0 !important;
}

/* Unsupported type fallback */
.p3xr-key-unsupported {
    padding: 16px;
    opacity: 0.7;
}
</style>

// src/react/pages/database/DatabaseKeyPage.tsx
import { useState, useEffect, useCallback, useRef, lazy, Suspense } from 'react'
import { useParams } from 'react-router-dom'
import {
    Box, Button, Tooltip, CircularProgress,
    ToggleButtonGroup, ToggleButton, useMediaQuery,
} from '@mui/material'
import { useTheme } from '@mui/material'
import { Add, Delete, Timer, Fingerprint, Refresh } from '@mui/icons-material'
import { useI18nStore } from '../../stores/i18n.store'
import { useRedisStateStore } from '../../stores/redis-state.store'
import { useSettingsStore } from '../../stores/settings.store'
import { useCommonStore } from '../../stores/common.store'
import { useMainCommandStore, onCommandEvent } from '../../stores/main-command.store'
import { useThemeStore } from '../../stores/theme.store'
import { request } from '../../stores/socket.service'
import { navigateTo } from '../../stores/navigation.store'
import { trackPage } from '../../stores/analytics'
import { isDarkTheme } from '../../themes'
import humanizeDuration from 'humanize-duration'
import KeyString from './key/KeyString'
import KeyList from './key/KeyList'
import KeyHash from './key/KeyHash'
import KeySet from './key/KeySet'
import KeyZset from './key/KeyZset'
import KeyStream from './key/KeyStream'
import KeyJson from './key/KeyJson'
import KeyTimeseries from './key/KeyTimeseries'
import KeyProbabilistic from './key/KeyProbabilistic'
import KeyVectorset from './key/KeyVectorset'
import TtlDialog from '../../dialogs/TtlDialog'

// Lazy-loaded renderer (MANDATORY per AGENTS.md for new key types)
const KeyArray = lazy(() => import('./key/KeyArray'))

const TextDecoder_ = typeof TextDecoder !== 'undefined' ? TextDecoder : class { decode(b: any) { return String(b) } }

function toBytes(buf: any): any {
    if (buf instanceof Uint8Array || buf instanceof ArrayBuffer) return buf instanceof ArrayBuffer ? new Uint8Array(buf) : buf
    if (buf && buf.type === 'Buffer' && Array.isArray(buf.data)) return new Uint8Array(buf.data)
    if (ArrayBuffer.isView(buf)) return new Uint8Array((buf as any).buffer, (buf as any).byteOffset, (buf as any).byteLength)
    return buf
}

function decodeValueBuffer(response: any, jsonFormat: number): void {
    const td = new TextDecoder_()
    const { type, valueBuffer } = response
    switch (type) {
        case 'string':
            response.value = td.decode(toBytes(valueBuffer))
            break
        case 'list':
        case 'set':
            response.value = valueBuffer.map((buf: any) => td.decode(toBytes(buf)))
            break
        case 'array':
        case 'hash':
            response.value = {}
            Object.entries(valueBuffer).forEach(([key, buf]: [string, any]) => {
                response.value[key] = td.decode(toBytes(buf))
            })
            break
        case 'zset':
            response.value = []
            for (let i = 0; i < valueBuffer.length; i += 2) {
                response.value.push(td.decode(toBytes(valueBuffer[i])))
                response.value.push(td.decode(valueBuffer[i + 1]))
            }
            break
        case 'json': {
            const rawJson = td.decode(toBytes(valueBuffer))
            try {
                const parsed = JSON.parse(rawJson)
                const unwrapped = Array.isArray(parsed) ? parsed[0] : parsed
                response.value = JSON.stringify(unwrapped, null, jsonFormat ?? 2)
            } catch {
                response.value = rawJson
            }
            break
        }
        case 'stream': {
            const decodeEntry = (entry: any): any => {
                return entry.map((item: any) => {
                    if (Array.isArray(item)) return decodeEntry(item)
                    if (ArrayBuffer.isView(item) || item instanceof ArrayBuffer) return td.decode(toBytes(item))
                    return item
                })
            }
            response.value = valueBuffer.map((entry: any) => decodeEntry(entry))
            break
        }
        case 'timeseries':
        case 'bloom':
        case 'cuckoo':
        case 'topk':
        case 'cms':
        case 'tdigest':
        case 'vectorset':
            try { response.value = JSON.parse(td.decode(toBytes(valueBuffer))) }
            catch { response.value = {} }
            break
        default:
            try { response.value = JSON.parse(td.decode(toBytes(valueBuffer))) }
            catch { response.value = td.decode(toBytes(valueBuffer)) }
            break
    }
}

function calculateSize(response: any): void {
    response.size = 0
    if (response.type !== 'stream') {
        if (typeof response.valueBuffer === 'object' && !Array.isArray(response.valueBuffer) && response.length > 0) {
            for (const k of Object.keys(response.valueBuffer)) response.size += response.valueBuffer[k]?.byteLength ?? 0
        } else if (Array.isArray(response.valueBuffer)) {
            for (const buf of response.valueBuffer) response.size += buf?.byteLength ?? 0
        } else if (response.valueBuffer) {
            response.size = response.valueBuffer.byteLength ?? 0
        }
    } else {
        const sumBytes = (arr: any[]): number => {
            let total = 0
            const process = (el: any) => {
                if (ArrayBuffer.isView(el) || el instanceof ArrayBuffer) total += el.byteLength
                else if (Array.isArray(el)) el.forEach(process)
            }
            arr.forEach(process)
            return total
        }
        response.size = sumBytes(response.valueBuffer ?? [])
    }
}

export default function DatabaseKeyPage() {
    const { key: rawKey } = useParams()
    const key = decodeURIComponent(rawKey ?? '')
    const strings = useI18nStore(s => s.strings)
    const connection = useRedisStateStore(s => s.connection)
    const themeKey = useThemeStore(s => s.themeKey)
    const jsonFormat = useSettingsStore(s => s.jsonFormat)
    const muiTheme = useTheme()
    const { confirm, toast, generalHandleError } = useCommonStore()
    const isGtSm = useMediaQuery('(min-width: 960px)')
    const isReadonly = connection?.readonly === true
    const isDark = muiTheme.palette.mode === 'dark'

    const [loading, setLoading] = useState(true)
    const [response, setResponse] = useState<any>(null)
    const [valueFormat, setValueFormat] = useState<'raw' | 'json' | 'hex' | 'base64'>('raw')
    const [ttlDialogOpen, setTtlDialogOpen] = useState(false)
    const ttlIntervalRef = useRef<any>(null)
    const wasExpiringRef = useRef(false)

    // Border color matching Angular SCSS
    const borderColor = isDark ? 'rgba(255,255,255,0.12)' : 'rgba(0,0,0,0.12)'
    const hoverBg = isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)'

    // Highlight the selected key in the tree
    useEffect(() => {
        const dark = isDarkTheme(themeKey)
        const bg = dark ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.15)'
        const color = dark ? 'white' : 'black'
        const style = document.createElement('style')
        style.id = 'p3xr-theme-styles-tree-key'
        style.textContent = `[data-p3xr-tree-key="${key.replace(/"/g, '\\"')}"] .p3xr-database-tree-node-label {
            background-color: ${bg} !important; color: ${color} !important; padding: 2px;
        }`
        document.getElementById('p3xr-theme-styles-tree-key')?.remove()
        document.head.appendChild(style)
        return () => { document.getElementById('p3xr-theme-styles-tree-key')?.remove() }
    }, [key, themeKey])

    // Load key data
    const loadKey = useCallback(async () => {
        clearInterval(ttlIntervalRef.current)
        setLoading(true)
        try {
            const resp = await request({ action: 'key/get', payload: { key } })
            if (resp.ttl === -2) {
                toast(strings?.status?.keyIsNotExisting)
                navigateTo('database.statistics')
                return
            }
            resp.size = 0
            decodeValueBuffer(resp, jsonFormat ? 2 : 0)
            calculateSize(resp)
            if (resp.ttl > -1) wasExpiringRef.current = true
            setResponse(resp)

            if (resp.ttl > -1) {
                ttlIntervalRef.current = setInterval(() => {
                    setResponse((prev: any) => {
                        if (!prev) return prev
                        const newTtl = prev.ttl - 1
                        if (newTtl < -1 || (wasExpiringRef.current && newTtl < 1)) {
                            clearInterval(ttlIntervalRef.current)
                            toast(strings?.status?.keyIsNotExisting)
                            useRedisStateStore.setState({ redisChanged: true })
                            navigateTo('database.statistics')
                            return prev
                        }
                        return { ...prev, ttl: newTtl }
                    })
                }, 1000)
            }
        } catch (e: any) {
            console.error(e)
            if (e?.message === 'Connection is closed.') {
                useRedisStateStore.setState({ connection: undefined })
                useCommonStore.getState().confirm({ message: e.message, disableCancel: true }).catch(() => {})
            } else {
                const fn = strings?.label?.unableToLoadKey
                const msg = typeof fn === 'function' ? fn({ key }) : String(e)
                useCommonStore.getState().confirm({ message: msg, disableCancel: true }).catch(() => {})
            }
            navigateTo('database.statistics')
        } finally {
            setLoading(false)
        }
    }, [key, strings, jsonFormat, toast])

    useEffect(() => { loadKey(); return () => clearInterval(ttlIntervalRef.current) }, [key])

    useEffect(() => { return onCommandEvent('refresh-key', () => loadKey()) }, [loadKey])

    // --- Actions ---
    const addKey = useCallback((e: React.MouseEvent) => {
        e.stopPropagation()
        useMainCommandStore.getState().addKey({ event: e.nativeEvent, node: { key } })
    }, [key])

    const deleteKey = useCallback(async (e: React.MouseEvent) => {
        e.stopPropagation()
        try {
            await confirm({ message: strings?.confirm?.deleteKey })
            await request({ action: 'key/delete', payload: { key } })
            trackPage('/delete')
            navigateTo('database.statistics')
            toast(typeof strings?.status?.deletedKey === 'function' ? strings.status.deletedKey({ key }) : '')
            await useMainCommandStore.getState().refresh({ withoutParent: false, force: true })
        } catch (err) { generalHandleError(err) }
    }, [key, strings, confirm, toast, generalHandleError])

    const renameKey = useCallback(async (e: React.MouseEvent) => {
        e.stopPropagation()
        try {
            const newKey = await useCommonStore.getState().prompt({
                title: strings?.confirm?.rename?.title,
                placeholder: strings?.confirm?.rename?.placeholder,
                initialValue: key,
                okLabel: strings?.intention?.rename,
                cancelLabel: strings?.intention?.cancel,
            })
            await request({ action: 'key/rename', payload: { key, keyNew: newKey } })
            trackPage('/rename')
            navigateTo('database.key', { key: newKey })
            toast(strings?.status?.renamedKey)
            await useMainCommandStore.getState().refresh({ withoutParent: false, force: true })
        } catch (err) { generalHandleError(err) }
    }, [key, strings, toast, generalHandleError])

    const setTtl = useCallback((e: React.MouseEvent) => {
        e.stopPropagation()
        setTtlDialogOpen(true)
    }, [])

    const handleTtlClose = useCallback(async (result?: { model: { ttl: number } }) => {
        setTtlDialogOpen(false)
        if (!result) return
        try {
            const ttlVal = result.model.ttl
            const ttlStr = String(ttlVal).trim()
            if (ttlStr === '' || ttlVal == null) {
                await request({ action: 'key/persist', payload: { key } })
                trackPage('/persist')
                await useMainCommandStore.getState().refresh({ withoutParent: true, force: true })
                await loadKey()
                toast(strings?.status?.persisted)
            } else if (!/^-?\d+$/.test(ttlStr)) {
                toast(strings?.status?.notInteger)
                return
            } else {
                await request({ action: 'key/expire', payload: { key, ttl: parseInt(ttlStr) } })
                trackPage('/expire')
                await useMainCommandStore.getState().refresh({ withoutParent: true, force: true })
                await loadKey()
                toast(strings?.status?.ttlChanged)
            }
        } catch (err) { generalHandleError(err) }
    }, [key, strings, toast, loadKey, generalHandleError])

    const refreshKey = useCallback(async () => {
        trackPage('/refresh')
        try {
            const resp = await request({ action: 'key/get', payload: { key } })
            if (resp.ttl === -2) return
            resp.size = 0
            decodeValueBuffer(resp, jsonFormat ? 2 : 0)
            calculateSize(resp)
            if (resp.ttl > -1) wasExpiringRef.current = true
            setResponse(resp)
        } catch {}
    }, [key, jsonFormat])

    // --- Responsive button ---
    const ActionBtn = ({ icon, label, color, onClick }: {
        icon: React.ReactNode; label: string; color: 'primary' | 'secondary' | 'error'; onClick: (e: React.MouseEvent) => void
    }) => isGtSm ? (
        <Button variant="contained" color={color} onClick={onClick}>
            {icon}<span>{label}</span>
        </Button>
    ) : (
        <Tooltip title={label} placement="top">
            <Button variant="contained" color={color} onClick={onClick}
                sx={{ minWidth: 40, width: 40, height: 40, p: 0, borderRadius: '4px' }}>
                {icon}
            </Button>
        </Tooltip>
    )

    // --- Render ---
    if (loading) {
        return (
            <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100%', p: 4 }}>
                <CircularProgress size={40} />
            </Box>
        )
    }

    if (!response) return null

    const hdOpts = useSettingsStore.getState().getHumanizeDurationOptions()

    return (
        <Box>
            {/* Action buttons — right-aligned, matching .p3xr-database-key-actions */}
            <Box sx={{
                display: 'flex', flexWrap: 'wrap', justifyContent: 'flex-end',
                alignItems: 'center', gap: 1, px: 1, py: '4px',
            }}>
                {!isReadonly && (
                    <>
                        <ActionBtn icon={<Add fontSize="small" />} label={strings?.intention?.addKey} color="secondary" onClick={addKey} />
                        <ActionBtn icon={<Delete fontSize="small" />} label={strings?.intention?.delete} color="error" onClick={deleteKey} />
                        <ActionBtn icon={<Timer fontSize="small" />} label={strings?.intention?.ttl} color="primary" onClick={setTtl} />
                        <ActionBtn icon={<Fingerprint fontSize="small" />} label={strings?.intention?.rename} color="primary" onClick={renameKey} />
                    </>
                )}
                <ActionBtn icon={<Refresh fontSize="small" />} label={strings?.intention?.reloadKey} color="secondary" onClick={refreshKey} />
            </Box>

            {/* Key info — matching .p3xr-database-key-info */}
            <Box sx={{ borderTop: `1px solid ${borderColor}` }}>
                {/* Key name — clickable */}
                <Box onClick={renameKey} sx={{
                    display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
                    px: 2, py: 1.5, borderBottom: `1px solid ${borderColor}`,
                    cursor: 'pointer', '&:hover': { bgcolor: hoverBg },
                }}>
                    <strong style={{ whiteSpace: 'nowrap', marginRight: 16 }}>{strings?.page?.key?.label?.key}:</strong>
                    <Box component="span" sx={{ textAlign: 'right', overflow: 'hidden', textOverflow: 'ellipsis', userSelect: 'text' }} title={key}>{key}</Box>
                </Box>

                {/* TTL — clickable */}
                <Box onClick={setTtl} sx={{
                    display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
                    px: 2, py: 1.5, borderBottom: `1px solid ${borderColor}`,
                    cursor: 'pointer', '&:hover': { bgcolor: hoverBg },
                }}>
                    <strong style={{ whiteSpace: 'nowrap', marginRight: 16 }}>{strings?.page?.key?.label?.ttl}:</strong>
                    {response.ttl === -1 ? (
                        <span>{strings?.page?.key?.label?.ttlNotExpire}</span>
                    ) : (
                        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end' }}>
                            <span>{response.ttl}</span>
                            <Box component="span" sx={{ opacity: 0.5, fontSize: '0.85em', fontWeight: 'normal' }}>
                                {humanizeDuration(response.ttl * 1000, { ...hdOpts, delimiter: ' ' })}
                            </Box>
                        </Box>
                    )}
                </Box>

                {/* Type */}
                <Box sx={{
                    display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
                    px: 2, py: 1.5, borderBottom: `1px solid ${borderColor}`,
                }}>
                    <strong style={{ whiteSpace: 'nowrap', marginRight: 16 }}>{strings?.page?.key?.label?.type}:</strong>
                    <span>{strings?.redisTypes?.[response.type]}</span>
                </Box>

                {/* Encoding */}
                <Box sx={{
                    display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
                    px: 2, py: 1.5, borderBottom: `1px solid ${borderColor}`,
                }}>
                    <strong style={{ whiteSpace: 'nowrap', marginRight: 16 }}>{strings?.page?.key?.label?.encoding}:</strong>
                    <span>{response.encoding}</span>
                </Box>

                {/* Compression */}
                {response.compression && (
                    <Box sx={{
                        display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
                        px: 2, py: 1.5, borderBottom: `1px solid ${borderColor}`,
                    }}>
                        <strong style={{ whiteSpace: 'nowrap', marginRight: 16 }}>{strings?.page?.key?.label?.compression}:</strong>
                        <Box sx={{ display: 'inline-flex', alignItems: 'center', gap: '6px' }}>
                            <Box component="span" sx={{
                                bgcolor: 'secondary.main', color: 'secondary.contrastText',
                                px: '6px', py: '2px', borderRadius: '4px', fontSize: 11, fontWeight: 'bold', letterSpacing: '0.5px',
                            }}>
                                {response.compression.algorithm.toUpperCase()}
                            </Box>
                            <Box component="span" sx={{
                                px: '6px', py: '2px', borderRadius: '4px', fontSize: 11, fontWeight: 'bold',
                                bgcolor: response.compression.ratio >= 0 ? 'success.main' : 'error.main',
                                color: response.compression.ratio >= 0 ? 'success.contrastText' : 'error.contrastText',
                            }}>
                                {response.compression.ratio >= 0 ? '' : '-'}{Math.abs(response.compression.ratio)}%
                            </Box>
                        </Box>
                    </Box>
                )}

                {/* Length/Size */}
                <Box sx={{
                    display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
                    px: 2, py: 1.5, borderBottom: `1px solid ${borderColor}`,
                }}>
                    <strong style={{ whiteSpace: 'nowrap', marginRight: 16 }}>{strings?.page?.key?.label?.length}:</strong>
                    <span>
                        <span style={{ opacity: 0.5 }}>{response.size >= 1024 ? `(${useSettingsStore.getState().prettyBytes(response.size)})` : ''}&nbsp;</span>
                        {response.size}&nbsp;{strings?.page?.key?.label?.lengthString}
                        {response.length ? <span>, {response.length} {strings?.page?.key?.label?.lengthItem}</span> : null}
                    </span>
                </Box>

                {/* Format toggle */}
                {response.type !== 'timeseries' && response.type !== 'json' && !['bloom', 'cuckoo', 'topk', 'cms', 'tdigest', 'vectorset'].includes(response.type) && (
                    <Box sx={{
                        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                        px: 2, py: 1.5, borderBottom: `1px solid ${borderColor}`,
                    }}>
                        <strong style={{ flex: 1, whiteSpace: 'nowrap', marginRight: 16 }}>{strings?.label?.format}:</strong>
                        <ToggleButtonGroup size="small" exclusive value={valueFormat}
                            onChange={(_, v) => v && setValueFormat(v)}
                            sx={{
                                borderRadius: '4px', overflow: 'hidden',
                                border: `thin solid ${isDark ? 'rgba(255,255,255,0.12)' : 'rgba(0,0,0,0.12)'}`,
                                '& .MuiToggleButton-root': {
                                    height: 32, fontSize: 13, px: 1.5, borderRadius: '0 !important',
                                    textTransform: 'none',
                                    bgcolor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
                                },
                                '& .MuiToggleButton-root.Mui-selected': {
                                    bgcolor: `${muiTheme.p3xr.matSysPrimary}40 !important`,
                                    color: muiTheme.p3xr.matSysPrimary,
                                },
                                '& .MuiToggleButton-root:first-of-type': { borderRadius: '4px 0 0 4px !important' },
                                '& .MuiToggleButton-root:last-of-type': { borderRadius: '0 4px 4px 0 !important' },
                            }}>
                            <ToggleButton value="raw">Raw</ToggleButton>
                            <ToggleButton value="json">JSON</ToggleButton>
                            <ToggleButton value="hex">Hex</ToggleButton>
                            <ToggleButton value="base64">Base64</ToggleButton>
                        </ToggleButtonGroup>
                    </Box>
                )}
            </Box>

            {/* Type-specific renderer */}
                {response.type === 'string' && (
                    <KeyString response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {response.type === 'hash' && (
                    <KeyHash response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {response.type === 'zset' && (
                    <KeyZset response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {response.type === 'set' && (
                    <KeySet response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {response.type === 'list' && (
                    <KeyList response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {response.type === 'stream' && (
                    <KeyStream response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {response.type === 'json' && (
                <KeyJson response={response} value={response.value} valueBuffer={response.valueBuffer}
                    keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
            )}

                {response.type === 'timeseries' && (
                    <KeyTimeseries response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {['bloom', 'cuckoo', 'topk', 'cms', 'tdigest'].includes(response.type) && (
                    <KeyProbabilistic response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {response.type === 'vectorset' && (
                    <KeyVectorset response={response} value={response.value} valueBuffer={response.valueBuffer}
                        keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                )}
                {response.type === 'array' && (
                    <Suspense fallback={<Box sx={{ display: 'flex', justifyContent: 'center', p: 4 }}><CircularProgress size={40} /></Box>}>
                        <KeyArray response={response} value={response.value} valueBuffer={response.valueBuffer}
                            keyName={key} valueFormat={valueFormat} onRefresh={refreshKey} />
                    </Suspense>
                )}

            {response.type !== 'string' && response.type !== 'hash' && response.type !== 'set' && response.type !== 'zset' && response.type !== 'list' && response.type !== 'stream' && response.type !== 'json' && response.type !== 'timeseries' && !['bloom', 'cuckoo', 'topk', 'cms', 'tdigest'].includes(response.type) && response.type !== 'vectorset' && response.type !== 'array' && (
                    <Box sx={{ mt: 2, p: 2, opacity: 0.7 }}>
                        {strings?.page?.key?.probabilistic?.noItems}
                    </Box>
                )}

            <TtlDialog open={ttlDialogOpen} ttl={response?.ttl === -1 ? '' : response?.ttl} onClose={handleTtlClose} />
        </Box>
    )
}
