// src/react/pages/console/ConsoleComponent.tsx
import { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import { Box, Toolbar, Tooltip, Popper, Paper, ClickAwayListener } from '@mui/material'
import { CheckBox, CheckBoxOutlineBlank, Terminal, Backspace, MenuBook } from '@mui/icons-material'
import { useTheme } from '@mui/material'
import P3xrButton from '../../components/P3xrButton'
import { useI18nStore } from '../../stores/i18n.store'
import { useRedisStateStore } from '../../stores/redis-state.store'
import { useCommonStore } from '../../stores/common.store'
import { useMainCommandStore } from '../../stores/main-command.store'
import { request } from '../../stores/socket.service'
import { consoleParse } from '../../stores/redis-parser'

function htmlEncode(str: string): string {
    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;')
}

const CONSOLE_OUTPUT_KEY = 'p3xr-console-output-v1'
const CONSOLE_OUTPUT_MAX = 10 * 1024 * 1024
let actionHistoryPosition = -1

interface ConsoleProps {
    embedded?: boolean
    collapsed?: boolean
}

export default function ConsoleComponent({ embedded = false, collapsed = false }: ConsoleProps) {
    const strings = useI18nStore(s => s.strings)
    const cfg = useRedisStateStore(s => s.cfg)
    const commands = useRedisStateStore(s => s.commands)
    const commandsMeta = useRedisStateStore(s => s.commandsMeta)
    const muiTheme = useTheme()
    const { toast } = useCommonStore()

    const [searchText, setSearchText] = useState('')
    const [currentHint, setCurrentHint] = useState('')
    const [aiLoading, setAiLoading] = useState(false)
    const [aiAutoDetect, setAiAutoDetect] = useState(() => {
        try { return localStorage.getItem('p3xr-ai-auto-detect') !== 'false' } catch { return true }
    })

    const outputRef = useRef<HTMLDivElement>(null)
    const scrollerRef = useRef<HTMLDivElement>(null)
    const inputRef = useRef<HTMLTextAreaElement>(null)
    const indexRef = useRef(0)
    const singleLineHeightRef = useRef(0)
    const aiCommandPendingRef = useRef(false)

    const aiEnabled = cfg?.aiEnabled !== false
    const [autocompleteHighlight, setAutocompleteHighlight] = useState(0)
    const [autocompleteDismissed, setAutocompleteDismissed] = useState(false)
    const [autocompleteNavigated, setAutocompleteNavigated] = useState(false)

    // --- Autocomplete: grouped commands matching Angular mat-autocomplete ---
    const filteredCommands = useMemo(() => {
        if (!searchText || searchText.length === 0 || !commands?.length) return []
        const text = searchText.toUpperCase()
        const matched = commands
            .filter((cmd: string) => cmd.toUpperCase().includes(text))
            .slice(0, 20)
        const groups = new Map<string, { name: string; syntax: string }[]>()
        for (const cmd of matched) {
            const info = commandsMeta[cmd.toUpperCase()]
            const group = info?.group || 'Other'
            const syntax = info?.syntax || ''
            if (!groups.has(group)) groups.set(group, [])
            groups.get(group)!.push({ name: cmd, syntax })
        }
        return Array.from(groups.entries()).map(([group, cmds]) => ({ group, commands: cmds }))
    }, [searchText, commands, commandsMeta])

    const flatOptions = useMemo(() => {
        const result: { name: string; syntax: string }[] = []
        for (const g of filteredCommands) result.push(...g.commands)
        return result
    }, [filteredCommands])

    // --- AI toggle ---
    const toggleAiAutoDetect = useCallback(() => {
        const next = !aiAutoDetect
        setAiAutoDetect(next)
        try { localStorage.setItem('p3xr-ai-auto-detect', String(next)) } catch {}
    }, [aiAutoDetect])

    // --- Output (direct DOM matching Angular) ---
    const getByteSize = (v: string) => { try { return new Blob([v || '']).size } catch { return (v || '').length } }

    const dropOldest = useCallback(() => {
        const el = outputRef.current
        if (!el) return false
        const items = el.querySelectorAll('.p3xr-console-content-output-item')
        if (items.length < 1) return false
        const count = Math.max(Math.floor(items.length * 0.1), 1)
        for (let i = 0; i < count; i++) items[i].remove()
        return true
    }, [])

    const trimOutput = useCallback(() => {
        const el = outputRef.current
        if (!el) return
        while (getByteSize(el.innerHTML) > CONSOLE_OUTPUT_MAX) {
            if (!dropOldest()) break
        }
    }, [dropOldest])

    const persistNow = useCallback(() => {
        const el = outputRef.current
        if (!el) return
        trimOutput()
        try { localStorage.setItem(CONSOLE_OUTPUT_KEY, el.innerHTML || '') }
        catch { try { localStorage.removeItem(CONSOLE_OUTPUT_KEY) } catch {} }
    }, [trimOutput])

    const persistTimerRef = useRef<any>(null)
    const persistDebounced = useCallback(() => {
        clearTimeout(persistTimerRef.current)
        persistTimerRef.current = setTimeout(persistNow, 100)
    }, [persistNow])

    const scrollToBottom = useCallback(() => {
        setTimeout(() => {
            const s = scrollerRef.current
            if (!s) return
            if (s.scrollHeight - s.scrollTop - s.clientHeight < 100) {
                s.scrollTop = s.scrollHeight
            }
        }, 0)
    }, [])

    const forceScrollToBottom = useCallback(() => {
        setTimeout(() => {
            const s = scrollerRef.current
            if (s) s.scrollTop = s.scrollHeight
        }, 0)
    }, [])

    const outputAppend = useCallback((message: string) => {
        const el = outputRef.current
        if (!el) return
        const stripped = message.replace(/<[^>]*>/g, '').replace(/&[a-z]+;/g, '').trim()
        if (!stripped) return
        el.insertAdjacentHTML('beforeend',
            `<span data-index="${indexRef.current++}" class="p3xr-console-content-output-item">${message}<br/></span>`)
        trimOutput()
        persistDebounced()
        scrollToBottom()
    }, [trimOutput, persistDebounced, scrollToBottom])

    // --- Init: restore output ---
    useEffect(() => {
        const el = outputRef.current
        if (!el) return
        let stored = ''
        try { stored = localStorage.getItem(CONSOLE_OUTPUT_KEY) || '' } catch {}
        if (stored) {
            el.innerHTML = stored
            trimOutput()
            persistNow()
            const items = el.querySelectorAll('.p3xr-console-content-output-item')
            const last = items.length > 0 ? items[items.length - 1] : null
            if (last) {
                const idx = Number(last.getAttribute('data-index'))
                if (Number.isFinite(idx)) indexRef.current = idx + 1
            }
            forceScrollToBottom()
        } else {
            // Welcome message
            el.innerHTML = ''
            const welcome = strings?.label?.welcomeConsole ?? 'Welcome to the Redis Console'
            const info = strings?.label?.welcomeConsoleInfo ?? 'Shift + Cursor UP or DOWN for history'
            el.insertAdjacentHTML('beforeend',
                `<span data-index="${indexRef.current++}" class="p3xr-console-content-output-item"><strong>${welcome}</strong><br/></span>`)
            el.insertAdjacentHTML('beforeend',
                `<span data-index="${indexRef.current++}" class="p3xr-console-content-output-item">${info}<br/><br/></span>`)
            persistNow()
        }
    }, [])

    // --- Clear ---
    const clearConsole = useCallback(() => {
        const el = outputRef.current
        if (!el) return
        el.innerHTML = ''
        const welcome = strings?.label?.welcomeConsole ?? 'Welcome to the Redis Console'
        const info = strings?.label?.welcomeConsoleInfo ?? 'Shift + Cursor UP or DOWN for history'
        outputAppend(`<strong>${welcome}</strong>`)
        outputAppend(`${info}<br/>`)
        persistNow()
        forceScrollToBottom()
        inputRef.current?.focus()
    }, [strings, outputAppend, persistNow, forceScrollToBottom])

    // --- History ---
    const getHistory = (): string[] => {
        try { return JSON.parse(localStorage.getItem('console-history') || '[]') } catch { return [] }
    }
    const updateHistory = (entry: string) => {
        let h = getHistory()
        const idx = h.indexOf(entry)
        if (idx > -1) h.splice(idx, 1)
        h.unshift(entry)
        if (h.length > 20) h = h.slice(0, 20)
        localStorage.setItem('console-history', JSON.stringify(h))
        actionHistoryPosition = -1
    }

    // --- Auto-resize ---
    const autoResize = useCallback(() => {
        const el = inputRef.current
        if (!el) return
        if (!singleLineHeightRef.current) singleLineHeightRef.current = el.offsetHeight
        const focused = document.activeElement === el
        if (!focused && (el.value || '').includes('\n')) {
            el.style.height = singleLineHeightRef.current + 'px'
            el.style.overflowY = 'hidden'
            return
        }
        el.style.height = singleLineHeightRef.current + 'px'
        el.style.overflowY = 'hidden'
        if ((el.value || '').includes('\n') && el.scrollHeight > el.clientHeight) {
            const max = singleLineHeightRef.current * 3
            const border = el.offsetHeight - el.clientHeight
            const needed = el.scrollHeight + border
            if (needed > max) {
                el.style.height = max + 'px'
                el.style.overflowY = 'auto'
            } else {
                el.style.height = needed + 'px'
            }
        }
    }, [])

    const autocompleteListRef = useRef<HTMLDivElement>(null)

    useEffect(() => { setAutocompleteHighlight(0) }, [flatOptions.length])

    // Scroll highlighted autocomplete item into view
    useEffect(() => {
        const list = autocompleteListRef.current
        if (!list) return
        const item = list.querySelector(`[data-ac-idx="${autocompleteHighlight}"]`) as HTMLElement
        if (item) item.scrollIntoView({ block: 'nearest' })
    }, [autocompleteHighlight])

    const selectAutocomplete = useCallback((cmdName: string) => {
        setSearchText(cmdName)
        setAutocompleteDismissed(true)
        setTimeout(() => { inputRef.current?.focus(); autoResize() }, 0)
    }, [autoResize])

    const dismissAutocomplete = useCallback(() => {
        setAutocompleteDismissed(true)
    }, [])

    // --- Natural language detection ---
    const looksLikeNaturalLanguage = useCallback((input: string, errorMsg: string): boolean => {
        if (!/unknown command|wrong number of arguments|ERR unknown/i.test(errorMsg)) return false
        const firstWord = input.trim().split(/\s+/)[0].toUpperCase()
        if (commands?.includes(firstWord)) return false
        return true
    }, [commands])

    // --- AI query ---
    const handleAiQuery = useCallback(async (prompt: string, originalInput: string): Promise<boolean> => {
        if (prompt.length > 4096) {
            toast(strings?.error?.aiPromptTooLong)
            return false
        }
        setAiLoading(true)
        inputRef.current?.focus()
        try {
            let indexes: string[] = []
            try { const r = await request({ action: 'search/list', payload: {} }); indexes = r.data || [] } catch {}
            const info = useRedisStateStore.getState().info || {}
            const server = info.server || {}
            const clients = info.clients || {}
            const memory = info.memory || {}
            const keyspace = info.keyspace || {}
            const modules = useRedisStateStore.getState().modules || []
            const ctx: any = { indexes }
            if (server.redis_version) ctx.redisVersion = server.redis_version
            if (server.redis_mode) ctx.redisMode = server.redis_mode
            if (server.os) ctx.os = server.os
            if (clients.connected_clients) ctx.connectedClients = clients.connected_clients
            if (memory.used_memory_human) ctx.usedMemory = memory.used_memory_human
            const dbKeys = Object.keys(keyspace).filter((k: string) => /^db\d+$/.test(k))
            if (dbKeys.length > 0) ctx.databases = dbKeys.map((k: string) => `${k}: ${keyspace[k]}`)
            if (modules.length > 0) ctx.modules = modules
            ctx.uiLanguage = useI18nStore.getState().currentLang

            const response = await request({ action: 'ai/redis-query', payload: { prompt, context: ctx } })
            const command = response.command || ''
            const explanation = response.explanation || ''
            outputAppend(htmlEncode(originalInput))
            updateHistory(originalInput)
            if (command) {
                let line = `<strong style="color: ${muiTheme.p3xr.matSysPrimary};">AI &rarr;</strong> <code>${htmlEncode(command)}</code>`
                if (explanation) line += `<br/><span style="opacity: 0.7; font-size: 0.9em;">${htmlEncode(explanation)}</span>`
                outputAppend(line + '<br/>')
                setSearchText(command)
                setCurrentHint('')
                aiCommandPendingRef.current = true
                setTimeout(() => autoResize(), 0)
            }
            return true
        } catch (e: any) {
            const msg = e.message || String(e)
            if (msg.includes('429') || msg.includes('rate_limit')) toast(strings?.page?.key?.label?.aiRateLimited)
            else toast(strings?.page?.key?.label?.aiError + ': ' + msg)
            return false
        } finally {
            setAiLoading(false)
            forceScrollToBottom()
            inputRef.current?.focus()
        }
    }, [muiTheme, strings, outputAppend, forceScrollToBottom, toast, autoResize])

    // --- Execute ---
    const executeSingleLine = useCallback(async (command: string) => {
        const enter = command.trim()
        if (!enter) return
        if (aiEnabled && /^ai:\s*/i.test(enter)) {
            const prompt = enter.replace(/^ai:\s*/i, '').trim()
            if (prompt) await handleAiQuery(prompt, enter)
            return
        }
        try {
            const response = await request({ action: 'redis/console', payload: { command: enter } })
            const result = htmlEncode(String(consoleParse(response.result)))
            outputAppend(`${htmlEncode(enter)}<br/><pre>${result}</pre>`)
            if (response.hasOwnProperty('database')) {
                useRedisStateStore.setState({ currentDatabase: response.database, redisChanged: true })
            }
        } catch (e: any) {
            const errorMsg = e.message || ''
            if (aiEnabled && aiAutoDetect && looksLikeNaturalLanguage(enter, errorMsg)) {
                if (await handleAiQuery(enter, enter)) return
            }
            const strs = useI18nStore.getState().strings
            outputAppend(`${htmlEncode(enter)}<br/><pre>${strs?.code?.[errorMsg] || errorMsg}</pre>`)
        }
    }, [aiEnabled, aiAutoDetect, looksLikeNaturalLanguage, handleAiQuery, outputAppend])

    const actionEnter = useCallback(async () => {
        const full = searchText.trim()
        if (!full || aiLoading) return
        try {
            const lines = full.split('\n').map(l => l.trim()).filter(l => l.length > 0)
            if (!lines.length) return
            const first = lines[0].split(/\s+/)[0].toUpperCase()
            const single = lines.length === 1 || first === 'EVAL' || first === 'EVALSHA'
            if (single) await executeSingleLine(full)
            else for (const line of lines) await executeSingleLine(line)
        } finally {
            updateHistory(full)
            setCurrentHint('')
            if (aiCommandPendingRef.current) aiCommandPendingRef.current = false
            else { setSearchText(''); setTimeout(() => autoResize(), 0) }
            forceScrollToBottom()
            if (embedded) useMainCommandStore.getState().refresh({ withoutParent: true, force: true })
            inputRef.current?.focus()
        }
    }, [searchText, aiLoading, executeSingleLine, autoResize, forceScrollToBottom, embedded])

    // --- Input change ---
    const onInputChange = useCallback((value: string) => {
        setSearchText(value)
        setAutocompleteDismissed(false)
        setAutocompleteNavigated(false)
        const first = value.trim().split(/\s+/)[0]?.toUpperCase()
        if (first && commandsMeta[first]?.syntax) setCurrentHint(first + ' ' + commandsMeta[first].syntax)
        else setCurrentHint('')
        setTimeout(() => autoResize(), 0)
    }, [commandsMeta, autoResize])

    // --- Key handler ---
    const autocompleteOpen = flatOptions.length > 0 && !autocompleteDismissed

    const onKeyDown = useCallback((e: React.KeyboardEvent) => {
        // Tab — select highlighted autocomplete item
        if (e.key === 'Tab' && autocompleteOpen) {
            e.preventDefault()
            const opt = flatOptions[autocompleteHighlight]
            if (opt) selectAutocomplete(opt.name)
            return
        }
        if (e.key === 'Enter') {
            if (e.shiftKey) { setTimeout(() => autoResize(), 0); return }
            e.preventDefault()
            // If user navigated autocomplete, Enter selects the item
            if (autocompleteOpen && autocompleteNavigated) {
                const opt = flatOptions[autocompleteHighlight]
                if (opt) { selectAutocomplete(opt.name); return }
            }
            setAutocompleteDismissed(true)
            actionEnter()
            return
        }
        // Arrow keys — autocomplete navigation (without Shift)
        if (autocompleteOpen && !e.shiftKey && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) {
            e.preventDefault()
            setAutocompleteNavigated(true)
            setAutocompleteHighlight(prev => {
                if (e.key === 'ArrowDown') return (prev + 1) % flatOptions.length
                return (prev - 1 + flatOptions.length) % flatOptions.length
            })
            return
        }
        if (e.key === 'Escape') {
            setAutocompleteDismissed(true)
            return
        }
        if (e.key !== 'ArrowUp' && e.key !== 'ArrowDown') { actionHistoryPosition = -1; return }
        if (!e.shiftKey) return
        const history = getHistory()
        if (history.length < 1) return
        e.preventDefault(); e.stopPropagation()
        if (e.key === 'ArrowDown') {
            if (actionHistoryPosition === -1) actionHistoryPosition = history.length
            actionHistoryPosition--
            if (actionHistoryPosition < 0) actionHistoryPosition = history.length - 1
        } else {
            actionHistoryPosition++
            if (actionHistoryPosition >= history.length) actionHistoryPosition = 0
        }
        const value = history[actionHistoryPosition] ?? ''
        setSearchText(value)
        setTimeout(() => { const el = inputRef.current; if (el) { el.blur(); el.focus() }; autoResize() }, 0)
    }, [actionEnter, autoResize, flatOptions, autocompleteHighlight, selectAutocomplete, autocompleteDismissed, autocompleteNavigated, autocompleteOpen])

    // --- Auto-resize when searchText changes (AI, history, etc.) ---
    useEffect(() => {
        requestAnimationFrame(() => autoResize())
    }, [searchText, autoResize])

    // --- Paste ---
    useEffect(() => {
        const el = inputRef.current
        if (!el) return
        const handler = () => setTimeout(() => autoResize(), 0)
        el.addEventListener('paste', handler)
        return () => el.removeEventListener('paste', handler)
    }, [autoResize])

    // --- Cleanup ---
    useEffect(() => {
        return () => {
            clearTimeout(persistTimerRef.current)
            persistNow()
        }
    }, [persistNow])

    return (
        <Box className="p3xr-console-root" sx={{
            display: 'flex', flexDirection: 'column',
            width: '100%', height: '100%', overflow: 'hidden',
        }}>
            {/* Header toolbar — strongBg, 48px */}
            <Toolbar id="p3xr-console-header" variant="dense" disableGutters sx={{
                backgroundColor: `${muiTheme.p3xr.strongBg} !important`,
                backgroundImage: 'none !important',
                color: 'rgba(255,255,255,0.87) !important',
                minHeight: '48px !important', height: 48, maxHeight: 48,
                px: 0, flexShrink: 0, zIndex: 2,
                '& *': { color: 'inherit' },
                '& .MuiButton-root': {
                    color: 'inherit !important', textTransform: 'uppercase',
                    height: 36, minHeight: 36, minWidth: 'auto', px: 1, mx: 1,
                    letterSpacing: '0.1px', display: 'inline-flex', alignItems: 'center',
                    gap: '3px',
                    '&:hover': { bgcolor: 'rgba(255,255,255,0.15) !important' },
                },
                '& .MuiIconButton-root': {
                    color: 'inherit !important', borderRadius: '4px',
                    '&:hover': { bgcolor: 'rgba(255,255,255,0.15) !important' },
                },
            }}>
                <Box sx={{ display: 'flex', alignItems: 'center', width: '100%', height: '100%', px: '3px' }}>
                    <Terminal sx={{ mr: '6px' }} />
                    <Box className="p3xr-console-title" sx={{
                        fontSize: 20, fontWeight: 500,
                        whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                    }}>
                        {strings?.label?.console}
                    </Box>
                    <Box sx={{ flex: '1 1 auto' }} />
                    <Box className="p3xr-console-toolbar-actions" sx={{ display: 'inline-flex', alignItems: 'center', flexShrink: 0, whiteSpace: 'nowrap' }}>
                        {aiEnabled && (
                            <Box className="p3xr-console-ai-toggle" onClick={toggleAiAutoDetect} sx={{
                                display: 'inline-flex', alignItems: 'center', gap: '4px',
                                mx: 1, px: 1, height: 36, cursor: 'pointer',
                                fontSize: 13, textTransform: 'uppercase', borderRadius: '4px',
                                userSelect: 'none', whiteSpace: 'nowrap', flexShrink: 0,
                                '&:hover': { bgcolor: 'rgba(255,255,255,0.15)' },
                            }}>
                                {aiAutoDetect
                                    ? <CheckBox sx={{ fontSize: 20, width: 20, height: 20 }} />
                                    : <CheckBoxOutlineBlank sx={{ fontSize: 20, width: 20, height: 20 }} />}
                                <span>Auto AI</span>
                            </Box>
                        )}
                        <P3xrButton label={strings?.label?.redisCommandsReference ?? 'Redis Commands'}
                            icon={<MenuBook fontSize="small" />}
                            onClick={() => window.open('https://redis.io/docs/latest/commands/', '_blank')} />
                        <P3xrButton label={strings?.intention?.clear ?? 'Clear'}
                            icon={<Backspace fontSize="small" />}
                            onClick={clearConsole} />
                    </Box>
                </Box>
            </Toolbar>

            {/* Output area — hidden when collapsed */}
            <Box ref={scrollerRef} id="p3xr-console-content" sx={{
                flex: collapsed ? '0 0 0px' : '1 1 auto',
                minHeight: 0,
                overflow: collapsed ? 'hidden' : 'auto',
                display: collapsed ? 'none' : 'block',
                fontFamily: "'Roboto Mono', monospace",
                textAlign: 'center',
                '& pre': {
                    fontFamily: "'Roboto Mono', monospace",
                    whiteSpace: 'pre-wrap', wordBreak: 'break-word', overflowWrap: 'anywhere',
                },
            }}>
                <Box ref={outputRef} id="p3xr-console-content-output" sx={{
                    textAlign: 'left', overflow: 'auto', flexGrow: 1, minWidth: 'calc(100% - 20px)',
                }} />
            </Box>

            {/* Autocomplete dropdown — opens ABOVE input via Popper */}
            {autocompleteOpen && !collapsed && inputRef.current && (
                <ClickAwayListener onClickAway={dismissAutocomplete}>
                    <Popper open anchorEl={inputRef.current} placement="top-start"
                        sx={{ zIndex: 1300, width: inputRef.current?.offsetWidth || '100%' }}>
                        <Paper ref={autocompleteListRef} sx={{
                            maxHeight: 350, overflow: 'auto',
                            fontFamily: "'Roboto Mono', monospace", fontSize: 13,
                            bgcolor: 'background.paper', backgroundImage: 'none',
                        }}>
                            {filteredCommands.map(group => (
                                <Box key={group.group}>
                                    <Box sx={{
                                        fontSize: 11, fontWeight: 'bold', textTransform: 'uppercase',
                                        letterSpacing: '0.5px', minHeight: 28, lineHeight: '28px',
                                        opacity: 0.7, px: 2,
                                    }}>
                                        {group.group}
                                    </Box>
                                    {group.commands.map(cmd => {
                                        const idx = flatOptions.indexOf(cmd)
                                        return (
                                            <Box key={cmd.name}
                                                data-ac-idx={idx}
                                                onClick={() => selectAutocomplete(cmd.name)}
                                                sx={{
                                                    minHeight: 32, lineHeight: '32px', px: 2,
                                                    cursor: 'pointer', fontSize: 13,
                                                    fontFamily: "'Roboto Mono', monospace",
                                                    bgcolor: idx === autocompleteHighlight ? 'action.hover' : 'transparent',
                                                    '&:hover': { bgcolor: 'action.hover' },
                                                }}>
                                                <Box component="span" sx={{ fontWeight: 'bold', mr: 1 }}>{cmd.name}</Box>
                                                {cmd.syntax && <Box component="span" sx={{ opacity: 0.5, fontSize: 11 }}>{cmd.syntax}</Box>}
                                            </Box>
                                        )
                                    })}
                                </Box>
                            ))}
                        </Paper>
                    </Popper>
                </ClickAwayListener>
            )}

            {/* Input area */}
            <Box id="p3xr-console-autocomplete" sx={{
                position: 'relative', width: '100%', flexShrink: 0,
                minWidth: 0,
            }}>
                {currentHint && !collapsed && (
                    <Box className="p3xr-console-hint" sx={{
                        fontFamily: "'Roboto Mono', monospace", fontSize: 12,
                        px: '6px', py: '2px', opacity: 0.6,
                        whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                    }}>
                        {currentHint}
                    </Box>
                )}
                <textarea
                    ref={inputRef}
                    id="p3xr-console-input"
                    rows={1}
                    value={searchText}
                    onChange={e => onInputChange(e.target.value)}
                    onKeyDown={onKeyDown}
                    onFocus={() => autoResize()}
                    onBlur={() => setTimeout(() => autoResize(), 0)}
                    autoComplete="off"
                    placeholder={aiLoading ? (strings?.label?.aiTranslating ?? 'Translating...') : ''}
                    style={{
                        display: 'block',
                        width: collapsed ? 'calc(100% - 1px)' : '100%',
                        minWidth: collapsed ? 'calc(100% - 1px)' : '100%',
                        boxSizing: 'border-box',
                        padding: 3,
                        borderStyle: 'solid',
                        borderWidth: 3,
                        margin: 0,
                        fontFamily: "'Roboto Mono', monospace",
                        resize: 'none',
                        overflowY: 'hidden',
                        outline: 'none',
                        maxHeight: 90,
                        position: 'relative',
                        backgroundColor: muiTheme.p3xr.inputBg,
                        color: muiTheme.p3xr.inputColor,
                        borderColor: aiLoading ? muiTheme.p3xr.matSysPrimary : muiTheme.p3xr.inputBorderColor,
                    }}
                />
            </Box>
        </Box>
    )
}

// src/vue/pages/console/ConsoleComponent.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { storeToRefs } from 'pinia'
import P3xrButton from '../../components/P3xrButton.vue'
import { useI18nStore } from '../../stores/i18n'
import { useRedisStateStore } from '../../stores/redis-state'
import { useCommonStore } from '../../stores/common'
import { useThemeStore } from '../../stores/theme'
import { useMainCommandStore } from '../../stores/main-command'
import { request } from '../../stores/socket.service'
import { consoleParse } from '../../stores/redis-parser'

const props = withDefaults(defineProps<{
    embedded?: boolean
    collapsed?: boolean
}>(), {
    embedded: false,
    collapsed: false,
})

const i18n = useI18nStore()
const state = useRedisStateStore()
const common = useCommonStore()
const cmd = useMainCommandStore()
const { themeKey } = storeToRefs(useThemeStore())

const strings = computed(() => i18n.strings)
const aiEnabled = computed(() => state.cfg?.aiEnabled !== false)

// --- State ---
const searchText = ref('')
const currentHint = ref('')
const aiLoading = ref(false)
const aiAutoDetect = ref((() => {
    try { return localStorage.getItem('p3xr-ai-auto-detect') !== 'false' } catch { return true }
})())
const autocompleteHighlight = ref(0)
const autocompleteDismissed = ref(false)

// --- Refs ---
const outputEl = ref<HTMLDivElement>()
const scrollerEl = ref<HTMLDivElement>()
const inputEl = ref<HTMLTextAreaElement>()
let indexCounter = 0
let singleLineHeight = 0
let aiCommandPending = false

const CONSOLE_OUTPUT_KEY = 'p3xr-console-output-v1'
const CONSOLE_OUTPUT_MAX = 10 * 1024 * 1024

// Theme colors (exact from Angular _theme-custom.scss + React themes/index.ts)
const STRONG_BG: Record<string, string> = {
    enterprise: '#212121', light: '#263238', redis: '#b71c1c',
    dark: '#212121', darkNeu: '#263238', darkoBluo: '#1a237e',
    matrix: '#33691e',
}
const INPUT_BG: Record<string, string> = {
    enterprise: 'white', light: 'white', redis: 'white',
    dark: 'rgba(64,64,64,1)', darkNeu: 'rgba(64,64,64,1)', darkoBluo: 'rgba(64,64,64,1)',
    matrix: 'rgba(64,64,64,1)',
}
const INPUT_COLOR: Record<string, string> = {
    enterprise: 'black', light: 'black', redis: 'black',
    dark: 'white', darkNeu: 'white', darkoBluo: 'white',
    matrix: 'white',
}
const INPUT_BORDER: Record<string, string> = {
    enterprise: '#9e9e9e', light: '#b0bec5', redis: '#ef9a9a',
    dark: '#9e9e9e', darkNeu: '#90a4ae', darkoBluo: '#3f51b5',
    matrix: '#76ff03',
}
const toolbarBg = computed(() => STRONG_BG[themeKey.value] || '#212121')
const inputBg = computed(() => INPUT_BG[themeKey.value] || 'rgba(64,64,64,1)')
const inputColor = computed(() => INPUT_COLOR[themeKey.value] || 'white')
const inputBorder = computed(() => INPUT_BORDER[themeKey.value] || '#9e9e9e')

// --- HTML encoding ---
function htmlEncode(str: string): string {
    return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;')
}

// --- Autocomplete ---
const filteredCommands = computed(() => {
    if (!searchText.value || !state.commands?.length) return []
    const text = searchText.value.toUpperCase()
    const matched = state.commands
        .filter((c: string) => c.toUpperCase().includes(text))
        .slice(0, 20)
    const groups = new Map<string, { name: string; syntax: string }[]>()
    for (const c of matched) {
        const info = state.commandsMeta?.[c.toUpperCase()]
        const group = info?.group || 'Other'
        const syntax = info?.syntax || ''
        if (!groups.has(group)) groups.set(group, [])
        groups.get(group)!.push({ name: c, syntax })
    }
    return Array.from(groups.entries()).map(([group, cmds]) => ({ group, commands: cmds }))
})

const flatOptions = computed(() => {
    const result: { name: string; syntax: string }[] = []
    for (const g of filteredCommands.value) result.push(...g.commands)
    return result
})

const showAutocomplete = computed(() =>
    filteredCommands.value.length > 0 && !autocompleteDismissed.value && searchText.value.length > 0
)

function selectAutocomplete(cmdName: string) {
    searchText.value = cmdName + ' '
    autocompleteDismissed.value = true
    // Update hint with syntax
    const meta = state.commandsMeta?.[cmdName.toUpperCase()]
    if (meta?.syntax) {
        currentHint.value = cmdName.toUpperCase() + ' ' + meta.syntax
    }
    nextTick(() => { inputEl.value?.focus(); autoResize() })
}

// --- Output management ---
function getByteSize(v: string): number {
    try { return new Blob([v || '']).size } catch { return (v || '').length }
}

function dropOldest(): boolean {
    const el = outputEl.value
    if (!el) return false
    const items = el.querySelectorAll('.p3xr-console-content-output-item')
    if (items.length < 1) return false
    const count = Math.max(Math.floor(items.length * 0.1), 1)
    for (let i = 0; i < count; i++) items[i].remove()
    return true
}

function trimOutput() {
    const el = outputEl.value
    if (!el) return
    while (getByteSize(el.innerHTML) > CONSOLE_OUTPUT_MAX) {
        if (!dropOldest()) break
    }
}

let persistTimer: any = null
function persistNow() {
    const el = outputEl.value
    if (!el) return
    trimOutput()
    try { localStorage.setItem(CONSOLE_OUTPUT_KEY, el.innerHTML || '') }
    catch { try { localStorage.removeItem(CONSOLE_OUTPUT_KEY) } catch {} }
}

function persistDebounced() {
    clearTimeout(persistTimer)
    persistTimer = setTimeout(persistNow, 100)
}

function scrollToBottom() {
    setTimeout(() => {
        const s = scrollerEl.value
        if (!s) return
        if (s.scrollHeight - s.scrollTop - s.clientHeight < 100) {
            s.scrollTop = s.scrollHeight
        }
    }, 0)
}

function forceScrollToBottom() {
    setTimeout(() => {
        const s = scrollerEl.value
        if (s) s.scrollTop = s.scrollHeight
    }, 0)
}

function outputAppend(message: string) {
    const el = outputEl.value
    if (!el) return
    const stripped = message.replace(/<[^>]*>/g, '').replace(/&[a-z]+;/g, '').trim()
    if (!stripped) return
    el.insertAdjacentHTML('beforeend',
        `<span data-index="${indexCounter++}" class="p3xr-console-content-output-item">${message}<br/></span>`)
    trimOutput()
    persistDebounced()
    scrollToBottom()
}

// --- Textarea auto-resize ---
function autoResize() {
    const el = inputEl.value
    if (!el) return
    if (!singleLineHeight) singleLineHeight = el.offsetHeight
    const focused = document.activeElement === el
    if (!focused && (el.value || '').includes('\n')) {
        el.style.height = singleLineHeight + 'px'
        el.style.overflowY = 'hidden'
        return
    }
    el.style.height = singleLineHeight + 'px'
    el.style.overflowY = 'hidden'
    if ((el.value || '').includes('\n') && el.scrollHeight > el.clientHeight) {
        const max = singleLineHeight * 3
        const border = el.offsetHeight - el.clientHeight
        const needed = el.scrollHeight + border
        if (needed > max) {
            el.style.height = max + 'px'
            el.style.overflowY = 'auto'
        } else {
            el.style.height = needed + 'px'
        }
    }
}

// --- History ---
let actionHistoryPosition = -1

function getHistory(): string[] {
    try { return JSON.parse(localStorage.getItem('console-history') || '[]') } catch { return [] }
}

function updateHistory(entry: string) {
    let h = getHistory()
    const idx = h.indexOf(entry)
    if (idx > -1) h.splice(idx, 1)
    h.unshift(entry)
    if (h.length > 20) h = h.slice(0, 20)
    try { localStorage.setItem('console-history', JSON.stringify(h)) } catch {}
    actionHistoryPosition = -1
}

// --- AI auto-detect ---
function looksLikeNaturalLanguage(input: string, errorMsg: string): boolean {
    if (!/unknown command|wrong number of arguments|ERR unknown/i.test(errorMsg)) return false
    const firstWord = input.trim().split(/\s+/)[0].toUpperCase()
    if (state.commands?.includes(firstWord)) return false
    return true
}

// --- AI query ---
async function executeAiQuery(prompt: string, originalInput: string): Promise<boolean> {
    if (!prompt) return false
    aiLoading.value = true
    try {
        const info = state.info || {}
        const server = info.server || {}
        const clients = info.clients || {}
        const memory = info.memory || {}
        const keyspace = info.keyspace || {}
        const modules = state.modules || []

        const ctx: any = {}
        if (server.redis_version) ctx.redisVersion = server.redis_version
        if (server.redis_mode) ctx.redisMode = server.redis_mode
        if (server.os) ctx.os = server.os
        if (clients.connected_clients) ctx.connectedClients = clients.connected_clients
        if (memory.used_memory_human) ctx.usedMemory = memory.used_memory_human
        const dbKeys = Object.keys(keyspace).filter((k: string) => /^db\d+$/.test(k))
        if (dbKeys.length > 0) ctx.databases = dbKeys.map((k: string) => `${k}: ${keyspace[k]}`)
        if (modules.length > 0) ctx.modules = modules
        ctx.uiLanguage = i18n.currentLang

        const response = await request({ action: 'ai/redis-query', payload: { prompt, context: ctx } })
        const command = response.command || ''
        const explanation = response.explanation || ''

        if (command) {
            let line = `<strong>&gt; <span style="color: rgb(var(--v-theme-primary));">AI &rarr;</span></strong> <code>${htmlEncode(command)}</code>`
            if (explanation) line += `<br/><span style="opacity: 0.7; font-size: 0.9em;">${htmlEncode(explanation)}</span>`
            outputAppend(line + '<br/>')
            searchText.value = command
            currentHint.value = ''
            aiCommandPending = true
            nextTick(() => autoResize())
        }
        return true
    } catch (e: any) {
        outputAppend(`<span style="color: rgb(var(--v-theme-error));">AI error: ${htmlEncode(e?.message || String(e))}</span>`)
        return false
    } finally {
        aiLoading.value = false
    }
}

// --- Command execution ---
async function executeCommand() {
    const enter = searchText.value.trim()
    if (!enter) return

    searchText.value = ''
    currentHint.value = ''
    autocompleteDismissed.value = true
    nextTick(() => autoResize())

    // AI prefix
    if (/^ai:\s*/i.test(enter)) {
        const prompt = enter.replace(/^ai:\s*/i, '').trim()
        outputAppend(`<strong>&gt; ${htmlEncode(enter)}</strong>`)
        updateHistory(enter)
        await executeAiQuery(prompt, enter)
        forceScrollToBottom()
        return
    }

    // AI command pending (user reviewing AI suggestion — execute it)
    if (aiCommandPending) {
        aiCommandPending = false
    }

    outputAppend(`<strong>&gt; ${htmlEncode(enter)}</strong>`)
    updateHistory(enter)

    try {
        const response = await request({
            action: 'redis/console',
            payload: { command: enter },
        })
        const result = htmlEncode(String(consoleParse(response.result)))
        outputAppend(`<pre>${result}</pre>`)

        // Refresh after write commands
        if (props.embedded) {
            cmd.refresh({ withoutParent: true })
        }
    } catch (e: any) {
        const errorMsg = e?.message || String(e)

        // AI auto-detect: try AI first, suppress error if AI succeeds
        if (aiEnabled.value && aiAutoDetect.value && looksLikeNaturalLanguage(enter, errorMsg)) {
            const aiSuccess = await executeAiQuery(enter, enter)
            if (aiSuccess) return
        }

        outputAppend(`<span style="color: rgb(var(--v-theme-error));">${htmlEncode(errorMsg)}</span>`)
    }

    forceScrollToBottom()
}

// --- Keyboard handling ---
function onKeyDown(e: KeyboardEvent) {
    // Tab: select autocomplete item into input
    if (e.key === 'Tab' && showAutocomplete.value) {
        e.preventDefault()
        const opt = flatOptions.value[autocompleteHighlight.value]
        if (opt) selectAutocomplete(opt.name)
        return
    }

    // Escape: dismiss autocomplete
    if (e.key === 'Escape') {
        autocompleteDismissed.value = true
        return
    }

    // Enter (no Shift):
    //   - If autocomplete open → fill input with selected item, close autocomplete, DON'T execute
    //   - If autocomplete closed → execute command
    if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault()
        if (showAutocomplete.value) {
            const opt = flatOptions.value[autocompleteHighlight.value]
            if (opt) selectAutocomplete(opt.name)
        } else {
            executeCommand()
        }
        return
    }

    // Arrow Up/Down without Shift: navigate autocomplete
    if (!e.shiftKey && (e.key === 'ArrowUp' || e.key === 'ArrowDown') && showAutocomplete.value) {
        e.preventDefault()
        const len = flatOptions.value.length
        if (!len) return
        autocompleteHighlight.value = e.key === 'ArrowDown'
            ? (autocompleteHighlight.value + 1) % len
            : (autocompleteHighlight.value - 1 + len) % len
        // Scroll highlighted item into view
        nextTick(() => {
            const dropdown = document.querySelector('.p3xr-console-autocomplete-dropdown')
            const highlighted = dropdown?.querySelector('.p3xr-console-ac-highlight')
            highlighted?.scrollIntoView({ block: 'nearest' })
        })
        return
    }

    // Shift+Arrow Up/Down: history navigation
    if (e.shiftKey && (e.key === 'ArrowUp' || e.key === 'ArrowDown')) {
        e.preventDefault()
        const history = getHistory()
        if (history.length === 0) return
        if (e.key === 'ArrowDown') {
            if (actionHistoryPosition === -1) actionHistoryPosition = history.length
            actionHistoryPosition--
            if (actionHistoryPosition < 0) actionHistoryPosition = history.length - 1
        } else {
            actionHistoryPosition++
            if (actionHistoryPosition >= history.length) actionHistoryPosition = 0
        }
        searchText.value = history[actionHistoryPosition] ?? ''
        nextTick(() => autoResize())
    }
}

// --- Input change watcher ---
watch(searchText, (value) => {
    autocompleteDismissed.value = false
    autocompleteHighlight.value = 0
    const firstWord = (value || '').trim().split(/\s+/)[0]?.toUpperCase()
    if (firstWord && state.commandsMeta?.[firstWord]?.syntax) {
        currentHint.value = firstWord + ' ' + state.commandsMeta[firstWord].syntax
    } else {
        currentHint.value = ''
    }
    nextTick(() => autoResize())
})

// --- Clear ---
function clearConsole() {
    const el = outputEl.value
    if (!el) return
    el.innerHTML = ''
    const welcome = strings.value?.label?.welcomeConsole ?? 'Welcome to the Redis Console'
    const info = strings.value?.label?.welcomeConsoleInfo ?? 'Shift + Cursor UP or DOWN for history'
    outputAppend(`<strong>${welcome}</strong>`)
    outputAppend(`${info}<br/>`)
    persistNow()
    forceScrollToBottom()
    inputEl.value?.focus()
}

function toggleAiAutoDetect() {
    aiAutoDetect.value = !aiAutoDetect.value
    try { localStorage.setItem('p3xr-ai-auto-detect', String(aiAutoDetect.value)) } catch {}
}

function openCommands() {
    window.open('https://redis.io/commands', '_blank')
}

// --- Focus/blur for auto-resize ---
function onInputFocus() { nextTick(() => autoResize()) }
function onInputBlur() { nextTick(() => autoResize()) }
function onInputPaste() { nextTick(() => autoResize()) }

// --- Init ---
onMounted(() => {
    const el = outputEl.value
    if (!el) return
    let stored = ''
    try { stored = localStorage.getItem(CONSOLE_OUTPUT_KEY) || '' } catch {}
    if (stored) {
        el.innerHTML = stored
        trimOutput()
        persistNow()
        const items = el.querySelectorAll('.p3xr-console-content-output-item')
        const last = items.length > 0 ? items[items.length - 1] : null
        if (last) {
            const idx = Number(last.getAttribute('data-index'))
            if (Number.isFinite(idx)) indexCounter = idx + 1
        }
        forceScrollToBottom()
    } else {
        el.innerHTML = ''
        const welcome = strings.value?.label?.welcomeConsole ?? 'Welcome to the Redis Console'
        const info = strings.value?.label?.welcomeConsoleInfo ?? 'Shift + Cursor UP or DOWN for history'
        outputAppend(`<strong>${welcome}</strong>`)
        outputAppend(`${info}<br/>`)
        persistNow()
    }
})
</script>

<template>
    <div class="p3xr-console-root" :class="{ 'p3xr-console-embedded': embedded }">
        <!-- Header toolbar -->
        <div class="p3xr-console-header" :style="{ backgroundColor: toolbarBg }">
            <div class="p3xr-console-header-inner">
                <v-icon size="20" style="margin-right: 6px; color: inherit;">mdi-console</v-icon>
                <span class="p3xr-console-title">{{ strings?.label?.console || 'Console' }}</span>
                <span style="flex: 1 1 auto;" />
                <div class="p3xr-console-toolbar-actions">
                    <!-- AI auto-detect toggle -->
                    <div v-if="aiEnabled" class="p3xr-console-ai-toggle" @click.stop="toggleAiAutoDetect()">
                        <v-icon size="20">{{ aiAutoDetect ? 'mdi-checkbox-marked' : 'mdi-checkbox-blank-outline' }}</v-icon>
                        <span>Auto AI</span>
                    </div>
                    <!-- Redis Commands -->
                    <P3xrButton
                        @click="openCommands(); $event.stopPropagation()"
                        :label="strings?.label?.redisCommandsReference || 'Redis Commands'"
                        icon="mdi-book-open-page-variant"
                    />
                    <!-- Clear -->
                    <P3xrButton
                        @click="clearConsole(); $event.stopPropagation()"
                        :label="strings?.intention?.clear || 'Clear'"
                        icon="mdi-backspace"
                    />
                </div>
            </div>
        </div>

        <!-- Output area -->
        <div v-show="!collapsed" ref="scrollerEl" class="p3xr-console-output-scroller">
            <div ref="outputEl" class="p3xr-console-output"></div>
        </div>

        <!-- Input area with floating autocomplete above -->
        <div class="p3xr-console-input-area">
            <!-- Autocomplete dropdown (floats above input) -->
            <div v-if="showAutocomplete && !collapsed" class="p3xr-console-autocomplete-dropdown">
                <template v-for="(group, gi) in filteredCommands" :key="gi">
                    <div class="p3xr-console-ac-group">{{ group.group }}</div>
                    <div
                        v-for="opt in group.commands"
                        :key="opt.name"
                        class="p3xr-console-ac-item"
                        :class="{ 'p3xr-console-ac-highlight': flatOptions.indexOf(opt) === autocompleteHighlight }"
                        @mousedown.prevent="selectAutocomplete(opt.name)"
                    >
                        <span class="p3xr-console-ac-cmd">{{ opt.name }}</span>
                        <span v-if="opt.syntax" class="p3xr-console-ac-syntax">{{ opt.syntax }}</span>
                    </div>
                </template>
            </div>
            <div v-if="currentHint && !collapsed" class="p3xr-console-hint">{{ currentHint }}</div>
            <textarea
                ref="inputEl"
                v-model="searchText"
                class="p3xr-console-input"
                :placeholder="aiLoading ? (strings?.label?.aiTranslating || 'Translating...') : ''"
                rows="1"
                autocomplete="off"
                :style="{
                    backgroundColor: inputBg,
                    color: inputColor,
                    borderColor: aiLoading ? 'rgb(var(--v-theme-primary))' : inputBorder,
                }"
                @keydown="onKeyDown"
                @focus="onInputFocus"
                @blur="onInputBlur"
                @paste="onInputPaste"
            />
        </div>
    </div>
</template>

<style scoped>
.p3xr-console-root {
    display: flex;
    flex-direction: column;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

.p3xr-console-header {
    height: 48px;
    min-height: 48px;
    max-height: 48px;
    flex-shrink: 0;
    z-index: 2;
    color: rgba(255,255,255,0.87);
}

.p3xr-console-header-inner {
    display: flex;
    align-items: center;
    width: 100%;
    height: 48px;
    padding: 0 3px;
    box-sizing: border-box;
}

.p3xr-console-title {
    font-size: 20px;
    font-weight: 500;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.p3xr-console-toolbar-actions {
    display: inline-flex;
    align-items: center;
    flex-shrink: 0;
    white-space: nowrap;
}

.p3xr-console-ai-toggle {
    display: inline-flex;
    align-items: center;
    gap: 2px;
    cursor: pointer;
    margin: 0 8px;
    padding: 0 8px;
    height: 36px;
    font-size: 13px;
    letter-spacing: 0.1px;
    text-transform: uppercase;
    border-radius: 4px;
    color: inherit;
    user-select: none;
    white-space: nowrap;
    flex-shrink: 0;
}
.p3xr-console-ai-toggle:hover {
    background-color: rgba(255,255,255,0.15);
}

.p3xr-console-output-scroller {
    flex: 1 1 auto;
    min-height: 0;
    overflow-y: auto;
    overflow-x: hidden;
    font-family: 'Roboto Mono', monospace;
    text-align: center;
}

.p3xr-console-output {
    text-align: left;
    overflow: auto;
    flex-grow: 1;
    min-width: calc(100% - 20px);
    font-family: 'Roboto Mono', monospace;
    font-size: 13px;
    word-break: break-all;
    white-space: pre-wrap;
}

/* Autocomplete dropdown — floats above input like Angular mat-autocomplete position="above" */
.p3xr-console-autocomplete-dropdown {
    position: absolute;
    bottom: 100%;
    left: 0;
    right: 0;
    max-height: 350px;
    overflow-y: auto;
    font-family: 'Roboto Mono', monospace;
    font-size: 13px;
    background-color: rgb(var(--v-theme-surface));
    border: 1px solid rgba(var(--v-border-color), 0.12);
    border-radius: 4px 4px 0 0;
    box-shadow: 0 -4px 8px rgba(0,0,0,0.2);
    z-index: 10;
}

.p3xr-console-ac-group {
    padding: 4px 12px 2px;
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    opacity: 0.5;
}

.p3xr-console-ac-item {
    padding: 4px 12px;
    cursor: pointer;
    display: flex;
    gap: 8px;
    align-items: baseline;
}
.p3xr-console-ac-item:hover,
.p3xr-console-ac-highlight {
    background-color: rgba(var(--v-theme-on-surface), 0.08);
}

.p3xr-console-ac-cmd {
    font-weight: bold;
    margin-right: 8px;
}

.p3xr-console-ac-syntax {
    opacity: 0.5;
    font-size: 11px;
}

/* Input area — matches Angular #p3xr-console-autocomplete */
.p3xr-console-input-area {
    position: relative;
    width: 100%;
    flex-shrink: 0;
}

.p3xr-console-input-area .p3xr-console-input {
    width: 100%;
    min-width: 0;
}

.p3xr-console-hint {
    font-family: 'Roboto Mono', monospace;
    font-size: 12px;
    opacity: 0.4;
    padding: 0 6px 2px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.p3xr-console-input {
    display: block;
    width: 100%;
    font-family: 'Roboto Mono', monospace;
    font-size: 14px;
    border-style: solid;
    border-width: 3px;
    padding: 3px;
    margin: 0;
    outline: none;
    resize: none;
    overflow-y: hidden;
    max-height: 90px;
    box-sizing: border-box;
}
</style>

<style>
/* Console toolbar buttons: exact match of Angular/React */
.p3xr-console-header .v-btn {
    color: inherit !important;
    letter-spacing: 0.1px !important;
    text-transform: uppercase !important;
    height: 36px !important;
    min-height: 36px !important;
    min-width: auto !important;
    padding: 0 8px !important;
    margin: 0 8px !important;
    display: inline-flex !important;
    align-items: center !important;
}
.p3xr-console-header .v-btn .v-btn__content {
    gap: 2px;
}
.p3xr-console-header .v-btn .v-icon {
    color: inherit !important;
}
.p3xr-console-header .v-btn .v-btn__overlay {
    opacity: 0 !important;
}
.p3xr-console-header .v-btn:hover .v-btn__overlay {
    opacity: 0 !important;
}
.p3xr-console-header .v-btn:hover {
    background-color: rgba(255,255,255,0.15) !important;
}

/* Output pre elements */
.p3xr-console-output pre {
    font-family: 'Roboto Mono', monospace;
    white-space: pre-wrap;
    word-break: break-word;
    overflow-wrap: anywhere;
    margin: 0;
}
</style>
