// src/react/pages/database/DatabaseTreeControls.tsx
import { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import { Box, Tooltip, Menu, MenuItem, Divider, IconButton, useTheme } from '@mui/material'
import {
    KeyboardArrowDown, KeyboardArrowUp, Refresh, Settings,
    ArrowDropDown, SkipPrevious, KeyboardArrowLeft, KeyboardArrowRight,
    SkipNext, Search, Clear, Add, MoreVert, FileDownload, FileUpload, DeleteSweep,
} from '@mui/icons-material'
import { useI18nStore } from '../../stores/i18n.store'
import { useRedisStateStore, getPages, getFilteredKeys } from '../../stores/redis-state.store'
import { useSettingsStore } from '../../stores/settings.store'
import { useCommonStore, emitTreeEvent } from '../../stores/common.store'
import { useMainCommandStore } from '../../stores/main-command.store'
import { request } from '../../stores/socket.service'
import { useOverlayStore } from '../../stores/overlay.store'
import TreeSettingsDialog from '../../dialogs/TreeSettingsDialog'
import KeyImportDialog from '../../dialogs/KeyImportDialog'

// Icon button styles — will be set per-instance using theme colors
const iconBtnBase = {
    p: 0, width: 24, height: 24, minWidth: 24, minHeight: 24,
    borderRadius: '50%',
}

export default function DatabaseTreeControls() {
    const strings = useI18nStore(s => s.strings)
    const keysRaw = useRedisStateStore(s => s.keysRaw)
    const search = useRedisStateStore(s => s.search)
    const page = useRedisStateStore(s => s.page)
    const cfg = useRedisStateStore(s => s.cfg)
    const connection = useRedisStateStore(s => s.connection)
    const redisTreeDivider = useSettingsStore(s => s.redisTreeDivider)
    const searchClientSide = useSettingsStore(s => s.searchClientSide)
    const pageCount = useSettingsStore(s => s.pageCount)
    const { toast, generalHandleError } = useCommonStore()
    const { refresh, addKey: cmdAddKey } = useMainCommandStore()
    const overlay = useOverlayStore()
    const muiTheme = useTheme()

    const iconBtnSx = { ...iconBtnBase, color: muiTheme.p3xr.treecontrolIconColor }
    const primaryIconBtnSx = { ...iconBtnBase, color: muiTheme.palette.primary.main }

    // p3xr-input base style
    const inputBase: React.CSSProperties = {
        boxSizing: 'border-box',
        borderStyle: 'solid',
        borderWidth: 2,
        margin: 1,
        borderColor: muiTheme.p3xr.inputBorderColor,
        background: muiTheme.p3xr.inputBg,
        color: muiTheme.p3xr.inputColor,
        outline: 'none',
        fontFamily: "'Roboto Mono', monospace",
        fontSize: 12,
    }
    // Compact: pager + divider (no padding)
    const inputCompact: React.CSSProperties = { ...inputBase, padding: 0 }
    // Normal: search (with padding)
    const inputStyle: React.CSSProperties = { ...inputBase, padding: 3 }

    const isReadonly = connection?.readonly === true
    const keyCount = Array.isArray(keysRaw) ? keysRaw.length : 0
    const treeDividers: string[] = Array.isArray(cfg?.treeDividers) ? cfg.treeDividers : []
    const pages = getPages()

    const [localSearch, setLocalSearch] = useState(search || '')
    const [localDivider, setLocalDivider] = useState(redisTreeDivider || ':')
    const [localPage, setLocalPage] = useState(page || 1)
    const dividerTimerRef = useRef<any>(null)

    // Sync from store
    useEffect(() => { setLocalSearch(search || '') }, [search])
    useEffect(() => { setLocalDivider(redisTreeDivider || ':') }, [redisTreeDivider])
    useEffect(() => { setLocalPage(page || 1) }, [page])

    // --- Expand menu ---
    const [expandAnchor, setExpandAnchor] = useState<null | HTMLElement>(null)

    // --- Divider menu ---
    const [dividerAnchor, setDividerAnchor] = useState<null | HTMLElement>(null)

    // --- Actions menu ---
    const [actionsAnchor, setActionsAnchor] = useState<null | HTMLElement>(null)

    // --- Tree settings dialog ---
    const [treeSettingsOpen, setTreeSettingsOpen] = useState(false)

    // --- Import dialog ---
    const [importDialogOpen, setImportDialogOpen] = useState(false)
    const [importDialogData, setImportDialogData] = useState<any>(null)

    // --- Key count text ---
    const keyCountText = useMemo(() => {
        const fn = strings?.status?.keyCount
        return typeof fn === 'function' ? fn({ keyCount }) : String(keyCount)
    }, [strings, keyCount])

    // --- Search ---
    const searchPlaceholder = useMemo(() => {
        const s = strings?.page?.treeControls?.search
        return searchClientSide
            ? (s?.placeholderClient || 'Search keys')
            : (s?.placeholderServer || 'Search keys on server')
    }, [strings, searchClientSide])

    const onSearchChange = useCallback(async () => {
        useRedisStateStore.setState({ search: localSearch, page: 1 })
        if (searchClientSide) useRedisStateStore.setState({ redisChanged: true })
        await refresh()
    }, [localSearch, searchClientSide, refresh])

    const clearSearch = useCallback(async () => {
        setLocalSearch('')
        useRedisStateStore.setState({ search: '', page: 1 })
        if (searchClientSide) useRedisStateStore.setState({ redisChanged: true })
        await refresh()
    }, [searchClientSide, refresh])

    // --- Divider ---
    const onDividerInputChange = useCallback((value: string) => {
        setLocalDivider(value)
        useSettingsStore.getState().setSetting('p3xr-main-treecontrol-divider', value)
        clearTimeout(dividerTimerRef.current)
        dividerTimerRef.current = setTimeout(() => {
            useRedisStateStore.setState({ redisChanged: true })
        }, 666)
    }, [])

    const setDivider = useCallback((value: string) => {
        setLocalDivider(value)
        useSettingsStore.getState().setSetting('p3xr-main-treecontrol-divider', value)
        useRedisStateStore.setState({ redisChanged: true })
        setDividerAnchor(null)
    }, [])

    // --- Pagination ---
    const pageAction = useCallback((action: 'first' | 'prev' | 'next' | 'last') => {
        const currentPage = useRedisStateStore.getState().page ?? 1
        const totalPages = getPages()
        let newPage = currentPage
        switch (action) {
            case 'first': newPage = 1; break
            case 'prev': newPage = Math.max(1, currentPage - 1); break
            case 'next': newPage = Math.min(totalPages, currentPage + 1); break
            case 'last': newPage = totalPages; break
        }
        setLocalPage(newPage)
        useRedisStateStore.setState({ page: newPage, redisChanged: true })
    }, [])

    const onPageInputChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const parsed = parseInt(e.target.value, 10)
        const totalPages = getPages()
        const clamped = isNaN(parsed) ? 1 : Math.max(1, Math.min(totalPages, parsed))
        setLocalPage(clamped)
        useRedisStateStore.setState({ page: clamped, redisChanged: true })
    }, [])

    // --- Expand/Collapse ---
    const treeExpandToLevel = useCallback((level: number) => {
        setExpandAnchor(null)
        setTimeout(() => emitTreeEvent('expand-level-' + level))
    }, [])

    const treeExpandAll = useCallback(() => {
        emitTreeEvent('expand-all')
        setExpandAnchor(null)
    }, [])

    const treeCollapseAll = useCallback(() => {
        emitTreeEvent('collapse-all')
    }, [])

    // --- Export ---
    const exportKeys = useCallback(async () => {
        setActionsAnchor(null)
        if (!Array.isArray(keysRaw) || keysRaw.length === 0) {
            toast(strings?.label?.noKeysToExport)
            return
        }
        try {
            overlay.show({ message: strings?.label?.exportProgress })
            const response = await request({ action: 'key/export', payload: { keys: keysRaw } })
            const json = JSON.stringify(response.data, null, 2)
            const blob = new Blob([json], { type: 'application/json' })
            const url = URL.createObjectURL(blob)
            const a = document.createElement('a')
            a.href = url
            const connName = connection?.name || 'redis'
            const db = useRedisStateStore.getState().currentDatabase ?? 0
            a.download = `${connName}-db${db}-export.json`
            a.click()
            URL.revokeObjectURL(url)
            toast(strings?.status?.exportDone)
        } catch (e) {
            generalHandleError(e)
        } finally {
            overlay.hide()
        }
    }, [keysRaw, connection, strings, toast, generalHandleError, overlay])

    // --- Import ---
    const importKeys = useCallback(() => {
        setActionsAnchor(null)
        const input = document.createElement('input')
        input.type = 'file'
        input.accept = '.json'
        input.onchange = () => {
            const file = input.files?.[0]
            if (!file) return
            const reader = new FileReader()
            reader.onload = (e: any) => {
                try {
                    const parsed = JSON.parse(e.target.result)
                    if (!parsed?.keys || !Array.isArray(parsed.keys) || parsed.keys.length === 0) {
                        toast(strings?.label?.importNoKeys)
                        return
                    }
                    setImportDialogData(parsed)
                    setImportDialogOpen(true)
                } catch (err: any) {
                    if (err !== undefined && err !== null) generalHandleError(err)
                }
            }
            reader.readAsText(file)
        }
        input.click()
    }, [strings, toast, generalHandleError])

    const handleImportDialogClose = useCallback(async (result: any) => {
        setImportDialogOpen(false)
        setImportDialogData(null)
        if (!result?.pending) return
        try {
            overlay.show({ message: strings?.label?.importProgress })
            const response = await request({
                action: 'key/import',
                payload: { keys: result.keys, conflictMode: result.conflictMode },
            })
            const data = response.data
            const statusFn = strings?.status?.importDone
            const message = typeof statusFn === 'function'
                ? statusFn(data)
                : `Import complete: ${data.created} created, ${data.skipped} skipped, ${data.errors} errors`
            toast(message)
            await refresh()
        } catch (e: any) {
            if (e !== undefined && e !== null) generalHandleError(e)
        } finally {
            overlay.hide()
        }
    }, [strings, toast, refresh, generalHandleError, overlay])

    // --- Delete search keys ---
    const deleteSearchLabel = useMemo(() => {
        if (localSearch.length > 0) {
            const fn = strings?.intention?.deleteSearchKeys
            return typeof fn === 'function' ? fn({ count: keyCount }) : `Delete ${keyCount} matching keys`
        }
        const fn = strings?.intention?.deleteAllKeysMenu
        return typeof fn === 'function' ? fn({ count: keyCount }) : `Delete all ${keyCount} keys`
    }, [strings, localSearch, keyCount])

    const exportLabel = useMemo(() => {
        if (localSearch.length > 0) {
            const fn = strings?.intention?.exportSearchResults
            return typeof fn === 'function' ? fn({ count: keyCount }) : `Export ${keyCount} results`
        }
        const fn = strings?.intention?.exportAllKeys
        return typeof fn === 'function' ? fn({ count: keyCount }) : `Export all ${keyCount} keys`
    }, [strings, localSearch, keyCount])

    const deleteSearchKeys = useCallback(async () => {
        setActionsAnchor(null)
        const searchStartsWith = useSettingsStore.getState().searchStartsWith
        let match: string
        if (localSearch.length > 0) {
            match = searchStartsWith ? localSearch + '*' : '*' + localSearch + '*'
        } else {
            match = '*'
        }
        try {
            const confirmFn = strings?.confirm?.deleteSearchKeys
            const confirmMsg = typeof confirmFn === 'function'
                ? confirmFn({ count: keyCount, pattern: match })
                : `Are you sure to delete all keys matching "${match}"? Found ${keyCount} keys.`
            await useCommonStore.getState().confirm({ message: confirmMsg })
            overlay.show({ message: strings?.label?.deletingSearchKeys })
            const response = await request({ action: 'key/delete-search-keys', payload: { match } })
            const deletedCount = response.deletedCount || 0
            const statusFn = strings?.status?.deletedSearchKeys
            const message = typeof statusFn === 'function'
                ? statusFn({ count: deletedCount })
                : `Deleted ${deletedCount} keys`
            toast(message)
            await refresh()
        } catch (e: any) {
            if (e !== undefined && e !== null) generalHandleError(e)
        } finally {
            overlay.hide()
        }
    }, [localSearch, keyCount, strings, toast, refresh, generalHandleError, overlay])

    return (
        <Box sx={{ minHeight: 24 }}>
            {/* Leading row: controls + pager, single line */}
            <Box sx={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', minHeight: 31 }}>
                <Tooltip title={strings?.intention?.extend} placement="top" enterDelay={300}>
                    <IconButton size="small" sx={primaryIconBtnSx} onClick={e => setExpandAnchor(e.currentTarget)}>
                        <KeyboardArrowDown fontSize="small" />
                    </IconButton>
                </Tooltip>
                <Menu anchorEl={expandAnchor} open={!!expandAnchor} onClose={() => setExpandAnchor(null)}>
                    {[1,2,3,4,5].map(n => (
                        <MenuItem key={n} onClick={() => treeExpandToLevel(n)}>
                            {strings?.page?.treeControls?.level} {n}
                        </MenuItem>
                    ))}
                    <Divider />
                    <MenuItem onClick={treeExpandAll}>{strings?.page?.treeControls?.expandAll}</MenuItem>
                </Menu>

                <Tooltip title={strings?.page?.treeControls?.collapseAll} placement="top" enterDelay={300}>
                    <IconButton size="small" sx={iconBtnSx} onClick={treeCollapseAll}>
                        <KeyboardArrowUp fontSize="small" />
                    </IconButton>
                </Tooltip>

                <Tooltip title={strings?.intention?.refresh} placement="top" enterDelay={300}>
                    <IconButton size="small" sx={iconBtnSx} onClick={() => refresh()}>
                        <Refresh fontSize="small" />
                    </IconButton>
                </Tooltip>

                <Tooltip title={strings?.form?.treeSettings?.label?.formName} placement="top" enterDelay={300}>
                    <IconButton size="small" sx={iconBtnSx} onClick={() => setTreeSettingsOpen(true)}>
                        <Settings fontSize="small" />
                    </IconButton>
                </Tooltip>
                <TreeSettingsDialog open={treeSettingsOpen} onClose={() => setTreeSettingsOpen(false)} />
                <KeyImportDialog open={importDialogOpen} data={importDialogData} onClose={handleImportDialogClose} />

                {/* Divider input */}
                <Tooltip title={strings?.form?.treeSettings?.field?.treeSeparator} placement="top" enterDelay={300}>
                    <input
                        value={localDivider}
                        onChange={e => onDividerInputChange(e.target.value)}
                        style={{
                            ...inputCompact,
                            width: 23, fontFamily: "'Roboto Mono', monospace", fontSize: 14,
                            fontWeight: 500, textAlign: 'center', verticalAlign: 'middle',
                        }}
                    />
                </Tooltip>

                {treeDividers.length > 0 && (
                    <>
                        <Tooltip title={strings?.form?.treeSettings?.field?.treeSeparatorSelector} placement="top" enterDelay={300}>
                            <IconButton size="small" sx={{ ...iconBtnSx, width: 14 }} onClick={e => setDividerAnchor(e.currentTarget)}>
                                <ArrowDropDown sx={{ fontSize: 18 }} />
                            </IconButton>
                        </Tooltip>
                        <Menu anchorEl={dividerAnchor} open={!!dividerAnchor} onClose={() => setDividerAnchor(null)}
                            slotProps={{ paper: { sx: {
                                minWidth: '20px !important', maxWidth: '40px !important',
                                transform: 'translateX(-23px) !important',
                                marginTop: '4px',
                            } }, list: { sx: { p: 0 } } }}>
                            {treeDividers.map(d => (
                                <MenuItem key={d} onClick={() => setDivider(d)}
                                    sx={{
                                        minHeight: 28, height: 28, p: '0 !important', minWidth: 0,
                                        textAlign: 'center', justifyContent: 'center',
                                        fontFamily: "'Roboto Mono', monospace", fontWeight: 500, fontSize: 14,
                                    }}>
                                    {d === '' ? '(empty)' : d}
                                </MenuItem>
                            ))}
                        </Menu>
                    </>
                )}

                {/* Pager or key count — same flex row */}
                {pages > 1 ? (
                    <Tooltip title={keyCountText} placement="top" enterDelay={300}>
                    <Box component="span" sx={{
                        display: 'inline-flex', alignItems: 'center',
                        whiteSpace: 'nowrap', ml: '2px',
                    }}>
                    <Tooltip title={strings?.page?.treeControls?.pager?.first} enterDelay={300}>
                        <IconButton size="small" sx={primaryIconBtnSx} onClick={() => pageAction('first')}>
                            <SkipPrevious sx={{ fontSize: 18 }} />
                        </IconButton>
                    </Tooltip>
                    <Tooltip title={strings?.page?.treeControls?.pager?.prev} enterDelay={300}>
                        <IconButton size="small" sx={iconBtnSx} onClick={() => pageAction('prev')}>
                            <KeyboardArrowLeft sx={{ fontSize: 18 }} />
                        </IconButton>
                    </Tooltip>
                    <input
                        type="number" step={1} min={1} max={pages} value={localPage}
                        onChange={onPageInputChange}
                        className="p3xr-pager-input"
                        style={{
                            ...inputCompact,
                            width: 32,
                            height: 20,
                            textAlign: 'center',
                            MozAppearance: 'textfield',
                        }}
                    /><span style={{ fontSize: 12, fontFamily: "'Roboto Mono', monospace" }}>/ {pages}</span>
                    <Tooltip title={strings?.page?.treeControls?.pager?.next} enterDelay={300}>
                        <IconButton size="small" sx={iconBtnSx} onClick={() => pageAction('next')}>
                            <KeyboardArrowRight sx={{ fontSize: 18 }} />
                        </IconButton>
                    </Tooltip>
                    <Tooltip title={strings?.page?.treeControls?.pager?.last} enterDelay={300}>
                        <IconButton size="small" sx={primaryIconBtnSx} onClick={() => pageAction('last')}>
                            <SkipNext sx={{ fontSize: 18 }} />
                        </IconButton>
                    </Tooltip>
                </Box>
                </Tooltip>
                ) : (
                    <Box component="span" sx={{ ml: 'auto', opacity: 0.5, fontSize: 12 }}>
                        {keyCountText}&nbsp;
                    </Box>
                )}
            </Box>

            {/* Search row */}
            <Box sx={{ clear: 'both', p: '5px', textAlign: 'left', lineHeight: '24px', display: 'flex', alignItems: 'center', gap: 0.5 }}>
                <input
                    placeholder={searchPlaceholder}
                    value={localSearch}
                    onChange={e => setLocalSearch(e.target.value)}
                    onKeyDown={e => { if (e.key === 'Enter') onSearchChange() }}
                    style={{
                        ...inputStyle,
                        flex: 1, minWidth: 0,
                        verticalAlign: 'middle',
                    }}
                />

                <Tooltip title={strings?.page?.treeControls?.search?.search} placement="top" enterDelay={300}>
                    <IconButton size="small" sx={primaryIconBtnSx} onClick={onSearchChange}>
                        <Search fontSize="small" />
                    </IconButton>
                </Tooltip>

                {localSearch.length > 0 && (
                    <Tooltip title={strings?.page?.treeControls?.search?.clear} placement="top" enterDelay={300}>
                        <IconButton size="small" sx={primaryIconBtnSx} onClick={clearSearch}>
                            <Clear fontSize="small" />
                        </IconButton>
                    </Tooltip>
                )}

                {!isReadonly && (
                    <Tooltip title={strings?.intention?.addKeyRoot} placement="top" enterDelay={300}>
                        <Add
                            onClick={e => cmdAddKey({ event: e.nativeEvent })}
                            sx={{ fontSize: 24, cursor: 'pointer', color: muiTheme.p3xr.commonWarnColor }}
                        />
                    </Tooltip>
                )}

                <IconButton size="small" sx={iconBtnSx} onClick={e => setActionsAnchor(e.currentTarget)}>
                    <MoreVert fontSize="small" />
                </IconButton>

                <Menu anchorEl={actionsAnchor} open={!!actionsAnchor} onClose={() => setActionsAnchor(null)}>
                    <MenuItem onClick={exportKeys}>
                        <FileDownload sx={{ mr: 1 }} fontSize="small" />
                        {exportLabel}
                    </MenuItem>
                    {localSearch.length > 0 && (
                        <Box sx={{ px: 2, pb: 1, fontSize: 11, opacity: 0.5, fontStyle: 'italic', pointerEvents: 'none', lineHeight: 1.3 }}>
                            {strings?.label?.exportSearchHint}
                        </Box>
                    )}
                    {!isReadonly && (
                        <MenuItem onClick={importKeys}>
                            <FileUpload sx={{ mr: 1 }} fontSize="small" />
                            {strings?.intention?.importKeys}
                        </MenuItem>
                    )}
                    {!isReadonly && localSearch.length > 0 && (
                        <Box sx={{ px: 2, pb: 1, fontSize: 11, opacity: 0.5, fontStyle: 'italic', pointerEvents: 'none', lineHeight: 1.3 }}>
                            {strings?.label?.importSearchHint}
                        </Box>
                    )}
                    {!isReadonly && <Divider />}
                    {!isReadonly && (
                        <MenuItem onClick={deleteSearchKeys}>
                            <DeleteSweep sx={{ mr: 1 }} fontSize="small" />
                            {deleteSearchLabel}
                        </MenuItem>
                    )}
                    {!isReadonly && localSearch.length > 0 && (
                        <Box sx={{ px: 2, pb: 1, fontSize: 11, opacity: 0.5, fontStyle: 'italic', pointerEvents: 'none', lineHeight: 1.3 }}>
                            {strings?.label?.deleteSearchHint}
                        </Box>
                    )}
                </Menu>
            </Box>
        </Box>
    )
}

// src/vue/pages/database/DatabaseTreeControls.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { storeToRefs } from 'pinia'
import TreeSettingsDialog from '../../dialogs/TreeSettingsDialog.vue'
import KeyImportDialog from '../../dialogs/KeyImportDialog.vue'
import { useI18nStore } from '../../stores/i18n'
import { useRedisStateStore } from '../../stores/redis-state'
import { useSettingsStore } from '../../stores/settings'
import { useCommonStore } from '../../stores/common'
import { useMainCommandStore, emitCommand } from '../../stores/main-command'
import { useOverlayStore } from '../../stores/overlay'
import { useThemeStore } from '../../stores/theme'
import { request } from '../../stores/socket.service'

const i18n = useI18nStore()
const state = useRedisStateStore()
const settings = useSettingsStore()
const common = useCommonStore()
const cmd = useMainCommandStore()
const overlay = useOverlayStore()
const { themeKey } = storeToRefs(useThemeStore())

const strings = computed(() => i18n.strings)
const isReadonly = computed(() => state.connection?.readonly === true)
const pages = computed(() => state.pages)

// Local state synced from store
const localSearch = ref(state.search || '')
const localDivider = ref(settings.redisTreeDivider || ':')
const localPage = ref(state.page || 1)

watch(() => state.search, (v) => { localSearch.value = v || '' })
watch(() => settings.redisTreeDivider, (v) => { localDivider.value = v || ':' })
watch(() => state.page, (v) => { localPage.value = v || 1 })

// Menus & dialogs
const expandMenuOpen = ref(false)
const dividerMenuOpen = ref(false)
const moreMenuOpen = ref(false)
const treeSettingsOpen = ref(false)
const importDialogOpen = ref(false)
const importDialogData = ref<{ keys: any[] } | null>(null)

// Theme colors (exact from React themes/index.ts)
const TREECONTROL_ICON_COLOR: Record<string, string> = {
    enterprise: 'rgba(0,0,0,0.87)', light: 'rgba(0,0,0,0.87)', redis: 'rgba(0,0,0,0.87)',
    dark: 'rgba(255,255,255,0.7)', darkNeu: 'rgba(255,255,255,0.7)', darkoBluo: 'rgba(255,255,255,0.7)',
    matrix: 'rgba(255,255,255,0.7)',
}
const INPUT_BG: Record<string, string> = {
    enterprise: 'white', light: 'white', redis: 'white',
    dark: 'rgba(64,64,64,1)', darkNeu: 'rgba(64,64,64,1)', darkoBluo: 'rgba(64,64,64,1)',
    matrix: 'rgba(64,64,64,1)',
}
const INPUT_COLOR: Record<string, string> = {
    enterprise: 'black', light: 'black', redis: 'black',
    dark: 'white', darkNeu: 'white', darkoBluo: 'white',
    matrix: 'white',
}
const INPUT_BORDER: Record<string, string> = {
    enterprise: '#9e9e9e', light: '#b0bec5', redis: '#ef9a9a',
    dark: '#9e9e9e', darkNeu: '#90a4ae', darkoBluo: '#3f51b5',
    matrix: '#76ff03',
}
const COMMON_WARN: Record<string, string> = {
    enterprise: '#03a9f4', light: '#607d8b', redis: '#f44336',
    dark: '#9fa8da', darkNeu: '#2196f3', darkoBluo: '#03a9f4',
    matrix: '#4caf50',
}

const iconColor = computed(() => TREECONTROL_ICON_COLOR[themeKey.value] || 'rgba(255,255,255,0.7)')
const inputBg = computed(() => INPUT_BG[themeKey.value] || 'rgba(64,64,64,1)')
const inputColor = computed(() => INPUT_COLOR[themeKey.value] || 'white')
const inputBorder = computed(() => INPUT_BORDER[themeKey.value] || '#9e9e9e')
const warnColor = computed(() => COMMON_WARN[themeKey.value] || '#9fa8da')

const treeDividers = computed(() => state.cfg?.treeDividers || [':', '/', '-', '.', '_', '|'])

// Helper: resolve translation strings that may be functions
function str(val: any, opts?: any): string {
    if (typeof val === 'function') return val(opts)
    return val || ''
}

const hasSearch = computed(() => localSearch.value.length > 0)
const keyCount = computed(() => state.keysRaw?.length ?? 0)

const exportLabel = computed(() => {
    if (hasSearch.value) {
        return str(strings.value?.intention?.exportSearchResults, { count: keyCount.value }) || `Export ${keyCount.value} results`
    }
    return str(strings.value?.intention?.exportAllKeys, { count: keyCount.value }) || `Export ${keyCount.value} keys`
})

const deleteSearchLabel = computed(() => {
    return str(strings.value?.intention?.deleteMatchingKeys, { count: keyCount.value }) || `Delete ${keyCount.value} matching keys`
})

const keyCountLabel = computed(() => {
    const fn = strings.value?.label?.keysCount
    const count = state.keysRaw?.length ?? 0
    return typeof fn === 'function' ? fn({ count }) : `${count} keys`
})

// --- Search ---
function onSearchSubmit() {
    state.search = localSearch.value
    state.page = 1
    cmd.refresh({ force: true })
}

function clearSearch() {
    localSearch.value = ''
    state.search = ''
    state.page = 1
    cmd.refresh({ force: true })
}

// --- Pagination ---
function pagerAction(action: string) {
    const p = pages.value
    if (p <= 1) return
    let newPage = localPage.value
    if (action === 'first') newPage = 1
    else if (action === 'prev') newPage = Math.max(1, newPage - 1)
    else if (action === 'next') newPage = Math.min(p, newPage + 1)
    else if (action === 'last') newPage = p
    localPage.value = newPage
    state.page = newPage
}

function onPageChange() {
    let p = localPage.value
    if (p < 1) p = 1
    if (p > pages.value) p = pages.value
    localPage.value = p
    state.page = p
}

// --- Divider ---
let dividerTimer: any = null
function onDividerChange() {
    clearTimeout(dividerTimer)
    dividerTimer = setTimeout(() => {
        settings.setSetting('p3xr-main-treecontrol-divider', localDivider.value)
    }, 666)
}

function setDividerQuick(d: string) {
    localDivider.value = d
    settings.setSetting('p3xr-main-treecontrol-divider', d)
    dividerMenuOpen.value = false
}

// --- Expand/Collapse ---
function expandAll() { emitCommand('expand-all'); expandMenuOpen.value = false }
function collapseAll() { emitCommand('collapse-all') }
function expandToLevel(level: number) { emitCommand(`expand-level-${level}`); expandMenuOpen.value = false }

// --- Add key ---
function cmdAddKey(e: Event) { cmd.addKey({ event: e }) }

// --- Export (matches React: action 'key/export', uses keysRaw) ---
async function exportKeys() {
    moreMenuOpen.value = false
    const keys = state.keysRaw
    if (!Array.isArray(keys) || keys.length === 0) {
        common.toast(str(strings.value?.label?.noKeysToExport) || 'No keys to export')
        return
    }
    try {
        overlay.show({ message: str(strings.value?.label?.exportProgress) || 'Exporting...' })
        const response = await request({ action: 'key/export', payload: { keys } })
        const json = JSON.stringify(response.data, null, 2)
        const blob = new Blob([json], { type: 'application/json' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        const connName = state.connection?.name || 'redis'
        const db = state.currentDatabase ?? 0
        a.download = `${connName}-db${db}-export.json`
        a.click()
        URL.revokeObjectURL(url)
        common.toast(str(strings.value?.status?.exportDone) || 'Export complete')
    } catch (e) {
        common.generalHandleError(e)
    } finally {
        overlay.hide()
    }
}

// --- Import (matches React: file picker → dialog for conflict mode → action 'key/import') ---
function importKeys() {
    moreMenuOpen.value = false
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = '.json'
    input.onchange = () => {
        const file = input.files?.[0]
        if (!file) return
        const reader = new FileReader()
        reader.onload = (e: any) => {
            try {
                const parsed = JSON.parse(e.target.result)
                if (!parsed?.keys || !Array.isArray(parsed.keys) || parsed.keys.length === 0) {
                    common.toast(str(strings.value?.label?.importNoKeys) || 'No keys found in file')
                    return
                }
                importDialogData.value = parsed
                importDialogOpen.value = true
            } catch (err: any) {
                if (err !== undefined && err !== null) common.generalHandleError(err)
            }
        }
        reader.readAsText(file)
    }
    input.click()
}

async function handleImportDialogClose(result: { pending: boolean; keys: any[]; conflictMode: string } | null) {
    importDialogOpen.value = false
    importDialogData.value = null
    if (!result?.pending) return
    try {
        overlay.show({ message: str(strings.value?.label?.importProgress) || 'Importing...' })
        const response = await request({
            action: 'key/import',
            payload: { keys: result.keys, conflictMode: result.conflictMode },
        })
        const data = response.data || response
        const statusMsg = str(strings.value?.status?.importDone, data)
            || `Import complete: ${data.created ?? 0} created, ${data.skipped ?? 0} skipped, ${data.errors ?? 0} errors`
        common.toast(statusMsg)
        await cmd.refresh({ force: true })
    } catch (e: any) {
        if (e !== undefined && e !== null) common.generalHandleError(e)
    } finally {
        overlay.hide()
    }
}

// --- Delete search keys (matches React: pattern with wildcard, action 'key/delete-search-keys') ---
async function deleteSearchKeys() {
    moreMenuOpen.value = false
    const searchVal = localSearch.value
    let match: string
    if (searchVal.length > 0) {
        match = settings.searchStartsWith ? searchVal + '*' : '*' + searchVal + '*'
    } else {
        match = '*'
    }
    const keyCount = state.keysRaw?.length ?? 0
    try {
        const confirmMsg = str(strings.value?.confirm?.deleteSearchKeys, { count: keyCount, pattern: match })
            || `Are you sure to delete all keys matching "${match}"? Found ${keyCount} keys.`
        await common.confirm({ message: confirmMsg })
        overlay.show({ message: str(strings.value?.label?.deletingSearchKeys) || 'Deleting...' })
        const response = await request({ action: 'key/delete-search-keys', payload: { match } })
        const deletedCount = response.deletedCount || response.deleted || 0
        const toastMsg = str(strings.value?.status?.deletedSearchKeys, { count: deletedCount })
            || `Deleted ${deletedCount} keys`
        common.toast(toastMsg)
        await cmd.refresh({ force: true })
    } catch (e) {
        if (e !== undefined) common.generalHandleError(e)
    } finally {
        overlay.hide()
    }
}
</script>

<template>
    <div class="p3xr-tree-controls">
        <!-- Row 1: expand/collapse, divider, refresh, settings, pagination -->
        <div class="p3xr-tree-controls-row">
            <!-- Expand menu -->
            <v-menu v-model="expandMenuOpen" location="bottom start">
                <template #activator="{ props: mp }">
                    <v-btn v-bind="mp" icon variant="text" class="p3xr-tc-btn-primary">
                        <v-icon>mdi-chevron-down</v-icon>
                    </v-btn>
                </template>
                <v-list density="compact">
                    <v-list-item v-for="lvl in 5" :key="lvl" @click="expandToLevel(lvl)">
                        {{ strings?.intention?.expandLevel || 'Level' }} {{ lvl }}
                    </v-list-item>
                    <v-divider />
                    <v-list-item @click="expandAll()">{{ strings?.intention?.expandAll || 'Expand All' }}</v-list-item>
                </v-list>
            </v-menu>

            <!-- Collapse -->
            <v-tooltip :text="strings?.page?.treeControls?.collapseAll || 'Collapse All'" location="top" :open-delay="300">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn" :style="{ color: iconColor }" @click="collapseAll()">
                        <v-icon>mdi-chevron-up</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>

            <!-- Refresh -->
            <v-tooltip :text="strings?.intention?.refresh || 'Refresh'" location="top" :open-delay="300">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn" :style="{ color: iconColor }" @click="cmd.refresh({ force: true })">
                        <v-icon>mdi-refresh</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>

            <!-- Settings (opens TreeSettingsDialog) -->
            <v-tooltip :text="strings?.form?.treeSettings?.label?.formName || 'Tree Settings'" location="top" :open-delay="300">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn" :style="{ color: iconColor }" @click="treeSettingsOpen = true">
                        <v-icon>mdi-cog</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>

            <!-- Divider input -->
            <v-tooltip :text="strings?.form?.treeSettings?.field?.treeSeparator || 'Tree separator'" location="top" :open-delay="300">
                <template #activator="{ props: tp }">
                    <input
                        v-bind="tp"
                        v-model="localDivider"
                        class="p3xr-tc-divider-input"
                        :style="{ backgroundColor: inputBg, color: inputColor, borderColor: inputBorder }"
                        maxlength="3"
                        @input="onDividerChange()"
                    />
                </template>
            </v-tooltip>

            <!-- Divider selector dropdown — narrow, aligned under input (matches React translateX(-23px)) -->
            <v-menu v-if="treeDividers.length > 0" v-model="dividerMenuOpen" location="bottom start" :offset="[0, 4]">
                <template #activator="{ props: mp }">
                    <v-btn v-bind="mp" icon variant="text" class="p3xr-tc-btn-narrow" :style="{ color: iconColor }">
                        <v-icon size="18">mdi-menu-down</v-icon>
                    </v-btn>
                </template>
                <v-list density="compact" class="p3xr-tc-divider-menu">
                    <v-list-item v-for="d in treeDividers" :key="d" @click="setDividerQuick(d)" class="p3xr-tc-divider-menu-item">
                        {{ d }}
                    </v-list-item>
                </v-list>
            </v-menu>

            <span style="flex: 1;" />

            <!-- Pagination (only if multiple pages) -->
            <template v-if="pages > 1">
                <span style="display: inline-flex; align-items: center; white-space: nowrap; margin-left: 2px;">
                    <v-tooltip :text="strings?.page?.treeControls?.pager?.first || 'First'" location="top" :open-delay="300">
                        <template #activator="{ props: tp }">
                            <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn-primary" :disabled="localPage <= 1" @click="pagerAction('first')">
                                <v-icon size="18">mdi-skip-previous</v-icon>
                            </v-btn>
                        </template>
                    </v-tooltip>
                    <v-tooltip :text="strings?.page?.treeControls?.pager?.prev || 'Previous'" location="top" :open-delay="300">
                        <template #activator="{ props: tp }">
                            <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn" :style="{ color: iconColor }" :disabled="localPage <= 1" @click="pagerAction('prev')">
                                <v-icon size="18">mdi-chevron-left</v-icon>
                            </v-btn>
                        </template>
                    </v-tooltip>
                    <input
                        v-model.number="localPage"
                        type="number"
                        class="p3xr-tc-page-input"
                        :style="{ backgroundColor: inputBg, color: inputColor, borderColor: inputBorder }"
                        min="1" :max="pages"
                        @change="onPageChange()"
                        @input="onPageChange()"
                    />
                    <span style="opacity: 0.6; font-family: 'Roboto Mono', monospace; font-size: 12px; margin: 0 2px;">/ {{ pages }}</span>
                    <v-tooltip :text="strings?.page?.treeControls?.pager?.next || 'Next'" location="top" :open-delay="300">
                        <template #activator="{ props: tp }">
                            <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn" :style="{ color: iconColor }" :disabled="localPage >= pages" @click="pagerAction('next')">
                                <v-icon size="18">mdi-chevron-right</v-icon>
                            </v-btn>
                        </template>
                    </v-tooltip>
                    <v-tooltip :text="strings?.page?.treeControls?.pager?.last || 'Last'" location="top" :open-delay="300">
                        <template #activator="{ props: tp }">
                            <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn-primary" :disabled="localPage >= pages" @click="pagerAction('last')">
                                <v-icon size="18">mdi-skip-next</v-icon>
                            </v-btn>
                        </template>
                    </v-tooltip>
                </span>
            </template>
            <span v-else style="margin-left: auto; opacity: 0.5; font-size: 12px;">{{ keyCountLabel }}&nbsp;</span>
        </div>

        <!-- Row 2: search bar -->
        <div class="p3xr-tree-controls-search">
            <input
                v-model="localSearch"
                class="p3xr-tc-search-input"
                :style="{ backgroundColor: inputBg, color: inputColor, borderColor: inputBorder }"
                :placeholder="settings.searchClientSide ? (strings?.label?.searchKeys || 'Search keys') : (strings?.label?.searchKeysServer || 'Search keys on server')"
                @keydown.enter="onSearchSubmit()"
            />

            <!-- Search button -->
            <v-tooltip :text="strings?.page?.treeControls?.search?.search || 'Search'" location="top" :open-delay="300">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn-primary" @click="onSearchSubmit()">
                        <v-icon>mdi-magnify</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>

            <!-- Clear search -->
            <v-tooltip v-if="localSearch" :text="strings?.page?.treeControls?.search?.clear || 'Clear'" location="top" :open-delay="300">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" icon variant="text" class="p3xr-tc-btn-primary" @click="clearSearch()">
                        <v-icon>mdi-close</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>

            <!-- Add key (non-readonly) -->
            <v-tooltip v-if="!isReadonly" :text="strings?.intention?.addKeyRoot || 'Add key'" location="top" :open-delay="300">
                <template #activator="{ props: tp }">
                    <v-icon v-bind="tp" :style="{ fontSize: '24px', cursor: 'pointer', color: warnColor }" @click="cmdAddKey($event)">mdi-plus</v-icon>
                </template>
            </v-tooltip>

            <!-- More actions menu -->
            <v-menu v-model="moreMenuOpen" location="bottom end">
                <template #activator="{ props: mp }">
                    <v-btn v-bind="mp" icon variant="text" class="p3xr-tc-btn" :style="{ color: iconColor }">
                        <v-icon>mdi-dots-vertical</v-icon>
                    </v-btn>
                </template>
                <v-list density="compact" style="min-width: 280px;">
                    <v-list-item @click="exportKeys()">
                        <template #prepend><v-icon size="18" style="margin-right: 8px;">mdi-download</v-icon></template>
                        <v-list-item-title>{{ exportLabel }}</v-list-item-title>
                        <v-list-item-subtitle v-if="hasSearch" style="opacity: 0.5; font-size: 11px; font-style: italic; white-space: normal;">
                            {{ str(strings?.label?.exportSearchHint) || 'Exporting only keys matching current search' }}
                        </v-list-item-subtitle>
                    </v-list-item>
                    <v-list-item v-if="!isReadonly" @click="importKeys()">
                        <template #prepend><v-icon size="18" style="margin-right: 8px;">mdi-upload</v-icon></template>
                        <v-list-item-title>{{ str(strings?.intention?.importKeys) || 'Import keys' }}</v-list-item-title>
                        <v-list-item-subtitle v-if="hasSearch" style="opacity: 0.5; font-size: 11px; font-style: italic; white-space: normal;">
                            {{ str(strings?.label?.importSearchHint) || 'Import applies to the full database, not just search results' }}
                        </v-list-item-subtitle>
                    </v-list-item>
                    <template v-if="!isReadonly">
                        <v-divider />
                        <v-list-item @click="deleteSearchKeys()">
                            <template #prepend><v-icon size="18" color="error" style="margin-right: 8px;">mdi-delete-sweep</v-icon></template>
                            <v-list-item-title>{{ deleteSearchLabel }}</v-list-item-title>
                            <v-list-item-subtitle v-if="hasSearch" style="opacity: 0.5; font-size: 11px; font-style: italic; white-space: normal;">
                                {{ str(strings?.label?.deleteSearchHint) || 'Deletes all keys matching the current search on the server' }}
                            </v-list-item-subtitle>
                        </v-list-item>
                    </template>
                </v-list>
            </v-menu>
        </div>
    </div>

    <!-- Tree Settings Dialog -->
    <TreeSettingsDialog :open="treeSettingsOpen" @close="treeSettingsOpen = false" />

    <!-- Key Import Dialog -->
    <KeyImportDialog :open="importDialogOpen" :data="importDialogData" @close="handleImportDialogClose" />
</template>

<style scoped>
.p3xr-tree-controls {
    flex-shrink: 0;
    padding: 4px;
}

.p3xr-tree-controls-row {
    display: flex;
    align-items: center;
    gap: 1px;
    min-height: 28px;
    flex-wrap: wrap;
}

.p3xr-tree-controls-search {
    display: flex;
    align-items: center;
    gap: 1px;
    margin-top: 4px;
}

/* Icon button base: 24x24 circular, matching React iconBtnBase */
.p3xr-tc-btn {
    padding: 0 !important;
    width: 24px !important;
    height: 24px !important;
    min-width: 24px !important;
    min-height: 24px !important;
    border-radius: 50% !important;
}

/* Primary icon buttons use theme primary color */
.p3xr-tc-btn-primary {
    padding: 0 !important;
    width: 24px !important;
    height: 24px !important;
    min-width: 24px !important;
    min-height: 24px !important;
    border-radius: 50% !important;
    color: rgb(var(--v-theme-primary)) !important;
}

/* Narrow button (divider dropdown) */
.p3xr-tc-btn-narrow {
    padding: 0 !important;
    width: 14px !important;
    height: 24px !important;
    min-width: 14px !important;
    min-height: 24px !important;
    border-radius: 50% !important;
}

/* Divider input */
.p3xr-tc-divider-input {
    width: 23px;
    text-align: center;
    font-family: 'Roboto Mono', monospace;
    font-size: 14px;
    font-weight: 500;
    border: 2px solid;
    border-radius: 3px;
    padding: 0;
    outline: none;
    box-sizing: border-box;
    height: 24px;
    margin: 0 1px;
}

/* Page number input */
.p3xr-tc-page-input {
    width: 32px;
    height: 20px;
    text-align: center;
    font-family: 'Roboto Mono', monospace;
    font-size: 12px;
    border: 2px solid;
    border-radius: 3px;
    padding: 0;
    outline: none;
    box-sizing: border-box;
    -moz-appearance: textfield;
}
.p3xr-tc-page-input::-webkit-inner-spin-button,
.p3xr-tc-page-input::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0;
}

/* Search input */
.p3xr-tc-search-input {
    flex: 1;
    min-width: 0;
    font-family: 'Roboto Mono', monospace;
    font-size: 12px;
    border: 2px solid;
    border-radius: 3px;
    padding: 3px;
    outline: none;
    box-sizing: border-box;
    height: 28px;
    margin: 0 1px;
    vertical-align: middle;
}
</style>

<style>
/* Divider dropdown — narrow single-char width */
.p3xr-tc-divider-menu {
    min-width: 0 !important;
    max-width: 32px !important;
    padding: 0 !important;
    transform: translateX(-25px);
    overflow: hidden !important;
}
.p3xr-tc-divider-menu-item {
    font-family: 'Roboto Mono', monospace !important;
    font-size: 14px !important;
    min-height: 28px !important;
    padding: 0 6px !important;
    text-align: center !important;
    justify-content: center !important;
}
.p3xr-tc-divider-menu-item .v-list-item__content {
    text-align: center !important;
}

/* Override global v-icon 24px for tree control buttons */
.p3xr-tc-btn .v-icon,
.p3xr-tc-btn-primary .v-icon,
.p3xr-tc-btn-narrow .v-icon {
    font-size: 20px !important;
    width: 20px !important;
    height: 20px !important;
}
/* Button overlay reset */
.p3xr-tc-btn .v-btn__overlay,
.p3xr-tc-btn-primary .v-btn__overlay,
.p3xr-tc-btn-narrow .v-btn__overlay {
    opacity: 0 !important;
}
</style>
