// src/react/pages/database/StatisticsPage.tsx
import { useMemo, useState, useEffect } from 'react'
import { Box, Tabs, Tab, Typography, useTheme } from '@mui/material'
import { useI18nStore } from '../../stores/i18n.store'
import { useRedisStateStore } from '../../stores/redis-state.store'
import { useThemeStore } from '../../stores/theme.store'
import { useMainCommandStore, onCommandEvent } from '../../stores/main-command.store'

const EXCLUDE = ['in', 'run', 'per']
const INCLUDE = ['sha1']
const REPLACE: Record<string, string> = { perc: 'percent', sec: 'seconds' }

function generateKey(key: string, strings: any): string {
    if (strings?.title?.hasOwnProperty(key)) {
        return strings.title[key]
    }
    return key.split('_').map((instance, index) => {
        if (REPLACE.hasOwnProperty(instance)) {
            instance = REPLACE[instance]
        }
        if (INCLUDE.includes(instance) ||
            (instance.length < 4 && !EXCLUDE.includes(instance))) {
            return instance.toUpperCase()
        } else if (index === 0) {
            return instance[0].toUpperCase() + instance.substring(1)
        }
        return instance
    }).join(' ')
}

function formatValue(value: any): string {
    if (value === null || value === undefined) return ''
    if (typeof value === 'object') return JSON.stringify(value)
    return String(value)
}

interface TabSection {
    key: string
    label: string
    items: Array<{ key: string; value: any }>
}

export default function StatisticsPage() {
    const strings = useI18nStore(s => s.strings)
    const info = useRedisStateStore(s => s.info)
    const modules = useRedisStateStore(s => s.modules)
    const connection = useRedisStateStore(s => s.connection)
    const redisChanged = useRedisStateStore(s => s.redisChanged)
    const muiTheme = useTheme()
    const themeKey = useThemeStore(s => s.themeKey)
    const [topTab, setTopTab] = useState(0)
    const [dbTab, setDbTab] = useState(0)
    const itemBorderColor = muiTheme.palette.mode === 'dark' ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)'

    // Broadcast tree refresh if state changed
    useEffect(() => {
        if (redisChanged) {
            useRedisStateStore.setState({ redisChanged: false })
        }
    }, [redisChanged])

    const isCluster = connection?.cluster === true

    // Parse keyspace databases
    const keyspaceDatabaseEntries = useMemo(() => {
        const ksDbs = info?.keyspaceDatabases ?? {}
        return Object.keys(ksDbs).map(k => ({ key: k, value: ksDbs[k] }))
    }, [info])

    const keyspaceItems = useMemo(() => {
        const result: Record<string, Array<{ key: string; value: any }>> = {}
        for (const dbEntry of keyspaceDatabaseEntries) {
            const ks = info?.keyspace?.['db' + dbEntry.key]
            result[dbEntry.key] = ks
                ? Object.keys(ks).map(k => ({ key: k, value: ks[k] }))
                : []
        }
        return result
    }, [info, keyspaceDatabaseEntries])

    const hasDatabases = keyspaceDatabaseEntries.length > 0

    // Parse info sections + modules
    const infoSections: TabSection[] = useMemo(() => {
        if (!info) return []
        const sections = Object.keys(info)
            .filter(k => k !== 'keyspace' && k !== 'keyspaceDatabases')
            .map(k => ({
                key: k,
                label: generateKey(k, strings),
                items: Object.keys(info[k]).map(ik => ({ key: ik, value: info[k][ik] })),
            }))

        // Replace or add modules section
        const mods = Array.isArray(modules) ? modules : []
        if (mods.length > 0) {
            const moduleItems = mods.map((m: any) => ({ key: m.name, value: `v${m.ver}` }))
            const existingIdx = sections.findIndex(s => s.key.toLowerCase() === 'modules')
            if (existingIdx >= 0) {
                sections[existingIdx].items = moduleItems
            } else {
                sections.push({ key: 'modules', label: generateKey('modules', strings), items: moduleItems })
            }
        }

        return sections
    }, [info, modules, strings])

    // All top-level tabs: DB (if applicable) + info sections
    const allTabs = useMemo(() => {
        const tabs: TabSection[] = []
        if (hasDatabases && !isCluster) {
            tabs.push({
                key: '__db__',
                label: strings?.title?.db ?? 'DB',
                items: [],
            })
        }
        tabs.push(...infoSections)
        return tabs
    }, [hasDatabases, isCluster, infoSections, strings])

    if (!connection) {
        return <Box sx={{ p: 2 }}><Typography>{strings?.title?.main}</Typography></Box>
    }

    const currentTab = allTabs[topTab]
    const isDbTab = currentTab?.key === '__db__'

    return (
        <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
            {/* Top-level tabs */}
            <Tabs
                value={Math.min(topTab, allTabs.length - 1)}
                onChange={(_, v) => setTopTab(v)}
                variant="scrollable"
                scrollButtons="auto"
                textColor="inherit"
                sx={{
                    position: 'sticky',
                    top: 0,
                    zIndex: 2,
                    bgcolor: muiTheme.palette.background.paper,
                    backgroundImage: 'none',
                    flexShrink: 0,
                    '& .MuiTab-root': { color: muiTheme.p3xr.treecontrolIconColor, textTransform: 'none' },
                    '& .MuiTab-root.Mui-selected': { color: muiTheme.palette.text.primary },
                    '& .MuiTabs-indicator': { bgcolor: muiTheme.p3xr.matSysPrimary },
                }}
            >
                {allTabs.map(tab => (
                    <Tab key={tab.key} label={tab.label} />
                ))}
            </Tabs>

            {/* Tab content */}
            <Box sx={{ flex: 1, overflow: 'auto' }}>
                {isDbTab ? (
                    /* Nested DB keyspace tabs */
                    <Box>
                        <Tabs
                            value={Math.min(dbTab, keyspaceDatabaseEntries.length - 1)}
                            onChange={(_, v) => setDbTab(v)}
                            variant="scrollable"
                            scrollButtons="auto"
                            textColor="inherit"
                            sx={() => {
                                const isMatrix = themeKey === 'matrix'
                                const activeColor = isMatrix ? 'rgba(0,0,0,0.87)' : 'white'
                                const inactiveColor = isMatrix ? 'rgba(0,0,0,0.6)' : 'rgba(255,255,255,0.7)'
                                return {
                                    bgcolor: 'primary.main',
                                    '& .MuiTab-root': { color: inactiveColor },
                                    '& .MuiTab-root.Mui-selected': { color: activeColor },
                                    '& .MuiTabs-indicator': { bgcolor: activeColor },
                                    '& .MuiTabScrollButton-root': { color: inactiveColor },
                                }
                            }}
                        >
                            {keyspaceDatabaseEntries.map(dbEntry => (
                                <Tab key={dbEntry.key} label={dbEntry.key} />
                            ))}
                        </Tabs>
                        {keyspaceDatabaseEntries.map((dbEntry, i) => (
                            dbTab === i && (
                                <Box key={dbEntry.key} sx={{ px: 2, py: 1 }}>
                                    {(keyspaceItems[dbEntry.key] ?? []).map(item => (
                                        <Box key={item.key} sx={{
                                            display: 'flex',
                                            alignItems: 'baseline',
                                            justifyContent: 'space-between',
                                            py: '8px',
                                            borderBottom: '1px solid',
                                            borderColor: itemBorderColor,
                                        }}>
                                            <strong>{generateKey(item.key, strings)}</strong>
                                            <span style={{ textAlign: 'right' }}>{item.value}</span>
                                        </Box>
                                    ))}
                                </Box>
                            )
                        ))}
                    </Box>
                ) : currentTab ? (
                    /* Info section content */
                    <Box sx={{ px: 2, py: 1 }}>
                        {currentTab.items.map(item => (
                            <Box key={item.key} sx={{
                                display: 'flex',
                                alignItems: 'baseline',
                                justifyContent: 'space-between',
                                py: '8px',
                                borderBottom: '1px solid',
                                borderColor: itemBorderColor,
                            }}>
                                <strong>{generateKey(item.key, strings)}</strong>
                                <Box sx={{ textAlign: 'right', wordBreak: 'break-all', maxWidth: '60%' }}>
                                    {formatValue(item.value)}
                                </Box>
                            </Box>
                        ))}
                    </Box>
                ) : null}
            </Box>
        </Box>
    )
}

// src/vue/pages/database/StatisticsPage.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useI18nStore } from '../../stores/i18n'
import { useRedisStateStore } from '../../stores/redis-state'
import { useThemeStore } from '../../stores/theme'

const EXCLUDE = ['in', 'run', 'per']
const REPLACE: Record<string, string> = { perc: 'percent', sec: 'seconds' }

function generateKey(key: string, s: any): string {
    if (s?.title?.hasOwnProperty(key)) return s.title[key]
    return key.split('_').map((part, idx) => {
        if (REPLACE.hasOwnProperty(part)) part = REPLACE[part]
        if (part.length < 4 && !EXCLUDE.includes(part)) return part.toUpperCase()
        if (idx === 0) return part[0].toUpperCase() + part.substring(1)
        return part
    }).join(' ')
}

function formatValue(value: any): string {
    if (value === null || value === undefined) return ''
    if (typeof value === 'object') return JSON.stringify(value)
    return String(value)
}

interface TabSection {
    key: string
    label: string
    items: Array<{ key: string; value: any }>
}

const i18n = useI18nStore()
const state = useRedisStateStore()
const theme = useThemeStore()

const strings = computed(() => i18n.strings)
const topTab = ref(0)
const dbTab = ref(0)

const isCluster = computed(() => state.connection?.cluster === true)

const keyspaceDatabaseEntries = computed(() => {
    const ksDbs = state.info?.keyspaceDatabases ?? {}
    return Object.keys(ksDbs).map(k => ({ key: k, value: ksDbs[k] }))
})

const keyspaceItems = computed(() => {
    const result: Record<string, Array<{ key: string; value: any }>> = {}
    for (const dbEntry of keyspaceDatabaseEntries.value) {
        const ks = state.info?.keyspace?.['db' + dbEntry.key]
        result[dbEntry.key] = ks
            ? Object.keys(ks).map(k => ({ key: k, value: ks[k] }))
            : []
    }
    return result
})

const hasDatabases = computed(() => keyspaceDatabaseEntries.value.length > 0)

const infoSections = computed<TabSection[]>(() => {
    if (!state.info) return []
    const sections = Object.keys(state.info)
        .filter(k => k !== 'keyspace' && k !== 'keyspaceDatabases')
        .map(k => ({
            key: k,
            label: generateKey(k, strings.value),
            items: Object.keys(state.info[k]).map(ik => ({ key: ik, value: state.info[k][ik] })),
        }))

    const mods = Array.isArray(state.modules) ? state.modules : []
    if (mods.length > 0) {
        const moduleItems = mods.map((m: any) => ({ key: m.name, value: `v${m.ver}` }))
        const existingIdx = sections.findIndex(s => s.key.toLowerCase() === 'modules')
        if (existingIdx >= 0) {
            sections[existingIdx].items = moduleItems
        } else {
            sections.push({ key: 'modules', label: generateKey('modules', strings.value), items: moduleItems })
        }
    }
    return sections.filter(s => s.items.length > 0)
})

const allTabs = computed<TabSection[]>(() => {
    const tabs: TabSection[] = []
    if (hasDatabases.value && !isCluster.value) {
        tabs.push({ key: '__db__', label: strings.value?.title?.db ?? 'DB', items: [] })
    }
    tabs.push(...infoSections.value)
    return tabs
})

const currentTab = computed(() => allTabs.value[topTab.value])
const isDbTab = computed(() => currentTab.value?.key === '__db__')
</script>

<template>
    <div v-if="!state.connection" style="padding: 16px;">
        {{ strings?.title?.main }}
    </div>

    <div v-else class="p3xr-statistics">
        <!-- Top-level tabs -->
        <v-tabs
            v-model="topTab"
            variant="scrollable"
            show-arrows
            class="p3xr-statistics-tabs"
            color="primary"
            slider-color="primary"
        >
            <v-tab v-for="tab in allTabs" :key="tab.key">{{ tab.label }}</v-tab>
        </v-tabs>

        <!-- Tab content -->
        <div class="p3xr-statistics-content">
            <!-- DB keyspace tabs -->
            <template v-if="isDbTab">
                <v-tabs
                    v-model="dbTab"
                    variant="scrollable"
                    show-arrows
                    class="p3xr-statistics-db-tabs"
                    bg-color="primary"
                >
                    <v-tab v-for="dbEntry in keyspaceDatabaseEntries" :key="dbEntry.key">{{ dbEntry.key }}</v-tab>
                </v-tabs>
                <div v-for="(dbEntry, i) in keyspaceDatabaseEntries" :key="dbEntry.key">
                    <div v-if="dbTab === i" class="p3xr-statistics-items">
                        <div v-for="item in (keyspaceItems[dbEntry.key] ?? [])" :key="item.key" class="p3xr-statistics-row">
                            <strong>{{ generateKey(item.key, strings) }}</strong>
                            <span>{{ item.value }}</span>
                        </div>
                    </div>
                </div>
            </template>

            <!-- Info section content -->
            <template v-else-if="currentTab">
                <div class="p3xr-statistics-items">
                    <div v-for="item in currentTab.items" :key="item.key" class="p3xr-statistics-row">
                        <strong>{{ generateKey(item.key, strings) }}</strong>
                        <span style="text-align: right; word-break: break-all; max-width: 60%;">{{ formatValue(item.value) }}</span>
                    </div>
                </div>
            </template>
        </div>
    </div>
</template>

<style scoped>
.p3xr-statistics {
    height: 100%;
    display: flex;
    flex-direction: column;
}

.p3xr-statistics-tabs {
    flex-shrink: 0;
    position: sticky;
    top: 0;
    z-index: 2;
    background-color: rgb(var(--v-theme-surface));
}

.p3xr-statistics-tabs :deep(.v-tab) {
    text-transform: none !important;
}

.p3xr-statistics-db-tabs {
    flex-shrink: 0;
}

.p3xr-statistics-content {
    flex: 1;
    overflow: auto;
}

.p3xr-statistics-items {
    padding: 8px 16px;
}

.p3xr-statistics-row {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    padding: 8px 0;
    border-bottom: 1px solid rgba(var(--v-border-color), 0.06);
}
</style>

<style>
/* DB tabs on primary background — white text, except matrix (black) */
.p3xr-statistics-db-tabs .v-tab {
    color: rgba(255,255,255,0.7) !important;
}
.p3xr-statistics-db-tabs .v-tab--selected {
    color: white !important;
}
.v-theme--matrix .p3xr-statistics-db-tabs .v-tab {
    color: rgba(0,0,0,0.6) !important;
}
.v-theme--matrix .p3xr-statistics-db-tabs .v-tab--selected {
    color: rgba(0,0,0,0.87) !important;
}
</style>
