// src/vue/pages/monitoring/MonitoringShell.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useI18nStore } from '../../stores/i18n'
import { useRedisStateStore } from '../../stores/redis-state'
import { onSocketEvent } from '../../stores/socket.service'
import {
    initMonitoringData,
    bindMonitoringStore,
    startProfiler,
    stopProfiler,
    startPubSub,
    stopPubSub,
    destroyMonitoringData,
} from '../../stores/monitoring-data'

const router = useRouter()
const route = useRoute()
const i18n = useI18nStore()
const state = useRedisStateStore()

const strings = computed(() => i18n.strings)

const routes = ['/monitoring', '/monitoring/profiler', '/monitoring/pubsub', '/monitoring/analysis']
const selectedTab = ref(0)

function syncTab(path: string) {
    if (path.startsWith('/monitoring/profiler')) selectedTab.value = 1
    else if (path.startsWith('/monitoring/pubsub')) selectedTab.value = 2
    else if (path.startsWith('/monitoring/analysis')) selectedTab.value = 3
    else selectedTab.value = 0
}

function onTabChange(index: number) {
    if (index >= 0 && index < routes.length) {
        router.push(routes[index])
    }
}

let servicesStarted = false
const unsubFns: Array<() => void> = []

async function startServices() {
    try { await startProfiler() } catch (e) { console.error('startProfiler failed', e) }
    try { await startPubSub() } catch (e) { console.error('startPubSub failed', e) }
}

function initServices() {
    servicesStarted = true
    initMonitoringData(() => i18n.currentLang)
    bindMonitoringStore()
    startServices()
}

onMounted(() => {
    syncTab(route.path)

    // Redirect to settings on Redis disconnect
    unsubFns.push(onSocketEvent('redis-disconnected', () => {
        router.push('/settings')
    }))

    // If connected, start immediately; otherwise wait
    if (state.connection) {
        initServices()
    } else {
        unsubFns.push(onSocketEvent('connections', () => {
            if (state.connection && !servicesStarted) {
                initServices()
            }
        }))
    }
})

// Watch route changes to sync tab
watch(() => route.path, (path) => syncTab(path))

onUnmounted(() => {
    stopProfiler()
    stopPubSub()
    destroyMonitoringData()
    unsubFns.forEach(fn => fn())
})
</script>

<template>
    <div class="p3xr-monitoring-shell-container">
        <v-tabs
            v-model="selectedTab"
            class="p3xr-monitoring-tabs"
            grow
            centered
            color="primary"
            slider-color="primary"
            @update:model-value="onTabChange"
        >
            <v-tab :value="0">{{ strings?.intention?.pulse || 'Pulse' }}</v-tab>
            <v-tab :value="1">{{ strings?.intention?.profiler || 'Profiler' }}</v-tab>
            <v-tab :value="2">{{ strings?.intention?.pubsubMonitor || 'PubSub' }}</v-tab>
            <v-tab :value="3">{{ strings?.intention?.memoryAnalysis || 'Analysis' }}</v-tab>
        </v-tabs>
        <div class="p3xr-monitoring-shell-content">
            <router-view />
        </div>
    </div>
</template>

<style scoped>
.p3xr-monitoring-shell-container {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}

.p3xr-monitoring-tabs {
    flex: 0 0 auto;
    background-color: var(--p3xr-content-bg, rgb(var(--v-theme-surface))) !important;
    border-bottom: 1px solid rgba(var(--v-border-color), var(--v-border-opacity, 0.12));
}

.p3xr-monitoring-shell-content {
    flex: 1;
    min-height: 0;
    overflow: auto;
    padding: 5px;
}
</style>

// src/ng/pages/monitoring/monitoring-shell.component.ts
import { Component, Inject, OnInit, OnDestroy, ViewEncapsulation } from '@angular/core';
import { Router, RouterOutlet, NavigationEnd } from '@angular/router';
import { MatTabsModule } from '@angular/material/tabs';
import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';
import { I18nService } from '../../services/i18n.service';
import { SocketService } from '../../services/socket.service';
import { CommonService } from '../../services/common.service';
import { MonitoringDataService } from './monitoring-data.service';
import { RedisStateService } from '../../services/redis-state.service';

@Component({
    selector: 'p3xr-monitoring-shell',
    standalone: true,
    imports: [RouterOutlet, MatTabsModule],
    styleUrls: ['./monitoring-shell.component.scss'],
    template: `
        <div class="p3xr-monitoring-shell-container">
            <mat-tab-group class="p3xr-monitoring-tabs" [selectedIndex]="selectedTab" (selectedIndexChange)="onTabChange($event)">
                <mat-tab [label]="strings().intention?.pulse || 'Pulse'"></mat-tab>
                <mat-tab [label]="strings().intention?.profiler || 'Profiler'"></mat-tab>
                <mat-tab [label]="strings().intention?.pubsubMonitor || 'PubSub'"></mat-tab>
                <mat-tab [label]="strings().intention?.memoryAnalysis || 'Analysis'"></mat-tab>
            </mat-tab-group>
            <div class="p3xr-monitoring-shell-content">
                <router-outlet></router-outlet>
            </div>
        </div>
    `,
    encapsulation: ViewEncapsulation.None,
})
export class MonitoringShellComponent implements OnInit, OnDestroy {
    strings;
    selectedTab = 0;

    private readonly routes = ['/monitoring', '/monitoring/profiler', '/monitoring/pubsub', '/monitoring/analysis'];
    private routerSub?: Subscription;
    private subs: Subscription[] = [];
    private servicesStarted = false;

    constructor(
        @Inject(I18nService) private readonly i18n: I18nService,
        @Inject(Router) private readonly router: Router,
        @Inject(SocketService) private readonly socket: SocketService,
        @Inject(CommonService) private readonly common: CommonService,
        @Inject(MonitoringDataService) private readonly data: MonitoringDataService,
        @Inject(RedisStateService) private readonly state: RedisStateService,
    ) {
        this.strings = this.i18n.strings;
    }

    ngOnInit(): void {
        this.syncTab(this.router.url);
        this.routerSub = this.router.events
            .pipe(filter(e => e instanceof NavigationEnd))
            .subscribe((e: NavigationEnd) => this.syncTab(e.urlAfterRedirects));

        // Redirect to settings on Redis disconnect
        this.subs.push(this.socket.redisDisconnected$.subscribe(() => {
            this.router.navigate(['/settings']);
        }));

        // If connected, start immediately; otherwise wait for connection
        if (this.state.connection()) {
            this.initServices();
        } else {
            this.subs.push(this.socket.stateChanged$.subscribe(() => {
                if (this.state.connection() && !this.servicesStarted) {
                    this.initServices();
                }
            }));
        }
    }

    ngOnDestroy(): void {
        this.data.stopProfiler();
        this.data.stopPubSub();
        this.data.destroy();
        this.routerSub?.unsubscribe();
        this.subs.forEach(s => s.unsubscribe());
    }

    private initServices(): void {
        this.servicesStarted = true;
        this.data.init(this.socket, () => this.i18n.currentLang());
        this.startServices();
    }

    private async startServices(): Promise<void> {
        try {
            await this.data.startProfiler();
        } catch (e) {
            this.common.generalHandleError(e);
        }
        try {
            await this.data.startPubSub();
        } catch (e) {
            this.common.generalHandleError(e);
        }
    }

    onTabChange(index: number): void {
        if (index >= 0 && index < this.routes.length) {
            this.router.navigate([this.routes[index]]);
        }
    }

    private syncTab(url: string): void {
        if (url.startsWith('/monitoring/profiler')) {
            this.selectedTab = 1;
        } else if (url.startsWith('/monitoring/pubsub')) {
            this.selectedTab = 2;
        } else if (url.startsWith('/monitoring/analysis')) {
            this.selectedTab = 3;
        } else {
            this.selectedTab = 0;
        }
    }
}
