// src/react/pages/login/LoginPage.tsx
import { useState } from 'react'
import {
    Box, TextField, Button, IconButton, Tooltip, Menu, MenuItem,
    InputAdornment, AppBar, Toolbar, useMediaQuery,
} from '@mui/material'
import { Done, Visibility, VisibilityOff, Close, Person, Lock, Login } from '@mui/icons-material'
import { useTheme } from '@mui/material'
import { useI18nStore } from '../../stores/i18n.store'
import { useAuthStore } from '../../stores/auth.store'
import { useThemeStore } from '../../stores/theme.store'

export default function LoginPage() {
    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')
    const [pwVisible, setPwVisible] = useState(false)
    const [loading, setLoading] = useState(false)
    const [guiAnchor, setGuiAnchor] = useState<null | HTMLElement>(null)

    const strings = useI18nStore(s => s.strings)
    const isWide = useMediaQuery('(min-width: 600px)')
    const { login, loginError } = useAuthStore()
    const muiTheme = useTheme()
    const themeKey = useThemeStore(s => s.themeKey)

    const footerBg = themeKey === 'matrix' ? '#0a2e0d' : muiTheme.p3xr.accordionBg

    const currentGui = (() => {
        try { return localStorage.getItem('p3xr-frontend') || 'ng' } catch { return 'ng' }
    })()

    const handleLogin = async () => {
        if (loading || !username || !password) return
        setLoading(true)
        const success = await login(username, password)
        if (success) {
            location.reload()
        }
        setLoading(false)
    }

    const switchGui = (gui: string) => {
        try { localStorage.setItem('p3xr-frontend', gui) } catch {}
        location.href = gui === 'react' ? '/react/' : gui === 'vue' ? '/vue/' : '/ng/'
    }

    const getErrorMessage = (error: string) => {
        return strings?.confirm?.invalidCredentials || 'Invalid username or password.'
    }

    return (
        <Box sx={{
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            minHeight: 'calc(100vh - 96px)',
        }}>
            <Box sx={{
                width: 400, maxWidth: 'calc(100vw - 32px)',
                borderRadius: '4px', overflow: 'hidden',
                boxShadow: '0 11px 15px -7px rgba(0,0,0,.2), 0 24px 38px 3px rgba(0,0,0,.14), 0 9px 46px 8px rgba(0,0,0,.12)',
            }}>
                {/* Header — matches P3xrDialog toolbar */}
                <AppBar position="static" sx={{
                    backgroundColor: `${muiTheme.p3xr.strongBg} !important`,
                    backgroundImage: 'none !important',
                    color: 'rgba(255,255,255,0.87) !important',
                    boxShadow: 'none',
                }}>
                    <Toolbar variant="dense" disableGutters sx={{
                        minHeight: '48px !important', height: 48, px: 1,
                    }}>
                        <Box sx={{ flex: 1 }} />
                        <Button color="inherit" size="small" onClick={e => setGuiAnchor(e.currentTarget)}
                            startIcon={<i className="fas fa-desktop" style={{ fontSize: 14 }} />}>
                            GUI
                        </Button>
                        <Menu anchorEl={guiAnchor} open={!!guiAnchor} onClose={() => setGuiAnchor(null)}>
                            <MenuItem selected={currentGui === 'ng'} onClick={() => switchGui('ng')}>
                                <i className="fab fa-angular" style={{ fontSize: 18, width: 24, textAlign: 'center', marginRight: 8, color: '#dd0031' }} />
                                Angular
                            </MenuItem>
                            <MenuItem selected={currentGui === 'react'} onClick={() => switchGui('react')}>
                                <i className="fab fa-react" style={{ fontSize: 18, width: 24, textAlign: 'center', marginRight: 8, color: '#61dafb' }} />
                                React
                            </MenuItem>
                            <MenuItem selected={currentGui === 'vue'} onClick={() => switchGui('vue')}>
                                <i className="fab fa-vuejs" style={{ fontSize: 18, width: 24, textAlign: 'center', marginRight: 8, color: '#42b883' }} />
                                Vue
                            </MenuItem>
                        </Menu>
                    </Toolbar>
                </AppBar>

                {/* Content — matches P3xrDialog content */}
                <Box sx={{
                    p: 2,
                    bgcolor: muiTheme.palette.background.paper,
                    color: muiTheme.palette.text.primary,
                }}>
                    <TextField
                        autoFocus fullWidth margin="dense"
                        label={strings?.form?.connection?.label?.username || 'Username'}
                        value={username}
                        onChange={e => setUsername(e.target.value)}
                        autoComplete="username"
                        onKeyDown={e => e.key === 'Enter' && handleLogin()}
                        slotProps={{
                            input: {
                                startAdornment: (
                                    <InputAdornment position="start">
                                        <Person fontSize="small" />
                                    </InputAdornment>
                                ),
                            },
                        }}
                    />
                    <TextField
                        fullWidth margin="dense"
                        label={strings?.form?.connection?.label?.password || 'Password'}
                        type={pwVisible ? 'text' : 'password'}
                        value={password}
                        onChange={e => setPassword(e.target.value)}
                        autoComplete="current-password"
                        onKeyDown={e => e.key === 'Enter' && handleLogin()}
                        slotProps={{
                            input: {
                                startAdornment: (
                                    <InputAdornment position="start">
                                        <Lock fontSize="small" />
                                    </InputAdornment>
                                ),
                                endAdornment: (
                                    <InputAdornment position="end">
                                        <IconButton onClick={() => setPwVisible(!pwVisible)} size="small">
                                            {pwVisible ? <VisibilityOff fontSize="small" /> : <Visibility fontSize="small" />}
                                        </IconButton>
                                    </InputAdornment>
                                ),
                            },
                        }}
                    />
                    {loginError && (
                        <Box sx={{ color: '#f44336', fontSize: 13, mt: 1 }}>
                            {getErrorMessage(loginError)}
                        </Box>
                    )}
                </Box>

                {/* Footer — matches P3xrDialog actions */}
                <Box sx={{
                    bgcolor: footerBg,
                    gap: 1, px: 1, py: 1,
                    display: 'flex', justifyContent: 'flex-end',
                }}>
                    {isWide ? (
                        <Button variant="contained" color="primary" onClick={handleLogin}
                                disabled={loading || !username || !password}>
                            <Login fontSize="small" />
                            <span style={{ marginLeft: 3 }}>{strings?.intention?.ok || 'Login'}</span>
                        </Button>
                    ) : (
                        <Tooltip title={strings?.intention?.ok || 'Login'} placement="top">
                            <span>
                                <IconButton color="primary" onClick={handleLogin}
                                            disabled={loading || !username || !password}
                                            sx={{ borderRadius: '4px' }}>
                                    <Done fontSize="small" />
                                </IconButton>
                            </span>
                        </Tooltip>
                    )}
                </Box>
            </Box>
        </Box>
    )
}

// src/vue/pages/login/LoginPage.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { storeToRefs } from 'pinia'
import { useI18nStore } from '../../stores/i18n'
import { useAuthStore } from '../../stores/auth'
import { useThemeStore } from '../../stores/theme'

const i18n = useI18nStore()
const strings = computed(() => i18n.strings)
const auth = useAuthStore()
const themeStore = useThemeStore()
const { themeKey } = storeToRefs(themeStore)

const STRONG_BG: Record<string, string> = {
    enterprise: '#212121', light: '#263238', redis: '#b71c1c',
    dark: '#212121', darkNeu: '#263238', darkoBluo: '#1a237e',
    matrix: '#33691e',
}
const ACCORDION_BG: Record<string, string> = {
    enterprise: '#9e9e9e', light: '#b0bec5', redis: '#ef9a9a',
    dark: '#9e9e9e', darkNeu: '#90a4ae', darkoBluo: '#3f51b5',
    matrix: '#76ff03',
}
const headerBg = computed(() => STRONG_BG[themeKey.value] || '#212121')
const footerBg = computed(() => themeKey.value === 'matrix' ? '#0a2e0d' : (ACCORDION_BG[themeKey.value] || '#9e9e9e'))

const username = ref('')
const password = ref('')
const pwVisible = ref(false)
const loading = ref(false)
const guiMenu = ref(false)

const currentGui = (() => {
    try { return localStorage.getItem('p3xr-frontend') || 'ng' } catch { return 'ng' }
})()

async function handleLogin() {
    if (loading.value || !username.value || !password.value) return
    loading.value = true
    const success = await auth.login(username.value, password.value)
    if (success) location.reload()
    loading.value = false
}

function switchGui(gui: string) {
    try { localStorage.setItem('p3xr-frontend', gui) } catch {}
    location.href = gui === 'vue' ? '/vue/' : gui === 'react' ? '/react/' : '/ng/'
}
</script>

<template>
    <div class="p3xr-login-wrapper">
        <div class="p3xr-login-card">
            <!-- Header -->
            <v-toolbar density="compact" :style="{ backgroundColor: headerBg, color: 'rgba(255,255,255,0.87)' }" class="p3xr-login-toolbar">
                <v-spacer />
                <v-menu v-model="guiMenu" location="bottom end">
                    <template #activator="{ props: mp }">
                        <v-btn v-bind="mp" variant="text" size="small" style="color: inherit;">
                            <v-icon size="18" class="mr-1">mdi-monitor</v-icon>
                            GUI
                        </v-btn>
                    </template>
                    <v-list density="compact">
                        <v-list-item :class="{ 'v-list-item--active': currentGui === 'ng' }" @click="switchGui('ng')">
                            <template #prepend><i class="fab fa-angular" style="font-size:18px;width:24px;text-align:center;margin-right:8px;color:#dd0031;"></i></template>
                            <v-list-item-title>Angular</v-list-item-title>
                        </v-list-item>
                        <v-list-item :class="{ 'v-list-item--active': currentGui === 'react' }" @click="switchGui('react')">
                            <template #prepend><i class="fab fa-react" style="font-size:18px;width:24px;text-align:center;margin-right:8px;color:#61dafb;"></i></template>
                            <v-list-item-title>React</v-list-item-title>
                        </v-list-item>
                        <v-list-item :class="{ 'v-list-item--active': currentGui === 'vue' }" @click="switchGui('vue')">
                            <template #prepend><i class="fab fa-vuejs" style="font-size:18px;width:24px;text-align:center;margin-right:8px;color:#42b883;"></i></template>
                            <v-list-item-title>Vue</v-list-item-title>
                        </v-list-item>
                    </v-list>
                </v-menu>
            </v-toolbar>

            <!-- Content -->
            <div class="p3xr-login-content">
                <v-text-field
                    v-model="username" autofocus
                    :label="str(strings?.form?.connection?.label?.username) || 'Username'"
                    autocomplete="username" density="comfortable" variant="outlined" hide-details class="mb-3"
                    @keydown.enter="handleLogin"
                >
                    <template #prepend-inner>
                        <v-icon size="20">mdi-account</v-icon>
                    </template>
                </v-text-field>
                <v-text-field
                    v-model="password"
                    :label="str(strings?.form?.connection?.label?.password) || 'Password'"
                    :type="pwVisible ? 'text' : 'password'"
                    autocomplete="current-password" density="comfortable" variant="outlined" hide-details class="mb-3"
                    @keydown.enter="handleLogin"
                >
                    <template #prepend-inner>
                        <v-icon size="20">mdi-lock</v-icon>
                    </template>
                    <template #append-inner>
                        <v-icon size="20" style="cursor:pointer;" @click="pwVisible = !pwVisible">
                            {{ pwVisible ? 'mdi-eye-off' : 'mdi-eye' }}
                        </v-icon>
                    </template>
                </v-text-field>
                <div v-if="auth.loginError" class="p3xr-login-error">
                    {{ strings?.confirm?.invalidCredentials || 'Invalid username or password.' }}
                </div>
            </div>

            <!-- Footer -->
            <div class="p3xr-login-footer" :style="{ backgroundColor: footerBg }">
                <v-btn color="primary" variant="flat" :disabled="loading || !username || !password" @click="handleLogin">
                    <v-icon size="20" class="mr-1">mdi-login</v-icon>
                    {{ strings?.intention?.ok || 'Login' }}
                </v-btn>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
function str(val: any, opts?: any): string {
    if (typeof val === 'function') return val(opts)
    return val ?? ''
}
</script>

<style scoped>
.p3xr-login-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: calc(100vh - 96px);
}
.p3xr-login-card {
    width: 400px;
    max-width: calc(100vw - 32px);
    border-radius: 4px;
    overflow: hidden;
    box-shadow: 0 11px 15px -7px rgba(0,0,0,.2), 0 24px 38px 3px rgba(0,0,0,.14), 0 9px 46px 8px rgba(0,0,0,.12);
}
.p3xr-login-toolbar {
    box-shadow: none !important;
}
.p3xr-login-content {
    padding: 16px;
    background-color: rgb(var(--v-theme-surface));
    color: rgb(var(--v-theme-on-surface));
}
.p3xr-login-footer {
    padding: 8px;
    display: flex;
    justify-content: flex-end;
    gap: 8px;
}
.p3xr-login-error {
    color: rgb(var(--v-theme-error));
    font-size: 13px;
    margin-top: 4px;
}
</style>
