// src/vue/dialogs/KeyImportDialog.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useDisplay } from 'vuetify'
import { useVirtualizer } from '@tanstack/vue-virtual'
import { useI18nStore } from '../stores/i18n'
import P3xrDialog from '../components/P3xrDialog.vue'

const ROW_HEIGHT = 40

const props = defineProps<{
    open: boolean
    data: { keys: any[] } | null
}>()

const emit = defineEmits<{
    close: [result: { pending: boolean; keys: any[]; conflictMode: string } | null]
}>()

const i18n = useI18nStore()
const strings = computed(() => i18n.strings)
const { width } = useDisplay()
const isWide = computed(() => width.value >= 600)

const conflictMode = ref('overwrite')
const keys = computed(() => props.data?.keys || [])
const parentRef = ref<HTMLDivElement | null>(null)

const virtualizer = useVirtualizer(computed(() => ({
    count: keys.value.length,
    getScrollElement: () => parentRef.value,
    estimateSize: () => ROW_HEIGHT,
    overscan: 10,
})))

function cancel() {
    emit('close', null)
}

function doImport() {
    emit('close', { pending: true, keys: keys.value, conflictMode: conflictMode.value })
}
</script>

<template>
    <P3xrDialog v-if="open && keys.length > 0" :open="true"
        :title="strings?.intention?.importKeys"
        @close="cancel()">

        <!-- Preview label -->
        <div style="margin-bottom: 8px; font-size: 13px; opacity: 0.7;">
            {{ keys.length }} {{ strings?.label?.keysToImport }}
        </div>

        <!-- Virtual scrolled key preview list (300px height, 40px rows) -->
        <div ref="parentRef" class="p3xr-import-preview-list">
            <div :style="{ height: virtualizer.getTotalSize() + 'px', width: '100%', position: 'relative' }">
                <div
                    v-for="virtualRow in virtualizer.getVirtualItems()"
                    :key="keys[virtualRow.index].key"
                    class="p3xr-import-preview-row"
                    :style="{
                        position: 'absolute', top: 0, left: 0, width: '100%',
                        height: ROW_HEIGHT + 'px',
                        transform: 'translateY(' + virtualRow.start + 'px)',
                    }"
                >
                    <span class="p3xr-import-key-name">{{ keys[virtualRow.index].key }}</span>
                    <kbd v-if="keys[virtualRow.index].type" class="p3xr-import-key-type">{{ keys[virtualRow.index].type }}</kbd>
                </div>
            </div>
        </div>

        <!-- Conflict mode radio -->
        <div style="margin-top: 12px;">
            <v-radio-group v-model="conflictMode" inline hide-details>
                <v-radio value="overwrite" :label="strings?.label?.importOverwrite" />
                <v-radio value="skip" :label="strings?.label?.importSkip" />
            </v-radio-group>
        </div>

        <template #actions>
            <v-btn variant="flat" color="warning" @click="cancel()">
                <v-icon :class="{ 'mr-1': isWide }">mdi-close-circle</v-icon>
                <span v-if="isWide">{{ strings?.intention?.cancel }}</span>
                <v-tooltip v-if="!isWide" activator="parent" location="top">{{ strings?.intention?.cancel }}</v-tooltip>
            </v-btn>
            <v-btn variant="flat" color="primary" @click="doImport()">
                <v-icon class="mr-1">mdi-upload</v-icon>
                <span>{{ strings?.intention?.import }}</span>
            </v-btn>
        </template>
    </P3xrDialog>
</template>

<style scoped>
.p3xr-import-preview-list {
    height: 300px;
    overflow-y: auto;
    border: 1px solid rgba(var(--v-border-color), 0.12);
    border-radius: 4px;
}

.p3xr-import-preview-row {
    display: flex;
    align-items: center;
    padding: 0 12px;
    border-bottom: 1px solid rgba(var(--v-border-color), 0.06);
    gap: 8px;
    box-sizing: border-box;
}

.p3xr-import-key-name {
    flex: 1;
    font-family: 'Roboto Mono', monospace;
    font-size: 13px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.p3xr-import-key-type {
    display: inline-block;
    font-family: 'Roboto Mono', monospace;
    font-size: 11px;
    padding: 1px 6px;
    border: 1px solid rgba(var(--v-border-color), 0.2);
    border-radius: 3px;
    background: rgba(128, 128, 128, 0.1);
    white-space: nowrap;
}
</style>

// src/ng/dialogs/key-import-dialog.component.ts
import { Component, Inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatDialogModule, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { MatRadioModule } from '@angular/material/radio';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { DialogCancelButtonComponent } from '../components/dialog-cancel-button.component';
import { I18nService } from '../services/i18n.service';
import { SocketService } from '../services/socket.service';
import { CommonService } from '../services/common.service';

@Component({
    selector: 'p3xr-key-import-dialog',
    standalone: true,
    imports: [
        CommonModule, FormsModule,
        MatDialogModule, MatToolbarModule, MatButtonModule, MatIconModule,
        MatDividerModule, MatRadioModule, ScrollingModule,
        DialogCancelButtonComponent,
    ],
    template: `
        <mat-toolbar class="p3xr-dialog-toolbar p3xr-mat-layout-strong">
            <span mat-dialog-title class="p3xr-dialog-title">
                {{ strings().intention?.importKeys }}
            </span>
            <button mat-icon-button type="button" (click)="cancel()">
                <mat-icon>close</mat-icon>
            </button>
        </mat-toolbar>

        <mat-dialog-content class="p3xr-dialog-content">
            <div class="p3xr-padding">

                <div style="margin-bottom: 16px;">
                    <strong>{{ strings().label?.importPreview }}</strong>
                    <span style="opacity: 0.7; margin-left: 8px;">
                        ({{ data.keys.length }})
                    </span>
                </div>

                <cdk-virtual-scroll-viewport itemSize="40" class="p3xr-import-preview-list">
                    <div *cdkVirtualFor="let entry of data.keys; trackBy: trackByKey" class="p3xr-import-preview-row">
                        <span class="p3xr-import-key-name">{{ entry.key }}</span>
                        <kbd class="p3xr-kbd p3xr-kbd-small">{{ strings().redisTypes?.[entry.type] || entry.type }}</kbd>
                    </div>
                </cdk-virtual-scroll-viewport>

                <div style="margin-top: 16px;">
                    <div style="margin-bottom: 8px; font-weight: 500;">
                        {{ strings().label?.importConflict }}
                    </div>
                    <mat-radio-group [(ngModel)]="conflictMode">
                        <mat-radio-button value="overwrite" style="margin-right: 16px;">
                            {{ strings().label?.importOverwrite }}
                        </mat-radio-button>
                        <mat-radio-button value="skip">
                            {{ strings().label?.importSkip }}
                        </mat-radio-button>
                    </mat-radio-group>
                </div>

            </div>
        </mat-dialog-content>

        <mat-dialog-actions class="p3xr-dialog-actions">
            <p3xr-dialog-cancel (cancel)="cancel()"></p3xr-dialog-cancel>
            <button mat-raised-button class="btn-primary" (click)="doImport()" [disabled]="importing">
                <mat-icon>file_upload</mat-icon>
                {{ importing ? (strings().label?.importProgress) : (strings().intention?.importKeys) }}
            </button>
        </mat-dialog-actions>
    `,
    styles: [`
        .p3xr-import-preview-list { height: 300px; }
        .p3xr-import-preview-row {
            display: flex; align-items: center; justify-content: space-between; width: 100%; gap: 8px;
            height: 40px; padding: 0 16px; box-sizing: border-box;
            border-bottom: 1px solid var(--p3xr-list-border, rgba(0,0,0,0.12));
        }
        .p3xr-import-key-name {
            flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
            font-family: 'Roboto Mono', monospace; font-size: 13px;
        }
    `],
})
export class KeyImportDialogComponent {
    strings;
    conflictMode: 'overwrite' | 'skip' = 'overwrite';
    importing = false;

    constructor(
        @Inject(MatDialogRef) private dialogRef: MatDialogRef<KeyImportDialogComponent>,
        @Inject(MAT_DIALOG_DATA) public data: { keys: any[] },
        @Inject(I18nService) private i18n: I18nService,
        @Inject(SocketService) private socket: SocketService,
        @Inject(CommonService) private common: CommonService,
    ) {
        this.strings = this.i18n.strings;
    }

    trackByKey(_index: number, entry: any): string {
        return entry.key;
    }

    cancel(): void {
        this.dialogRef.close(null);
    }

    async doImport(): Promise<void> {
        const keys = this.data.keys;
        const conflictMode = this.conflictMode;
        this.dialogRef.close({ pending: true, keys, conflictMode });
    }
}
