// src/vue/components/ConfirmDialog.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useDisplay } from 'vuetify'
import { useCommonStore } from '../stores/common.store'
import { useI18nStore } from '../stores/i18n.store'
import P3xrDialog from './P3xrDialog.vue'

const commonStore = useCommonStore()
const i18n = useI18nStore()
const { width } = useDisplay()
const isWide = computed(() => width.value >= 600)

const isAlert = computed(() => commonStore.confirmOptions?.disableCancel === true)
const okLabel = computed(() => isAlert.value ? (i18n.strings?.intention?.ok || 'OK') : (i18n.strings?.intention?.sure || 'Sure'))
const cancelLabel = computed(() => i18n.strings?.intention?.cancel || 'Cancel')

function handleOk() {
    commonStore.resolveConfirm?.(true)
}

function handleCancel() {
    commonStore.resolveConfirm?.(false)
}
</script>

<template>
    <P3xrDialog
        v-if="commonStore.confirmOpen && commonStore.confirmOptions"
        :open="true"
        :title="commonStore.confirmOptions.title || ''"
        width="600px"
        @close="handleCancel"
    >
        <div v-html="commonStore.confirmOptions.message" />

        <template #actions>
            <v-btn
                v-if="!isAlert"
                variant="flat"
                color="warning"
                :aria-label="cancelLabel"
                @click="handleCancel"
            >
                <v-icon :class="{ 'mr-1': isWide }">mdi-close-circle</v-icon>
                <span v-if="isWide">{{ cancelLabel }}</span>
                <v-tooltip v-if="!isWide" activator="parent" location="top">{{ cancelLabel }}</v-tooltip>
            </v-btn>

            <v-btn
                variant="flat"
                color="primary"
                @click="handleOk"
            >
                <v-icon class="mr-1">mdi-check</v-icon>
                <span>{{ okLabel }}</span>
            </v-btn>
        </template>
    </P3xrDialog>
</template>

// src/react/components/ConfirmDialog.tsx
import { Button, Tooltip, useMediaQuery } from '@mui/material'
import { Done, Cancel } from '@mui/icons-material'
import { useI18nStore } from '../stores/i18n.store'
import { useCommonStore } from '../stores/common.store'
import P3xrDialog from './P3xrDialog'

export default function ConfirmDialog() {
    const strings = useI18nStore(s => s.strings)
    const { confirmOpen, confirmOptions, resolveConfirm } = useCommonStore()
    const isWide = useMediaQuery('(min-width: 600px)')

    if (!confirmOpen || !confirmOptions) return null

    const isAlert = confirmOptions.disableCancel === true
    const okLabel = isAlert ? strings?.intention?.ok : strings?.intention?.sure
    const cancelLabel = strings?.intention?.cancel

    return (
        <P3xrDialog
            open
            onClose={() => resolveConfirm?.(false)}
            title={confirmOptions.title}
            width="600px"
            actions={
                <>
                    {!isAlert && (
                        <Tooltip title={isWide ? '' : cancelLabel} placement="top">
                            <Button variant="contained" color="warning" onClick={() => resolveConfirm?.(false)}>
                                <Cancel sx={isWide ? { mr: 0.5 } : undefined} />
                                {isWide && <span>{cancelLabel}</span>}
                            </Button>
                        </Tooltip>
                    )}
                    <Button variant="contained" color="primary" onClick={() => resolveConfirm?.(true)}>
                        <Done sx={{ mr: 0.5 }} /><span>{okLabel}</span>
                    </Button>
                </>
            }
        >
            <div dangerouslySetInnerHTML={{ __html: confirmOptions.message }} />
        </P3xrDialog>
    )
}
