// src/vue/components/P3xrButton.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useDisplay } from 'vuetify'

const props = withDefaults(defineProps<{
    label: string
    icon?: string
    raised?: boolean
    color?: string
    disabled?: boolean
    tooltipPlacement?: 'top' | 'bottom' | 'left' | 'right'
    breakpoint?: number
}>(), {
    raised: false,
    color: 'inherit',
    disabled: false,
    tooltipPlacement: 'top',
    breakpoint: 720,
})

const emit = defineEmits<{ click: [e: MouseEvent] }>()

const { width: displayWidth } = useDisplay()
const isWide = computed(() => displayWidth.value >= props.breakpoint)
</script>

<template>
    <!-- Wide: icon + text -->
    <v-btn v-if="isWide"
        :variant="raised ? 'flat' : 'text'"
        :color="color"
        :disabled="disabled"
        @click="emit('click', $event)"
        style="gap: 3px;"
    >
        <v-icon v-if="icon">{{ icon }}</v-icon>
        <span>{{ label }}</span>
    </v-btn>

    <!-- Narrow + raised: small contained button with tooltip -->
    <v-tooltip v-else-if="raised" :text="label" :location="tooltipPlacement">
        <template #activator="{ props: tp }">
            <v-btn v-bind="tp"
                :color="color === 'inherit' ? 'primary' : color"
                :disabled="disabled"
                variant="flat"
                size="small"
                @click="emit('click', $event)"
                style="border-radius: 4px; box-shadow: none; min-width: 40px; width: 40px; height: 36px; padding: 0;"
            >
                <v-icon v-if="icon">{{ icon }}</v-icon>
            </v-btn>
        </template>
    </v-tooltip>

    <!-- Narrow + flat: icon-only button with tooltip -->
    <v-tooltip v-else :text="label" :location="tooltipPlacement">
        <template #activator="{ props: tp }">
            <v-btn v-bind="tp"
                :color="color"
                :disabled="disabled"
                variant="text"
                icon
                size="small"
                @click="emit('click', $event)"
                style="border-radius: 4px; margin: 0;"
            >
                <v-icon v-if="icon">{{ icon }}</v-icon>
            </v-btn>
        </template>
    </v-tooltip>
</template>

// src/react/components/P3xrButton.tsx
import { ReactNode } from 'react'
import { Button, IconButton, Fab, Tooltip, useMediaQuery } from '@mui/material'

/**
 * Responsive button — shows icon+text on wide screens, icon-only+tooltip on narrow.
 * Matches Angular p3xr-ng-button (720px breakpoint).
 *
 * raised=false: text button (Button variant="text") / icon button
 * raised=true:  contained button (Button variant="contained") / mini fab style
 */
interface P3xrButtonProps {
    label: string
    icon?: ReactNode
    raised?: boolean
    color?: 'inherit' | 'primary' | 'secondary' | 'error' | 'success' | 'warning' | 'info'
    disabled?: boolean
    tooltipPlacement?: 'top' | 'bottom' | 'left' | 'right'
    breakpoint?: number
    onClick?: (e: React.MouseEvent) => void
}

export default function P3xrButton({
    label,
    icon,
    raised = false,
    color = 'inherit',
    disabled = false,
    tooltipPlacement = 'top',
    breakpoint = 720,
    onClick,
}: P3xrButtonProps) {
    const isWide = useMediaQuery(`(min-width: ${breakpoint}px)`)

    if (isWide) {
        return (
            <Button
                variant={raised ? 'contained' : 'text'}
                color={color}
                disabled={disabled}
                onClick={onClick}
                sx={{ gap: '3px' }}
            >
                {icon}
                <span>{label}</span>
            </Button>
        )
    }

    if (raised) {
        return (
            <Tooltip title={label} placement={tooltipPlacement}>
                <span>
                    <Fab
                        size="small"
                        color={color === 'inherit' ? 'primary' : color}
                        disabled={disabled}
                        onClick={onClick}
                        sx={{ borderRadius: '4px', boxShadow: 'none' }}
                    >
                        {icon}
                    </Fab>
                </span>
            </Tooltip>
        )
    }

    return (
        <Tooltip title={label} placement={tooltipPlacement}>
            <span>
                <IconButton
                    color={color}
                    disabled={disabled}
                    onClick={onClick}
                    sx={{
                        borderRadius: '4px',
                        m: 0,
                    }}
                >
                    {icon}
                </IconButton>
            </span>
        </Tooltip>
    )
}
