// src/react/layout/Layout.tsx
import { useState, useRef, useEffect, useCallback, useMemo } from 'react'
import {
    AppBar, Toolbar, Button, IconButton, Typography, Menu, MenuItem,
    Divider, Tooltip, Box, useMediaQuery,
} from '@mui/material'
import {
    Storage, MonitorHeart, Search, Info, Settings,
    Power, PowerOff, Language,
} from '@mui/icons-material'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { ColorLens } from '@mui/icons-material'
import { useI18nStore } from '../stores/i18n.store'
import { useThemeStore } from '../stores/theme.store'
import { useRedisStateStore } from '../stores/redis-state.store'
import { useSettingsStore } from '../stores/settings.store'
import { useCommonStore } from '../stores/common.store'
import { useOverlayStore } from '../stores/overlay.store'
import { useMainCommandStore } from '../stores/main-command.store'
import { request, onSocketEvent } from '../stores/socket.service'
import { trackPage } from '../stores/analytics'
import { ALL_THEME_KEYS } from '../themes'

const TOOLBAR_HEIGHT = 48
const LAYOUT_PADDING = 5

export default function Layout() {
    const navigate = useNavigate()
    const location = useLocation()

    // Stores
    const strings = useI18nStore(s => s.strings)
    const currentLang = useI18nStore(s => s.currentLang)
    const isLangAuto = useI18nStore(s => s.isAuto)
    const setLanguage = useI18nStore(s => s.setLanguage)
    const { themeKey, isAuto, setTheme } = useThemeStore()
    const connection = useRedisStateStore(s => s.connection)
    const connections = useRedisStateStore(s => s.connections)
    const version = useRedisStateStore(s => s.version)
    const hasRediSearch = useRedisStateStore(s => s.hasRediSearch)
    const settings = useSettingsStore()
    const { generalHandleError } = useCommonStore()
    const overlay = useOverlayStore()
    const { disconnect } = useMainCommandStore()

    const { askAuth } = useCommonStore()

    // Connect to a Redis connection (exact port of Angular LayoutComponent.connect)
    const connect = async (conn: any) => {
        const cloned = structuredClone(conn)
        try {
            const dbStorageKey = settings.getStorageKeyCurrentDatabase(cloned.id)
            let db: string | undefined
            try { db = localStorage.getItem(dbStorageKey) ?? undefined } catch {}

            if (cloned.askAuth === true) {
                try {
                    const auth = await askAuth()
                    cloned.username = auth.username || undefined
                    cloned.password = auth.password || undefined
                } catch {
                    return // user cancelled
                }
            }

            overlay.show({ message: strings?.title?.connectingRedis })

            const response = await request({
                action: 'connection-connect',
                payload: { connection: cloned, db },
            })

            // Update state
            const databaseIndexes: number[] = []
            let i = 0
            while (i < response.databases) databaseIndexes.push(i++)

            const commands: string[] = []
            Object.keys(response.commands ?? {}).forEach(k => {
                commands.push(response.commands[k][0])
            })
            commands.sort()

            const modules = Array.isArray(response.modules) ? response.modules : []

            useRedisStateStore.setState({
                page: 1,
                monitor: false,
                dbsize: response.dbsize,
                databaseIndexes,
                connection: cloned,
                commands,
                commandsMeta: response.commandsMeta ?? {},
                modules,
                hasReJSON: modules.some((m: any) => m.name === 'ReJSON'),
                hasRediSearch: modules.some((m: any) => m.name === 'search'),
                hasTimeSeries: modules.some((m: any) => m.name === 'timeseries' || m.name === 'Timeseries'),
            })

            useCommonStore.getState().loadRedisInfoResponse({ response })

            // Save last connection to localStorage
            try { localStorage.setItem(settings.connectInfoStorageKey, JSON.stringify(cloned)) } catch {}
        } catch (error) {
            try { localStorage.removeItem(settings.connectInfoStorageKey) } catch {}
            useRedisStateStore.setState({ connection: undefined })
            generalHandleError(error)
        } finally {
            overlay.hide()
        }
    }

    // Responsive breakpoints matching Angular layout
    const isWide = useMediaQuery('(min-width: 720px)')
    const isGtXs = useMediaQuery('(min-width: 600px)')
    const isGtSm = useMediaQuery('(min-width: 960px)')

    const isElectron = useMemo(() => /electron/i.test(navigator.userAgent), [])
    const connectionsList = connections?.list ?? []

    // Connection name (computed, matches Angular)
    const connectionName = useMemo(() => {
        if (connection) {
            const fn = strings?.label?.connected
            return typeof fn === 'function' ? fn({ name: connection.name }) : connection.name
        }
        return strings?.intention?.connect
    }, [connection, strings])

    // Track group mode reactively (Settings page toggles this in localStorage)
    const [groupMode, setGroupMode] = useState(() => {
        try { return localStorage.getItem('p3xr-connection-group-mode') === 'true' } catch { return false }
    })
    useEffect(() => {
        const check = () => {
            try { setGroupMode(localStorage.getItem('p3xr-connection-group-mode') === 'true') } catch {}
        }
        window.addEventListener('storage', check)
        // Also poll since same-tab localStorage changes don't fire 'storage'
        const interval = setInterval(check, 1000)
        return () => { window.removeEventListener('storage', check); clearInterval(interval) }
    }, [])

    // Grouped connections
    const groupedConnectionsList = useMemo(() => {
        if (!groupMode) return [{ name: '', connections: connectionsList }]
        const groups = new Map<string, any[]>()
        for (const conn of connectionsList) {
            const name = conn.group?.trim() || ''
            if (!groups.has(name)) groups.set(name, [])
            groups.get(name)!.push(conn)
        }
        return Array.from(groups, ([name, conns]) => ({ name, connections: conns }))
    }, [connectionsList, groupMode])

    const isActivePage = (page: string) => {
        const url = location.pathname
        switch (page) {
            case 'database': return url.startsWith('/database')
            case 'search': return url === '/search'
            case 'monitoring': return url.startsWith('/monitoring')
            case 'info': return url === '/info'
            case 'settings': return url === '/settings'
            default: return false
        }
    }

    const navigateTo = (stateName: string) => {
        const routes: Record<string, string> = {
            'database.statistics': '/database/statistics',
            'database': '/database',
            'monitoring': '/monitoring',
            'search': '/search',
            'info': '/info',
            'settings': '/settings',
        }
        navigate(routes[stateName] || `/${stateName}`)
    }

    const openLink = (target: string) => {
        const urls: Record<string, string> = {
            github: 'https://github.com/patrikx3/redis-ui',
            githubRelease: 'https://github.com/patrikx3/redis-ui/releases',
            githubChangelog: 'https://github.com/patrikx3/redis-ui/blob/master/change-log.md#change-log',
            donate: 'https://www.paypal.me/patrikx3',
        }
        window.open(urls[target], '_blank')
    }

    // --- Menu anchors ---
    const [connectionAnchor, setConnectionAnchor] = useState<null | HTMLElement>(null)
    const [themeAnchor, setThemeAnchor] = useState<null | HTMLElement>(null)
    const [githubAnchor, setGithubAnchor] = useState<null | HTMLElement>(null)
    const [languageAnchor, setLanguageAnchor] = useState<null | HTMLElement>(null)

    // --- Language menu with search ---
    const [languageSearch, setLanguageSearch] = useState('')
    const [highlightedLangIdx, setHighlightedLangIdx] = useState(0)
    const languageInputRef = useRef<HTMLInputElement>(null)

    // Close language menu on resize to avoid stale positioning
    useEffect(() => {
        const onResize = () => { if (languageAnchor) setLanguageAnchor(null) }
        window.addEventListener('resize', onResize)
        return () => window.removeEventListener('resize', onResize)
    }, [languageAnchor])

    const availableLanguages = useMemo(() =>
        Object.keys(strings?.language ?? {}), [strings])

    const filteredLanguages = useMemo(() => {
        const search = languageSearch.trim().toLowerCase()
        if (!search) return availableLanguages
        return availableLanguages.filter(key => {
            const label = (strings?.language?.[key] ?? key).toLowerCase()
            return label.includes(search) || key.toLowerCase().includes(search)
        })
    }, [availableLanguages, languageSearch, strings])

    const languageLabel = useCallback((key: string): string =>
        strings?.language?.[key] ?? key, [strings])

    const onLanguageMenuOpen = () => {
        const idx = filteredLanguages.indexOf(currentLang)
        setHighlightedLangIdx(idx >= 0 ? idx : 0)
        // MUI Menu needs time to render before we can focus the input and scroll
        setTimeout(() => {
            languageInputRef.current?.focus()
            // Scroll current language into view
            const menu = document.querySelector('.p3xr-language-menu .MuiList-root')
            if (menu) {
                const items = menu.querySelectorAll('.MuiMenuItem-root')
                const target = items[idx >= 0 ? idx : 0]
                target?.scrollIntoView({ block: 'nearest' })
            }
        }, 150)
    }

    const onLanguageMenuClose = () => {
        setLanguageSearch('')
    }

    const onLanguageKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Escape') {
            setLanguageAnchor(null)
            return
        }
        if (e.key === 'Enter') {
            e.preventDefault()
            if (filteredLanguages.length > 0) {
                setLanguage(filteredLanguages[highlightedLangIdx])
                setLanguageAnchor(null)
            }
            return
        }
        if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
            e.preventDefault()
            const len = filteredLanguages.length
            if (!len) return
            setHighlightedLangIdx(prev =>
                e.key === 'ArrowDown' ? (prev + 1) % len : (prev - 1 + len) % len
            )
            return
        }
        e.stopPropagation()
    }

    // Scroll highlighted language into view
    useEffect(() => {
        if (!languageAnchor) return
        setTimeout(() => {
            const menu = document.querySelector('.p3xr-language-menu .MuiList-root')
            if (!menu) return
            const items = menu.querySelectorAll('.MuiMenuItem-root')
            items[highlightedLangIdx]?.scrollIntoView({ block: 'nearest' })
        })
    }, [highlightedLangIdx, languageAnchor])

    // --- Electron bridge ---
    useEffect(() => {
        if (!isElectron) return
        const handler = (event: MessageEvent) => {
            const data = event.data
            if (!data || typeof data.type !== 'string') return
            if (data.type === 'p3x-set-language' && typeof data.translation === 'string') {
                setLanguage(data.translation)
            } else if (data.type === 'p3x-menu' && typeof data.action === 'string') {
                navigateTo(data.action)
            }
        }
        window.addEventListener('message', handler)
        return () => { window.removeEventListener('message', handler) }
    }, [isElectron])

    // Remove loading splash
    useEffect(() => {
        document.getElementById('p3xr-loading')?.remove()
    }, [])

    // Auto-connect from localStorage on startup
    useEffect(() => {
        try {
            const saved = localStorage.getItem(settings.connectInfoStorageKey)
            if (saved) {
                const conn = JSON.parse(saved)
                if (conn?.id) connect(conn)
            }
        } catch {}
    }, [])

    // Subscribe to redis disconnect → navigate to settings
    useEffect(() => {
        const unsub = onSocketEvent('redis-disconnected', () => {
            navigateTo('settings')
        })
        return unsub
    }, [])

    // Track route changes for analytics (matches Angular setupRouteTracking)
    useEffect(() => {
        const path = location.pathname.toLowerCase().startsWith('/database/key/')
            ? '/database/key'
            : location.pathname
        trackPage(path)
    }, [location.pathname])

    // Show overlay on raw socket disconnect/error (matches Angular behavior)
    useEffect(() => {
        const unsubDisconnect = onSocketEvent('disconnect', () => {
            overlay.show({ message: strings?.status?.socketDisconnected || 'Disconnected' })
        })
        const unsubError = onSocketEvent('socket-error', () => {
            overlay.show({ message: strings?.status?.socketError || 'Connection error' })
        })
        return () => { unsubDisconnect(); unsubError() }
    }, [strings])

    // --- Responsive button helpers ---
    const activeSx = { bgcolor: 'rgba(255,255,255,0.1)' }

    const NavBtn = ({ icon, label, tooltip, page, onClick }: {
        icon: React.ReactNode, label: string, tooltip?: string, page?: string, onClick: () => void
    }) => {
        const active = page ? isActivePage(page) : false
        return isWide ? (
            <Button color="inherit" onClick={onClick} sx={active ? activeSx : undefined}>
                {icon}<span>{label}</span>
            </Button>
        ) : (
            <Tooltip title={tooltip || label} placement="bottom">
                <IconButton color="inherit" onClick={onClick} sx={active ? activeSx : undefined}>
                    {icon}
                </IconButton>
            </Tooltip>
        )
    }

    const FooterBtn = ({ icon, label, onClick, bp = 'wide' }: {
        icon: React.ReactNode, label: string, onClick: (e: React.MouseEvent<HTMLButtonElement>) => void,
        bp?: 'wide' | 'gtXs' | 'gtSm'
    }) => {
        const show = bp === 'gtXs' ? isGtXs : bp === 'gtSm' ? isGtSm : isWide
        return show ? (
            <Button color="inherit" onClick={onClick}>
                {icon}<span>{label}</span>
            </Button>
        ) : (
            <Tooltip title={label} placement="top">
                <IconButton color="inherit" onClick={onClick}>
                    {icon}
                </IconButton>
            </Tooltip>
        )
    }

    return (
        <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', bgcolor: 'background.default' }}>
            {/* ===== HEADER ===== */}
            <AppBar position="fixed" sx={{ height: TOOLBAR_HEIGHT, zIndex: 2 }}>
                <Toolbar variant="dense" sx={{ minHeight: TOOLBAR_HEIGHT, height: TOOLBAR_HEIGHT, overflow: 'hidden' }}>
                    <NavBtn icon={<i className="fas fa-database" />}
                        label={strings?.title?.name}
                        tooltip={`${strings?.title?.name || ''}${version ? ' ' + version : ''}`}
                        onClick={() => navigateTo(connection ? 'database.statistics' : 'settings')} />

                    {connection && (
                        <NavBtn icon={<Storage fontSize="small" />}
                            label={strings?.intention?.main}
                            page="database" onClick={() => navigateTo('database.statistics')} />
                    )}

                    {connection && (
                        <NavBtn icon={<MonitorHeart fontSize="small" />}
                            label={strings?.page?.monitor?.title}
                            page="monitoring" onClick={() => navigateTo('monitoring')} />
                    )}

                    {connection && hasRediSearch && (
                        <NavBtn icon={<Search fontSize="small" />}
                            label={strings?.page?.search?.title}
                            page="search" onClick={() => navigateTo('search')} />
                    )}

                    <Box sx={{ flex: 1, minWidth: 8 }} />

                    <NavBtn icon={<Info fontSize="small" />}
                        label={strings?.intention?.info}
                        page="info" onClick={() => navigateTo('info')} />

                    <NavBtn icon={<Settings fontSize="small" />}
                        label={strings?.intention?.settings}
                        page="settings" onClick={() => navigateTo('settings')} />
                </Toolbar>
            </AppBar>

            {/* Version overlay */}
            {!isElectron && version && isWide && (
                <Typography variant="caption" sx={{
                    position: 'fixed', top: 31, left: 20, width: 120,
                    textAlign: 'right', zIndex: 3, fontSize: 10, opacity: 0.7, pointerEvents: 'none',
                }}>
                    {version}
                </Typography>
            )}

            {/* ===== CONTENT ===== */}
            <Box id="p3xr-layout-content" sx={{
                position: 'absolute', left: 0, right: 0,
                top: TOOLBAR_HEIGHT,
                bottom: TOOLBAR_HEIGHT,
                padding: `${LAYOUT_PADDING}px`,
                overflow: 'auto',
                display: 'flex',
                flexDirection: 'column',
            }}>
                <Outlet />
            </Box>

            {/* ===== FOOTER ===== */}
            <AppBar id="p3xr-layout-footer-container" position="fixed" sx={{ top: 'auto', bottom: 0, height: TOOLBAR_HEIGHT, zIndex: 2 }}>
                <Toolbar variant="dense" sx={{ minHeight: TOOLBAR_HEIGHT, height: TOOLBAR_HEIGHT }}>

                    {/* Connection menu */}
                    {connectionsList.length > 0 && (
                        <>
                            {isWide ? (
                                <Button color="inherit" onClick={e => setConnectionAnchor(e.currentTarget)}>
                                    <Power fontSize="small" /><span>{connectionName}</span>
                                </Button>
                            ) : (
                                <Tooltip title={connectionName} placement="top">
                                    <IconButton color="inherit" onClick={e => setConnectionAnchor(e.currentTarget)}>
                                        <Power fontSize="small" />
                                    </IconButton>
                                </Tooltip>
                            )}
                            <Menu anchorEl={connectionAnchor} open={Boolean(connectionAnchor)}
                                onClose={() => setConnectionAnchor(null)}
                                anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
                                transformOrigin={{ vertical: 'bottom', horizontal: 'left' }}>
                                {groupedConnectionsList.map((group, gi) => [
                                    groupedConnectionsList.length > 1 && (
                                        <Box key={`g-${gi}`} sx={{
                                            px: 2, pt: 0.75, pb: 0.25, fontSize: 11, fontWeight: 600,
                                            textTransform: 'uppercase', letterSpacing: 0.5, opacity: 0.6,
                                            pointerEvents: 'none',
                                        }}>
                                            {group.name || strings?.label?.ungrouped}
                                        </Box>
                                    ),
                                    ...group.connections.map((conn: any) => (
                                        <MenuItem key={conn.id}
                                            selected={connection?.id === conn.id}
                                            onClick={() => { setConnectionAnchor(null); connect(conn) }}>
                                            {conn.name}
                                        </MenuItem>
                                    )),
                                    gi < groupedConnectionsList.length - 1 && groupedConnectionsList.length > 1 && (
                                        <Divider key={`d-${gi}`} />
                                    ),
                                ])}
                            </Menu>
                        </>
                    )}

                    {/* Disconnect */}
                    {connection && (
                        <FooterBtn icon={<i className="fa fa-power-off" />}
                            label={strings?.intention?.disconnect}
                            bp="gtSm" onClick={() => disconnect()} />
                    )}

                    <Box sx={{ flex: 1 }} />

                    {/* Donate */}
                    <FooterBtn icon={<i className="fas fa-donate" />}
                        label={strings?.title?.donate}
                        onClick={() => openLink('donate')} />

                    {/* Language menu with search */}
                    {isGtSm ? (
                        <Button color="inherit" onClick={e => { setLanguageAnchor(e.currentTarget); onLanguageMenuOpen() }}>
                            <Language fontSize="small" /><span>{strings?.intention?.language}</span>
                        </Button>
                    ) : (
                        <Tooltip title={strings?.intention?.language} placement="top">
                            <IconButton color="inherit" onClick={e => { setLanguageAnchor(e.currentTarget); onLanguageMenuOpen() }}>
                                <Language fontSize="small" />
                            </IconButton>
                        </Tooltip>
                    )}
                    <Menu anchorEl={languageAnchor} open={Boolean(languageAnchor)}
                        onClose={() => { setLanguageAnchor(null); onLanguageMenuClose() }}
                        className="p3xr-language-menu"
                        anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
                        transformOrigin={{ vertical: 'bottom', horizontal: 'left' }}
                        slotProps={{
                            paper: { sx: { minWidth: 320, maxWidth: '90vw', maxHeight: 400, overflow: 'hidden' } },
                            list: { sx: { pt: 0, overflow: 'auto', maxHeight: 400 } },
                        }}>
                        <Box
                            sx={{
                                position: 'sticky', top: 0, zIndex: 1,
                                bgcolor: 'background.paper',
                                backgroundImage: 'inherit',
                                px: 1, py: 1,
                                overflow: 'hidden',
                            }}
                            onClick={e => e.stopPropagation()}
                            onKeyDown={onLanguageKeyDown}
                        >
                            <Box
                                component="input"
                                ref={languageInputRef}
                                placeholder={strings?.label?.searchLanguage}
                                value={languageSearch}
                                onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                                    setLanguageSearch(e.target.value)
                                    setHighlightedLangIdx(0)
                                }}
                                autoComplete="off"
                                sx={{
                                    display: 'block', width: '100%', mx: 'auto',
                                    px: 1, py: 1, borderStyle: 'solid', borderWidth: 2,
                                    borderColor: 'rgba(255,255,255,0.25)',
                                    borderRadius: '4px', fontSize: 14,
                                    bgcolor: 'transparent',
                                    color: 'text.primary',
                                    outline: 'none', boxSizing: 'border-box',
                                    overflow: 'hidden', textOverflow: 'ellipsis',
                                    '&:focus': {
                                        borderWidth: 3,
                                        borderColor: 'primary.main',
                                    },
                                    '&::placeholder': {
                                        color: 'text.secondary',
                                        opacity: 0.5,
                                    },
                                }}
                            />
                        </Box>
                        <MenuItem selected={isLangAuto}
                            sx={{ borderRadius: 0, '&:hover': { borderRadius: 0 }, '&.Mui-selected': { borderRadius: 0 } }}
                            onClick={() => { setLanguage('auto'); setLanguageAnchor(null) }}>
                            {strings?.label?.languageAuto || 'Auto (system)'}
                        </MenuItem>
                        <Divider />
                        {filteredLanguages.map((key, i) => (
                            <MenuItem key={key}
                                selected={!isLangAuto && currentLang === key}
                                sx={{
                                    borderRadius: 0,
                                    ...(!isLangAuto && currentLang === key && { bgcolor: 'action.selected' }),
                                    ...(i === highlightedLangIdx && { bgcolor: 'action.hover' }),
                                    '&:hover': { borderRadius: 0 },
                                    '&.Mui-selected': { borderRadius: 0 },
                                }}
                                onClick={() => { setLanguage(key); setLanguageAnchor(null) }}>
                                {languageLabel(key)}
                            </MenuItem>
                        ))}
                    </Menu>

                    {/* Theme menu — exact port of Angular theme menu */}
                    {isGtXs ? (
                        <Button color="inherit" onClick={e => setThemeAnchor(e.currentTarget)}>
                            <ColorLens fontSize="small" /><span>{strings?.intention?.theme}</span>
                        </Button>
                    ) : (
                        <Tooltip title={strings?.intention?.theme} placement="top">
                            <IconButton color="inherit" onClick={e => setThemeAnchor(e.currentTarget)}>
                                <ColorLens fontSize="small" />
                            </IconButton>
                        </Tooltip>
                    )}
                    <Menu anchorEl={themeAnchor} open={Boolean(themeAnchor)}
                        onClose={() => setThemeAnchor(null)}
                        anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
                        transformOrigin={{ vertical: 'bottom', horizontal: 'left' }}>
                        <MenuItem selected={isAuto}
                            onClick={() => { setTheme('auto'); setThemeAnchor(null) }}>
                            {strings?.label?.themeAuto}
                        </MenuItem>
                        <Divider />
                        {ALL_THEME_KEYS.map(key => (
                            <MenuItem key={key}
                                selected={!isAuto && themeKey === key}
                                onClick={() => { setTheme(key); setThemeAnchor(null) }}>
                                {strings?.label?.theme?.[key] ?? key}
                            </MenuItem>
                        ))}
                    </Menu>

                    {/* GitHub menu */}
                    {isGtSm ? (
                        <Button color="inherit" onClick={e => setGithubAnchor(e.currentTarget)}>
                            <i className="fab fa-github" /><span>{strings?.intention?.github}</span>
                        </Button>
                    ) : (
                        <Tooltip title={strings?.intention?.github} placement="top">
                            <IconButton color="inherit" onClick={e => setGithubAnchor(e.currentTarget)}>
                                <i className="fab fa-github" />
                            </IconButton>
                        </Tooltip>
                    )}
                    <Menu anchorEl={githubAnchor} open={Boolean(githubAnchor)}
                        onClose={() => setGithubAnchor(null)}
                        anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
                        transformOrigin={{ vertical: 'bottom', horizontal: 'left' }}>
                        <MenuItem onClick={() => { openLink('github'); setGithubAnchor(null) }}>
                            {strings?.intention?.githubRepo}
                        </MenuItem>
                        <MenuItem onClick={() => { openLink('githubRelease'); setGithubAnchor(null) }}>
                            {strings?.intention?.githubRelease}
                        </MenuItem>
                        <MenuItem onClick={() => { openLink('githubChangelog'); setGithubAnchor(null) }}>
                            {strings?.intention?.githubChangelog}
                        </MenuItem>
                    </Menu>

                </Toolbar>
            </AppBar>
        </Box>
    )
}

// src/vue/layout/Layout.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, nextTick, defineAsyncComponent } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useDisplay } from 'vuetify'
import { storeToRefs } from 'pinia'
import { useI18nStore } from '../stores/i18n'
import { useThemeStore, ALL_THEME_KEYS } from '../stores/theme'
import { useRedisStateStore } from '../stores/redis-state'
import { useSettingsStore } from '../stores/settings'
import { useCommonStore } from '../stores/common'
import { useOverlayStore } from '../stores/overlay'
import { useMainCommandStore } from '../stores/main-command'
import { useAuthStore } from '../stores/auth'
import { request, onSocketEvent } from '../stores/socket.service'
import { setNavigate } from '../stores/navigation.store'
import { trackPage } from '../stores/analytics'

const TOOLBAR_HEIGHT = 48

const router = useRouter()
const route = useRoute()
const { width: displayWidth } = useDisplay()

const i18n = useI18nStore()
const themeStore = useThemeStore()
const state = useRedisStateStore()
const settings = useSettingsStore()
const common = useCommonStore()
const overlay = useOverlayStore()
const mainCommand = useMainCommandStore()
const auth = useAuthStore()

const { themeKey, isAuto: isThemeAuto } = storeToRefs(themeStore)
const strings = computed(() => i18n.strings)
const showLogin = computed(() => auth.authChecked && auth.authRequired && !auth.isAuthenticated)

setNavigate((path: string) => router.push(path))

// Responsive breakpoints (exact match of React)
const isWide = computed(() => displayWidth.value >= 720)
const isGtXs = computed(() => displayWidth.value >= 600)
const isGtSm = computed(() => displayWidth.value >= 960)

const connectionsList = computed(() => state.connections?.list ?? [])

// Toolbar background per theme (exact from React themes/index.ts)
const TOOLBAR_COLORS: Record<string, { bg: string, color: string }> = {
    enterprise: { bg: '#424242', color: 'rgba(255,255,255,0.87)' },
    light: { bg: '#37474f', color: 'rgba(255,255,255,0.87)' },
    redis: { bg: '#c62828', color: 'rgba(255,255,255,0.87)' },
    dark: { bg: '#424242', color: 'rgba(255,255,255,0.87)' },
    darkNeu: { bg: '#37474f', color: 'rgba(255,255,255,0.87)' },
    darkoBluo: { bg: '#1a237e', color: 'rgba(255,255,255,0.87)' },
    matrix: { bg: '#76ff03', color: 'rgba(0,0,0,0.87)' },
}
const toolbarStyle = computed(() => {
    const t = TOOLBAR_COLORS[themeKey.value] || TOOLBAR_COLORS.dark
    return { backgroundColor: t.bg, color: t.color, height: TOOLBAR_HEIGHT + 'px' }
})

// Connection name
const connectionName = computed(() => {
    if (state.connection) {
        const fn = strings.value?.label?.connected
        return typeof fn === 'function' ? fn({ name: state.connection.name }) : state.connection.name
    }
    return strings.value?.intention?.connect
})

// Group mode
const groupMode = ref(false)
try { groupMode.value = localStorage.getItem('p3xr-connection-group-mode') === 'true' } catch {}
const groupedConnectionsList = computed(() => {
    if (!groupMode.value) return [{ name: '', connections: connectionsList.value }]
    const groups = new Map<string, any[]>()
    for (const conn of connectionsList.value) {
        const name = conn.group?.trim() || ''
        if (!groups.has(name)) groups.set(name, [])
        groups.get(name)!.push(conn)
    }
    return Array.from(groups, ([name, conns]) => ({ name, connections: conns }))
})

// Menu states
const connectionMenuOpen = ref(false)
const themeMenuOpen = ref(false)
const githubMenuOpen = ref(false)
const languageMenuOpen = ref(false)

// Language search
const languageSearch = ref('')
const highlightedLangIdx = ref(0)
const languageInputRef = ref<HTMLInputElement | null>(null)
const languageListRef = ref<HTMLElement | null>(null)
const availableLanguages = computed(() => Object.keys(strings.value?.language ?? {}))
const filteredLanguages = computed(() => {
    const s = languageSearch.value.trim().toLowerCase()
    if (!s) return availableLanguages.value
    return availableLanguages.value.filter(k => {
        const label = (strings.value?.language?.[k] ?? k).toLowerCase()
        return label.includes(s) || k.toLowerCase().includes(s)
    })
})
function languageLabel(key: string) { return strings.value?.language?.[key] ?? key }

function scrollLanguageIntoView(idx: number) {
    nextTick(() => {
        const el = languageListRef.value?.$el || languageListRef.value
        if (!el) return
        // +1 to skip the "Auto" item at index 0
        const items = el.querySelectorAll('.v-list-item')
        items[idx + 1]?.scrollIntoView({ block: 'nearest' })
    })
}

function onLanguageMenuOpen() {
    const idx = filteredLanguages.value.indexOf(i18n.currentLang)
    highlightedLangIdx.value = idx >= 0 ? idx : 0
    setTimeout(() => {
        languageInputRef.value?.focus()
        scrollLanguageIntoView(idx >= 0 ? idx : 0)
    }, 150)
}
function onLanguageMenuClose() { languageSearch.value = '' }
function onLanguageKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') { languageMenuOpen.value = false; return }
    if (e.key === 'Enter') {
        e.preventDefault()
        if (filteredLanguages.value.length > 0) {
            i18n.setLanguage(filteredLanguages.value[highlightedLangIdx.value])
            languageMenuOpen.value = false
        }
        return
    }
    if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        e.preventDefault()
        const len = filteredLanguages.value.length
        if (!len) return
        highlightedLangIdx.value = e.key === 'ArrowDown'
            ? (highlightedLangIdx.value + 1) % len
            : (highlightedLangIdx.value - 1 + len) % len
        return
    }
    e.stopPropagation()
}
watch(highlightedLangIdx, (idx) => {
    if (!languageMenuOpen.value) return
    scrollLanguageIntoView(idx)
})

// Navigation
function isActivePage(page: string): boolean {
    const p = route.path
    if (page === 'database') return p.startsWith('/database')
    if (page === 'monitoring') return p.startsWith('/monitoring')
    return p === `/${page}`
}
function navigateTo(name: string) {
    const map: Record<string, string> = {
        'database.statistics': '/database/statistics', database: '/database',
        monitoring: '/monitoring', search: '/search', info: '/info', settings: '/settings',
    }
    router.push(map[name] || `/${name}`)
}
function openLink(target: string) {
    const urls: Record<string, string> = {
        github: 'https://github.com/patrikx3/redis-ui',
        githubRelease: 'https://github.com/patrikx3/redis-ui/releases',
        githubChangelog: 'https://github.com/patrikx3/redis-ui/blob/master/change-log.md#change-log',
        donate: 'https://www.paypal.me/patrikx3',
    }
    window.open(urls[target], '_blank')
}

// Connect — delegates to shared store function
const connect = (conn: any) => mainCommand.connect(conn)

// Lifecycle
onMounted(async () => {
    await auth.checkAuthStatus()
    if (auth.authRequired && !auth.isAuthenticated) overlay.hide()
})
watch(() => auth.isAuthenticated, (v) => {
    if (!v) return
    try {
        const saved = localStorage.getItem(settings.connectInfoStorageKey)
        if (saved) { const c = JSON.parse(saved); if (c?.id) connect(c) }
    } catch {}
}, { immediate: true })

const unsubs: (() => void)[] = []
unsubs.push(onSocketEvent('redis-disconnected', () => navigateTo('settings')))
unsubs.push(onSocketEvent('disconnect', () => { if (!showLogin.value) overlay.show({ message: strings.value?.status?.socketDisconnected }) }))
unsubs.push(onSocketEvent('socket-error', () => { if (!showLogin.value) overlay.show({ message: strings.value?.status?.socketError }) }))
onUnmounted(() => unsubs.forEach(u => u()))

watch(() => route.path, (p) => {
    trackPage(p.toLowerCase().startsWith('/database/key/') ? '/database/key' : p)
}, { immediate: true })

// Prefetch other GUI frameworks — fetch HTML, parse script/style tags, cache all assets
onMounted(() => {
    setTimeout(() => {
        for (const gui of ['/ng/', '/react/']) {
            fetch(gui).then(r => r.text()).then(html => {
                const doc = new DOMParser().parseFromString(html, 'text/html')
                doc.querySelectorAll('script[src], link[rel="stylesheet"]').forEach(el => {
                    const url = (el as any).src || (el as any).href
                    if (url) fetch(url).catch(() => {})
                })
            }).catch(() => {})
        }
    }, 3000)
})

// Group mode poll
let groupInterval: any
onMounted(() => {
    groupInterval = setInterval(() => {
        try { groupMode.value = localStorage.getItem('p3xr-connection-group-mode') === 'true' } catch {}
    }, 1000)
})
onUnmounted(() => clearInterval(groupInterval))
</script>

<template>
    <!-- ===== HEADER ===== -->
    <v-toolbar
        :style="{ ...toolbarStyle, position: 'fixed', top: 0, left: 0, right: 0, zIndex: 1000, boxShadow: '0 2px 4px -1px rgba(0,0,0,0.2), 0 4px 5px 0 rgba(0,0,0,0.14), 0 1px 10px 0 rgba(0,0,0,0.12)' }"
        density="compact"
        class="p3xr-toolbar"
    >
        <!-- App title with version caption -->
        <div v-if="isWide" style="position: relative; display: inline-flex; align-items: center;">
            <v-btn variant="text" :class="{}"
                @click="navigateTo(state.connection ? 'database.statistics' : 'settings')">
                <i class="fas fa-database" /><span>{{ strings?.title?.name }}</span>
            </v-btn>
            <span v-if="state.version" style="position: absolute; bottom: -3px; left: 4px; right: 13px; text-align: right; font-size: 10px; opacity: 0.7; pointer-events: none; color: inherit; letter-spacing: normal; font-weight: 400; line-height: 1;">
                {{ state.version }}
            </span>
        </div>
        <v-tooltip v-else :text="`${strings?.title?.name || ''}${state.version ? ' ' + state.version : ''}`" location="bottom">
            <template #activator="{ props: tp }">
                <v-btn v-bind="tp" variant="text" :class="{}"
                    @click="navigateTo(state.connection ? 'database.statistics' : 'settings')">
                    <i class="fas fa-database" />
                </v-btn>
            </template>
        </v-tooltip>

        <!-- Database -->
        <template v-if="state.connection">
            <v-btn v-if="isWide" variant="text" :class="{ 'p3xr-active': isActivePage('database') }"
                @click="navigateTo('database.statistics')">
                <v-icon size="small">mdi-dns</v-icon><span>{{ strings?.intention?.main }}</span>
            </v-btn>
            <v-tooltip v-else :text="strings?.intention?.main" location="bottom">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" variant="text" :class="{ 'p3xr-active': isActivePage('database') }"
                        @click="navigateTo('database.statistics')">
                        <v-icon size="small">mdi-dns</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>
        </template>

        <!-- Monitoring -->
        <template v-if="state.connection">
            <v-btn v-if="isWide" variant="text" :class="{ 'p3xr-active': isActivePage('monitoring') }"
                @click="navigateTo('monitoring')">
                <v-icon size="small">mdi-heart-pulse</v-icon><span>{{ strings?.page?.monitor?.title }}</span>
            </v-btn>
            <v-tooltip v-else :text="strings?.page?.monitor?.title" location="bottom">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" variant="text" :class="{ 'p3xr-active': isActivePage('monitoring') }"
                        @click="navigateTo('monitoring')">
                        <v-icon size="small">mdi-heart-pulse</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>
        </template>

        <!-- Search -->
        <template v-if="state.connection && state.hasRediSearch">
            <v-btn v-if="isWide" variant="text" :class="{ 'p3xr-active': isActivePage('search') }"
                @click="navigateTo('search')">
                <v-icon size="small">mdi-magnify</v-icon><span>{{ strings?.page?.search?.title }}</span>
            </v-btn>
            <v-tooltip v-else :text="strings?.page?.search?.title" location="bottom">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" variant="text" :class="{ 'p3xr-active': isActivePage('search') }"
                        @click="navigateTo('search')">
                        <v-icon size="small">mdi-magnify</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>
        </template>

        <v-spacer />

        <!-- Info -->
        <template v-if="!showLogin">
            <v-btn v-if="isWide" variant="text" :class="{ 'p3xr-active': isActivePage('info') }"
                @click="navigateTo('info')">
                <v-icon size="small">mdi-information</v-icon><span>{{ strings?.intention?.info }}</span>
            </v-btn>
            <v-tooltip v-else :text="strings?.intention?.info" location="bottom">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" variant="text" :class="{ 'p3xr-active': isActivePage('info') }"
                        @click="navigateTo('info')">
                        <v-icon size="small">mdi-information</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>
        </template>

        <!-- Settings -->
        <template v-if="!showLogin">
            <v-btn v-if="isWide" variant="text" :class="{ 'p3xr-active': isActivePage('settings') }"
                @click="navigateTo('settings')">
                <v-icon size="small">mdi-cog</v-icon><span>{{ strings?.intention?.settings }}</span>
            </v-btn>
            <v-tooltip v-else :text="strings?.intention?.settings" location="bottom">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" variant="text" :class="{ 'p3xr-active': isActivePage('settings') }"
                        @click="navigateTo('settings')">
                        <v-icon size="small">mdi-cog</v-icon>
                    </v-btn>
                </template>
            </v-tooltip>
        </template>

        <!-- Logout -->
        <v-tooltip v-if="auth.authRequired && auth.isAuthenticated" :text="strings?.intention?.logout" location="bottom">
            <template #activator="{ props: tp }">
                <v-btn v-bind="tp" variant="text" icon @click="async () => { try { await common.confirm({ message: strings?.intention?.logout }); auth.logout() } catch {} }">
                    <v-icon size="small">mdi-logout</v-icon>
                </v-btn>
            </template>
        </v-tooltip>
    </v-toolbar>

    <!-- ===== CONTENT ===== -->
    <div id="p3xr-layout-content">
        <component v-if="showLogin" :is="defineAsyncComponent(() => import('../pages/login/LoginPage.vue'))" />
        <router-view v-else />
    </div>

    <!-- ===== FOOTER ===== -->
    <v-toolbar
        :style="{ ...toolbarStyle, position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 1000 }"
        density="compact"
        flat
        class="p3xr-toolbar"
    >
        <!-- Connection menu -->
        <template v-if="!showLogin && connectionsList.length > 0">
            <v-menu v-model="connectionMenuOpen" location="top start" origin="bottom start">
                <template #activator="{ props: menuProps }">
                    <v-btn v-if="isWide" v-bind="menuProps" variant="text">
                        <v-icon size="small">mdi-power-plug</v-icon><span>{{ connectionName }}</span>
                    </v-btn>
                    <v-tooltip v-else :text="connectionName" location="top">
                        <template #activator="{ props: tp }">
                            <v-btn v-bind="{ ...menuProps, ...tp }" variant="text" icon>
                                <v-icon size="small">mdi-power-plug</v-icon>
                            </v-btn>
                        </template>
                    </v-tooltip>
                </template>
                <v-list density="compact">
                    <template v-for="(group, gi) in groupedConnectionsList" :key="'g-' + gi">
                        <v-list-subheader v-if="groupedConnectionsList.length > 1" style="font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.6;">
                            {{ group.name || strings?.label?.ungrouped }}
                        </v-list-subheader>
                        <v-list-item v-for="conn in group.connections" :key="conn.id"
                            :active="state.connection?.id === conn.id"
                            @click="connectionMenuOpen = false; connect(conn)">
                            <v-list-item-title style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 280px;">
                                {{ conn.name }}
                            </v-list-item-title>
                        </v-list-item>
                        <v-divider v-if="gi < groupedConnectionsList.length - 1 && groupedConnectionsList.length > 1" />
                    </template>
                </v-list>
            </v-menu>
        </template>

        <!-- Disconnect -->
        <template v-if="!showLogin && state.connection">
            <v-btn v-if="isGtSm" variant="text" @click="mainCommand.disconnect()">
                <i class="fa fa-power-off" /><span>{{ strings?.intention?.disconnect }}</span>
            </v-btn>
            <v-tooltip v-else :text="strings?.intention?.disconnect" location="top">
                <template #activator="{ props: tp }">
                    <v-btn v-bind="tp" variant="text" icon @click="mainCommand.disconnect()">
                        <i class="fa fa-power-off" />
                    </v-btn>
                </template>
            </v-tooltip>
        </template>

        <v-spacer />

        <!-- Donate -->
        <v-btn v-if="isWide" variant="text" @click="openLink('donate')">
            <i class="fas fa-donate" /><span>{{ strings?.title?.donate }}</span>
        </v-btn>
        <v-tooltip v-else :text="strings?.title?.donate" location="top">
            <template #activator="{ props: tp }">
                <v-btn v-bind="tp" variant="text" icon @click="openLink('donate')">
                    <i class="fas fa-donate" />
                </v-btn>
            </template>
        </v-tooltip>

        <!-- Language menu with search -->
        <v-menu v-model="languageMenuOpen" location="top start" origin="bottom start"
            :close-on-content-click="false" class="p3xr-language-menu"
            @update:model-value="(v: boolean) => { if (v) onLanguageMenuOpen(); else onLanguageMenuClose() }">
            <template #activator="{ props: menuProps }">
                <v-btn v-if="isGtSm" v-bind="menuProps" variant="text">
                    <v-icon size="small">mdi-web</v-icon><span>{{ strings?.intention?.language }}</span>
                </v-btn>
                <v-tooltip v-else :text="strings?.intention?.language" location="top">
                    <template #activator="{ props: tp }">
                        <v-btn v-bind="{ ...menuProps, ...tp }" variant="text" icon>
                            <v-icon size="small">mdi-web</v-icon>
                        </v-btn>
                    </template>
                </v-tooltip>
            </template>
            <v-card style="min-width: 320px; max-width: 90vw; max-height: 400px; overflow: hidden;">
                <!-- Search input -->
                <div style="position: sticky; top: 0; z-index: 1; padding: 8px;" @click.stop @keydown="onLanguageKeyDown">
                    <input ref="languageInputRef" :placeholder="strings?.label?.searchLanguage"
                        :value="languageSearch" @input="(e: any) => { languageSearch = e.target.value; highlightedLangIdx = 0 }"
                        autocomplete="off"
                        style="display: block; width: 100%; padding: 8px; border: 2px solid rgba(255,255,255,0.25); border-radius: 4px; font-size: 14px; background: transparent; color: inherit; outline: none; box-sizing: border-box; cursor: text;" />
                </div>
                <v-list ref="languageListRef" density="compact" style="overflow: auto; max-height: 340px; padding-top: 0;">
                    <v-list-item :active="i18n.isAuto"
                        @click="i18n.setLanguage('auto'); languageMenuOpen = false">
                        {{ strings?.label?.languageAuto }}
                    </v-list-item>
                    <v-divider />
                    <v-list-item v-for="(key, idx) in filteredLanguages" :key="key"
                        :active="!i18n.isAuto && i18n.currentLang === key"
                        :class="{ 'p3xr-lang-highlighted': idx === highlightedLangIdx }"
                        @click="i18n.setLanguage(key); languageMenuOpen = false">
                        {{ languageLabel(key) }}
                    </v-list-item>
                </v-list>
            </v-card>
        </v-menu>

        <!-- Theme menu -->
        <v-menu v-model="themeMenuOpen" location="top start" origin="bottom start">
            <template #activator="{ props: menuProps }">
                <v-btn v-if="isGtXs" v-bind="menuProps" variant="text">
                    <v-icon size="small">mdi-palette</v-icon><span>{{ strings?.intention?.theme }}</span>
                </v-btn>
                <v-tooltip v-else :text="strings?.intention?.theme" location="top">
                    <template #activator="{ props: tp }">
                        <v-btn v-bind="{ ...menuProps, ...tp }" variant="text" icon>
                            <v-icon size="small">mdi-palette</v-icon>
                        </v-btn>
                    </template>
                </v-tooltip>
            </template>
            <v-list density="compact">
                <v-list-item :active="isThemeAuto" @click="themeStore.setTheme('auto'); themeMenuOpen = false">
                    {{ strings?.label?.themeAuto }}
                </v-list-item>
                <v-divider />
                <v-list-item v-for="key in ALL_THEME_KEYS" :key="key"
                    :active="!isThemeAuto && themeKey === key"
                    @click="themeStore.setTheme(key); themeMenuOpen = false">
                    {{ strings?.label?.theme?.[key] ?? key }}
                </v-list-item>
            </v-list>
        </v-menu>

        <!-- GitHub menu -->
        <v-menu v-model="githubMenuOpen" location="top start" origin="bottom start">
            <template #activator="{ props: menuProps }">
                <v-btn v-if="isGtSm" v-bind="menuProps" variant="text">
                    <i class="fab fa-github" /><span>{{ strings?.intention?.github }}</span>
                </v-btn>
                <v-tooltip v-else :text="strings?.intention?.github" location="top">
                    <template #activator="{ props: tp }">
                        <v-btn v-bind="{ ...menuProps, ...tp }" variant="text" icon>
                            <i class="fab fa-github" />
                        </v-btn>
                    </template>
                </v-tooltip>
            </template>
            <v-list density="compact">
                <v-list-item @click="openLink('github'); githubMenuOpen = false">{{ strings?.intention?.githubRepo }}</v-list-item>
                <v-list-item @click="openLink('githubRelease'); githubMenuOpen = false">{{ strings?.intention?.githubRelease }}</v-list-item>
                <v-list-item @click="openLink('githubChangelog'); githubMenuOpen = false">{{ strings?.intention?.githubChangelog }}</v-list-item>
            </v-list>
        </v-menu>

    </v-toolbar>
</template>
