// src/vue/dialogs/AiSettingsDialog.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useDisplay } from 'vuetify'
import { useI18nStore } from '../stores/i18n'
import { useRedisStateStore } from '../stores/redis-state'
import { useCommonStore } from '../stores/common.store'
import { useOverlayStore } from '../stores/overlay.store'
import { request } from '../stores/socket.service'
import P3xrDialog from '../components/P3xrDialog.vue'

const props = defineProps<{ open: boolean }>()
const emit = defineEmits<{ close: [] }>()

const i18n = useI18nStore()
const strings = computed(() => i18n.strings)
const state = useRedisStateStore()
const common = useCommonStore()
const overlay = useOverlayStore()
const { width } = useDisplay()
const isWide = computed(() => width.value >= 600)

const apiKey = ref('')

watch(() => props.open, (v) => { if (v) apiKey.value = '' })

async function submit() {
    try {
        const trimmedKey = apiKey.value.trim()
        if (trimmedKey) {
            overlay.show({ message: strings.value?.title?.connectingRedis })
            let validation: any
            try {
                validation = await request({ action: 'ai/validate-groq-api-key', payload: { apiKey: trimmedKey } })
            } catch (e) { common.generalHandleError(e); return }
            finally { overlay.hide() }
            if (!validation.valid) {
                common.toast(strings.value?.label?.aiGroqApiKeyInvalid)
                return
            }
        }
        await request({
            action: 'ai/set-groq-api-key',
            payload: { apiKey: trimmedKey, aiEnabled: state.cfg?.aiEnabled !== false, aiUseOwnKey: state.cfg?.aiUseOwnKey === true },
        })
        state.cfg = { ...state.cfg, hasGroqApiKey: !!(trimmedKey && trimmedKey.startsWith('gsk_') && trimmedKey.length > 20) }
        common.toast(strings.value?.status?.saved)
        emit('close')
    } catch (e) { common.generalHandleError(e) }
}
</script>

<template>
    <P3xrDialog v-if="open" :open="true" :title="strings?.label?.aiSettings" @close="emit('close')">
        <div style="margin-bottom: 16px; font-size: 14px; opacity: 0.8;">
            {{ strings?.label?.aiGroqApiKeyInfo }}
            <a href="https://console.groq.com" target="_blank" rel="noreferrer"
                style="color: inherit; text-decoration: underline;">console.groq.com</a>
        </div>
        <v-text-field
            v-model="apiKey"
            :label="strings?.label?.aiGroqApiKey"
            placeholder="gsk_..."
            type="password"
            variant="outlined"
            density="comfortable"
            hide-details
            autocomplete="off"
        />

        <template #actions>
            <v-btn variant="flat" color="warning" @click="emit('close')">
                <v-icon :class="{ 'mr-1': isWide }">mdi-close-circle</v-icon>
                <span v-if="isWide">{{ strings?.intention?.cancel }}</span>
                <v-tooltip v-if="!isWide" activator="parent" location="top">{{ strings?.intention?.cancel }}</v-tooltip>
            </v-btn>
            <v-btn variant="flat" color="primary" @click="submit">
                <v-icon class="mr-1">mdi-check</v-icon>
                <span>{{ strings?.intention?.save }}</span>
            </v-btn>
        </template>
    </P3xrDialog>
</template>

// src/react/dialogs/AiSettingsDialog.tsx
import { useState, useEffect } from 'react'
import { TextField, Button, Tooltip, Box, useMediaQuery } from '@mui/material'
import { Done, Cancel } from '@mui/icons-material'
import { useI18nStore } from '../stores/i18n.store'
import { useRedisStateStore } from '../stores/redis-state.store'
import { useCommonStore } from '../stores/common.store'
import { useOverlayStore } from '../stores/overlay.store'
import { request } from '../stores/socket.service'
import P3xrDialog from '../components/P3xrDialog'

interface AiSettingsDialogProps {
    open: boolean
    onClose: () => void
}

export default function AiSettingsDialog({ open, onClose }: AiSettingsDialogProps) {
    const strings = useI18nStore(s => s.strings)
    const cfg = useRedisStateStore(s => s.cfg)
    const { toast, generalHandleError } = useCommonStore()
    const overlay = useOverlayStore()
    const isWide = useMediaQuery('(min-width: 600px)')

    const [apiKey, setApiKey] = useState('')

    useEffect(() => {
        if (open) setApiKey('')
    }, [open])

    const submit = async () => {
        try {
            const trimmedKey = apiKey.trim()
            if (trimmedKey) {
                overlay.show({ message: strings?.title?.connectingRedis })
                let validation: any
                try {
                    validation = await request({ action: 'ai/validate-groq-api-key', payload: { apiKey: trimmedKey } })
                } catch (e) { generalHandleError(e); return }
                finally { overlay.hide() }
                if (!validation.valid) {
                    toast(strings?.label?.aiGroqApiKeyInvalid)
                    return
                }
            }
            await request({
                action: 'ai/set-groq-api-key',
                payload: { apiKey: trimmedKey, aiEnabled: cfg?.aiEnabled !== false, aiUseOwnKey: cfg?.aiUseOwnKey === true },
            })
            useRedisStateStore.setState({ cfg: { ...cfg, groqApiKey: trimmedKey } })
            toast(strings?.status?.saved)
            onClose()
        } catch (e) { generalHandleError(e) }
    }

    if (!open) return null

    return (
        <P3xrDialog open onClose={onClose} title={strings?.label?.aiSettings}
            actions={
                <>
                    {isWide ? (
                        <Button variant="contained" color="error" size="small" onClick={onClose}>
                            <Cancel fontSize="small" /><span style={{ marginLeft: 3 }}>{strings?.intention?.cancel}</span>
                        </Button>
                    ) : (
                        <Tooltip title={strings?.intention?.cancel} placement="top">
                            <Button variant="contained" color="error" size="small" onClick={onClose}
                                sx={{ minWidth: 40, width: 40, height: 36, p: 0 }}>
                                <Cancel fontSize="small" />
                            </Button>
                        </Tooltip>
                    )}
                    <Button variant="contained" color="primary" size="small" onClick={submit}>
                        <Done fontSize="small" /><span style={{ marginLeft: 3 }}>{strings?.intention?.save}</span>
                    </Button>
                </>
            }>
            <Box sx={{ mb: 2, fontSize: 14, opacity: 0.8 }}>
                {strings?.label?.aiGroqApiKeyInfo}{' '}
                <a href="https://console.groq.com" target="_blank" rel="noreferrer"
                    style={{ color: 'inherit', textDecoration: 'underline' }}>
                    console.groq.com
                </a>
            </Box>
            <TextField fullWidth margin="dense" label={strings?.label?.aiGroqApiKey}
                placeholder="gsk_..." type="password" value={apiKey}
                onChange={e => setApiKey(e.target.value)} autoComplete="off" />
        </P3xrDialog>
    )
}
