// src/vue/dialogs/DiffDialog.vue
<script setup lang="ts">
/**
 * DiffDialog — exact port of React DiffDialog.tsx
 * Inline / side-by-side diff view with collapsible context.
 */
import { ref, computed, watch } from 'vue'
import { useDisplay } from 'vuetify'
import { diffLines, type Change } from 'diff'
import { useI18nStore } from '../stores/i18n'
import P3xrDialog from '../components/P3xrDialog.vue'

interface DiffBlock {
    type: 'added' | 'removed' | 'unchanged' | 'collapse'
    lines: string[]
    collapsedCount?: number
}

const CONTEXT_LINES = 3

function buildBlocks(changes: Change[]): DiffBlock[] {
    const blocks: DiffBlock[] = []
    for (const change of changes) {
        const lines = change.value.replace(/\n$/, '').split('\n')
        if (change.added) {
            blocks.push({ type: 'added', lines })
        } else if (change.removed) {
            blocks.push({ type: 'removed', lines })
        } else {
            if (lines.length <= CONTEXT_LINES * 2 + 1) {
                blocks.push({ type: 'unchanged', lines })
            } else {
                blocks.push({ type: 'unchanged', lines: lines.slice(0, CONTEXT_LINES) })
                const collapsed = lines.slice(CONTEXT_LINES, -CONTEXT_LINES)
                blocks.push({ type: 'collapse', lines: collapsed, collapsedCount: collapsed.length })
                blocks.push({ type: 'unchanged', lines: lines.slice(-CONTEXT_LINES) })
            }
        }
    }
    return blocks
}

const props = defineProps<{
    open: boolean
    keyName: string
    fieldName?: string
    oldValue: string
    newValue: string
}>()

const emit = defineEmits<{
    confirm: []
    cancel: []
}>()

const i18n = useI18nStore()
const strings = computed(() => i18n.strings)
const d = computed(() => strings.value?.diff || {} as any)
const { width } = useDisplay()
const isWide = computed(() => width.value >= 600)

const mode = ref<'inline' | 'side-by-side'>('inline')
const expanded = ref<Set<number>>(new Set())

watch(() => props.open, (v) => {
    if (v) {
        mode.value = 'inline'
        expanded.value = new Set()
    }
})

const changes = computed(() => diffLines(String(props.oldValue ?? ''), String(props.newValue ?? '')))
const blocks = computed(() => buildBlocks(changes.value))
const additions = computed(() => changes.value.filter(c => c.added).reduce((n, c) => n + (c.value.split('\n').length - 1 || 1), 0))
const deletions = computed(() => changes.value.filter(c => c.removed).reduce((n, c) => n + (c.value.split('\n').length - 1 || 1), 0))

function toggleExpand(i: number) {
    const s = new Set(expanded.value)
    s.has(i) ? s.delete(i) : s.add(i)
    expanded.value = s
}

function lineClass(type: string) {
    if (type === 'added') return 'p3xr-diff-added'
    if (type === 'removed') return 'p3xr-diff-removed'
    return 'p3xr-diff-unchanged'
}

const title = computed(() => {
    const prefix = d.value.reviewChanges || 'Review changes'
    const field = props.fieldName ? `${props.fieldName} @ ` : ''
    return `${prefix} — ${field}${props.keyName}`
})
</script>

<template>
    <P3xrDialog v-if="open" :open="true" :title="title" width="800px" :content-padding="false" @close="emit('cancel')">
        <template #headerActions>
            <v-btn-toggle v-model="mode" mandatory density="compact" class="p3xr-diff-mode-toggle" style="margin-right: 4px;">
                <v-btn value="inline" size="x-small">{{ d.inline || 'Inline' }}</v-btn>
                <v-btn value="side-by-side" size="x-small">{{ d.sideBySide || 'Side by side' }}</v-btn>
            </v-btn-toggle>
            <span style="font-size: 12px; opacity: 0.8; margin-right: 4px; white-space: nowrap;">
                <span style="color: #81c784; font-weight: 700;">+{{ additions }}</span> {{ d.additions || 'additions' }},
                <span style="color: #ef9a9a; font-weight: 700;">-{{ deletions }}</span> {{ d.deletions || 'deletions' }}
            </span>
        </template>

        <div class="p3xr-diff-body" :class="{ 'p3xr-diff-side': mode === 'side-by-side' }">
            <!-- Inline mode -->
            <template v-if="mode === 'inline'">
                <div>
                    <template v-for="(block, i) in blocks" :key="i">
                        <div v-if="block.type === 'collapse' && !expanded.has(i)" class="p3xr-diff-collapse" @click="toggleExpand(i)">
                            ... {{ block.collapsedCount }} {{ d.unchangedLines || 'unchanged lines' }} ...
                        </div>
                        <template v-else>
                            <div v-for="(line, j) in block.lines" :key="`${i}-${j}`" :class="lineClass(block.type)" class="p3xr-diff-line">
                                <span class="p3xr-diff-prefix">{{ block.type === 'added' ? '+' : block.type === 'removed' ? '-' : ' ' }}</span>{{ line }}
                            </div>
                        </template>
                    </template>
                </div>
            </template>

            <!-- Side-by-side mode -->
            <template v-else>
                <div style="border-right: 1px solid rgba(var(--v-theme-on-surface), 0.12); overflow: auto;">
                    <div style="padding: 4px 8px; font-weight: 500; border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.12); position: sticky; top: 0; z-index: 1; background: rgb(var(--v-theme-surface));">
                        {{ d.before || 'Before' }}
                    </div>
                    <template v-for="(block, i) in blocks" :key="'l'+i">
                        <div v-if="block.type === 'collapse' && !expanded.has(i)" class="p3xr-diff-collapse" @click="toggleExpand(i)">
                            ... {{ block.collapsedCount }} {{ d.unchangedLines || 'unchanged lines' }} ...
                        </div>
                        <template v-else-if="block.type !== 'added'">
                            <div v-for="(line, j) in block.lines" :key="`l${i}-${j}`" :class="lineClass(block.type)" class="p3xr-diff-line">{{ line }}</div>
                        </template>
                    </template>
                </div>
                <div style="overflow: auto;">
                    <div style="padding: 4px 8px; font-weight: 500; border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.12); position: sticky; top: 0; z-index: 1; background: rgb(var(--v-theme-surface));">
                        {{ d.after || 'After' }}
                    </div>
                    <template v-for="(block, i) in blocks" :key="'r'+i">
                        <div v-if="block.type === 'collapse' && !expanded.has(i)" class="p3xr-diff-collapse" @click="toggleExpand(i)">
                            ... {{ block.collapsedCount }} {{ d.unchangedLines || 'unchanged lines' }} ...
                        </div>
                        <template v-else-if="block.type !== 'removed'">
                            <div v-for="(line, j) in block.lines" :key="`r${i}-${j}`" :class="lineClass(block.type)" class="p3xr-diff-line">{{ line }}</div>
                        </template>
                    </template>
                </div>
            </template>
        </div>

        <template #actions>
            <v-btn variant="flat" color="warning" @click="emit('cancel')">
                <v-icon :class="{ 'mr-1': isWide }">mdi-close-circle</v-icon>
                <span v-if="isWide">{{ strings?.intention?.cancel }}</span>
            </v-btn>
            <v-btn variant="flat" color="primary" @click="emit('confirm')">
                <v-icon :class="{ 'mr-1': isWide }">mdi-check</v-icon>
                <span v-if="isWide">{{ strings?.intention?.save }}</span>
            </v-btn>
        </template>
    </P3xrDialog>
</template>

<style>
.p3xr-diff-body { min-height: 200px; max-height: 60vh; overflow: auto; }
.p3xr-diff-side { display: grid; grid-template-columns: 1fr 1fr; }
.p3xr-diff-line { padding: 1px 8px; white-space: pre-wrap; word-break: break-all; font-family: 'Roboto Mono', monospace; font-size: 13px; }
.p3xr-diff-added { background-color: rgba(76,175,80,0.12); }
.p3xr-diff-removed { background-color: rgba(244,67,54,0.12); }
.p3xr-diff-unchanged { opacity: 0.6; }
.p3xr-diff-collapse { padding: 4px 8px; opacity: 0.4; font-style: italic; cursor: pointer; font-family: 'Roboto Mono', monospace; font-size: 13px; }
.p3xr-diff-collapse:hover { opacity: 0.7; }
.p3xr-diff-prefix { display: inline-block; width: 16px; font-weight: 700; user-select: none; }
.p3xr-diff-mode-toggle .v-btn { padding: 2px 12px !important; font-size: 12px !important; border-radius: 4px !important; text-transform: none !important; }
</style>

// src/react/dialogs/DiffDialog.tsx
import { useState, useMemo } from 'react'
import {
    Button, Box, ToggleButtonGroup, ToggleButton,
    useMediaQuery, Tooltip,
} from '@mui/material'
import { Save, Cancel } from '@mui/icons-material'
import { diffLines, Change } from 'diff'
import { useI18nStore } from '../stores/i18n.store'
import P3xrDialog from '../components/P3xrDialog'

interface DiffBlock {
    type: 'added' | 'removed' | 'unchanged' | 'collapse'
    lines: string[]
    collapsedCount?: number
}

const CONTEXT_LINES = 3

function buildBlocks(changes: Change[]): DiffBlock[] {
    const blocks: DiffBlock[] = []
    for (const change of changes) {
        const lines = change.value.replace(/\n$/, '').split('\n')
        if (change.added) {
            blocks.push({ type: 'added', lines })
        } else if (change.removed) {
            blocks.push({ type: 'removed', lines })
        } else {
            if (lines.length <= CONTEXT_LINES * 2 + 1) {
                blocks.push({ type: 'unchanged', lines })
            } else {
                blocks.push({ type: 'unchanged', lines: lines.slice(0, CONTEXT_LINES) })
                const collapsed = lines.slice(CONTEXT_LINES, -CONTEXT_LINES)
                blocks.push({ type: 'collapse', lines: collapsed, collapsedCount: collapsed.length })
                blocks.push({ type: 'unchanged', lines: lines.slice(-CONTEXT_LINES) })
            }
        }
    }
    return blocks
}

interface DiffDialogProps {
    open: boolean
    keyName: string
    fieldName?: string
    oldValue: string
    newValue: string
    onConfirm: () => void
    onCancel: () => void
}

export default function DiffDialog({ open, keyName, fieldName, oldValue, newValue, onConfirm, onCancel }: DiffDialogProps) {
    const strings = useI18nStore(s => s.strings)
    const d = strings?.diff || {} as any
    const isWide = useMediaQuery('(min-width: 600px)')
    const [mode, setMode] = useState<'inline' | 'side-by-side'>('inline')
    const [expanded, setExpanded] = useState<Set<number>>(new Set())

    const changes = useMemo(() => diffLines(String(oldValue ?? ''), String(newValue ?? '')), [oldValue, newValue])
    const blocks = useMemo(() => buildBlocks(changes), [changes])
    const additions = useMemo(() => changes.filter(c => c.added).reduce((n, c) => n + (c.value.split('\n').length - 1 || 1), 0), [changes])
    const deletions = useMemo(() => changes.filter(c => c.removed).reduce((n, c) => n + (c.value.split('\n').length - 1 || 1), 0), [changes])

    const toggleExpand = (i: number) => setExpanded(prev => { const s = new Set(prev); s.has(i) ? s.delete(i) : s.add(i); return s })

    const lineSx = (type: string) => ({
        px: 1, py: '1px', whiteSpace: 'pre-wrap', wordBreak: 'break-all',
        fontFamily: "'Roboto Mono', monospace", fontSize: 13,
        ...(type === 'added' ? { bgcolor: 'rgba(76,175,80,0.12)' } : {}),
        ...(type === 'removed' ? { bgcolor: 'rgba(244,67,54,0.12)' } : {}),
        ...(type === 'unchanged' || type === 'collapse' ? { opacity: 0.6 } : {}),
    })

    const collapseSx = {
        px: 1, py: '4px', opacity: 0.4, fontStyle: 'italic', cursor: 'pointer',
        fontFamily: "'Roboto Mono', monospace", fontSize: 13,
        '&:hover': { opacity: 0.7 },
    }

    const renderInline = () => blocks.map((block, i) => {
        if (block.type === 'collapse' && !expanded.has(i)) {
            return <Box key={i} sx={collapseSx} onClick={() => toggleExpand(i)}>... {block.collapsedCount} {d.unchangedLines || 'unchanged lines'} ...</Box>
        }
        return block.lines.map((line, j) => (
            <Box key={`${i}-${j}`} sx={lineSx(block.type)}>
                <Box component="span" sx={{ display: 'inline-block', width: 16, fontWeight: 700, userSelect: 'none' }}>
                    {block.type === 'added' ? '+' : block.type === 'removed' ? '-' : ' '}
                </Box>{line}
            </Box>
        ))
    })

    const renderSide = (side: 'before' | 'after') => {
        const skipType = side === 'before' ? 'added' : 'removed'
        return (<>
            <Box sx={{ px: 1, py: '4px', fontWeight: 500, borderBottom: 1, borderColor: 'divider', position: 'sticky', top: 0, zIndex: 1, bgcolor: 'background.paper' }}>
                {side === 'before' ? (d.before || 'Before') : (d.after || 'After')}
            </Box>
            {blocks.map((block, i) => {
                if (block.type === 'collapse' && !expanded.has(i)) {
                    return <Box key={i} sx={collapseSx} onClick={() => toggleExpand(i)}>... {block.collapsedCount} {d.unchangedLines || 'unchanged lines'} ...</Box>
                }
                if (block.type === skipType) return null
                return block.lines.map((line, j) => <Box key={`${i}-${j}`} sx={lineSx(block.type)}>{line}</Box>)
            })}
        </>)
    }

    const title = `${d.reviewChanges || 'Review changes'} — ${fieldName ? `${fieldName} @ ` : ''}${keyName}`

    return (
        <P3xrDialog
            open={open}
            onClose={onCancel}
            title={title}
            width="800px"
            contentPadding={false}
            headerActions={<>
                <ToggleButtonGroup size="small" exclusive value={mode} onChange={(_, v) => v && setMode(v)}
                    sx={{ mr: 0.5, '& .MuiToggleButton-root': { py: '2px', px: 1.5, fontSize: 12, borderRadius: '4px', textTransform: 'none', color: 'rgba(255,255,255,0.7)', borderColor: 'rgba(255,255,255,0.3)' } }}>
                    <ToggleButton value="inline">{d.inline || 'Inline'}</ToggleButton>
                    <ToggleButton value="side-by-side">{d.sideBySide || 'Side by side'}</ToggleButton>
                </ToggleButtonGroup>
                <Box sx={{ fontSize: 12, opacity: 0.8, mr: 0.5, whiteSpace: 'nowrap' }}>
                    <Box component="span" sx={{ color: '#81c784', fontWeight: 700 }}>+{additions}</Box>{' '}{d.additions || 'additions'},{' '}
                    <Box component="span" sx={{ color: '#ef9a9a', fontWeight: 700 }}>-{deletions}</Box>{' '}{d.deletions || 'deletions'}
                </Box>
            </>}
            actions={<>
                <Tooltip title={strings?.intention?.cancel || 'Cancel'} disableHoverListener={isWide}>
                    <Button variant="contained" color="warning" onClick={onCancel}>
                        <Cancel sx={{ fontSize: 18, mr: isWide ? 0.5 : 0 }} />
                        {isWide && <span>{strings?.intention?.cancel || 'Cancel'}</span>}
                    </Button>
                </Tooltip>
                <Tooltip title={strings?.intention?.save || 'Save'} disableHoverListener={isWide}>
                    <Button variant="contained" color="primary" onClick={onConfirm}>
                        <Save sx={{ fontSize: 18, mr: isWide ? 0.5 : 0 }} />
                        {isWide && <span>{strings?.intention?.save || 'Save'}</span>}
                    </Button>
                </Tooltip>
            </>}
        >
            <Box sx={{ minHeight: 200, maxHeight: '60vh', overflow: 'auto', ...(mode === 'side-by-side' ? { display: 'grid', gridTemplateColumns: '1fr 1fr' } : {}) }}>
                {mode === 'inline' ? (
                    <Box>{renderInline()}</Box>
                ) : (<>
                    <Box sx={{ borderRight: 1, borderColor: 'divider', overflow: 'auto' }}>{renderSide('before')}</Box>
                    <Box sx={{ overflow: 'auto' }}>{renderSide('after')}</Box>
                </>)}
            </Box>
        </P3xrDialog>
    )
}
