// src/vue/pages/database/key/KeyStream.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import HexMonitor from './HexMonitor.vue'
import KeyPagerInline from './KeyPagerInline.vue'
import KeyNewOrSetDialog from '../../../dialogs/KeyNewOrSetDialog.vue'
import JsonViewDialog from '../../../dialogs/JsonViewDialog.vue'
import { useI18nStore } from '../../../stores/i18n'
import { useRedisStateStore } from '../../../stores/redis-state'
import { useCommonStore } from '../../../stores/common'
import { request } from '../../../stores/socket.service'
import { type Paging, createPaging, rePaging, formatValue, truncateDisplay, isTruncated, copyToClipboard, str } from './key-type-base'

interface StreamEntry { id: string; fields: Array<[string, string]>; data: any; hasDuplicateFields: boolean }

const intlLocaleMap: Record<string, string> = { 'zn': 'zh-CN', 'no': 'nb', 'fil': 'tl' }

function hasDupFields(fields: Array<[string, string]>): boolean {
    const seen = new Set<string>()
    for (const [k] of fields) { if (seen.has(k)) return true; seen.add(k) }
    return false
}

function buildEntries(value: any[]): StreamEntry[] {
    if (!value) return []
    return value.map((entry: any) => {
        const id = entry[0]
        const raw = entry[1]
        const fields: Array<[string, string]> = []
        for (let i = 0; i < raw.length; i += 2) fields.push([raw[i], raw[i + 1]])
        const hasDup = hasDupFields(fields)
        const data = hasDup ? fields.map(([f, v]) => ({ field: f, value: v })) : Object.fromEntries(fields)
        return { id, fields, data, hasDuplicateFields: hasDup }
    })
}

function entryToExport(entry: StreamEntry): any {
    if (entry.hasDuplicateFields) return { id: entry.id, fields: entry.data }
    return { id: entry.id, ...entry.data }
}

const props = defineProps<{ response: any; value: any; valueBuffer: any; keyName: string; valueFormat: string }>()
const emit = defineEmits<{ refresh: [] }>()
const i18n = useI18nStore()
const strings = computed(() => i18n.strings)
const isReadonly = computed(() => useRedisStateStore().connection?.readonly === true)
const common = useCommonStore()

const allEntries = ref<StreamEntry[]>([])
const paging = ref<Paging>(createPaging(0))
const pagedEntries = ref<StreamEntry[]>([])
const editDialogOpen = ref(false)
const editDialogData = ref<any>(null)
const jsonViewOpen = ref(false)
const jsonViewValue = ref('')

function updatePaged(p: Paging) { paging.value = p; pagedEntries.value = allEntries.value.slice(p.startIndex, p.endIndex) }
watch(() => props.value, () => {
    const entries = buildEntries(props.value)
    allEntries.value = entries
    updatePaged(rePaging(paging.value, entries.length))
}, { immediate: true })

function showTimestamp(id: string): string {
    try {
        const ms = parseInt(id.slice(0, id.indexOf('-')))
        const lang = i18n.currentLang
        const locale = intlLocaleMap[lang] || lang
        return new Date(ms).toLocaleString(locale, { year: 'numeric', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' })
    } catch { return id }
}

function addStream() { editDialogData.value = { type: 'append', model: { type: 'stream', key: props.keyName } }; editDialogOpen.value = true }
function handleEditClose(r?: any) { editDialogOpen.value = false; editDialogData.value = null; if (r) emit('refresh') }

async function deleteEntry(id: string) {
    try { await common.confirm({ message: str(strings.value?.confirm?.deleteStreamTimestamp) }); await request({ action: 'key/stream-delete-timestamp', payload: { key: props.keyName, streamTimestamp: id } }); common.toast(str(strings.value?.status?.deletedStreamTimestamp)); emit('refresh') }
    catch (e) { if (e !== undefined) common.generalHandleError(e) }
}

function copyEntry(entry: StreamEntry) { copyToClipboard(JSON.stringify(entryToExport(entry), null, 2)) }
function downloadEntry(entry: StreamEntry) {
    const lines = [entry.id]; for (const [f, v] of entry.fields) { lines.push(f); lines.push(v) }
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${props.keyName}-${entry.id}.txt`; a.click(); URL.revokeObjectURL(url)
}
function viewEntryJson(entry: StreamEntry) { jsonViewValue.value = JSON.stringify(entryToExport(entry)); jsonViewOpen.value = true }
</script>

<template>
    <div>
        <KeyPagerInline :paging="paging" @page-changed="updatePaged" />
        <div class="p3xr-key-table-header">
            <span style="flex:1;">{{ str(strings?.page?.key?.stream?.table?.timestamp) }}</span>
            <span style="text-align:right;"><v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.add)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" style="cursor:pointer;color:inherit;" @click="addStream">mdi-plus</v-icon></template></v-tooltip></span>
        </div>
        <div v-for="(entry, i) in pagedEntries" :key="entry.id" class="p3xr-stream-entry" :class="{ 'p3xr-key-table-odd': i % 2 === 0 }">
            <div class="p3xr-stream-entry-header">
                <div style="display:flex;align-items:center;gap:12px;">
                    <v-tooltip :text="showTimestamp(entry.id)" location="top">
                        <template #activator="{ props: tp }">
                            <strong v-bind="tp" style="cursor:default;">{{ entry.id }}</strong>
                        </template>
                    </v-tooltip>
                    <span style="opacity:0.5;font-size:12px;">{{ showTimestamp(entry.id) }}</span>
                </div>
                <span style="white-space:nowrap;">
                    <v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.delete)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-error));" @click="deleteEntry(entry.id)">mdi-delete</v-icon></template></v-tooltip>
                    <v-tooltip :text="str(strings?.intention?.jsonViewShow)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="viewEntryJson(entry)">mdi-file-tree</v-icon></template></v-tooltip>
                    <v-tooltip :text="str(strings?.intention?.copy)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="copyEntry(entry)">mdi-content-copy</v-icon></template></v-tooltip>
                    <v-tooltip :text="str(strings?.intention?.downloadBuffer)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="downloadEntry(entry)">mdi-download</v-icon></template></v-tooltip>
                </span>
            </div>
            <div class="p3xr-stream-entry-fields">
                <div v-for="([field, val], fi) in entry.fields" :key="`${field}-${fi}`" class="p3xr-stream-field-row">
                    <span style="min-width:120px;opacity:0.7;">{{ field }}</span>
                    <span class="p3xr-stream-field-value">
                        <HexMonitor v-if="valueFormat === 'hex'" :value="truncateDisplay(val)" />
                        <template v-else>{{ truncateDisplay(formatValue(val, valueFormat)) }}<span v-if="isTruncated(val)" style="opacity:0.5;">...</span></template>
                    </span>
                </div>
            </div>
        </div>
        <KeyNewOrSetDialog :open="editDialogOpen" :data="editDialogData" @close="handleEditClose" />
        <JsonViewDialog :open="jsonViewOpen" :value="jsonViewValue" @close="jsonViewOpen = false" />
    </div>
</template>

<style src="./key-table.css"></style>
<style scoped>
.p3xr-stream-entry { border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.05); }
.p3xr-stream-entry:hover { background-color: rgba(var(--v-theme-on-surface), 0.1) !important; }
.p3xr-stream-entry-header { display: flex; align-items: center; justify-content: space-between; padding: 6px 16px; font-size: 13px; }
.p3xr-stream-entry-fields { padding: 0 16px 8px; overflow: auto; max-height: 300px; }
.p3xr-stream-field-row { display: flex; gap: 8px; padding: 2px 0; }
.p3xr-stream-field-value { flex: 1; max-height: 200px; overflow: auto; white-space: pre-wrap; word-break: break-all; font-family: 'Roboto Mono', monospace; }
</style>

// src/ng/pages/database/key/key-stream.component.ts
import { Component, Inject, OnInit, OnChanges, SimpleChanges, ChangeDetectorRef, CUSTOM_ELEMENTS_SCHEMA, ViewEncapsulation, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { BreakpointObserver } from '@angular/cdk/layout';
import { I18nService } from '../../../services/i18n.service';
import { SocketService } from '../../../services/socket.service';
import { CommonService } from '../../../services/common.service';
import { JsonViewDialogService } from '../../../dialogs/json-view-dialog.service';
import { KeyNewOrSetDialogService } from '../../../dialogs/key-new-or-set-dialog.service';
import { MainCommandService } from '../../../services/main-command.service';
import { RedisStateService } from '../../../services/redis-state.service';
import { SettingsService } from '../../../services/settings.service';
import { KeyTypeBase } from './key-type-base';
import { KeyPaging } from './key-paging';
import { KeyPagerInlineComponent } from './key-pager-inline.component';

const intlLocaleMap: Record<string, string> = { 'zn': 'zh-CN', 'no': 'nb', 'fil': 'tl' };

@Component({
    selector: 'p3xr-key-stream',
    standalone: true,
    imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatTooltipModule, KeyPagerInlineComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './key-stream.component.html',
    encapsulation: ViewEncapsulation.None,
})
export class KeyStreamComponent extends KeyTypeBase implements OnInit, OnChanges {
    paging: KeyPaging;
    pagedEntries: Array<{ id: string; fields: Array<[string, string]>; data: any; displayData: any; hasDuplicateFields: boolean }> = [];
    private allEntries: Array<{ id: string; fields: Array<[string, string]>; data: any; displayData: any; hasDuplicateFields: boolean }> = [];

    constructor(
        @Inject(I18nService) i18n: I18nService, @Inject(SocketService) socket: SocketService,
        @Inject(CommonService) common: CommonService, @Inject(JsonViewDialogService) jsonViewDialog: JsonViewDialogService,
        @Inject(KeyNewOrSetDialogService) keyNewOrSetDialog: KeyNewOrSetDialogService,
        @Inject(BreakpointObserver) breakpointObserver: BreakpointObserver,
        @Inject(MainCommandService) cmd: MainCommandService,
        @Inject(ChangeDetectorRef) cdr: ChangeDetectorRef,
        @Inject(RedisStateService) redisState: RedisStateService,
        @Inject(SettingsService) settingsService: SettingsService,
    ) {
        super(i18n, socket, common, jsonViewDialog, keyNewOrSetDialog, breakpointObserver, cmd, cdr, redisState, settingsService);
        this.paging = new KeyPaging({ settingsService });

        effect(() => {
            this.i18n.strings();
            if (this.allEntries.length === 0) {
                return;
            }

            this.allEntries = this.allEntries.map((entry) => ({
                ...entry,
                displayData: this.toDisplayData(entry.data, entry.hasDuplicateFields),
            }));
            this.updatePagedItems();
            this.cdr.markForCheck();
        });
    }

    ngOnInit(): void { this.updatePaging(); }
    ngOnChanges(c: SimpleChanges): void { if (c['p3xrValue']) this.updatePaging(); }

    updatePaging(): void {
        if (!this.p3xrValue) return;
        this.allEntries = this.p3xrValue.map((entry: any) => {
            const id = entry[0];
            const rawData = entry[1];
            const fields: Array<[string, string]> = [];
            for (let i = 0; i < rawData.length; i += 2) {
                fields.push([rawData[i], rawData[i + 1]]);
            }
            const hasDuplicateFields = this.hasDuplicateFields(fields);
            const data = hasDuplicateFields ? this.fieldsToArray(fields) : this.fieldsToObject(fields);
            return {
                id,
                fields,
                data,
                displayData: this.toDisplayData(data, hasDuplicateFields),
                hasDuplicateFields,
            };
        });
        this.paging.figurePaging(this.allEntries.length);
        this.updatePagedItems();
    }

    updatePagedItems(): void {
        this.pagedEntries = this.allEntries.slice(this.paging.startIndex, this.paging.endIndex);
    }

    showTimestamp(id: string): string {
        try {
            const ms = parseInt(id.slice(0, id.indexOf('-')));
            const lang = this.i18n.currentLang() || 'en';
            const locale = intlLocaleMap[lang] || lang;
            const date = new Date(ms);
            return date.toLocaleString(locale, { year: 'numeric', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' });
        } catch { return id; }
    }

    isJsonValue(value: string): boolean {
        if (!value || value.length < 2) return false;
        const first = value.charAt(0);
        if (first !== '{' && first !== '[') return false;
        try {
            JSON.parse(value);
            return true;
        } catch {
            return false;
        }
    }

    formatJsonValue(value: string): string {
        try {
            return JSON.stringify(JSON.parse(value), null, this.settingsService.jsonFormat() ?? 2);
        } catch {
            return value;
        }
    }

    private parseFieldValue(value: string): any {
        try {
            return JSON.parse(value);
        } catch {
            return value;
        }
    }

    private hasDuplicateFields(fields: Array<[string, string]>): boolean {
        const seen = new Set<string>();
        for (const [key] of fields) {
            if (seen.has(key)) {
                return true;
            }
            seen.add(key);
        }
        return false;
    }

    private fieldsToObject(fields: Array<[string, string]>): any {
        const obj: any = {};
        for (const [key, value] of fields) {
            obj[key] = this.parseFieldValue(value);
        }
        return obj;
    }

    private fieldsToArray(fields: Array<[string, string]>): Array<{ field: string; value: any }> {
        return fields.map(([field, value]) => ({
            field,
            value: this.parseFieldValue(value),
        }));
    }

    private toDisplayData(data: any, hasDuplicateFields: boolean): any {
        if (!hasDuplicateFields) {
            return data;
        }

        const fieldLabel = this.strings?.page?.key?.stream?.table?.field || 'Field';
        const valueLabel = this.strings?.page?.key?.stream?.table?.value || 'Value';
        return data.map((item: { field: string; value: any }) => ({
            [fieldLabel]: item.field,
            [valueLabel]: item.value,
        }));
    }

    private entryToExport(entry: { id: string; fields: Array<[string, string]>; data: any; displayData: any; hasDuplicateFields: boolean }): any {
        if (entry.hasDuplicateFields) {
            return {
                id: entry.id,
                fields: entry.data,
            };
        }
        return { id: entry.id, ...entry.data };
    }

    downloadEntry(entry: { id: string; fields: Array<[string, string]> }): void {
        const lines = [entry.id];
        for (const [field, value] of entry.fields) {
            lines.push(field);
            lines.push(value);
        }
        const text = lines.join('\n');
        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${this.p3xrKey}-${entry.id}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    }

    async copyEntry(entry: { id: string; fields: Array<[string, string]>; data: any; displayData: any; hasDuplicateFields: boolean }): Promise<void> {
        const obj = this.entryToExport(entry);
        await this.copy(JSON.stringify(obj, null, 2));
    }

    async viewEntryJson(entry: { id: string; fields: Array<[string, string]>; data: any; displayData: any; hasDuplicateFields: boolean }, event?: Event): Promise<void> {
        const obj = this.entryToExport(entry);
        await this.showJson(JSON.stringify(obj), event);
    }

    async viewFieldJson(value: string, event?: Event): Promise<void> {
        await this.showJson(value, event);
    }

    copyField(value: any): void { this.copy(value); }

    async addStream(event: Event): Promise<void> {
        try {
            await this.keyNewOrSetDialog.show({ $event: event, type: 'append', model: { type: 'stream', key: this.p3xrKey } });
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    async deleteStreamTimestamp(id: string, event: Event): Promise<void> {
        try {
            await this.common.confirm({ message: this.i18n.strings().confirm?.deleteStreamTimestamp });
            await this.socket.request({ action: 'key-stream-delete-timestamp', payload: { key: this.p3xrKey, streamTimestamp: id } });
            this.common.toast(this.i18n.strings().status?.deletedStreamTimestamp || this.i18n.strings().status?.deletedKey || 'Deleted');
            this.refreshKey();
        } catch (e) { if (e) this.common.generalHandleError(e); }
    }
}

<p3xr-key-pager-inline [paging]="paging" (pageChanged)="updatePagedItems()"></p3xr-key-pager-inline>

<div class="p3xr-key-type-table">
    <div class="p3xr-key-type-header">
        <span style="flex: 1">{{ strings?.page?.key?.stream?.table?.timestamp || 'Timestamp ID' }}</span>
        <span style="text-align: right">
            @if (!isReadonly) {
                <button mat-icon-button (click)="addStream($event)" [matTooltip]="strings?.intention?.add ?? 'Add'">
                    <mat-icon svgIcon="add"></mat-icon>
                </button>
            }
        </span>
    </div>

    @for (entry of pagedEntries; track entry.id) {
        <div class="p3xr-key-stream-entry-block">
            <!-- Entry header: timestamp + actions -->
            <div class="p3xr-key-stream-entry-header">
                <span class="p3xr-key-stream-timestamp">
                    <strong>{{ entry.id }}</strong>
                    <span class="p3xr-key-stream-timestamp-human">{{ showTimestamp(entry.id) }}</span>
                </span>
                <span class="p3xr-key-type-row-actions">
                    @if (!isReadonly) {
                        <mat-icon class="icon-warn" (click)="deleteStreamTimestamp(entry.id, $event)" [matTooltip]="strings?.intention?.delete ?? 'Delete'">delete</mat-icon>
                    }
                    <mat-icon class="icon-accent" (click)="viewEntryJson(entry, $event)" [matTooltip]="strings?.json ?? 'JSON'">account_tree</mat-icon>
                    <mat-icon class="icon-accent" (click)="copyEntry(entry)" [matTooltip]="strings?.intention?.copy ?? 'Copy'">content_copy</mat-icon>
                    <mat-icon class="icon-accent" (click)="downloadEntry(entry)" [matTooltip]="strings?.intention?.downloadBuffer ?? 'Download'">download</mat-icon>
                </span>
            </div>

            <!-- Entry fields -->
            <div class="p3xr-key-stream-data">
                @for (field of entry.fields; track field[0]) {
                    <div style="display: flex; gap: 8px; padding: 2px 0;">
                        <span style="min-width: 120px; opacity: 0.7;">{{ field[0] }}</span>
                        <span class="p3xr-value-col" [class.p3xr-pre]="valueFormat !== 'hex'" style="flex: 1; max-height: 200px; word-break: break-all;">@if (valueFormat === 'hex') {<p3xr-hex-monitor [value]="truncateDisplay(field[1])" [truncated]="isTruncated(field[1])"></p3xr-hex-monitor>} @else {{{ truncateDisplay(formatValue(field[1])) }}@if (isTruncated(field[1])) {<span style="opacity: 0.5;">...</span>}}</span>
                    </div>
                }
            </div>
        </div>
    }
</div>
