// src/vue/pages/database/key/KeyVectorset.vue
<script setup lang="ts">
/**
 * Vectorset key type renderer — exact port of React KeyVectorset.tsx.
 * Info display, element list with paging, similarity search (by element / by vector).
 */
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import P3xrAccordion from '../../../components/P3xrAccordion.vue'
import P3xrButton from '../../../components/P3xrButton.vue'
import KeyPagerInline from './KeyPagerInline.vue'
import { useI18nStore } from '../../../stores/i18n'
import { useRedisStateStore } from '../../../stores/redis-state'
import { useCommonStore } from '../../../stores/common'
import { request } from '../../../stores/socket.service'
import { type Paging, createPaging, rePaging, str } from './key-type-base'
import { parseRedisVersion } from '../../../../core/redis-version'

const props = defineProps<{ response: any; value: any; valueBuffer: any; keyName: string; valueFormat: string }>()
const emit = defineEmits<{ refresh: [] }>()

const strings = computed(() => useI18nStore().strings)
const state = useRedisStateStore()
const isReadonly = computed(() => state.connection?.readonly === true)
const common = useCommonStore()

const elements = ref<any[]>([])
const paging = ref<Paging>(createPaging(0))
const simResults = ref<Array<{ element: string; score: number }>>([])
const autoRefresh = ref(false)
const elementInput = ref('')
const vectorInput = ref('')
const simCountInput = ref(10)
const simFilterInput = ref('')
const simSearchInput = ref('')
const showAddForm = ref(false)
let autoRefreshTimer: any = null

const supportsFilter = computed(() => parseRedisVersion(state.info?.server?.redis_version).isAtLeast(8, 2))

const infoItems = computed(() => {
    try {
        let info: any
        if (typeof props.value === 'object' && props.value !== null && !ArrayBuffer.isView(props.value)) info = props.value
        else if (typeof props.value === 'string') info = JSON.parse(props.value)
        else if (ArrayBuffer.isView(props.value)) info = JSON.parse(new TextDecoder().decode(props.value))
        if (info && typeof info === 'object') return Object.entries(info).map(([key, value]) => ({ key, value }))
    } catch {}
    return []
})

onMounted(() => loadElements())
onUnmounted(() => clearInterval(autoRefreshTimer))

watch(autoRefresh, (v) => {
    clearInterval(autoRefreshTimer)
    if (v) autoRefreshTimer = setInterval(() => { emit('refresh'); loadElements() }, 10000)
})

async function loadElements() {
    try {
        const resp: any = await request({ action: 'vectorset/elements', payload: { key: props.keyName } })
        elements.value = resp.elements || []
        paging.value = rePaging(paging.value, elements.value.length)
    } catch { elements.value = [] }
}

function updatePaging(p: Paging) { paging.value = p }

async function searchByElement() {
    if (!simSearchInput.value.trim()) return
    try {
        const resp: any = await request({ action: 'vectorset/sim', payload: { key: props.keyName, mode: 'element', element: simSearchInput.value.trim(), count: simCountInput.value, filter: simFilterInput.value.trim() || undefined } })
        simResults.value = resp.results || []
        common.toast(str(strings.value?.page?.key?.vectorset?.searchComplete) || 'Search complete')
    } catch (e: any) { common.toast(e.message || 'Error') }
}

async function searchByVector() {
    if (!simSearchInput.value.trim()) return
    try {
        const values = simSearchInput.value.split(',').map(Number)
        const resp: any = await request({ action: 'vectorset/sim', payload: { key: props.keyName, mode: 'vector', values, count: simCountInput.value, filter: simFilterInput.value.trim() || undefined } })
        simResults.value = resp.results || []
        common.toast(str(strings.value?.page?.key?.vectorset?.searchComplete) || 'Search complete')
    } catch (e: any) { common.toast(e.message || 'Error') }
}

async function searchByElementDirect(element: string) {
    try {
        const resp: any = await request({ action: 'vectorset/sim', payload: { key: props.keyName, mode: 'element', element, count: simCountInput.value } })
        simResults.value = resp.results || []
        common.toast(str(strings.value?.page?.key?.vectorset?.searchComplete) || 'Search complete')
    } catch (e: any) { common.toast(e.message || 'Error') }
}

async function getAttributes(element: string) {
    try {
        const resp: any = await request({ action: 'vectorset/getattr', payload: { key: props.keyName, element } })
        const attrs = resp.attributes
        common.toast(attrs && Object.keys(attrs).length > 0
            ? `${element}: ${JSON.stringify(attrs)}`
            : `${element}: ${str(strings.value?.page?.key?.vectorset?.noAttributes) || 'No attributes'}`)
    } catch (e: any) { if (e?.message) common.toast(e.message) }
}

async function addElement() {
    if (!elementInput.value.trim() || !vectorInput.value.trim()) return
    try {
        await request({ action: 'vectorset/add', payload: { key: props.keyName, element: elementInput.value.trim(), values: vectorInput.value.split(',').map(Number) } })
        common.toast(str(strings.value?.page?.key?.vectorset?.addedSuccessfully) || 'Element added successfully')
        elementInput.value = ''; vectorInput.value = ''
        emit('refresh'); loadElements()
    } catch (e: any) { common.toast(e.message || 'Error') }
}

async function removeElement(element: string) {
    try {
        await common.confirm({ message: str(strings.value?.confirm?.delete) || 'Delete?' })
        await request({ action: 'vectorset/remove', payload: { key: props.keyName, element } })
        common.toast(str(strings.value?.page?.key?.vectorset?.deletedSuccessfully) || 'Element deleted successfully')
        emit('refresh'); loadElements()
    } catch (e: any) { if (e?.message) common.toast(e.message) }
}
</script>

<template>
    <div class="p3xr-key-type-content">
        <!-- INFO -->
        <br />
        <P3xrAccordion :title="str(strings?.page?.key?.vectorset?.info) || 'Info'" accordion-key="vs-info">
            <template #actions>
                <P3xrButton :icon="autoRefresh ? 'mdi-checkbox-marked' : 'mdi-checkbox-blank-outline'" :label="str(strings?.label?.autoRefresh) || 'Auto'" :breakpoint="1280" color="inherit" @click.stop="autoRefresh = !autoRefresh" />
                <P3xrButton v-if="!autoRefresh" icon="mdi-refresh" :label="str(strings?.intention?.refresh) || 'Refresh'" :breakpoint="1280" color="inherit" @click.stop="emit('refresh'); loadElements()" />
            </template>
            <v-list density="compact">
                <template v-for="(item, i) in infoItems" :key="item.key">
                    <v-list-item>
                        <div style="display: flex; width: 100%;">
                            <span style="flex: 1; font-weight: 500;">{{ item.key }}</span>
                            <span style="word-break: break-all;">{{ String(item.value) }}</span>
                        </div>
                    </v-list-item>
                    <v-divider v-if="i < infoItems.length - 1" />
                </template>
            </v-list>
        </P3xrAccordion>

        <!-- ELEMENTS -->
        <br />
        <P3xrAccordion :title="(str(strings?.page?.key?.vectorset?.elements) || 'Elements') + ` (${elements.length})`" accordion-key="vs-elements">
            <KeyPagerInline :paging="paging" @page-changed="updatePaging" />
            <div class="p3xr-key-table-header">
                <span style="flex: 50%;">{{ str(strings?.page?.key?.vectorset?.element) || 'Element' }}</span>
                <span style="flex: 20%;">{{ str(strings?.page?.key?.vectorset?.score) || 'Score' }}</span>
                <span style="flex: 30%; text-align: right; display: flex; justify-content: flex-end; align-items: center;">
                    <v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.add) || 'Add'" location="top">
                        <template #activator="{ props: tp }"><v-icon v-bind="tp" style="cursor:pointer;color:inherit;" @click="showAddForm = !showAddForm">mdi-plus</v-icon></template>
                    </v-tooltip>
                </span>
            </div>
            <div v-for="(elem, i) in elements.slice(paging.startIndex, paging.startIndex + paging.pageCount)" :key="elem.element"
                class="p3xr-vs-row" :class="{ 'p3xr-vs-odd': i % 2 === 0 }">
                <span style="flex: 50%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ elem.element }}</span>
                <span style="flex: 20%; font-family: 'Roboto Mono', monospace;">{{ elem.score?.toFixed(4) }}</span>
                <span style="flex: 30%; text-align: right; white-space: nowrap;">
                    <v-tooltip :text="'Find similar'" location="top"><template #activator="{ props: tp }">
                        <v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="simSearchInput = elem.element; searchByElementDirect(elem.element)">mdi-magnify</v-icon>
                    </template></v-tooltip>
                    <v-tooltip :text="str(strings?.page?.key?.vectorset?.attributes) || 'Attributes'" location="top"><template #activator="{ props: tp }">
                        <v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="getAttributes(elem.element)">mdi-information</v-icon>
                    </template></v-tooltip>
                    <v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.delete) || 'Delete'" location="top"><template #activator="{ props: tp }">
                        <v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-error));" @click="removeElement(elem.element)">mdi-delete</v-icon>
                    </template></v-tooltip>
                </span>
            </div>
            <!-- Add form -->
            <div v-if="!isReadonly && showAddForm" style="padding: 16px;">
                <div class="p3xr-vs-controls">
                    <v-text-field density="compact" variant="outlined" hide-details style="flex: 1; min-width: 200px;"
                        :label="str(strings?.page?.key?.vectorset?.elementName) || 'Element name'"
                        v-model="elementInput" @keyup.enter="addElement()" />
                    <v-text-field density="compact" variant="outlined" hide-details style="flex: 1; min-width: 200px;"
                        :label="str(strings?.page?.key?.vectorset?.vectorValues) || 'Vector values'" placeholder="0.1, 0.2, 0.3"
                        v-model="vectorInput" @keyup.enter="addElement()" />
                    <P3xrButton icon="mdi-plus" :label="str(strings?.intention?.add) || 'Add'" raised color="primary" @click="addElement()" />
                </div>
            </div>
        </P3xrAccordion>

        <!-- SIMILARITY SEARCH -->
        <br />
        <P3xrAccordion :title="str(strings?.page?.key?.vectorset?.similaritySearch) || 'Similarity Search'" accordion-key="vs-sim">
            <div style="padding: 16px;">
                <div class="p3xr-vs-controls">
                    <v-text-field density="compact" variant="outlined" hide-details style="flex: 1; min-width: 200px;"
                        :label="str(strings?.page?.key?.vectorset?.searchTerm) || 'Search term'"
                        v-model="simSearchInput" @keyup.enter="searchByElement()" />
                    <v-text-field density="compact" variant="outlined" hide-details type="number" style="width: 80px; max-width: 80px;"
                        :label="str(strings?.page?.key?.vectorset?.count) || 'Count'"
                        v-model.number="simCountInput" />
                    <v-text-field v-if="supportsFilter" density="compact" variant="outlined" hide-details style="flex: 1; min-width: 150px;"
                        :label="str(strings?.page?.key?.vectorset?.filter) || 'Filter'" placeholder="attr == 'value'"
                        v-model="simFilterInput" @keyup.enter="searchByElement()" />
                    <P3xrButton icon="mdi-account" :label="str(strings?.page?.key?.vectorset?.byElement) || 'By Element'" raised color="primary" @click="searchByElement()" />
                    <P3xrButton icon="mdi-code-array" :label="str(strings?.page?.key?.vectorset?.byVector) || 'By Vector'" raised color="primary" @click="searchByVector()" />
                </div>
                <template v-if="simResults.length > 0">
                    <v-divider class="my-2" />
                    <v-list density="compact">
                        <template v-for="(entry, i) in simResults" :key="i">
                            <v-list-item>
                                <div style="display: flex; width: 100%;">
                                    <span style="flex: 1; font-weight: 500;">{{ entry.element }}</span>
                                    <span>{{ entry.score }}</span>
                                </div>
                            </v-list-item>
                            <v-divider v-if="i < simResults.length - 1" />
                        </template>
                    </v-list>
                </template>
            </div>
        </P3xrAccordion>
    </div>
</template>

<style scoped>
.p3xr-key-type-content { padding: 8px 16px 24px; }
.p3xr-vs-controls { display: flex; flex-wrap: wrap; align-items: flex-start; gap: 12px; padding: 8px 0; }
.p3xr-key-table-header {
    display: flex; align-items: center; gap: 8px; padding: 8px 16px; font-weight: bold;
    background-color: rgb(var(--v-theme-primary)); color: rgb(var(--v-theme-on-primary));
    border-bottom: 2px solid rgba(var(--v-theme-on-surface), 0.05);
}
.p3xr-vs-row {
    display: flex; align-items: center; gap: 8px; padding: 6px 16px;
    border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.05);
}
.p3xr-vs-row:hover { background-color: rgba(var(--v-theme-on-surface), 0.1) !important; }
.p3xr-vs-odd { background-color: rgba(var(--v-theme-on-surface), 0.04); }
</style>

// src/ng/pages/database/key/key-vectorset.component.ts
import { Component, Inject, OnInit, OnChanges, OnDestroy, SimpleChanges, ChangeDetectorRef, CUSTOM_ELEMENTS_SCHEMA, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatListModule } from '@angular/material/list';
import { MatDividerModule } from '@angular/material/divider';
import { BreakpointObserver } from '@angular/cdk/layout';
import { I18nService } from '../../../services/i18n.service';
import { SocketService } from '../../../services/socket.service';
import { CommonService } from '../../../services/common.service';
import { JsonViewDialogService } from '../../../dialogs/json-view-dialog.service';
import { KeyNewOrSetDialogService } from '../../../dialogs/key-new-or-set-dialog.service';
import { MainCommandService } from '../../../services/main-command.service';
import { RedisStateService } from '../../../services/redis-state.service';
import { SettingsService } from '../../../services/settings.service';
import { KeyTypeBase } from './key-type-base';
import { KeyPaging } from './key-paging';
import { KeyPagerInlineComponent } from './key-pager-inline.component';
import { P3xrAccordionComponent } from '../../../components/p3xr-accordion.component';
import { P3xrButtonComponent } from '../../../components/p3xr-button.component';

@Component({
    selector: 'p3xr-key-vectorset',
    standalone: true,
    imports: [
        CommonModule, FormsModule,
        MatButtonModule, MatIconModule, MatTooltipModule,
        MatFormFieldModule, MatInputModule,
        MatListModule, MatDividerModule,
        P3xrAccordionComponent, P3xrButtonComponent, KeyPagerInlineComponent,
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './key-vectorset.component.html',
    encapsulation: ViewEncapsulation.None,
})
export class KeyVectorsetComponent extends KeyTypeBase implements OnInit, OnChanges, OnDestroy {

    infoItems: Array<{ key: string; value: any }> = [];
    elements: Array<{ element: string; score: number }> = [];
    pagedElements: Array<{ element: string; score: number }> = [];
    paging: KeyPaging;
    simResults: Array<{ element: string; score: number }> = [];

    elementInput = '';
    vectorInput = '';
    simQueryInput = '';
    simCountInput = 10;
    simFilterInput = '';
    simMode: 'element' | 'vector' = 'element';

    autoRefresh = false;
    private autoRefreshInterval: any = null;
    readonly = false;
    showAddForm = false;

    constructor(
        @Inject(I18nService) i18n: I18nService,
        @Inject(SocketService) socket: SocketService,
        @Inject(CommonService) common: CommonService,
        @Inject(JsonViewDialogService) jsonViewDialog: JsonViewDialogService,
        @Inject(KeyNewOrSetDialogService) keyNewOrSetDialog: KeyNewOrSetDialogService,
        @Inject(BreakpointObserver) breakpointObserver: BreakpointObserver,
        @Inject(MainCommandService) cmd: MainCommandService,
        @Inject(ChangeDetectorRef) cdr: ChangeDetectorRef,
        @Inject(RedisStateService) redisState: RedisStateService,
        @Inject(SettingsService) settingsService: SettingsService,
    ) {
        super(i18n, socket, common, jsonViewDialog, keyNewOrSetDialog, breakpointObserver, cmd, cdr, redisState, settingsService);
        this.paging = new KeyPaging({ settingsService });
    }

    updatePagedElements(): void {
        this.pagedElements = this.elements.slice(this.paging.startIndex, this.paging.endIndex);
    }

    get strings() {
        return this.i18n.strings;
    }

    ngOnInit() {
        this.readonly = this.redisState.connection()?.readonly === true;
        this.parseInfo();
        this.loadElements();
    }

    ngOnChanges(changes: SimpleChanges) {
        if (changes['p3xrValue']) {
            this.parseInfo();
        }
    }

    ngOnDestroy() {
        this.stopAutoRefresh();
        this.destroyBase();
    }

    toggleAutoRefresh(): void {
        this.autoRefresh = !this.autoRefresh;
        if (this.autoRefresh) {
            this.startAutoRefresh();
        } else {
            this.stopAutoRefresh();
        }
        this.cdr.markForCheck();
    }

    private startAutoRefresh(): void {
        this.stopAutoRefresh();
        this.autoRefreshInterval = setInterval(() => {
            this.refresh();
        }, 10000);
    }

    private stopAutoRefresh(): void {
        if (this.autoRefreshInterval) {
            clearInterval(this.autoRefreshInterval);
            this.autoRefreshInterval = null;
        }
    }

    private parseInfo() {
        this.infoItems = [];
        try {
            const val = this.p3xrValue;
            let info: any;
            if (typeof val === 'object' && val !== null && !ArrayBuffer.isView(val)) {
                info = val;
            } else if (typeof val === 'string') {
                info = JSON.parse(val);
            } else if (ArrayBuffer.isView(val)) {
                info = JSON.parse(new TextDecoder().decode(val as any));
            }
            if (info && typeof info === 'object') {
                this.infoItems = Object.entries(info).map(([key, value]) => ({ key, value }));
            }
        } catch {
            // ignore parse errors
        }
    }

    async loadElements() {
        try {
            const response = await this.socket.request({
                action: 'vectorset-elements',
                payload: {
                    key: this.p3xrKey,
                },
            });
            this.elements = (response as any).elements || [];
            this.paging.figurePaging(this.elements.length);
            this.updatePagedElements();
        } catch {
            this.elements = [];
            this.pagedElements = [];
        }
        this.cdr.markForCheck();
    }

    async searchSimilar(queryValue?: string, mode?: 'element' | 'vector') {
        const query = queryValue || this.simQueryInput;
        const searchMode = mode || this.simMode;
        if (!query.trim()) return;
        try {
            const response = await this.socket.request({
                action: 'vectorset-sim',
                payload: {
                    key: this.p3xrKey,
                    query: query.trim(),
                    count: this.simCountInput,
                    mode: searchMode,
                    filter: this.simFilterInput.trim() || undefined,
                },
            });
            this.simResults = (response as any).results || [];
            this.common.toast(this.strings()?.page?.key?.vectorset?.searchComplete || 'Search complete');
        } catch (e: any) {
            this.common.toast(e.message || 'Error');
            this.simResults = [];
        }
        this.cdr.markForCheck();
    }

    searchSimilarByElement(element: string) {
        this.simQueryInput = element;
        this.simMode = 'element';
        this.searchSimilar(element, 'element');
    }

    async addElement() {
        if (!this.elementInput.trim() || !this.vectorInput.trim()) return;
        try {
            await this.socket.request({
                action: 'vectorset-add',
                payload: {
                    key: this.p3xrKey,
                    element: this.elementInput.trim(),
                    vector: this.vectorInput.trim(),
                },
            });
            this.common.toast(this.strings()?.page?.key?.vectorset?.addedSuccessfully || 'Element added successfully');
            this.elementInput = '';
            this.vectorInput = '';
            this.refresh();
        } catch (e: any) {
            this.common.toast(e.message || 'Error');
        }
        this.cdr.markForCheck();
    }

    async removeElement(element: string) {
        try {
            await this.common.confirm({
                message: this.strings()?.confirm?.delete || 'Delete?',
            });
            await this.socket.request({
                action: 'vectorset-remove',
                payload: {
                    key: this.p3xrKey,
                    element: element,
                },
            });
            this.common.toast(this.strings()?.page?.key?.vectorset?.removedSuccessfully || 'Element removed successfully');
            this.refresh();
        } catch (e: any) {
            if (e?.message) this.common.toast(e.message);
        }
        this.cdr.markForCheck();
    }

    async getAttributes(element: string) {
        try {
            const response = await this.socket.request({
                action: 'vectorset-getattr',
                payload: {
                    key: this.p3xrKey,
                    element: element,
                },
            });
            const attrs = (response as any).attributes;
            if (attrs) {
                this.common.toast(`${element}: ${JSON.stringify(attrs)}`);
            } else {
                this.common.toast(`${element}: ${this.strings()?.page?.key?.vectorset?.noAttributes || 'No attributes'}`);
            }
        } catch (e: any) {
            this.common.toast(e.message || 'Error');
        }
        this.cdr.markForCheck();
    }

    refresh() {
        this.cmd.refreshKey$.next();
        this.loadElements();
    }
}

<div class="p3xr-key-type-content">

    <!-- INFO -->
    <br />
    <p3xr-ng-accordion [title]="strings()?.page?.key?.vectorset?.info || 'Info'" accordionKey="vs-info">
        <div actions>
            <p3xr-ng-button
                (click)="toggleAutoRefresh(); $event.stopPropagation()"
                [label]="strings()?.label?.autoRefresh || 'Auto'"
                [mdIcon]="autoRefresh ? 'check_box' : 'check_box_outline_blank'"
                [breakpoint]="1280">
            </p3xr-ng-button>
            @if (!autoRefresh) {
                <p3xr-ng-button
                    (click)="refresh(); $event.stopPropagation()"
                    [label]="strings()?.intention?.refresh || 'Refresh'"
                    mdIcon="refresh"
                    [breakpoint]="1280">
                </p3xr-ng-button>
            }
        </div>
        <div content>
            <mat-list>
                @for (item of infoItems; track item.key; let last = $last) {
                    <mat-list-item>
                        <div style="display: flex; width: 100%;">
                            <span class="p3xr-settings-label" style="flex: 1;">{{ item.key }}</span>
                            <span class="p3xr-settings-value">{{ item.value }}</span>
                        </div>
                    </mat-list-item>
                    @if (!last) { <mat-divider></mat-divider> }
                }
            </mat-list>
        </div>
    </p3xr-ng-accordion>

    <!-- ELEMENTS -->
    <br />
    <p3xr-ng-accordion [title]="(strings()?.page?.key?.vectorset?.elements || 'Elements') + ' (' + elements.length + ')'" accordionKey="vs-elements">
        <div content>
            <p3xr-key-pager-inline [paging]="paging" (pageChanged)="updatePagedElements()"></p3xr-key-pager-inline>
            <div class="p3xr-key-type-table">
                <div class="p3xr-key-type-header">
                    <span style="flex: 50%">{{ strings()?.page?.key?.vectorset?.element || 'Element' }}</span>
                    <span style="flex: 20%">{{ strings()?.page?.key?.vectorset?.score || 'Score' }}</span>
                    <span style="flex: 30%; text-align: right">
                        @if (!readonly) {
                            <button mat-icon-button (click)="showAddForm = !showAddForm" matTooltip="Add">
                                <mat-icon>add</mat-icon>
                            </button>
                        }
                    </span>
                </div>
                @for (elem of pagedElements; track elem.element) {
                    <div class="p3xr-key-type-row">
                        <span class="p3xr-key-col" style="flex: 50%">{{ elem.element }}</span>
                        <span class="p3xr-value-col" style="flex: 20%">{{ elem.score?.toFixed(4) }}</span>
                        <span style="flex: 30%; text-align: right" class="p3xr-key-type-row-actions">
                            <mat-icon class="icon-accent" (click)="searchSimilarByElement(elem.element)" matTooltip="Find similar">search</mat-icon>
                            <mat-icon class="icon-accent" (click)="getAttributes(elem.element)" matTooltip="Attributes">info</mat-icon>
                            @if (!readonly) {
                                <mat-icon class="icon-warn" (click)="removeElement(elem.element)" matTooltip="Delete">delete</mat-icon>
                            }
                        </span>
                    </div>
                }
            </div>

                @if (!readonly && showAddForm) {
                    <div class="p3xr-timeseries-controls" style="padding: 16px;">
                        <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic" style="flex: 1; min-width: 200px;">
                            <mat-label>{{ strings()?.page?.key?.vectorset?.elementName || 'Element name' }}</mat-label>
                            <input matInput [(ngModel)]="elementInput" (keydown.enter)="addElement()" />
                        </mat-form-field>

                        <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic" style="flex: 1; min-width: 200px;">
                            <mat-label>{{ strings()?.page?.key?.vectorset?.vectorValues || 'Vector values' }}</mat-label>
                            <input matInput [(ngModel)]="vectorInput" (keydown.enter)="addElement()" placeholder="0.1, 0.2, 0.3" />
                        </mat-form-field>

                        @if (isGtSm) {
                            <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="addElement()">
                                <mat-icon>add</mat-icon>
                                <span>{{ strings()?.intention?.add || 'Add' }}</span>
                            </button>
                        } @else {
                            <button mat-mini-fab class="btn-primary" type="button" (click)="addElement()"
                                    [matTooltip]="strings()?.intention?.add ?? 'Add'" matTooltipPosition="above">
                                <mat-icon>add</mat-icon>
                            </button>
                        }
                    </div>
                }
        </div>
    </p3xr-ng-accordion>

    <!-- SIMILARITY SEARCH -->
    <br />
    <p3xr-ng-accordion [title]="strings()?.page?.key?.vectorset?.similaritySearch || 'Similarity Search'" accordionKey="vs-sim">
        <div content>
            <div style="padding: 16px;">
                <div class="p3xr-timeseries-controls">
                    <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic" style="flex: 1; min-width: 200px;">
                        <mat-label>{{ simMode === 'element' ? (strings()?.page?.key?.vectorset?.elementName || 'Element name') : (strings()?.page?.key?.vectorset?.vectorValues || 'Vector values') }}</mat-label>
                        <input matInput [(ngModel)]="simQueryInput" (keydown.enter)="searchSimilar()" [placeholder]="simMode === 'vector' ? '0.1, 0.2, 0.3' : ''" />
                    </mat-form-field>

                    <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic" style="max-width: 80px;">
                        <mat-label>{{ strings()?.page?.key?.vectorset?.count || 'Count' }}</mat-label>
                        <input matInput type="number" [(ngModel)]="simCountInput" />
                    </mat-form-field>

                    @if (redisState.redisVersion().isAtLeast(8, 2)) {
                        <mat-form-field class="p3xr-timeseries-field" subscriptSizing="dynamic" style="flex: 1; min-width: 150px;">
                            <mat-label>{{ strings()?.page?.key?.vectorset?.filter || 'Filter' }}</mat-label>
                            <input matInput [(ngModel)]="simFilterInput" (keydown.enter)="searchSimilar()" placeholder="attr == 'value'" />
                        </mat-form-field>
                    }

                    @if (isGtSm) {
                        <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="simMode = 'element'; searchSimilar()">
                            <mat-icon>person</mat-icon>
                            <span>{{ strings()?.page?.key?.vectorset?.byElement || 'By Element' }}</span>
                        </button>
                        <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="simMode = 'vector'; searchSimilar()">
                            <mat-icon>data_array</mat-icon>
                            <span>{{ strings()?.page?.key?.vectorset?.byVector || 'By Vector' }}</span>
                        </button>
                    } @else {
                        <button mat-mini-fab class="btn-primary" type="button" (click)="simMode = 'element'; searchSimilar()"
                                [matTooltip]="strings()?.page?.key?.vectorset?.byElement ?? 'By Element'" matTooltipPosition="above">
                            <mat-icon>person</mat-icon>
                        </button>
                        <button mat-mini-fab class="btn-primary" type="button" (click)="simMode = 'vector'; searchSimilar()"
                                [matTooltip]="strings()?.page?.key?.vectorset?.byVector ?? 'By Vector'" matTooltipPosition="above">
                            <mat-icon>data_array</mat-icon>
                        </button>
                    }
                </div>

                @if (simResults.length > 0) {
                    <mat-divider style="margin: 16px 0;"></mat-divider>
                    <mat-list>
                        @for (result of simResults; track result.element; let last = $last) {
                            <mat-list-item>
                                <div style="display: flex; width: 100%;">
                                    <span class="p3xr-settings-label" style="flex: 1; font-weight: bold;">{{ result.element }}</span>
                                    <span class="p3xr-settings-value">{{ result.score }}</span>
                                </div>
                            </mat-list-item>
                            @if (!last) { <mat-divider></mat-divider> }
                        }
                    </mat-list>
                }
            </div>
        </div>
    </p3xr-ng-accordion>

</div>
