// src/react/pages/database/key/KeyString.tsx
/**
 * String key type renderer — exact port of Angular key-string.component.
 *
 * View mode: Upload, Download, JSON View, Copy, Format JSON, JSON Editor, Edit
 * Edit mode: Validate JSON toggle, Cancel, Upload, Save
 * Display: truncated value with format toggle, click to edit
 */
import { useState, useCallback, useRef } from 'react'
import { Box, Button, Tooltip, TextField, Switch, FormControlLabel, useMediaQuery } from '@mui/material'
import {
    Upload, Download, TableChart, ContentCopy, FormatLineSpacing,
    Description, Edit, Cancel, Save, Numbers,
} from '@mui/icons-material'
import { useI18nStore } from '../../../stores/i18n.store'
import { useRedisStateStore } from '../../../stores/redis-state.store'
import { trackPage } from '../../../stores/analytics'
import { useSettingsStore } from '../../../stores/settings.store'
import { useCommonStore } from '../../../stores/common.store'
import { useOverlayStore } from '../../../stores/overlay.store'
import { request } from '../../../stores/socket.service'
import { KeyTypeProps, formatValue, truncateDisplay, isTruncated, copyValue, downloadBuffer } from './key-type-base'
import HexMonitor from './HexMonitor'
import { parseRedisVersion } from '../../../../core/redis-version'
import JsonViewDialog from '../../../dialogs/JsonViewDialog'
import JsonEditorDialog from '../../../dialogs/JsonEditorDialog'
import DiffDialog from '../../../dialogs/DiffDialog'

export default function KeyString({ response, value: initValue, valueBuffer: initBuffer, keyName, valueFormat, onRefresh }: KeyTypeProps) {
    const strings = useI18nStore(s => s.strings)
    const connection = useRedisStateStore(s => s.connection)
    const settings = useSettingsStore()
    const { toast, generalHandleError, confirm } = useCommonStore()
    const overlay = useOverlayStore()
    const isGtSm = useMediaQuery('(min-width: 960px)')
    const isReadonly = connection?.readonly === true

    const [editable, setEditable] = useState(false)
    const [buffer, setBuffer] = useState(false)
    const [validateJson, setValidateJson] = useState(false)
    const [value, setValue] = useState(initValue)
    const [valueBuffer, setValueBuffer] = useState(initBuffer)
    const [originalValue, setOriginalValue] = useState<any>(null)
    const [jsonViewOpen, setJsonViewOpen] = useState(false)
    const [jsonEditorOpen, setJsonEditorOpen] = useState(false)
    const [diffOpen, setDiffOpen] = useState(false)
    const [diffData, setDiffData] = useState({ oldValue: '', newValue: '' })
    const diffResolveRef = useRef<((v: boolean) => void) | null>(null)

    // --- Actions matching Angular exactly ---

    const edit = useCallback(() => {
        if (typeof value === 'string' && value.length >= settings.maxValueAsBuffer) {
            setBuffer(true)
            setOriginalValue(structuredClone(valueBuffer))
        } else {
            setBuffer(false)
            setOriginalValue(structuredClone(value))
        }
        setEditable(true)
    }, [value, valueBuffer, settings.maxValueAsBuffer])

    const cancelEdit = useCallback(() => {
        if (buffer) setValueBuffer(originalValue)
        else setValue(originalValue)
        setEditable(false)
        setBuffer(false)
    }, [buffer, originalValue])

    const showDiff = useCallback((oldValue: string, newValue: string): Promise<boolean> => {
        if (!useSettingsStore.getState().showDiffBeforeSave) return Promise.resolve(true)
        if (oldValue === newValue) return Promise.resolve(true)
        setDiffData({ oldValue, newValue })
        setDiffOpen(true)
        return new Promise(resolve => { diffResolveRef.current = resolve })
    }, [])

    const save = useCallback(async () => {
        const v = buffer ? valueBuffer : value
        const oldVal = originalValue
        try {
            if (validateJson) JSON.parse(v)
            if (oldVal != null) {
                const confirmed = await showDiff(oldVal, v)
                if (!confirmed) return
            }
            overlay.show({ message: strings?.intention?.save })
            await request({ action: 'key-set', payload: { type: response?.type, key: keyName, value: v } })
            trackPage('/key-set')
            setEditable(false)
            setBuffer(false)
            onRefresh()
            overlay.hide()

            // Undo support
            if (settings.undoEnabled && oldVal !== undefined && oldVal !== v) {
                const undoClicked = await useCommonStore.getState().toastWithUndo(strings?.status?.saved || 'Saved')
                if (undoClicked) {
                    try {
                        overlay.show({ message: 'Undo...' })
                        await request({ action: 'key-set', payload: { type: response?.type, key: keyName, value: oldVal } })
                        setValue(oldVal)
                        setOriginalValue(oldVal)
                        onRefresh()
                        overlay.hide()
                        useCommonStore.getState().toast(strings?.status?.reverted || 'Reverted')
                    } catch(e) {
                        useCommonStore.getState().generalHandleError(e)
                        overlay.hide()
                    }
                }
            }
        } catch (e) { generalHandleError(e); overlay.hide() }
    }, [buffer, value, valueBuffer, validateJson, response, keyName, strings, onRefresh, generalHandleError, originalValue, settings.undoEnabled])

    const setBufferUpload = useCallback(() => {
        const input = document.createElement('input')
        input.type = 'file'
        input.onchange = async () => {
            const file = input.files?.[0]
            if (!file) return
            const reader = new FileReader()
            reader.onerror = (err) => generalHandleError(err)
            reader.onload = async (e: any) => {
                const arrayBuffer = e.target.result
                try {
                    if (editable) {
                        await confirm({ message: strings?.confirm?.uploadBuffer })
                        if (buffer) setValueBuffer(arrayBuffer)
                        else setValue(arrayBuffer)
                        toast(strings?.confirm?.uploadBufferDone)
                        return
                    }
                    await confirm({ message: strings?.confirm?.uploadBuffer })
                    overlay.show()
                    await request({ action: 'key-set', payload: { type: response?.type, value: arrayBuffer, key: keyName } })
                    trackPage('/key-set')
                    toast(strings?.confirm?.uploadBufferDoneAndSave)
                    onRefresh()
                } catch (e) { generalHandleError(e) }
                finally { overlay.hide() }
            }
            reader.readAsArrayBuffer(file)
        }
        input.click()
    }, [editable, buffer, response, keyName, strings, confirm, toast, generalHandleError, onRefresh])

    const jsonViewer = useCallback(() => setJsonViewOpen(true), [])

    const jsonEditor = useCallback(() => setJsonEditorOpen(true), [])

    const formatJson = useCallback(async () => {
        try {
            const formatted = JSON.stringify(JSON.parse(value), null, settings.jsonFormat || 2)
            setValue(formatted)
            overlay.show({ message: strings?.intention?.save })
            await request({ action: 'key-set', payload: { type: response?.type, key: keyName, value: formatted } })
            trackPage('/key-set')
            onRefresh()
        } catch { toast(strings?.label?.jsonViewNotParsable) }
        finally { overlay.hide() }
    }, [value, settings.jsonFormat, response, keyName, strings, onRefresh])

    const showDigest = useCallback(async () => {
        try {
            const res = await request({ action: 'string-digest', payload: { key: keyName } })
            toast(res.digest || 'No digest')
        } catch (e) { generalHandleError(e) }
    }, [keyName, toast, generalHandleError])

    const copyVal = useCallback(() => copyValue(value), [value])

    const downloadBufferFile = useCallback(() => downloadBuffer(valueBuffer, keyName), [valueBuffer, keyName])

    const bufferDisplay = (): string => {
        if (valueBuffer?.byteLength !== undefined) {
            return '(' + (settings.prettyBytes?.(valueBuffer.byteLength) ?? `${valueBuffer.byteLength} bytes`) + ')'
        }
        return ''
    }

    // --- Responsive button (matches Angular @if(isGtSm) pattern) ---
    const Btn = ({ icon, label, color = 'primary' as const, onClick }: {
        icon: React.ReactNode; label: string; color?: 'primary' | 'secondary' | 'error'; onClick: () => void
    }) => isGtSm ? (
        <Button variant="contained" color={color} size="small" onClick={onClick} sx={{ gap: '3px' }}>
            {icon}<span>{label}</span>
        </Button>
    ) : (
        <Tooltip title={label} placement="top">
            <Button variant="contained" color={color} onClick={onClick}
                sx={{ minWidth: 40, width: 40, height: 40, p: 0, borderRadius: '4px' }}>
                {icon}
            </Button>
        </Tooltip>
    )

    return (
        <Box>
            {/* View mode actions — matches Angular template lines 1-88 */}
            {!editable && (
                <Box className="p3xr-key-type-actions">
                    {!isReadonly && (
                        <Btn icon={<Upload fontSize="small" />} label={strings?.intention?.setBuffer} onClick={setBufferUpload} />
                    )}
                    <Btn icon={<Download fontSize="small" />} label={strings?.intention?.downloadBuffer} color="secondary" onClick={downloadBufferFile} />
                    <Btn icon={<TableChart fontSize="small" />} label={strings?.intention?.jsonViewShow} color="secondary" onClick={jsonViewer} />
                    <Btn icon={<ContentCopy fontSize="small" />} label={strings?.intention?.copy} color="secondary" onClick={copyVal} />
                    {!isReadonly && (
                        <Btn icon={<FormatLineSpacing fontSize="small" />} label={strings?.intention?.formatJson} onClick={formatJson} />
                    )}
                    <Btn icon={<Description fontSize="small" />} label={strings?.intention?.jsonViewEditor} onClick={jsonEditor} />
                    {parseRedisVersion(useRedisStateStore.getState().info?.server?.redis_version).isAtLeast(8, 4) && (
                        <Btn icon={<Numbers fontSize="small" />} label="Digest" color="secondary" onClick={showDigest} />
                    )}
                    {!isReadonly && (
                        <Btn icon={<Edit fontSize="small" />} label={strings?.intention?.edit} onClick={edit} />
                    )}
                </Box>
            )}

            {/* Edit mode actions — matches Angular template lines 90-136 */}
            {editable && (
                <Box className="p3xr-key-type-actions">
                    {!isReadonly && (
                        <FormControlLabel sx={{ mr: 1 }}
                            control={<Switch checked={validateJson} onChange={(_, v) => setValidateJson(v)} color="secondary" />}
                            label={strings?.label?.validateJson} />
                    )}
                    <Btn icon={<Cancel fontSize="small" />} label={strings?.intention?.cancel} color="error" onClick={cancelEdit} />
                    {!isReadonly && (
                        <>
                            <Btn icon={<Upload fontSize="small" />} label={strings?.intention?.setBuffer} onClick={setBufferUpload} />
                            <Btn icon={<Save fontSize="small" />} label={strings?.intention?.save} onClick={save} />
                        </>
                    )}
                </Box>
            )}

            {/* Value display / editor — matches Angular template lines 138-164 */}
            <Box className="p3xr-key-type-content">
                {editable ? (
                    <Box className="p3xr-key-type-editor">
                        {/* Buffer info — shown when value is ArrayBuffer or in buffer mode */}
                        {(String(value) === '[object ArrayBuffer]') && (
                            <Box className="p3xr-key-type-buffer-info">
                                {typeof strings?.label?.isBuffer === 'function'
                                    ? strings.label.isBuffer({ maxValueAsBuffer: settings.prettyBytes(settings.maxValueAsBuffer) })
                                    : ''}
                                {' '}{bufferDisplay()}
                            </Box>
                        )}
                        {buffer && (
                            <Box className="p3xr-key-type-buffer-info">
                                {typeof strings?.label?.isBuffer === 'function'
                                    ? strings.label.isBuffer({ maxValueAsBuffer: settings.prettyBytes(settings.maxValueAsBuffer) })
                                    : ''}
                                {' '}{bufferDisplay()}
                            </Box>
                        )}
                        {buffer ? (
                            <TextField fullWidth multiline minRows={4}
                                value={String(valueBuffer ?? '')}
                                onChange={e => setValueBuffer(e.target.value)}
                                slotProps={{ input: { sx: { fontFamily: "'Roboto Mono', monospace", fontSize: 13 } } }}
                            />
                        ) : (
                            <TextField fullWidth multiline minRows={4}
                                value={typeof value === 'string' ? value : String(value ?? '')}
                                onChange={e => setValue(e.target.value)}
                                slotProps={{ input: { sx: { fontFamily: "'Roboto Mono', monospace", fontSize: 13 } } }}
                            />
                        )}
                    </Box>
                ) : (
                    <Box className="p3xr-key-type-display" onClick={isReadonly ? undefined : edit}
                        sx={{ cursor: isReadonly ? 'default' : 'pointer', maxWidth: '100%', overflow: valueFormat === 'hex' ? 'visible' : 'auto' }}>
                        {settings.maxValueDisplay === -1 ? (
                            <Box sx={{ opacity: 0.5, fontStyle: 'italic' }}>
                                {strings?.label?.hiddenUntilEdit}
                            </Box>
                        ) : (
                            valueFormat === 'hex' ? (
                                <HexMonitor value={truncateDisplay(typeof value === 'string' ? value : '')} truncated={isTruncated(value)} />
                            ) : (
                                <Box component="span" className="p3xr-pre" sx={{
                                    wordBreak: 'break-all', whiteSpace: 'pre-wrap',
                                    fontFamily: "'Roboto Mono', monospace", fontSize: 16, lineHeight: '18px',
                                }}>
                                    {truncateDisplay(formatValue(typeof value === 'string' ? value : '', valueFormat))}
                                    {isTruncated(value) && <Box component="span" sx={{ opacity: 0.5 }}>...</Box>}
                                </Box>
                            )
                        )}
                    </Box>
                )}
            </Box>

            {/* Dialogs */}
            <JsonViewDialog open={jsonViewOpen} value={String(value ?? '')} onClose={() => setJsonViewOpen(false)} />
            <JsonEditorDialog open={jsonEditorOpen} value={String(value ?? '')}
                onClose={async (result) => {
                    setJsonEditorOpen(false)
                    if (result?.obj) {
                        const oldVal = String(value ?? '')
                        setOriginalValue(null)
                        setEditable(false)
                        setBuffer(false)
                        setValue(result.obj)
                        overlay.show({ message: strings?.intention?.save })
                        try {
                            await request({ action: 'key-set', payload: { type: response?.type, key: keyName, value: result.obj } })
                            trackPage('/key-set')
                            onRefresh()
                            overlay.hide()
                            if (settings.undoEnabled && oldVal !== result.obj) {
                                const undoClicked = await useCommonStore.getState().toastWithUndo(strings?.status?.saved || 'Saved')
                                if (undoClicked) {
                                    overlay.show({ message: 'Undo...' })
                                    await request({ action: 'key-set', payload: { type: response?.type, key: keyName, value: oldVal } })
                                    onRefresh()
                                    overlay.hide()
                                    useCommonStore.getState().toast(strings?.status?.reverted || 'Reverted')
                                }
                            }
                        } catch (e) { generalHandleError(e); overlay.hide() }
                    }
                }} />

            <DiffDialog open={diffOpen} keyName={keyName}
                oldValue={diffData.oldValue} newValue={diffData.newValue}
                onConfirm={() => { setDiffOpen(false); diffResolveRef.current?.(true) }}
                onCancel={() => { setDiffOpen(false); diffResolveRef.current?.(false) }} />
        </Box>
    )
}

// src/ng/pages/database/key/key-string.component.ts
import { Component, Inject, OnInit, OnDestroy, ChangeDetectorRef, CUSTOM_ELEMENTS_SCHEMA, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { TextFieldModule } from '@angular/cdk/text-field';
import { BreakpointObserver } from '@angular/cdk/layout';
import { MainCommandService } from '../../../services/main-command.service';

import { I18nService } from '../../../services/i18n.service';
import { SocketService } from '../../../services/socket.service';
import { CommonService } from '../../../services/common.service';
import { JsonViewDialogService } from '../../../dialogs/json-view-dialog.service';
import { JsonEditorDialogService } from '../../../dialogs/json-editor-dialog.service';
import { KeyNewOrSetDialogService } from '../../../dialogs/key-new-or-set-dialog.service';
import { RedisStateService } from '../../../services/redis-state.service';
import { SettingsService } from '../../../services/settings.service';
import { KeyTypeBase } from './key-type-base';
import { HexMonitorComponent } from './hex-monitor.component';
import { OverlayService } from '../../../services/overlay.service';
import { DiffDialogService } from '../../../dialogs/diff-dialog.service';

@Component({
    selector: 'p3xr-key-string',
    standalone: true,
    imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatTooltipModule, MatSlideToggleModule, MatInputModule, MatFormFieldModule, TextFieldModule, HexMonitorComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './key-string.component.html',
    encapsulation: ViewEncapsulation.None,
})
export class KeyStringComponent extends KeyTypeBase implements OnInit {
    editable = false;
    buffer = false;
    validateJson = false;
    originalValue: any;

    constructor(
        @Inject(I18nService) i18n: I18nService,
        @Inject(SocketService) socket: SocketService,
        @Inject(CommonService) common: CommonService,
        @Inject(JsonViewDialogService) jsonViewDialog: JsonViewDialogService,
        @Inject(KeyNewOrSetDialogService) keyNewOrSetDialog: KeyNewOrSetDialogService,
        @Inject(BreakpointObserver) breakpointObserver: BreakpointObserver,
        @Inject(MainCommandService) cmd: MainCommandService,
        @Inject(JsonEditorDialogService) private jsonEditorDialog: JsonEditorDialogService,
        @Inject(ChangeDetectorRef) cdr: ChangeDetectorRef,
        @Inject(RedisStateService) redisState: RedisStateService,
        @Inject(SettingsService) settingsService: SettingsService,
        @Inject(OverlayService) private overlay: OverlayService,
        @Inject(DiffDialogService) private diffDialog: DiffDialogService,
    ) {
        super(i18n, socket, common, jsonViewDialog, keyNewOrSetDialog, breakpointObserver, cmd, cdr, redisState, settingsService);
    }

    ngOnInit(): void {}

    async showDigest(): Promise<void> {
        try {
            const response = await this.socket.request({
                action: 'string-digest',
                payload: { key: this.p3xrKey },
            });
            this.common.toast(response.digest || 'No digest');
        } catch (e: any) {
            this.common.generalHandleError(e);
        }
    }

    edit(): void {
        const value = this.p3xrValue;
        if (typeof value === 'string' && value.length >= this.maxValueAsBuffer) {
            this.buffer = true;
            this.originalValue = structuredClone(this.p3xrValueBuffer);
        } else {
            this.buffer = false;
            this.originalValue = structuredClone(this.p3xrValue);
        }
        this.editable = true;
    }

    cancelEdit(): void {
        if (this.buffer) {
            this.p3xrValueBuffer = this.originalValue;
        } else {
            this.p3xrValue = this.originalValue;
        }
        this.editable = false;
        this.buffer = false;
    }

    async save(): Promise<void> {
        const valueToSave = this.buffer ? this.p3xrValueBuffer : this.p3xrValue;
        const oldValue = this.originalValue;
        try {
            if (this.validateJson) {
                JSON.parse(valueToSave);
            }
            if (oldValue !== undefined) {
                const confirmed = await this.diffDialog.show({ keyName: this.p3xrKey, oldValue, newValue: valueToSave });
                if (!confirmed) return;
            }
            this.overlay.show({ message: this.strings?.intention?.save ?? 'Saving...' });
            await this.socket.request({
                action: 'key-set',
                payload: {
                    type: this.p3xrResponse?.type,
                    key: this.p3xrKey,
                    value: valueToSave,
                },
            });
            this.gtag('/key-set');
            this.editable = false;
            this.buffer = false;
            this.refreshKey();
            this.overlay.hide();

            // Undo support
            if (this.settingsService.undoEnabled() && oldValue !== undefined && oldValue !== valueToSave) {
                const undoClicked = await this.common.toastWithUndo(this.strings?.status?.saved || 'Saved');
                if (undoClicked) {
                    this.overlay.show({ message: 'Undo...' });
                    await this.socket.request({
                        action: 'key-set',
                        payload: {
                            type: this.p3xrResponse?.type,
                            key: this.p3xrKey,
                            value: oldValue,
                        },
                    });
                    this.refreshKey();
                    this.overlay.hide();
                    this.common.toast(this.strings?.status?.reverted || 'Reverted');
                }
            }
        } catch (e) {
            this.common.generalHandleError(e);
            this.overlay.hide();
        }
    }

    async setBufferUpload(): Promise<void> {
        const input = document.createElement('input');
        input.type = 'file';
        input.onchange = async () => {
            const file = input.files?.[0];
            if (!file) return;
            const reader = new FileReader();
            reader.onerror = (error) => {
                this.common.generalHandleError(error);
            };
            reader.onload = async (loadEvent: any) => {
                const arrayBuffer = loadEvent.target.result;
                try {
                    if (this.editable) {
                        await this.common.confirm({ message: this.i18n.strings().confirm?.uploadBuffer });
                        if (this.buffer) {
                            this.p3xrValueBuffer = arrayBuffer;
                        } else {
                            this.p3xrValue = arrayBuffer;
                        }
                        this.common.toast(this.i18n.strings().confirm?.uploadBufferDone);
                        return;
                    }
                    await this.common.confirm({ message: this.i18n.strings().confirm?.uploadBuffer });
                    this.overlay.show();
                    await this.socket.request({
                        action: 'key-set',
                        payload: {
                            type: this.p3xrResponse?.type,
                            value: arrayBuffer,
                            key: this.p3xrKey,
                        },
                    });
                    this.common.toast(this.i18n.strings().confirm?.uploadBufferDoneAndSave);
                    this.gtag('/key-set');
                    this.refreshKey();
                } catch (e) {
                    this.common.generalHandleError(e);
                } finally {
                    this.overlay.hide();
                }
            };
            reader.readAsArrayBuffer(file);
        };
        input.click();
    }

    async jsonViewer(event?: Event): Promise<void> {
        await this.showJson(this.p3xrValue, event);
    }

    async jsonEditor(): Promise<void> {
        try {
            const oldValue = this.p3xrValue;
            const result = await this.jsonEditorDialog.show({ value: this.p3xrValue });
            this.originalValue = undefined;
            this.overlay.show({ message: this.strings?.intention?.save ?? 'Saving...' });
            await this.socket.request({
                action: 'key-set',
                payload: { type: this.p3xrResponse?.type, key: this.p3xrKey, value: result.obj },
            });
            this.p3xrValue = result.obj;
            this.editable = false;
            this.buffer = false;
            this.refreshKey();
            this.overlay.hide();

            if (this.settingsService.undoEnabled() && oldValue !== undefined && oldValue !== result.obj) {
                const undoClicked = await this.common.toastWithUndo(this.strings?.status?.saved || 'Saved');
                if (undoClicked) {
                    this.overlay.show({ message: 'Undo...' });
                    await this.socket.request({
                        action: 'key-set',
                        payload: { type: this.p3xrResponse?.type, key: this.p3xrKey, value: oldValue },
                    });
                    this.refreshKey();
                    this.overlay.hide();
                    this.common.toast(this.strings?.status?.reverted || 'Reverted');
                }
            }
        } catch { /* cancelled */ }
    }

    async formatJson(): Promise<void> {
        try {
            this.p3xrValue = JSON.stringify(JSON.parse(this.p3xrValue), null, this.settingsService.jsonFormat() ?? 2);
            await this.save();
        } catch {
            this.common.toast(this.strings?.label?.jsonViewNotParsable ?? 'Not valid JSON');
        }
    }

    copyValue(): void {
        this.copy(this.p3xrValue);
    }

    downloadBufferFile(): void {
        this.downloadBuffer(this.p3xrValueBuffer);
    }

    bufferDisplay(): string {
        if (this.p3xrValueBuffer?.byteLength !== undefined) {
            return '(' + this.prettyBytes(this.p3xrValueBuffer.byteLength) + ')';
        }
        return '';
    }
}

<!-- Action buttons when NOT editing -->
@if (!editable) {
    <div class="p3xr-key-type-actions">
        @if (!isReadonly) {
            @if (isGtSm) {
                <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="setBufferUpload()">
                    <mat-icon>upload</mat-icon>
                    <span>{{ strings?.intention?.setBuffer || 'Upload' }}</span>
                </button>
            } @else {
                <button mat-mini-fab class="btn-primary" type="button" (click)="setBufferUpload()"
                    [matTooltip]="strings?.intention?.setBuffer ?? 'Upload'" matTooltipPosition="above">
                    <mat-icon>upload</mat-icon>
                </button>
            }
        }
        @if (isGtSm) {
            <button mat-raised-button class="btn-accent p3xr-action-btn" type="button" (click)="downloadBufferFile()">
                <mat-icon>download</mat-icon>
                <span>{{ strings?.intention?.downloadBuffer || 'Download' }}</span>
            </button>
        } @else {
            <button mat-mini-fab class="btn-accent" type="button" (click)="downloadBufferFile()"
                [matTooltip]="strings?.intention?.downloadBuffer ?? 'Download'" matTooltipPosition="above">
                <mat-icon>download</mat-icon>
            </button>
        }
        @if (isGtSm) {
            <button mat-raised-button class="btn-accent p3xr-action-btn" type="button" (click)="jsonViewer($event)">
                <mat-icon>table_chart</mat-icon>
                <span>{{ strings?.intention?.jsonViewShow || 'JSON' }}</span>
            </button>
        } @else {
            <button mat-mini-fab class="btn-accent" type="button" (click)="jsonViewer($event)"
                [matTooltip]="strings?.intention?.jsonViewShow ?? 'JSON'" matTooltipPosition="above">
                <mat-icon>table_chart</mat-icon>
            </button>
        }
        @if (isGtSm) {
            <button mat-raised-button class="btn-accent p3xr-action-btn" type="button" (click)="copyValue()">
                <mat-icon>content_copy</mat-icon>
                <span>{{ strings?.intention?.copy || 'Copy' }}</span>
            </button>
        } @else {
            <button mat-mini-fab class="btn-accent" type="button" (click)="copyValue()"
                [matTooltip]="strings?.intention?.copy ?? 'Copy'" matTooltipPosition="above">
                <mat-icon>content_copy</mat-icon>
            </button>
        }
        @if (!isReadonly) {
            @if (isGtSm) {
                <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="formatJson()">
                    <mat-icon>format_line_spacing</mat-icon>
                    <span>{{ strings?.intention?.formatJson || 'Format' }}</span>
                </button>
            } @else {
                <button mat-mini-fab class="btn-primary" type="button" (click)="formatJson()"
                    [matTooltip]="strings?.intention?.formatJson ?? 'Format JSON'" matTooltipPosition="above">
                    <mat-icon>format_line_spacing</mat-icon>
                </button>
            }
        }
        @if (isGtSm) {
            <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="jsonEditor()">
                <mat-icon>description</mat-icon>
                <span>{{ strings?.intention?.jsonViewEditor || 'Editor' }}</span>
            </button>
        } @else {
            <button mat-mini-fab class="btn-primary" type="button" (click)="jsonEditor()"
                [matTooltip]="strings?.intention?.jsonViewEditor ?? 'JSON Editor'" matTooltipPosition="above">
                <mat-icon>description</mat-icon>
            </button>
        }
        @if (redisState.redisVersion().isAtLeast(8, 4)) {
            @if (isGtSm) {
                <button mat-raised-button class="btn-accent p3xr-action-btn" type="button" (click)="showDigest()">
                    <mat-icon>numbers</mat-icon>
                    <span>Digest</span>
                </button>
            } @else {
                <button mat-mini-fab class="btn-accent" type="button" (click)="showDigest()"
                    matTooltip="Digest" matTooltipPosition="above">
                    <mat-icon>numbers</mat-icon>
                </button>
            }
        }
        @if (!isReadonly) {
            @if (isGtSm) {
                <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="edit()">
                    <mat-icon>edit</mat-icon>
                    <span>{{ strings?.intention?.edit || 'Edit' }}</span>
                </button>
            } @else {
                <button mat-mini-fab class="btn-primary" type="button" (click)="edit()"
                    [matTooltip]="strings?.intention?.edit ?? 'Edit'" matTooltipPosition="above">
                    <mat-icon>edit</mat-icon>
                </button>
            }
        }
    </div>
}

<!-- Edit mode buttons -->
@if (editable) {
    <div class="p3xr-key-type-actions">
        @if (!isReadonly) {
            <mat-slide-toggle [(ngModel)]="validateJson" class="btn-accent" style="margin-right: 8px;">
                {{ strings?.label?.validateJson || 'Validate JSON' }}
            </mat-slide-toggle>
        }
        @if (isGtSm) {
            <button mat-raised-button class="btn-warn p3xr-action-btn" type="button" (click)="cancelEdit()">
                <mat-icon>cancel</mat-icon>
                <span>{{ strings?.intention?.cancel || 'Cancel' }}</span>
            </button>
        } @else {
            <button mat-mini-fab class="btn-warn" type="button" (click)="cancelEdit()"
                [matTooltip]="strings?.intention?.cancel ?? 'Cancel'" matTooltipPosition="above">
                <mat-icon>cancel</mat-icon>
            </button>
        }
        @if (!isReadonly) {
            @if (isGtSm) {
                <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="setBufferUpload()">
                    <mat-icon>upload</mat-icon>
                    <span>{{ strings?.intention?.setBuffer || 'Upload' }}</span>
                </button>
            } @else {
                <button mat-mini-fab class="btn-primary" type="button" (click)="setBufferUpload()"
                    [matTooltip]="strings?.intention?.setBuffer ?? 'Upload'" matTooltipPosition="above">
                    <mat-icon>upload</mat-icon>
                </button>
            }
        }
        @if (!isReadonly) {
            @if (isGtSm) {
                <button mat-raised-button class="btn-primary p3xr-action-btn" type="button" (click)="save()">
                    <mat-icon>save</mat-icon>
                    <span>{{ strings?.intention?.save || 'Save' }}</span>
                </button>
            } @else {
                <button mat-mini-fab class="btn-primary" type="button" (click)="save()"
                    [matTooltip]="strings?.intention?.save ?? 'Save'" matTooltipPosition="above">
                    <mat-icon>save</mat-icon>
                </button>
            }
        }
    </div>
}

<!-- Value display / editor -->
<div class="p3xr-key-type-content">
    @if (editable) {
        <mat-form-field class="p3xr-key-type-editor" appearance="fill">
        
            @if (p3xrValue && p3xrValue.toString() === '[object ArrayBuffer]') {
                <div class="p3xr-key-type-buffer-info">
                    {{ strings?.label?.isBuffer?.({ maxValueAsBuffer: prettyBytes(maxValueAsBuffer) }) }}
                    {{ bufferDisplay() }}
                </div>
            }
            @if (buffer) {
                <div class="p3xr-key-type-buffer-info">
                    {{ strings?.label?.isBuffer?.({ maxValueAsBuffer: prettyBytes(maxValueAsBuffer) }) }}
                    {{ bufferDisplay() }}
                </div>
                <textarea matInput [(ngModel)]="p3xrValueBuffer" cdkTextareaAutosize cdkAutosizeMinRows="4"></textarea>
            } @else {
                <textarea matInput [(ngModel)]="p3xrValue" cdkTextareaAutosize cdkAutosizeMinRows="4"></textarea>
            }
        </mat-form-field>
    } @else {
        <div class="p3xr-key-type-display" [style.overflow]="valueFormat === 'hex' ? 'visible' : 'auto'" style="cursor: pointer; max-width: 100%;" (click)="edit()">
            @if (valueFormat === 'hex') {
                <p3xr-hex-monitor [value]="truncateDisplay(p3xrValue)" [truncated]="isTruncated(p3xrValue)"></p3xr-hex-monitor>
            } @else {
                <span class="p3xr-pre" style="word-break: break-all; white-space: pre-wrap;">{{ formatValue(truncateDisplay(p3xrValue)) }}@if (isTruncated(p3xrValue)) {<span style="opacity: 0.5;">...</span>}</span>
            }
        </div>
    }
</div>
