// src/vue/pages/database/key/KeyZset.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import HexMonitor from './HexMonitor.vue'
import KeyPagerInline from './KeyPagerInline.vue'
import KeyNewOrSetDialog from '../../../dialogs/KeyNewOrSetDialog.vue'
import JsonViewDialog from '../../../dialogs/JsonViewDialog.vue'
import { useI18nStore } from '../../../stores/i18n'
import { useRedisStateStore } from '../../../stores/redis-state'
import { useCommonStore } from '../../../stores/common'
import { request } from '../../../stores/socket.service'
import { type Paging, createPaging, rePaging, formatValue, truncateDisplay, isTruncated, copyToClipboard, downloadBuffer, str } from './key-type-base'

interface ZsetItem { score: string; member: string; index: number }

const props = defineProps<{ response: any; value: any; valueBuffer: any; keyName: string; valueFormat: string }>()
const emit = defineEmits<{ refresh: [] }>()
const strings = computed(() => useI18nStore().strings)
const isReadonly = computed(() => useRedisStateStore().connection?.readonly === true)
const common = useCommonStore()

const paging = ref<Paging>(createPaging(0, true))
const pagedItems = ref<ZsetItem[]>([])
const editDialogOpen = ref(false)
const editDialogData = ref<any>(null)
const jsonViewOpen = ref(false)
const jsonViewValue = ref('')

function buildItems(val: any[], p: Paging): ZsetItem[] {
    if (!val) return []
    const items: ZsetItem[] = []
    for (let i = 0; i < val.length; i += 2) items.push({ member: val[i], score: val[i + 1], index: i / 2 })
    return items.slice(p.startIndex, p.endIndex)
}

function updatePaged(p: Paging) { paging.value = p; pagedItems.value = buildItems(props.value, p) }
watch(() => props.value, () => { if (props.value) { const p = rePaging(paging.value, props.value.length, true); updatePaged(p) } }, { immediate: true })

function addItem() { editDialogData.value = { type: 'append', model: { type: 'zset', key: props.keyName } }; editDialogOpen.value = true }
function editItem(item: ZsetItem) { editDialogData.value = { type: 'edit', model: { type: 'zset', key: props.keyName, value: item.member, score: item.score } }; editDialogOpen.value = true }
function handleEditClose(r?: any) { editDialogOpen.value = false; editDialogData.value = null; if (r) emit('refresh') }
async function deleteItem(item: ZsetItem) {
    try { await common.confirm({ message: str(strings.value?.confirm?.deleteZSetMember) }); await request({ action: 'key/zset-delete-member', payload: { key: props.keyName, value: props.valueBuffer?.[item.index * 2] } }); common.toast(str(strings.value?.status?.deletedZSetMember)); emit('refresh') }
    catch (e) { if (e !== undefined) common.generalHandleError(e) }
}
</script>

<template>
    <div>
        <KeyPagerInline :paging="paging" @page-changed="updatePaged" />
        <div class="p3xr-key-table-header">
            <span style="flex:20%;">{{ str(strings?.page?.key?.zset?.table?.score) }}</span>
            <span style="flex:60%;">{{ str(strings?.page?.key?.zset?.table?.value) }}</span>
            <span class="p3xr-key-table-header-actions"><v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.add)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" style="cursor:pointer;color:inherit;" @click="addItem">mdi-plus</v-icon></template></v-tooltip></span>
        </div>
        <div v-for="(item, i) in pagedItems" :key="item.index" class="p3xr-key-table-row" :class="{ 'p3xr-key-table-odd': i % 2 === 0 }">
            <span style="flex:20%;cursor:pointer;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;user-select:text;" @click="!isReadonly && editItem(item)">{{ item.score }}</span>
            <span class="p3xr-key-table-value" @click="!isReadonly && editItem(item)">
                <HexMonitor v-if="valueFormat === 'hex'" :value="truncateDisplay(item.member)" />
                <template v-else>{{ truncateDisplay(formatValue(item.member, valueFormat)) }}<span v-if="isTruncated(item.member)" style="opacity:0.5;">...</span></template>
            </span>
            <span class="p3xr-key-table-actions">
                <v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.delete)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-error));" @click="deleteItem(item)">mdi-delete</v-icon></template></v-tooltip>
                <v-tooltip :text="str(strings?.intention?.jsonViewShow)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="jsonViewValue = String(item.member ?? ''); jsonViewOpen = true">mdi-file-tree</v-icon></template></v-tooltip>
                <v-tooltip :text="str(strings?.intention?.copy)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="copyToClipboard(String(item.member ?? ''))">mdi-content-copy</v-icon></template></v-tooltip>
                <v-tooltip :text="str(strings?.intention?.downloadBuffer)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-secondary));" @click="downloadBuffer(valueBuffer?.[item.index * 2], keyName)">mdi-download</v-icon></template></v-tooltip>
                <v-tooltip v-if="!isReadonly" :text="str(strings?.intention?.edit)" location="top"><template #activator="{ props: tp }"><v-icon v-bind="tp" size="24" class="p3xr-key-icon" style="color:rgb(var(--v-theme-primary));" @click="editItem(item)">mdi-pencil</v-icon></template></v-tooltip>
            </span>
        </div>
        <KeyNewOrSetDialog :open="editDialogOpen" :data="editDialogData" @close="handleEditClose" />
        <JsonViewDialog :open="jsonViewOpen" :value="jsonViewValue" @close="jsonViewOpen = false" />
    </div>
</template>
<style src="./key-table.css"></style>

// src/ng/pages/database/key/key-zset.component.ts
import { Component, Inject, OnInit, OnChanges, SimpleChanges, ChangeDetectorRef, CUSTOM_ELEMENTS_SCHEMA, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { BreakpointObserver } from '@angular/cdk/layout';
import { I18nService } from '../../../services/i18n.service';
import { SocketService } from '../../../services/socket.service';
import { CommonService } from '../../../services/common.service';
import { JsonViewDialogService } from '../../../dialogs/json-view-dialog.service';
import { KeyNewOrSetDialogService } from '../../../dialogs/key-new-or-set-dialog.service';
import { MainCommandService } from '../../../services/main-command.service';
import { RedisStateService } from '../../../services/redis-state.service';
import { SettingsService } from '../../../services/settings.service';
import { KeyTypeBase } from './key-type-base';
import { KeyPaging } from './key-paging';
import { KeyPagerInlineComponent } from './key-pager-inline.component';

@Component({
    selector: 'p3xr-key-zset',
    standalone: true,
    imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatTooltipModule, KeyPagerInlineComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './key-zset.component.html',
    encapsulation: ViewEncapsulation.None,
})
export class KeyZsetComponent extends KeyTypeBase implements OnInit, OnChanges {
    paging: KeyPaging;
    pagedItems: Array<{ score: string; member: string; index: number }> = [];

    constructor(
        @Inject(I18nService) i18n: I18nService, @Inject(SocketService) socket: SocketService,
        @Inject(CommonService) common: CommonService, @Inject(JsonViewDialogService) jsonViewDialog: JsonViewDialogService,
        @Inject(KeyNewOrSetDialogService) keyNewOrSetDialog: KeyNewOrSetDialogService,
        @Inject(BreakpointObserver) breakpointObserver: BreakpointObserver,
        @Inject(MainCommandService) cmd: MainCommandService,
        @Inject(ChangeDetectorRef) cdr: ChangeDetectorRef,
        @Inject(RedisStateService) redisState: RedisStateService,
        @Inject(SettingsService) settingsService: SettingsService,
    ) {
        super(i18n, socket, common, jsonViewDialog, keyNewOrSetDialog, breakpointObserver, cmd, cdr, redisState, settingsService);
        this.paging = new KeyPaging({ zsetMode: true, settingsService });
    }

    ngOnInit(): void { this.updatePaging(); }
    ngOnChanges(c: SimpleChanges): void { if (c['p3xrValue']) this.updatePaging(); }

    updatePaging(): void {
        if (!this.p3xrValue) return;
        this.paging.figurePaging(this.p3xrValue.length);
        this.updatePagedItems();
    }

    updatePagedItems(): void {
        if (!this.p3xrValue) { this.pagedItems = []; return; }
        // Zset flat array: [member, score, member, score, ...]
        const items: Array<{ score: string; member: string; index: number }> = [];
        for (let i = 0; i < this.p3xrValue.length; i += 2) {
            items.push({ member: this.p3xrValue[i], score: this.p3xrValue[i + 1], index: i / 2 });
        }
        this.pagedItems = items.slice(this.paging.startIndex, this.paging.endIndex);
    }

    async addZSet(event: Event): Promise<void> {
        try {
            await this.keyNewOrSetDialog.show({ $event: event, type: 'append', model: { type: 'zset', key: this.p3xrKey } });
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    async deleteZSet(item: any, event: Event): Promise<void> {
        try {
            await this.common.confirm({ message: this.i18n.strings().confirm?.deleteZSetMember });
            await this.socket.request({
                action: 'key-zset-delete-member',
                payload: { key: this.p3xrKey, value: this.p3xrValueBuffer[item.index * 2] },
            });
            this.common.toast(this.i18n.strings().status?.deletedZSetMember);
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    async editValue(item: any, event: Event): Promise<void> {
        try {
            const editValue = typeof item.member === 'string' && item.member.length >= this.maxValueAsBuffer
                ? this.p3xrValueBuffer[item.index * 2] : item.member;
            await this.keyNewOrSetDialog.show({
                $event: event, type: 'edit',
                model: { type: 'zset', key: this.p3xrKey, value: editValue, score: item.score },
            });
            this.refreshKey();
        } catch (e) { this.common.generalHandleError(e); }
    }

    copyItem(value: any): void { this.copy(value); }
    showJsonItem(value: any, event: Event): void { this.showJson(value, event); }
    downloadItem(index: number): void { this.downloadBuffer(this.p3xrValueBuffer[index * 2]); }
}

<p3xr-key-pager-inline [paging]="paging" (pageChanged)="updatePagedItems()"></p3xr-key-pager-inline>
<div class="p3xr-key-type-table">
    <div class="p3xr-key-type-header">
        <span style="flex: 20%">{{ strings?.page?.key?.zset?.table?.score || 'Score' }}</span>
        <span style="flex: 60%">{{ strings?.page?.key?.zset?.table?.value || 'Member' }}</span>
        <span style="flex: 20%; text-align: right">
            @if (!isReadonly) {
                <button mat-icon-button (click)="addZSet($event)" matTooltip="Add">
                    <mat-icon svgIcon="add"></mat-icon>
                </button>
            }
        </span>
    </div>
    @for (item of pagedItems; track item.index) {
        <div class="p3xr-key-type-row">
            <span class="p3xr-key-col" style="flex: 20%; cursor: pointer" (click)="editValue(item, $event)">{{ item.score }}</span>
            <span class="p3xr-value-col" [class.p3xr-pre]="valueFormat !== 'hex'" style="flex: 60%; cursor: pointer" (click)="editValue(item, $event)">@if (valueFormat === 'hex') {<p3xr-hex-monitor [value]="truncateDisplay(item.member)" [truncated]="isTruncated(item.member)"></p3xr-hex-monitor>} @else {{{ truncateDisplay(formatValue(item.member)) }}@if (isTruncated(item.member)) {<span style="opacity: 0.5;">...</span>}}</span>
            <span style="flex: 20%; text-align: right" class="p3xr-key-type-row-actions">
                @if (!isReadonly) { <mat-icon class="icon-warn" (click)="deleteZSet(item, $event)" matTooltip="Delete">delete</mat-icon> }
                <mat-icon class="icon-accent" (click)="showJsonItem(item.member, $event)" matTooltip="JSON">account_tree</mat-icon>
                <mat-icon class="icon-accent" (click)="copyItem(item.member)" matTooltip="Copy">content_copy</mat-icon>
                <mat-icon class="icon-accent" (click)="downloadItem(item.index)" matTooltip="Download">download</mat-icon>
                @if (!isReadonly) { <mat-icon class="icon-primary" (click)="editValue(item, $event)" matTooltip="Edit">edit</mat-icon> }
            </span>
        </div>
    }
</div>
